### ISSUE TITLE
Add mention of WIP tests to Release Blocking Jobs and Criteria

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/sig-release#1002]
**What would you like to be added**:

Add section to https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md#promoting-or-demoting-jobs that explicitly mentions the exclusion of WIP jobs.

**Why is this needed**:

Tests that consistently fail without giving any quality signal end up adding noise to CI Signal projects boards and reports. Ref: https://github.com/kubernetes/kubernetes/issues/86788

**Comment by alejandrox1** [comment]
@hasheddan do you hve the bandwidth to work on this?

**Comment by hasheddan** [comment]
@alejandrox1 yes! Apologies for not addressing sooner

**Comment by alejandrox1** [comment]
:sweat_smile: no need to apologize, jut a friendly ping.
And thank you for filing this!
