### ISSUE TITLE
Limited timeline around securing release/feature blog content

### ISSUE THREAD

**Issue by karenhchu** [kubernetes/sig-release#1024]
Speaking from my team's experience with the Kubernetes 1.18 release, we've found that the current approach to gathering content for release blogs can result in too tight of a timeline.

As of right now, here's the order in which actions take place:

1.  Code freeze
2. Split up list of SIGs amongst team and reach out for KEPs/items of importance
3. Track items in Google sheet
4. Team evaluates all items and votes on priority for coverage
5. Reach out to SIGs for feature blog content + Team works on release blog (of which contains summaries of the feature blogs)
6. Send drafts to CNCF for review and publishing

With the 1.18 release, due to delays in several SIGs responding to our inquiries, we've had to push back #4/#5 and thus, we're now delayed on content as well given everyone is time crunched on getting things out the door for the release.

Given we can't do much before code freeze, I'd like to explore what processes we can change in-between then and the release. Perhaps syncing with Enhancements makes sense. Open to other proposals as well.

CC: @alejandrox1 @justaugustus @jeremyrickard @mkorbi @pgburt @cnadolny @mkhaas

**Comment by mkorbi** [comment]
What we discussed yet: pushing the deadline back as far as possible, what we need is a good first version for a feature blog which can be finalized in the week of the release until the feature blogs getting published. How much time does the CNCF need upfront?

Other ideas:
- We could do our voting/selecting earlier, even if some enhancements are not saved yet
- As soon as we reach the freeze we open documents for the top features with a draft/feature outline where the teams can work in (so we can see the progress)
- With the beginning of a release cycle have a conf call with all SIG leads (at least one representive, introducing timeline, expectations and how to support this process)

**Comment by alejandrox1** [comment]
@karenhchu thank you so much for creating this issue!
@mkorbi thank you for your comments as well (and thank you to all of the comms team)!

Let's get this rolling!
/sig release
/priority important-soon
/milestone v1.19
/assign @onlydole @alejandrox1

**Comment by onlydole** [comment]
+1 to that, @karenhchu - it goes from quiet to super busy, super quick. I’d really like to work with you and the comms team to improve that experience going forward.

**Comment by mkorbi** [comment]
@onlydole @karenhchu 
First draft of changes:
https://github.com/mkorbi/sig-release/commit/a8564863bdce0c814ec123c54080247e46ef45cf

**Comment by karenhchu** [comment]
I'd say CNCF usually appreciates a week's notice, given they have to coordinate with press/analyst and work with an embargo. 

While we're at this, we should update information around the feature blogs as well:

- Week 9: Code Freeze is usually around then so we should start feature blog drafts then.

- Week 12: Finalize feature blogs

- Week 13: Publish feature blogs

Otherwise, your changes LGTM. Thanks for your work here!

**Comment by mkorbi** [comment]
definitely, added it to the draft PR

**Comment by justaugustus** [comment]
Two suggestions:
- Get the Communications + Enhancements team leads in front of SIG Chairs/TLs in the SIG Leads monthly meeting about expectations
- Have the Communications team sync w/ Enhancements team close to Enhancements Freeze to get a pulse on what's hot for the release. Gives an extra month to work through this.

**Comment by mkorbi** [comment]
please see latest commit on https://github.com/kubernetes/sig-release/pull/1037

**Comment by mkorbi** [comment]
/close
https://github.com/kubernetes/sig-release/pull/1037 got merged
