### ISSUE TITLE
Assemble Kubernetes 1.19 Release Team

### ISSUE THREAD

**Issue by lachie83** [kubernetes/sig-release#1031]
The time is upon us to start assembling the 1.19 release team.

Please review the [Release Team Selection Process](https://github.com/kubernetes/sig-release/tree/master/release-team#release-team-selection) docs for details on the process and criteria.

At this stage we only require nominations for Role Leads. Once role leads are nominated we will then send out a shadow application survey.

/sig release
/are release-team
/milestone v1.19

cc @onlydole  @justaugustus @tpepper

**Comment by alejandrox1** [comment]
It is with great pleasure that I officially nominate the one and @onlydole !
It has been a privilege to be able to work with you and I have no doubt you will do a fantastic job in 1.19! :rocket:

**Comment by jeremyrickard** [comment]
It was an honor to work with everyone on 1.18! 

I'd also like to take this opportunity to nominate @palnabarun as the Enhancements Lead for 1.19.

**Comment by droslean** [comment]
Thank you everyone! It was an honor to work with such a great team at 1.18!!!
As a CI-Signal Lead for 1.19 I nominate @hasheddan

**Comment by karenhchu** [comment]
Thanks for all hard work everyone~

I would like to nominate @mkorbi as the Communications Lead for 1.19! I've worked with him on the Comms team for the last 2 cycles and am excited for him to take the lead 🥇

**Comment by smourapina** [comment]
Thank you to the team for Bug Triage in 1.18.

I would like to nominate @markyjackson-taulia as Bug Triage Lead for 1.19!

**Comment by VineethReddy02** [comment]
Thank you, everyone!

I would like to nominate @savitharaghunathan  as Docs lead for 1.19

**Comment by evillgenius75** [comment]
Thank you all for another amazing Release!  It is with great pride that I nominate Adolfo @puerco as the Release Notes Lead for 1.19!

**Comment by markyjackson-taulia** [comment]
I think this can be closed
