### ISSUE TITLE
Release Manager access for @Verolop  @markyjackson-taulia 

### ISSUE THREAD

**Issue by markyjackson-taulia** [kubernetes/sig-release#1047]
### GitHub Username

@Verolop 
@markyjackson-taulia 

### [Release Manager](/release-managers.md) role

Release Manager Associate

### Tenure

- permanent: @Verolop & @markyjackson-taulia will be joining the team permanetly 

### Release Manager Onboarding

**All pull requests within these checklists should be marked with an _explicit_ hold and only released once approved by a Release Engineering subproject owner.**

- [x] Addition of a new Release Manager has been discussed with and approved by Release Engineering subproject owners
- [x] Ensure new Release Manager:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
- [x] (https://github.com/kubernetes/sig-release/pull/1046) Update [Release Managers](https://git.k8s.io/sig-release/release-managers.md) page to include the new Release Manager

### Release Manager Associate

- [x] (https://github.com/kubernetes/org/pull/1785) Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `release-engineering`
  - `sig-release`
- [x] (https://github.com/kubernetes/k8s.io/pull/742) Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-viewers@`
  - `release-managers@`

cc: @kubernetes/release-engineering

**Comment by jeremyrickard** [comment]
👏

**Comment by cpanato** [comment]
+1000

**Comment by justaugustus** [comment]
Will be closed via https://github.com/kubernetes/k8s.io/pull/742.
/close
