### ISSUE TITLE
Branch FF failed in release-1.19

### ISSUE THREAD

**Issue by cpanato** [kubernetes/sig-release#1154]
### What happened:
While doing the branch FF for the release-1.19 on 16-Jul-2020 we got the following error:

```
INFO Merging master changes into release branch
CONFLICT (modify/delete): CHANGELOG/CHANGELOG-1.18.md deleted in HEAD and modified in origin/master. Version origin/master of CHANGELOG/CHANGELOG-1.18.md left in tree.
CONFLICT (modify/delete): CHANGELOG/CHANGELOG-1.17.md deleted in HEAD and modified in origin/master. Version origin/master of CHANGELOG/CHANGELOG-1.17.md left in tree.
CONFLICT (modify/delete): CHANGELOG/CHANGELOG-1.16.md deleted in HEAD and modified in origin/master. Version origin/master of CHANGELOG/CHANGELOG-1.16.md left in tree.
Automatic merge failed; fix conflicts and then commit the result.
```

This is because those files were removed in the release-1.19 branch, but those files got updated in a day before due the patch releases. 

One solution is add back those files in the release branch and maybe later remove it again. but this solves the branch FF issue.

more context see: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1594921378246500

**Comment by cpanato** [comment]
pr merged
/close

**Comment by saschagrunert** [comment]
We still have to fix the behavior for upcoming release: https://github.com/kubernetes/release/blob/cba1d9c10a6df1bcf06ec1047d06f9d40a72940d/cmd/krel/cmd/changelog.go#L527-L534

I suggest that we remove the files only on the final tag. Should I take care of this?

**Comment by cpanato** [comment]
@saschagrunert I can open a PR, then i can get to know a bit this piece as well :), off course if you don't mind.
We will remove that in the final ? or rc.2?

/reopen

**Comment by saschagrunert** [comment]
> @saschagrunert I can open a PR, then i can get to know a bit this piece as well :), off course if you don't mind.
> We will remove that in the final ? or rc.2?
> 
> /reopen

Sounds good, thanks! Go ahead, I think we should be safe if we remove them at the final rather than another rc. This way we're free to chose when to apply Code Thaw in the future.

**Comment by justaugustus** [comment]
How do we know when the "final" release is?
No release is guaranteed to have any set number of pre-releases, so whichever solution we choose has to work with a variable amount of pre-releases.

**Comment by justaugustus** [comment]
(Just read Sascha's comment)
Agreed that not removing until the official .0 is probably the right move.
