### ISSUE TITLE
Add triage tooltips to the CI Signal Handbook

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/sig-release#1155]
Add additional tool tips for the CI Signal Team when carrying out initial job fail/flake triage.

- How download all job run artifacts from **Prow** using **gsutil**
- How to search for code changes made to **Kubernetes** using Testgrid's Click and Search

**Comment by RobertKielty** [comment]
Proposed content new content, will figure out where this should go in consultation with the teams CI-Signal, Test-Infra
  
As I think think through this now perhaps it might be just as easy to add the relevant gsutil command at the top of the Artifacts links page and leave it at that. But for now I'll write this up here



### Download all log files generated by a run of CI Job in Prow 
The logs are stored in a publicly-accessible Cloud Storage Bucket which you can access using [gsutils](https://cloud.google.com/storage/docs/gsutil_install) 

1. Navigate to the Job page in Prow say by clicking on a grid cell on Testgrid
The Artifacts view allows you to see all of the log files generated when the job ran and download the

**Comment by RobertKielty** [comment]
@hasheddan if we get a chance this week can we find discuss finding a place for the above content?

**Comment by hasheddan** [comment]
@RobertKielty sure!
