### ISSUE TITLE
CI signal handbook: adjust issue guidance to target specific SIGs

### ISSUE THREAD

**Issue by liggitt** [kubernetes/sig-release#1162]
#### What would you like to be added:

Adjust the CI signal handbook guidance and templates to open one issue per SIG per set-of-failing-tests, rather than one issue per failing/flaking job.

#### Why is this needed:

The CI signal handbook gives [examples of issue templates to open for failing test jobs](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/ci-signal#routing-test-issues-to-sigowner) to route issues to sig owners, but the title and instructions describe opening an issue per job.

* `[Failing Test] testgrid-tab-name (prow-job-name)`
* `[Flaky Test] testgrid-tab-name (prow-job-name)`

For jobs with tests from multiple sigs (like integration / e2e), a description mentioning one SIG's failing test can dissuade other SIGs from investigating their failures in the test.

Example: 
https://github.com/kubernetes/kubernetes/issues/92360 was opened because the integration job flaked on `cmd/kubeadm/test/cmd TestCmdInitConfig/can_load_current_component_config`, which is owned by cluster-lifecycle

That flake was resolved, but the job was then flaking on sig-scheduling failures, which kept the issue from being closed, but no one from sig-scheduling was investigating the issue.

Ideally, there would be one issue per SIG per set-of-failing-tests, with a test-grid and triage query that captures the flakes/failures the sig needs to resolve. For example, https://github.com/kubernetes/kubernetes/issues/93485 was opened, targeted at sig-scheduling, sig-filtered testgrid and triage links.

**Comment by liggitt** [comment]
cc @kubernetes/ci-signal

**Comment by hasheddan** [comment]
Thanks for opening this @liggitt! I’ll get this updated ASAP
