### ISSUE TITLE
Assemble Kubernetes 1.20 Release Team

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#1185]
It's hard to believe that the Kubernetes 1.19 release is almost here, but the time is upon us to start assembling the 1.20 release team.

Please review the [Release Team Selection Process](https://github.com/kubernetes/sig-release/tree/master/release-team#release-team-selection) docs for details on the process and criteria.

At this stage we only require nominations for Role Leads. Once role leads are nominated we will then send out a shadow application survey.

/sig release
/are release-team
/milestone v1.20

cc @onlydole @justaugustus @tpepper @LappleApple @saschagrunert @alejandrox1

**Comment by justaugustus** [comment]
/assign @jeremyrickard 
(incoming 1.20 RT Lead)

/assign @alejandrox1 
(TL for the Release Team subproject)

**Comment by puerco** [comment]
:tada:  I'm very happy to nominate @JamesLaverack as lead of the 1.20 Release Notes team!

**Comment by mkorbi** [comment]
For the 1.20 Comms Team I'm very happy to nominate @jrsapi to take over the lead 🚀

**Comment by savitharaghunathan** [comment]
It was an honor to work with 1.19 release team :)  

For the 1.20 Docs Team, I would like to nominate @annajung as the lead! 🎉

**Comment by palnabarun** [comment]
I am very happy to nominate @kikisdeliveryservice to take over the lead of the 1.20 Enhancements Team. :rocket: :tada: 

It has been an amazing experience and an honour to work with the 1.19 release team. :smile:

**Comment by gianarb** [comment]
I am happy to nominate @bai for 1.20 Bug Triage Team Lead!!

**Comment by joshti** [comment]
Hi there! @bowei asked I reach out through this issue to help us merge https://github.com/kubernetes/kubernetes/pull/94241 for k8s 1.20.

Presently the Tide bot isn't seeing the milestone label on the PR so we cannot land it (at-least that's how I understand it). Any thoughts would be appreciated for how we can move this forward 😄

**Comment by lachie83** [comment]
Docs shadows PR - https://github.com/kubernetes/sig-release/pull/1250

**Comment by bai** [comment]
Bug Triage shadows ref https://github.com/kubernetes/sig-release/pull/1252

**Comment by lachie83** [comment]
Bug triage - #1252 
CI Signal - #1254

**Comment by annajung** [comment]
Enhancement https://github.com/kubernetes/sig-release/pull/1259
Comms https://github.com/kubernetes/sig-release/pull/1260

**Comment by lachie83** [comment]
Comms - #1260
Enhancements - #1259

**Comment by lachie83** [comment]
Release notes - #1261

**Comment by lachie83** [comment]
We have a full 1.20 release team roster. I think we can close this @jeremyrickard

**Comment by jeremyrickard** [comment]
Please see https://github.com/kubernetes/sig-release/blob/master/releases/release-1.20/release_team.md for the complete team. Thank you everyone for stepping up for 1.20
