### ISSUE TITLE
Publish download links during release process

### ISSUE THREAD

**Issue by sftim** [kubernetes/sig-release#1186]
### What would you like to be added:

The release process as it stands is something like:
- tag source
- build binaries
- push binaries
- build and push OS packages & container images
- update marker files (e.g. https://dl.k8s.io/release/stable-1.12.txt)
- send release notification

I'd like to add a step that publishes download links:
- tag source
- build binaries
- push binaries
- build and push OS packages & container images
- update marker files (e.g. https://dl.k8s.io/release/stable-1.12.txt)
- **update https://kubernetes.io/ with links to downloads**
- send release notification

### Why is this needed:

SIG Docs are [planning](https://github.com/kubernetes/website/issues/20293) to add a web page that lists Kubernetes releases and downloads. It's a key omission from the existing website.

There are related areas that I'd welcome discussing between SIG Release and SIG Docs; for example, see the comment at https://github.com/kubernetes/website/pull/22736#issuecomment-677929028.

**Update**: https://downloadkubernetes.com/ is being donated to Kubernetes and might well be part of the solution here.

/kind feature
/sig docs
/sig release

**Comment by saschagrunert** [comment]
I agree, this should be automated and has been forgotten sometimes in the past.
/priority important-longterm

**Comment by sftim** [comment]
Related change: https://github.com/kubernetes/org/issues/2131

**Comment by puerco** [comment]
I think we're in a much better shape to implement this in the near term
/remove-lifecycle stale
