### ISSUE TITLE
Release Team Lead access for @jeremyrickard @hasheddan @palnabarun @savitharaghunathan 

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#1201]
### GitHub Username(s)

- @jeremyrickard
- @hasheddan
- @palnabarun
- @savitharaghunathan 

### Release Cycle

Kubernetes 1.20

### Prerequisites

- [x] Ensure new Release Team Lead:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)

### Onboarding

- [x] Release Team Lead has agreed to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.
  This must be done as an issue comment by the incoming Release Team Lead.
- [x] (https://github.com/kubernetes/org/pull/2141) Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
  - `sig-release`
- [x] (https://github.com/kubernetes/sig-release/pull/1202) Update `kubernetes/sig-release` `OWNERS`
  - Release Team Lead and Shadows
    - Add an `approvers` entry in `releases/release-x.y/OWNERS`
  - **Release Team Lead only**
    - In `OWNERS_ALIASES`, add an entry in the following sections:
      - `release-team`
      - `release-team-lead-role`
- [ ] (https://github.com/kubernetes/k8s.io/pull/1220) Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `lead@`
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [x] Manually grant access on the following Google Groups:
  - [kubernetes-release-team](https://groups.google.com/forum/#!forum/kubernetes-release-team) (Add as Manager)
- [x] Grant calendar access ([ref](https://kubernetes.slack.com/archives/G019Q4U283U/p1599579135033000))
- [x] Grant Zoom credentials ([host key](https://kubernetes.slack.com/archives/G019Q4U283U/p1599579361034000))

### Offboarding previous (1.19) team

- [x] (https://github.com/kubernetes/org/pull/2141) Remove from GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
- [ ] (https://github.com/kubernetes/k8s.io/pull/1220) Remove from Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `lead@`
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [x] Manually remove from the following Google Groups:
  - [kubernetes-release-team](https://groups.google.com/forum/#!forum/kubernetes-release-team) (Add as Manager)

cc: @kubernetes/release-engineering @kubernetes/release-team

**Comment by hasheddan** [comment]
I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by savitharaghunathan** [comment]
✨ I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by palnabarun** [comment]
I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by justaugustus** [comment]
https://github.com/kubernetes/k8s.io/pull/1220 will close this out.
I've taken care of all of the other manual bits and passed off the relevant info to @jeremyrickard.
