### ISSUE TITLE
Improve docs role handbook

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/sig-release#1207]
### Elaborate on the following release day tasks

- [x] Clarify on the permissions needed to add `tide/merge-blocker` label

- [x] Permissions required to cut a release. Request for temporary write access.

### Overall improvements:

- [x] ~~How to request access to view Netlify builds~~ - We will circle back later if this access is required

- [x] ~~Netlify access cleanup post release~~ -We will circle back later on this if Netlify access is granted

- [x] Setting up a URL for dev-[future-release] branch - Done (Duplicate of existing doc)

- [x] Configure release-[current-version] URL in Netlify after cutting release-[current-version] branch

- [x] Clarify on the embargo process. 

- [x] Frequent branch syncs (2/week and 3/week closer to release) 

- [x] Report the health of `dev-[future-release]` branch weekly (in #sig-docs & RT meetings)

- [x] Templates for deadline communication

- [x] Add shadows to milestone maintainers & cleanup 

- [x] ~~Define shadow roles & responsibilities~~ - Going to be a part of RT prioritization tasks

### Retro AI:

1.19:

- [x] ~~Leverage `Implemented` field from enhancements tracking sheet to determine if the corresponding docs PR can be merged/not~~ - Going to be an issue on its own as it is a little complicated

1.17:

- [x] Look into improving the current process of tracking enhancement docs with help from the enhancement team. The goal is to reduce continuous pinging noise for the enhancement and to make sure enhancement owners are aware of the docs requirement earlier in the process (Based on discussion with Enhancement lead and 1.17 retro item https://kubernetes.slack.com/archives/C2C40FMNF/p1600864910029100)

- [x] Add general obligations/expectation for a lead in the docs role handbook

cc: @jimangel  

/assign

**Comment by savitharaghunathan** [comment]
cc: @annajung

**Comment by annajung** [comment]
Hey @savitharaghunathan, can we add the following to the description? Looks like I don't have access to edit 

- [ ] Look into improving the current process of tracking enhancement docs with help from the enhancement team. The goal is to reduce continuous pinging noise for the enhancement and to make sure enhancement owners are aware of the docs requirement earlier in the process (Based on discussion with Enhancement lead and 1.17 retro item https://kubernetes.slack.com/archives/C2C40FMNF/p1600864910029100)

**Comment by savitharaghunathan** [comment]
@annajung Thank you for the detailed description. I added it to the issue 🎉

**Comment by annajung** [comment]
Adding another task to the list based on 1.17 retro
- [ ] Add general obligations/expectation for a lead in the docs role handbook

**Comment by annajung** [comment]
@savitharaghunathan We can mark "Templates for deadline communication - PR in progress" as done :) 

I think we can also mark " Look into improving the current process of tracking enhancement docs with help from the enhancement team..." as done. I've been working with Kirsten during the release to make the process smoother which involved adding docs placeholder deadline for the enhancement team and adding docs into the enhancement issue template (https://github.com/kubernetes/enhancements/pull/2016).

**Comment by LappleApple** [comment]
Updated/checked both boxes -- great progress, team! Only three more items to go...

**Comment by annajung** [comment]
Also, commenting on "Leverage Implemented field from enhancements tracking sheet to determine if the corresponding docs PR can be merged/not", I think we actually want to make sure k/k prs are merged in and the enhancement team is one that's responsible for making sure the enhancement is not tracked if it's not in the "implementable" state. 

So, I'm not sure what the action item here is. But, during the sig docs quarterly planning meeting, I'm planning on discussing how to automate the k/k pr "look up" for docs in an automated way. Regardless, I think this should be a separate issue as it's not an easy change.

**Comment by savitharaghunathan** [comment]
> Also, commenting on "Leverage Implemented field from enhancements tracking sheet to determine if the corresponding docs PR can be merged/not", I think we actually want to make sure k/k prs are merged in and the enhancement team is one that's responsible for making sure the enhancement is not tracked if it's not in the "implementable" state.
> 
> So, I'm not sure what the action item here is. But, during the sig docs quarterly planning meeting, I'm planning on discussing how to automate the k/k pr "look up" for docs in an automated way. Regardless, I think this should be a separate issue as it's not an easy change.

@annajung : Anna, I marked it as done and added a note. Can you open an issue to track it, please? Thanks :)

**Comment by annajung** [comment]
Yes, I'll wait until after the sig docs planning today
