### ISSUE TITLE
Add the contact information in case of job issue it will send out a notification

### ISSUE THREAD

**Issue by cpanato** [kubernetes/sig-release#1216]
This is to add contact information for existing jobs.

Some jobs do not have contact information so it cannot send out notifications when the job is having issues.

/area release-eng
/area ci
/kind documentation
/priority important-soon
/milestone v1.20

**Comment by alejandrox1** [comment]
re-opening: this one is useful to work along the proposed work of https://github.com/kubernetes/test-infra/issues/18599 and do what we can in the scope of sig release.
/reopen

**Comment by cpanato** [comment]
added this to my next week backlog

**Comment by saschagrunert** [comment]
Took my freedom to rename the issue to optically match with others.

**Comment by hasheddan** [comment]
@cpanato is this issue scoped to _all_ CI or just sig-release? It looks like we are currently covered for sig-release baords.

**Comment by cpanato** [comment]
just sig-release. and you are right, i forgot to close this

/close
