### ISSUE TITLE
Remove SIG-PM references from Enhancements Lead handbook

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/sig-release#1222]
#### What would you like to be added:

The [Enhancements Lead handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/enhancements) has references to SIG-PM that need to be updated.

#### Why is this needed:

SIG-PM was [retired](https://github.com/kubernetes/community/pull/4722) back in April.

I didn't see this tracked in any open issues or PRs.

**Comment by kikisdeliveryservice** [comment]
Coincidentally this PR: https://github.com/kubernetes/sig-release/pull/1228 removes Sig PM from one of the paras and @palnabarun has a PR forthcoming that removes the rest (along with a few other updates)
