### ISSUE TITLE
Produce on-boarding video playlist for new CI Signal shadows

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/sig-release#1223]
The CI Signal team want to create a series of short videos that help onboard new CI Signal Shadows.

The Videos will provide all relevant information pertaining to Continuous Integration and how CI is implemented on the kubernetes/kubernetes project

The videos are specifically targeted at people who are considering becoming CI Signal shadows but it will also help other k8s contributors better understand the work carried out to discover tests that produce non-deterministic results and why it's important to eliminate flakes.

I'm logging an issue here to track script creation for these videos but I would like help on this.

Here is a rough guide as to the list of the video content that I think we could produce.

I see this content as being a mix of VO, animated tours of our CI and GH tooling and perhaps finishing up with some demos of using the tooling to report on specific flakes.
   
**Video 1** CI Overview - for beginners, can be skipped
**Video 2** The Kubernetes CI Signal Team - Overview / benefits of participating
**Video 3** How Continuous Integration is run on the Kubernetes Project   
**Video 4** Day-to-day work of the Kubernetes CI Signal Team
**Video 5** How CI Signal Team work with Test Infra

I have some script content written up already which I submit as a PR attached to this issue.

**Comment by RobertKielty** [comment]
@hasheddan and myself will look at this after the 1.20 Release

**Comment by thejoycekung** [comment]
@RobertKielty thoughts on keeping this open?

I've been using the talk that you and Dan did for the Contributors Summit as an onboarding resource so far: https://www.youtube.com/watch?v=bttEcArAjUw

**Comment by RobertKielty** [comment]
@thejoycekung I'm delighted that you are using that session for on-boarding I had this requirement in mind when I proposed the talk.

I also prepared a HackMD doc to cover the talk ... 

http://bit.ly/k8s-ci

If you are happy that the session is good enough to cover the on-boarding of new CI Signalers I would be ok with closing this issue.

**Comment by thejoycekung** [comment]
/cc @mkorbi @n3wscott @PriyankaH21 @s278gupt 

If anyone has time/is interested in a quick & easy PR, we should add these two links (the CI Signal walkthrough video and the HackMD notes) to the [CI Signal role handbook](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/ci-signal/README.md) for future CI Signal members. If you want to work on it, just comment `/assign` so that the rest of us are aware that you're taking this task.
