### ISSUE TITLE
Create some more CI signal documentation 

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#1224]
This issue may go with #1223 .
Overall, it would be good to have some video and writing on what the following tools are and how to use them

- [ ] Testgrid https://testgrid.k8s.io/
- [ ]  Triage https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-e2e-gce
- [ ]  Prow
- [ ] Prow monitoring https://monitoring.prow.k8s.io/?orgId=1
- [ ]  Prow status https://prow.k8s.io/
- [ ]  Prow tide pool https://prow.k8s.io/tide
- [ ]  GCP Prow dashboards https://github.com/kubernetes/k8s.io/blob/85a327269e221e9e4afd9846a4606327334bf1ba/groups/groups.yaml#L610
- [ ]  How e2e testswork
- [ ]  What the role of Ginkgo is and how we use it

/assign
/assign @hasheddan @roberthbailey 
/kind documentation
/priority important-soon

**Comment by hasheddan** [comment]
/assign @RobertKielty 
/unassign @roberthbailey 

Just a guess ;)

**Comment by hasheddan** [comment]
I can get started by writing up an outline for testgrid :+1:

**Comment by RobertKielty** [comment]
I'd also be interested in reading about how to understand Kubernetes behaviour by reading an e2e test.

**Comment by thejoycekung** [comment]
PR around more CI signal docs: https://github.com/kubernetes/community/pull/5449
