### ISSUE TITLE
Release Manager access for Marko Mudrinić (xmudrii)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1226]
### GitHub Username

@xmudrii 

### [Release Manager](https://git.k8s.io/sig-release/release-managers.md) role

Release Manager

### Tenure

permanent

### Release Manager Onboarding

**All pull requests within these checklists should be marked with an _explicit_ hold and only released once approved by a Release Engineering subproject owner.**

- [x] Addition of a new Release Manager has been discussed with and approved by Release Engineering subproject owners
- [x] Ensure new Release Manager:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
- [x] (https://github.com/kubernetes/sig-release/pull/1225) Update [Release Managers](https://git.k8s.io/sig-release/release-managers.md) page to include the new Release Manager

### Release Manager

- [x] Release Manager has agreed to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.
  (This must be done as an issue comment by the incoming Release Manager.)
- [x] (https://github.com/kubernetes/org/pull/2191) Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-engineering`
  - `release-managers`
- [x] Update `OWNERS`
  - [x] (https://github.com/kubernetes/sig-release/pull/1276) `kubernetes/sig-release` `OWNERS_ALIASES`
    - Add entry in the `release-engineering-reviewers` section
      (only if they are not already in the `release-engineering-reviewers`
      or `release-engineering-approvers` section)
  - [x] (https://github.com/kubernetes/release/pull/1624) `kubernetes/release` `OWNERS_ALIASES`
    - Add entry in the `release-engineering-reviewers` section
      (only if they are not already in the `release-engineering-reviewers`
      or `release-engineering-approvers` section)
  - [x] (https://github.com/kubernetes/test-infra/pull/19519) `kubernetes/test-infra` `OWNERS_ALIASES`
    - Add entry in the `release-engineering-reviewers` section
      (only if they are not already in the `release-engineering-reviewers`
      or `release-engineering-approvers` section)
  - [x] (https://github.com/kubernetes/kubernetes/pull/95478) `kubernetes/kubernetes` `OWNERS_ALIASES`
    - Add entry in the `release-engineering-reviewers` section
      (only if they are not already in the `release-engineering-reviewers`
      or `release-engineering-approvers` section)
- [x] (https://github.com/kubernetes/k8s.io/pull/1252) Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-editors@`
  - `k8s-infra-release-viewers@`
  - `release-managers@`
  - `release-managers-private@`
- [x] Manually grant permission to post on [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
- [x] Manually add to the [Release Team Google Group](https://groups.google.com/forum/#!forum/kubernetes-release-team)
- [x] (https://github.com/kubernetes/community/pull/5150) Update Slack `release-managers` User Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)
- [x] Manually add to the [#release-private](https://kubernetes.slack.com/archives/GKEA5EL67) Slack channel

cc: @kubernetes/release-engineering
/assign

**Comment by xmudrii** [comment]
I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by xmudrii** [comment]
@justaugustus I've already joined the required mailing lists (k-dev and sig-release) and Slack channels (sig-release and release-management).

**Comment by justaugustus** [comment]
Marko, would you mind completing the OWNERS file updates listed in the checklist?
/assign @xmudrii

**Comment by xmudrii** [comment]
@justaugustus I've created PRs in k/k and k/test-infra to update the OWNERS file. I've updated this issue with links to the PRs.

I'm already in the OWNERS file in k/sig-release and k/release in the release-engineering-reviewers group, but the description says Release Manager Associate, e.g. https://github.com/kubernetes/sig-release/blob/c89b433b7909a39d41e0856d2108b8465e8b8f2b/OWNERS_ALIASES#L28

Is that okay or should I change it to Release Manager?

**Comment by justaugustus** [comment]
@xmudrii -- for k/release and k/sig-release, you actually will want to:
- Add yourself into the `release-engineering-approvers` section
- Remove yourself from `release-engineering-reviewers`
- Update the role comment description to "Release Manager"

**Comment by xmudrii** [comment]
@justaugustus All required OWNERS files are now updated. Is there anything else I should take care of?

**Comment by justaugustus** [comment]
We're all set here!
/close
