### ISSUE TITLE
alpha.1 documentation

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#1229]
Looking back through 1.19, 1.18, 1.17 releases' README.md listed schedules, the alpha.1 release is not listed as a trailing action for the release.  In 1.19 and 1.18 it is not listed, and that carried forward to 1.20.  For 1.17 it was listed as an opening action for the release.

This leaves the when/why of the alpha.1 release ambiguous and that's carried forward some confusion into the 1.20 plan.

We should decide if the N+1 alpha.1 is the responsibility of the N Release Team or the N+1 Release Team and update docs accordingly.

**Comment by justaugustus** [comment]
FWIW, this HAS been documented in the past: https://github.com/kubernetes/sig-release/blob/667cf0d44b8fdd41894830b32e1c91415bdc763c/release-engineering/role-handbooks/branch-manager.md#cut-next-alpha / https://github.com/kubernetes/sig-release/pull/965

---

#### Cut next alpha

Recall that an alpha.0 of the next minor release was created during [branch creation](#branch-creation).

The previously created alpha.0 is now several commits behind `master`.
As an example, see the [comparison between the `v1.18.0-alpha.0` (after 1.17 branch creation) and `v1.18.0-alpha.1` (after 1.17.0 release) tags](https://github.com/kubernetes/kubernetes/compare/v1.18.0-alpha.0...v1.18.0-alpha.1).

To assist downstream consumers of Kubernetes, a new alpha should be cut to bring our next release tag to the tip of `master`.

Get the latest build version at `master`:

```shell
gsutil cat gs://kubernetes-release-dev/ci/latest.txt
```

Begin the release process:

```shell
krel gcbmgr --stage --branch master --build-version=<version-from-previous-step>
```

Proceed with the [alpha release steps](#alpha-releases).

Example `1.18.0-alpha.1` release issue template: https://github.com/kubernetes/sig-release/issues/928

---

**Comment by tpepper** [comment]
Yep.  I should've been more clear that this is about "when", not "how" and have hopefully added words to that in the description now.  I expect this issue to be resolved through a decision which leads to a PR 1.20 README.md schedule to indicate the 1.20 alpha.1 happens at the beginning of the 1.20 cycle, but more generally then for later does it continue to be 1.N's 1.N.0-alpha.1 happens at the beginning of the 1.N cycle or the end of the prior 1.(N-1) cycle.  The implementation will still be the release managers job to do and as described in their handbook.

**Comment by saschagrunert** [comment]
@xmudrii is this part of the docs enhancements? Do we need this issue as separate one?

**Comment by xmudrii** [comment]
@saschagrunert I don't think that we need a separate issue. I updated the refactor issue to mention this, so let's close this issue.
/close
