### ISSUE TITLE
Document Features role / responsibilities

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#124]
As a Release Team member shadowing the Features Lead role, it should be my responsibility to explicitly document and / or revise documentation that corresponds to that role.

Documentation should delineate:
- Role overview
- Responsibilities
- Access requirements

Here's a [good example](https://github.com/kubernetes/sig-release/blob/master/release-process-documentation/release-team-guides/ci-signal-playbook.md) of what the docs might look like.

We should also then cross-link that documentation to the [features repo](https://github.com/kubernetes/features).

/cc @idvoretskyi 
/assign

**Comment by justaugustus** [comment]
Ohhh, looks like this repo isn't bot-ified and I don't have access to pick up issues, which I may open an issue for.
I'm picking this issue up though.

**Comment by idvoretskyi** [comment]
Will be happy to work with you on this, @justaugustus!

**Comment by justaugustus** [comment]
Draft of the Features Lead handbook can be found [here](https://docs.google.com/document/d/1WPB0N4kjVN_CY205dBEzs9KULWgkBeW1GASV4YHaK_w/edit?usp=sharing).

@idvoretskyi @jdumars @jberkus @tpepper -- still WIP, but open for early feedback. I'd like to workshop it there before putting up the PR.

**Comment by tpepper** [comment]
Also should have more description around what qualifies as a tracked feature or not, and managing any gap between k/k milestone tagged issues and k/features during the features definition phase early in the cycle.

**Comment by justaugustus** [comment]
Features Lead Handbook PR up for review: https://github.com/kubernetes/sig-release/pull/231
