### ISSUE TITLE
Create a Release calendar

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#125]
I think it'd be pretty cool to have a Release calendar, which tracks the timeline laid out [here](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.11/release-1.11.md).
Ideally it lives outside of the `sig-release` calendar and survives across releases.

Thoughts @jberkus ?

**Comment by idvoretskyi** [comment]
@justaugustus are you speaking about the Google Calendar?

If yes, we may incorporate it into the Community-wide calendar. /cc @castrojo

**Comment by justaugustus** [comment]
Oooo, putting in the Community calendar would work nicely!

**Comment by castrojo** [comment]
I can either add someone to the release team to the main community calendar to add the events directly, or you can share individual events from your existing calendar with `cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com` to put them on the community calendar. 

Let me know which you would prefer!

**Comment by justaugustus** [comment]
@castrojo cool! If you add me I can populate the release events for the calendar. :)
`mylastname @ redhat.com`

**Comment by justaugustus** [comment]
@castrojo Thanks for hooking up access. 
I've just updated the Community calendar to include the `v1.11` [release key dates](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.11/release-1.11.md) and will shoot out a quick note to the group.

Good point on adding the step to the release process. 
I'll PR adding that step, but we need to decide who should be doing it as well.

Communications? Release Manager? Whoever volunteers for it?
Thoughts @jberkus / @idvoretskyi ?

**Comment by jberkus** [comment]
This should probably go into the Release Lead Handbook: https://github.com/kubernetes/sig-release/blob/master/release-process-documentation/release-team-guides/release-lead.md

**Comment by justaugustus** [comment]
Thanks for adding this, @nikhita!

**Comment by justaugustus** [comment]
This has since been added to the RT Lead Handbook: https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/release-lead.md

/close
