### ISSUE TITLE
Add Unconscious Bias Training requirement for Release Team Lead Onboarding

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#1251]
#### What would you like to be added:

Add [CNCF inclusive speaker training](https://training.linuxfoundation.org/training/inclusive-speaker-orientation/) to release lead on-boarding Github issue template. 

Additionally, I think we should consider making this a requirement for leads for the other release team roles (enhancements, etc). 

#### Why is this needed:
Ref: https://github.com/kubernetes/community/pull/4940

[Steering]( https://github.com/kubernetes/community/pull/4940) has added a requirement that chairs and tech leads need to take the CNCF inclusive speaker training: 

>As you are all aware, the Kubernetes community is both large and diverse. We have folks working on the project from many different backgrounds. Inclusivity is a core value[1] of our project, and we recognize the strength and success that comes from having an environment that is welcoming and respectful to that diversity.

The release team is a small part of the community, but mirrors the diversity of the community. With this in mind, I propose that we add this requirement to release lead on-boarding (and maybe for all sub-team leads?) to help ensure that the release team models these same behaviors. 

/area release-team
/milestone 1.20

**Comment by jeremyrickard** [comment]
ooops!

/milestone v1.20

**Comment by savitharaghunathan** [comment]
> > As you are all aware, the Kubernetes community is both large and diverse. We have folks working on the project from many different backgrounds. Inclusivity is a core value[1] of our project, and we recognize the strength and success that comes from having an environment that is welcoming and respectful to that diversity.
> 
> The release team is a small part of the community, but mirrors the diversity of the community. With this in mind, I propose that we add this requirement to release lead on-boarding (and maybe for all sub-team leads?) to help ensure that the release team models these same behaviors.
> 

+1 to adding the training as a requirement 🎉
