### ISSUE TITLE
CI Signal Project Board not accepting new flakes

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/sig-release#1262]
#### What happened:

The 1.20 CI Signal release team are logging flakes in issues

Issues are not appearing on https://github.com/orgs/kubernetes/projects/11 
Sample issue logged yesterday note present on board https://github.com/kubernetes/kubernetes/issues/95011

#### What you expected to happen:
See logged flakes appear on the board

#### How to reproduce it (as minimally and precisely as possible):
Log an issue with kind flake

#### Anything else we need to know?:
Impacts day-to-day CI Signal work flow 

The board provides 
 - a rapid means of checking if a flake has been logged
 - a configurable picture of the state of play of the effort that SIGs are putting into flake removal.    
 - blocks reporting/analytics development 
#### Environment:
Github / CI Signal day-to-day work

**Comment by hkamel** [comment]
@RobertKielty I remember in 1.19 that the board will not show the items automatically. There always a manual step where we add the issue by the "Add card" option on the board.

**Comment by justaugustus** [comment]
AFAIK, no automation today controls the addition of issues to org-level project boards.

Issues/PRs need to be manually added to boards.
ref: https://docs.github.com/en/github/managing-your-work-on-github/adding-issues-and-pull-requests-to-a-project-board

/close

**Comment by justaugustus** [comment]
ref: https://github.com/kubernetes/test-infra/issues/9925
(If anyone is interested in potentially working on this)

**Comment by RobertKielty** [comment]
@justaugustus @hkamel Thanks for the help.

Building on what @hkamel pointed out the manual way of placing cards on the board is 

On top right hand corner of the board

Click **+ Add Cards** 

Then enter a query to find issues you want on the board. 

So for all the v1.20 flakes we can use

`is:issue is:open [FLAKE] label:kind/flake sort:updated-desc milestone:v1.20 `

The query above is the same as the query format for finding issues

It can be built most easily by going to the Issues page and clicking on the labels you need to refine the list.

/close
