### ISSUE TITLE
Cut 1.19.3 release

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/sig-release#1282]
## Scheduled to happen: Wed, 2020-10-14

- [x] Screenshot unhealthy release branch testgrid boards and add them as a comment

- [x] Stage & release
  - [x] Notify [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y): [see notification](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1602659924179000)
  
  - [x] Collect metrics and add them to the `Release steps` table below

- [x] Send notification [email](https://groups.google.com/g/kubernetes-announce/c/SBaZnFcW1RU)

## Release steps

[krel](https://github.com/kubernetes/release/tree/master/docs/krel) version:
```
GitVersion:    v0.4.1
GitCommit:     27ed84c111ee78ab18b7714dd055346c903bb03a
GitTreeState:  clean
BuildDate:     2020-10-13T08:40:32Z
GoVersion:     go1.14.1
Compiler:      gc
Platform:      darwin/amd64
```

| Step | Command | Link | Start | Duration | Succeeded? |
| --- | --- | --- | --- | --- | --- |
| Mock stage | `krel gcbmgr --stage --type official --branch release-1.19 --build-version=v1.19.3-rc.0.69+37babbd0e76c11` | https://console.cloud.google.com/cloud-build/builds/01b2a651-bd67-4ce9-bd7b-82c44391e7fa| 14 October 2020 at 09:35:23 GMT+2 | 1:14:27 | YES |
| Mock release | `krel gcbmgr --release --type official --branch release-1.19 --build-version=v1.19.3-rc.0.69+37babbd0e76c11` | https://console.cloud.google.com/cloud-build/builds/2678a968-b225-4069-bfe3-9ff23f183657 |  14 October 2020 at 11:19:49 GMT+2| 00:21:30 | YES |
| Stage | `krel gcbmgr --stage --type official --branch release-1.19 --build-version=v1.19.3-rc.0.69+37babbd0e76c11 --nomock` | https://console.cloud.google.com/cloud-build/builds/bcf98f29-68ad-4b5a-8746-4a51eca5bf2a?project=kubernetes-release-test |  14 October 2020 at 14:36:28 GMT+2| 01:20:02 | YES |
| Image Promotion | `krel promote-images -i --fork=mkorbi--tag=v1.19.3` | https://github.com/kubernetes/k8s.io/pull/1329 |  |  |  |
| Release | `krel gcbmgr --release --type official --branch release-1.19 --build-version=v1.19.3-rc.0.69+37babbd0e76c11 --nomock` | https://console.cloud.google.com/cloud-build/builds/027b468a-f2a6-4f92-a8e0-ba17b6cb3b3a| 14 October 2020 at 18:47:40 GMT+2 | 00:09:17 | YES |
| Cut packages  | -- | [DONE](https://github.com/kubernetes/kubernetes/releases/tag/v1.19.3) |  |  |  |
| Notify | -- |  |  | -- |  |

## Action items

- [x] https://github.com/kubernetes/k8s.io/pull/1329

## Open questions

/milestone v1.19
/assign @mkorbi 
/cc @kubernetes/release-managers
/priority important-soon
/kind documentation

**Comment by saschagrunert** [comment]
cc @gianarb

**Comment by mkorbi** [comment]
### Failing testgrid jobs

#### sig-release-master-blocking
[Link](https://testgrid.k8s.io/sig-release-1.19-blocking)

#### sig-release-master-informing
[Link](https://testgrid.k8s.io/sig-release-1.19-informing)
<details><summary>`sig-release-master-informing`</summary><p>
<img width="1301" alt="sig-release-master-innforming" src="https://user-images.githubusercontent.com/16919345/96085220-c8c81e80-0ec0-11eb-8663-fe7c7f9b4da4.png">
</p></details>

**Comment by mkorbi** [comment]
@saschagrunert did I miss something?

**Comment by cpanato** [comment]
@mkorbi all looks good.

just a small comment next time you can use the `./testgridshot xxxx` to generate the testgrid comments
