### ISSUE TITLE
Cut 1.20.0-alpha.3 release

### ISSUE THREAD

**Issue by gianarb** [kubernetes/sig-release#1296]
## Scheduled to happen: Tue, 2020-10-20

- [x] Screenshot unhealthy release branch testgrid boards and add them as a comment

- [x] Stage & release
  - [x] Notify [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y): [see notification](https://link-to-slack-message)
  
  - [x] Collect metrics and add them to the `Release steps` table below

- [x] Send notification [email](https://link-to-email-on-kubernetes-announce-google-group)

## Release steps

[krel](https://github.com/kubernetes/release/tree/master/docs/krel) version:
```
GitVersion:    v0.4.1
GitCommit:     6ef811647cf73596a16811b877779c74c9b4afb3
GitTreeState:  clean
BuildDate:     2020-10-20T06:46:12Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      darwin/amd64
```

| Step | Command | Link | Start | Duration | Succeeded? |
| --- | --- | --- | --- | --- | --- |
| Mock stage | `krel gcbmgr --stage --type alpha --branch master` | https://console.cloud.google.com/cloud-build/builds/e830b07b-d80e-413b-84f5-517b56aa38d9?project=648026197307 | Tue Oct 20 09:43:26 CEST 2020 | 00:37:26 | yes |
| Mock release | `krel gcbmgr --release --type alpha --branch master --build-version=v1.20.0-alpha.2.191+6d3ccd8e6c409a` | https://console.cloud.google.com/cloud-build/builds/3f4d809b-2c7b-483d-91c1-8ccbcd44fc81?project=648026197307 | Tue Oct 20 10:25:51 CEST 2020 | 00:07:36 | yes |
| Stage | krel gcbmgr --stage --type alpha --branch master --nomock | https://console.cloud.google.com/cloud-build/builds/990fa859-45d6-4c7e-9fd0-026d976ce7c2?project=648026197307 | Tue Oct 20 10:45:05 CEST 2020 | 00:40:40 | yes |
| Image Promotion | `krel promote-images -i --fork=gianarb --tag=v1.20.0-alpha.3` | https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-cip/1318488168189661184 | Tue Oct 20 11:39:15 CEST 2020 | 00:02:47 | yes |
| Release | `krel gcbmgr --release --nomock --type alpha --branch master --build-version=v1.20.0-alpha.2.191+6d3ccd8e6c409a` | https://console.cloud.google.com/cloud-build/builds/421f0141-9cfb-4263-a0db-d6796a1da3c6?project=kubernetes-release-test | Tue Oct 20 11:51:24 CEST 2020 | 00:07:04 | yes |
| Notify | `krel announce send --nomock --tag v1.20.0-alpha.3` |  | Tue Oct 20 12:10:22 CEST 2020 | | yes  |

## Open questions

/milestone v1.20
/assign @gianarb
/cc @kubernetes/release-managers
/priority important-soon
/kind documentation

**Comment by gianarb** [comment]
# Failing testgrid jobs

* [sig-release-master-blocking](https://testgrid.k8s.io/sig-release-master-blocking)
* [sig-release-master-informing](https://testgrid.k8s.io/sig-release-master-informing)

<details><summary> 2020-10-20 07:03:35-500 FLAKY sig-release-master-blocking#conformance-ga-only</summary></p>

![Screenshot 2020-10-20 at 09 03 26](https://user-images.githubusercontent.com/1630267/96551792-238fba80-12b3-11eb-9709-35c5c7dd837d.png)

</p></details>

<details><summary> 2020-10-20 07:09:38-500 FLAKY sig-release-master-blocking#gce-ubuntu-master-containerd</summary></p>

![Screenshot 2020-10-20 at 09 09 17](https://user-images.githubusercontent.com/1630267/96552375-f42d7d80-12b3-11eb-87e5-4f4de9139f6e.png)

</p></details>

<details><summary> 2020-10-20 07:11:40-500 FLAKY sig-release-master-blocking#Conformance - GCE - master </summary></p>

![Screenshot 2020-10-20 at 09 11 52](https://user-images.githubusercontent.com/1630267/96552625-4ec6d980-12b4-11eb-928c-94c1165fc175.png)

</p></details>

<details><summary> 2020-10-20 07:13:45-500 FLAKY sig-release-master-blocking#integration-master</summary></p>

![Screenshot 2020-10-20 at 09 13 28](https://user-images.githubusercontent.com/1630267/96552770-86358600-12b4-11eb-8183-5fae64c015e7.png)

</p></details>

<details><summary> 2020-10-20 07:14:47-500 FLAKY sig-release-master-blocking#kind-master-parallel</summary></p>

![Screenshot 2020-10-20 at 09 14 06](https://user-images.githubusercontent.com/1630267/96552825-9e0d0a00-12b4-11eb-9a09-212649e88bc3.png)

</p></details>

<details><summary> 2020-10-20 07:15:49-500 FLAKY sig-release-master-blocking#kind-ipv6-master-parallel</summary></p>

![Screenshot 2020-10-20 at 09 15 06](https://user-images.githubusercontent.com/1630267/96552955-c268e680-12b4-11eb-9b9d-e08bb2bfffb3.png)

</p></details>

<details><summary> 2020-10-20 07:16:53-500 FLAKY sig-release-master-blocking#node-kubelet-master</summary></p>

![Screenshot 2020-10-20 at 09 16 40](https://user-images.githubusercontent.com/1630267/96553115-f93efc80-12b4-11eb-973f-accd1984503e.png)

</p></details>

<details><summary> 2020-10-20 07:22:53-500 FAILED sig-release-master-informing#Conformance 
 OpenStack</summary></p>

![Screenshot 2020-10-20 at 09 22 42](https://user-images.githubusercontent.com/1630267/96553693-d06b3700-12b5-11eb-8b05-53fcea7d0ff8.png)

</p></details>

<details><summary> 2020-10-20 07:23:53-500 FAILED sig-release-master-informing#capg-conformance-v1alpha3-k8s-master</summary></p>

![Screenshot 2020-10-20 at 09 23 28](https://user-images.githubusercontent.com/1630267/96553763-ec6ed880-12b5-11eb-9f99-530f572eafca.png)

</p></details>

<details><summary> 2020-10-20 07:25:53-500 FLAKY sig-release-master-informing#gce-master-scale-correctness</summary></p>

![Screenshot 2020-10-20 at 09 25 44](https://user-images.githubusercontent.com/1630267/96553987-3e176300-12b6-11eb-9536-fc326908ee83.png)
</p></details>

<details><summary> 2020-10-20 07:27:53-500 FLAKY sig-release-master-informing#gce-master-scale-performance</summary></p>

![Screenshot 2020-10-20 at 09 27 25](https://user-images.githubusercontent.com/1630267/96554176-79199680-12b6-11eb-85b5-2b03db6bb376.png)

</p></details>

<details><summary> 2020-10-20 07:28:53-500 FLAKY sig-release-master-informing#gce-cos-master-serial</summary></p>

![Screenshot 2020-10-20 at 09 28 13](https://user-images.githubusercontent.com/1630267/96554249-951d3800-12b6-11eb-8c94-837fbf9894da.png)
</p></details>

<details><summary> 2020-10-20 07:28:53-500 FLAKY sig-release-master-informing#gce-cos-master-slow</summary></p>

![Screenshot 2020-10-20 at 09 28 52](https://user-images.githubusercontent.com/1630267/96554332-af571600-12b6-11eb-8fe7-c993df864cc7.png)

</p></details>

<details><summary> 2020-10-20 07:30:53-500 FLAKY sig-release-master-informing#gce-ubuntu-master-default</summary></p>

![Screenshot 2020-10-20 at 09 30 03](https://user-images.githubusercontent.com/1630267/96554453-d877a680-12b6-11eb-809f-8988a9741f7f.png)

</p></details>

<details><summary> 2020-10-20 07:30:53-500 FLAKY sig-release-master-informing#gce-windows-1909-master</summary></p>
![Screenshot 2020-10-20 at 09 31 11](https://user-images.githubusercontent.com/1630267/96554580-00670a00-12b7-11eb-8e49-9ef9c44ca729.png)
</p></details>

<details><summary> 2020-10-20 07:32:53-500 FLAKY sig-release-master-informing#gce-windows-2019-master
</summary></p>

![Screenshot 2020-10-20 at 09 32 02](https://user-images.githubusercontent.com/1630267/96554655-1e346f00-12b7-11eb-875e-0b119bc7dd1a.png)

</p></details>

<details><summary> 2020-10-20 07:34:53-500 FLAKY sig-release-master-informing#node-kubelet-features-master</summary></p>

![Screenshot 2020-10-20 at 09 32 52](https://user-images.githubusercontent.com/1630267/96554743-3c01d400-12b7-11eb-9206-be04dca6d4ee.png)

</p></details>

<details><summary> 2020-10-20 07:34:53-500 FLAKY sig-release-master-informing#capa-conformance-v1alpha3-k8s-master</summary></p>

![Screenshot 2020-10-20 at 09 33 48](https://user-images.githubusercontent.com/1630267/96554896-6c497280-12b7-11eb-8c23-0571edea15a4.png)

</p></details>

**Comment by gianarb** [comment]
The testgridshot script failed for me, so I had to take them manually. @cpanato used the script, here the result:

### Testgrid dashboards for master
Boards checked for FAILING:
- [sig-release-master-blocking](https://testgrid.k8s.io/sig-release-master-blocking)
- [sig-release-master-informing](https://testgrid.k8s.io/sig-release-master-informing)
<details><summary><tt>2020-10-20 07:49:22+0000</tt> FAILING sig-release-master-informing#Conformance - OpenStack <a href="https://testgrid.k8s.io/sig-release-master-informing#Conformance - OpenStack&width=30">[testgrid]</a></summary><p>
![sig-release-master-informing#Conformance - OpenStack](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2020-10-20_07-49-14_22200a68/sig_release_master_informing_Conformance___OpenStack.jpg)
</p></details>
<details><summary><tt>2020-10-20 07:49:20+0000</tt> FAILING sig-release-master-informing#capa-conformance-v1alpha3-k8s-master <a href="https://testgrid.k8s.io/sig-release-master-informing#capa-conformance-v1alpha3-k8s-master&width=30">[testgrid]</a></summary><p>
![sig-release-master-informing#capa-conformance-v1alpha3-k8s-master](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2020-10-20_07-49-14_22200a68/sig_release_master_informing_capa_conformance_v1alpha3_k8s_master.jpg)
</p></details>
<details><summary><tt>2020-10-20 07:49:21+0000</tt> FAILING sig-release-master-informing#capg-conformance-v1alpha3-k8s-master <a href="https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-v1alpha3-k8s-master&width=30">[testgrid]</a></summary><p>
![sig-release-master-informing#capg-conformance-v1alpha3-k8s-master](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2020-10-20_07-49-14_22200a68/sig_release_master_informing_capg_conformance_v1alpha3_k8s_master.jpg)
</p></details>

**Comment by saschagrunert** [comment]
It's done 
/close
