### ISSUE TITLE
SIG Chair offboarding for Tim Pepper

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1321]
### GitHub Username

@tpepper (ref: https://github.com/kubernetes/community/pull/5286)

### [Chair/Technical Lead](https://git.k8s.io/sig-release/lead/onboarding.md) role

Chair

### Community requirements

_Note that this leadership change was proposed prior to new requirements being established by Steering in https://github.com/kubernetes/community/pull/5291._

#### Discuss with SIG leadership

- [x] Discuss the proposed changes with the current leadership.

#### Discuss with the SIG and wider community

- [x] Send an email to the SIG/WG/UG mailing list and cc the [kubernetes-dev]
mailing list: https://groups.google.com/g/kubernetes-dev/c/PId43yVF6cs/m/jlS0uaojAgAJ
  At a minimum, the email should contain:
  - [x] intent to step down as the current lead
  - [x] if nominating another lead
    - [x] 1-2 lines about why they are being nominated
    - [x] contacts to privately reach out to for questions (current leads)
          or concerns (current leads + [steering-private]) about the nomination
  - [x] ~if this was discussed in a meeting, link to meeting notes~
    - We discussed in the leads group DM, then private leads meeting, then sent notice to the community via [PR](https://github.com/kubernetes/community/pull/5286) and then [k-dev thread](https://groups.google.com/g/kubernetes-dev/c/PId43yVF6cs/m/jlS0uaojAgAJ).
  - [x] lazy consensus deadline of at least one week
    - Posted: 11/3
    - Lazy consensus timeout: 11/13

#### New lead requirements

(Tracking onboarding for @saschagrunert and @hasheddan here: https://github.com/kubernetes/sig-release/issues/1322)

- [x] If nominating another lead, ensure that they
  - [x] are a Kubernetes GitHub org [member]
  - [x] have completed the [Inclusive Leadership Training]

#### Making the change official

- [ ] Once lazy consensus has been achieved, update the following
      files in the respective repos:
  - [x] (https://github.com/kubernetes/community/pull/5286) [kubernetes/community]: [`sigs.yaml`] and use the [generator doc]
        to update `README.md` and `OWNERS_ALIASES` files
  - [ ] [kubernetes/org]: `OWNERS_ALIASES`, [milestone-maintainers team],
        kubernetes and kubernetes-sigs [team configs]
  - [ ] [kubernetes/enhancements]: `OWNERS_ALIASES`

#### Updating communication properties

- [ ] Update all communication properties used by the community group.
      See [sig-wg-lifecycle.md] for details.

[kubernetes-dev]: https://groups.google.com/g/kubernetes-dev
[steering-private]: steering-private@kubernetes.io
[member]: https://git.k8s.io/community/community-membership.md#member
[`sigs.yaml`]: https://git.k8s.io/community/sigs.yaml
[generator doc]: https://git.k8s.io/community/generator
[kubernetes/community]: https://github.com/kubernetes/community
[kubernetes/org]: https://github.com/kubernetes/org
[kubernetes/enhancements]: https://github.com/kubernetes/enhancements
[milestone-maintainers team]: https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml
[team configs]: https://git.k8s.io/org/config
[Inclusive Leadership Training]: https://training.linuxfoundation.org/training/inclusive-speaker-orientation/
[sig-wg-lifecycle.md]: https://git.k8s.io/community/sig-wg-lifecycle.md

### Chair and Technical Lead Offboarding

**_Basically, we're going to do the inverse of this list, with some exceptions as Tim will remain an approver in various areas._**

(I'll clean up this template in a follow-up.)

**All pull requests within these checklists should be marked with an _explicit_
hold and only released once approved by a SIG Release (subproject) owner.**

- [ ] Addition of a new Release Manager has been discussed with and approved by
      SIG Release owners
- [ ] Ensure new Chair/Technical Lead:
  - [ ] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-release-team](https://groups.google.com/a/kubernetes.io/g/release-team)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
    - [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
    - [release-managers](https://groups.google.com/a/kubernetes.io/forum/#!forum/release-managers)
    - [release-managers-private](https://groups.google.com/a/kubernetes.io/forum/#!forum/release-managers-private)
  - [ ] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [ ] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
  - [ ] Is part of the [@kubernetes/sig-release-admins](https://github.com/orgs/kubernetes/teams/sig-release-admins) GitHub team
- [ ] Update [Release Managers](https://git.k8s.io/sig-release/release-managers.md) page to include the new Chair or Technical Lead

### Chair/Technical Lead

- [ ] Chair/Technical Lead has agreed to abide by the guidelines set forth in
  the [Security Release
  Process](https://git.k8s.io/security/security-release-process.md),
  specifically the embargo on CVE communications.
  (This must be done as an issue comment by the incoming Chair/Technical Lead.)
- [ ] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-engineering`
  - `release-managers`
  - `sig-release-admins`
- [ ] Update `OWNERS`
  - [ ] `kubernetes/sig-release` `OWNERS_ALIASES`
    - Add entry in the `sig-release-leads` section
  - [ ] `kubernetes/release` `OWNERS_ALIASES`
    - Add entry in the `sig-release-leads` section
  - [ ] `kubernetes/test-infra` `OWNERS_ALIASES`
    - Add entry in the `sig-release-leads` section
  - [ ] `kubernetes/kubernetes` `OWNERS_ALIASES`
    - Add entry in the `sig-release-approvers` section
  - [ ] `kubernetes/k8s.io` `OWNERS_ALIASES`
    - Add entry in the `release-engineering-approvers` section
- [ ] Update `SECURITY_CONTACTS`
  - [ ] `kubernetes/release`
  - [ ] `kubernetes/sig-release`
- [ ] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `leads` (members)
  - `k8s-infra-release-admins` (members)
  - `k8s-infra-release-editors` (members)
  - `release-comms` (owners)
  - `release-managers` (owners)
  - `release-managers-private` (owners)
- [ ] Manually grant permission to post on [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
- [ ] Manually add to the [Release Team Google Group](https://groups.google.com/a/kubernetes.io/g/release-team)
- [ ] Update Slack `release-managers` and `release-team-leads` User Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)
- [ ] Manually add to the [#release-private](https://kubernetes.slack.com/archives/GKEA5EL67) Slack channel

cc: @kubernetes/sig-release-admins
/assign

**Comment by justaugustus** [comment]
Opened a separate tracking issue for @saschagrunert and @hasheddan's onboarding here: https://github.com/kubernetes/sig-release/issues/1322

**Comment by saschagrunert** [comment]
@hasheddan can we consider this as done?

**Comment by hasheddan** [comment]
@saschagrunert yep :+1: 

/close
