### ISSUE TITLE
Chair/Technical Lead access for Sascha and Dan

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1322]
### GitHub Username

@saschagrunert @hasheddan 
(follow-on to https://github.com/kubernetes/sig-release/issues/1321.)

### [Chair/Technical Lead](https://git.k8s.io/sig-release/lead/onboarding.md) role

- @saschagrunert (Chair)
- @hasheddan (Technical Lead)

### Chair and Technical Lead Onboarding

**All pull requests within these checklists should be marked with an _explicit_
hold and only released once approved by a SIG Release (subproject) owner.**

- [ ] Addition of a new Release Manager has been discussed with and approved by
      SIG Release owners
- [ ] Ensure new Chair/Technical Lead:
  - [ ] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-release-team](https://groups.google.com/a/kubernetes.io/g/release-team)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
    - [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
    - [release-managers](https://groups.google.com/a/kubernetes.io/forum/#!forum/release-managers)
    - [release-managers-private](https://groups.google.com/a/kubernetes.io/forum/#!forum/release-managers-private)
  - [ ] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [ ] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
  - [ ] Is part of the [@kubernetes/sig-release-admins](https://github.com/orgs/kubernetes/teams/sig-release-admins) GitHub team
- [ ] Update [Release Managers](https://git.k8s.io/sig-release/release-managers.md) page to include the new Chair or Technical Lead

### Chair/Technical Lead

- [ ] Chair/Technical Lead has agreed to abide by the guidelines set forth in
  the [Security Release
  Process](https://git.k8s.io/security/security-release-process.md),
  specifically the embargo on CVE communications.
  (This must be done as an issue comment by the incoming Chair/Technical Lead.)
- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) (https://github.com/kubernetes/org/pull/2336)
  - `milestone-maintainers`
  - `release-engineering`
  - `release-managers`
  - `sig-release-admins`
- [x] Update `OWNERS`
  - [x] `kubernetes/sig-release` `OWNERS_ALIASES` (https://github.com/kubernetes/sig-release/pull/1351)
    - Add entry in the `sig-release-leads` section
  - [x] `kubernetes/release` `OWNERS_ALIASES` (https://github.com/kubernetes/release/pull/1766)
    - Add entry in the `sig-release-leads` section
  - [x] `kubernetes/test-infra` `OWNERS_ALIASES` (https://github.com/kubernetes/test-infra/pull/20372)
    - Add entry in the `sig-release-leads` section
  - [x] `kubernetes/kubernetes` `OWNERS_ALIASES` (https://github.com/kubernetes/kubernetes/pull/97700)
    - Add entry in the `sig-release-approvers` section
  - [x] `kubernetes/k8s.io` `OWNERS_ALIASES` (https://github.com/kubernetes/k8s.io/pull/1436)
    - Add entry in the `release-engineering-approvers` section
- [ ] Update `SECURITY_CONTACTS`
  - [ ] `kubernetes/release`
  - [ ] `kubernetes/sig-release`
- [ ] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `leads` (members)
  - `k8s-infra-release-admins` (members)
  - `k8s-infra-release-editors` (members)
  - `release-comms` (owners)
  - `release-managers` (owners)
  - `release-managers-private` (owners)
- [ ] Manually grant permission to post on [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
- [ ] Manually add to the [Release Team Google Group](https://groups.google.com/a/kubernetes.io/g/release-team)
- [ ] Update Slack `release-managers` and `release-team-leads` User Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)
- [x] Manually add to the [#release-private](https://kubernetes.slack.com/archives/GKEA5EL67) Slack channel

cc: @kubernetes/sig-release-admins
/assign

**Comment by justaugustus** [comment]
(Most of this is already done since Dan and Sascha are Release Managers, but opening this to cross the 't's and dot the 'i's.)

**Comment by saschagrunert** [comment]
@hasheddan do you wanna check what is left open here? I think we just have to double check that everything is in place, right?

**Comment by hasheddan** [comment]
@saschagrunert yep I'll give this a run-through, thanks!

**Comment by saschagrunert** [comment]
@hasheddan can we consider this as done?

**Comment by hasheddan** [comment]
@saschagrunert yep :+1: 

/close
