### ISSUE TITLE
Assemble Kubernetes 1.21 Release Team

### ISSUE THREAD

**Issue by lachie83** [kubernetes/sig-release#1363]
The time is upon us to start assembling the 1.21 release team.

Please review the [Release Team Selection Process](https://github.com/kubernetes/sig-release/tree/master/release-team#release-team-selection) docs for details on the process and criteria.

At this stage we only require nominations for Role Leads. Once role leads are nominated we will then send out a shadow application survey.

/sig release
/area release-team
/milestone v1.21

cc @justaugustus @saschagrunert @LappleApple

**Comment by jeremyrickard** [comment]
Thanks for opening this @lachie83  and thanks so much for your time as EA for the 1.20 release! You've been such an asset.

I would like to nominate @palnabarun as the 1.21 Release Lead! He has done a fantastic job as a shadow and it was a pleasure working with him during this release, and through 1.17, 1.18 and 1.19! I think he will do a great job leading 1.21!

**Comment by bai** [comment]
I'd like to nominate @erismaster as Bug Triage Lead for 1.21. Have a great ride Derrik!

**Comment by palnabarun** [comment]
Thank you @lachie83 for devoting the time as an EA for this release. 🙂 

> I would like to nominate @palnabarun as the 1.21 Release Lead! He has done a fantastic job as a shadow and it was a pleasure working with him during this release, and through 1.17, 1.18 and 1.19! I think he will do a great job leading 1.21!

@jeremyrickard -- Thank you for showing confidence in me and your guidance throughout this release. I am really stoked to be nominated for the role. 😍

**Comment by annajung** [comment]
I am excited to nominate @reylejano as the lead of the 1.21 Release Docs Team 🎉 🎉

**Comment by JamesLaverack** [comment]
I'm very happy to nominate @wilsonehusin as Release Notes Lead for 1.21. 🎉 📓

**Comment by RobertKielty** [comment]
I am delighted to nominate @thejoycekung for the role of CI Signal Team Lead for the 1.21 Release.   

I would also like to take the opportunity to thank @ScrapCodes @hkamel and @eddiezane for their work on the 1.20 Release. I look forward to working with you all again in the future!

**Comment by jrsapi** [comment]
Excited to nominate @divya-mohan0209 for Comms lead for the 1.21 release cycle.

**Comment by divya-mohan0209** [comment]
Thank you so much @jrsapi for showing confidence in me and leading by example throughout ! I am super stoked and look forward to serving the community with this role🙏

**Comment by kikisdeliveryservice** [comment]
Happy to nominate @annajung for 1.21 Enhancements Lead. ☺️

**Comment by lachie83** [comment]
I would like to nominate @onlydole to serve at Emeritus Advisor for 1.21

**Comment by jeremyrickard** [comment]
Now that we have the 1.21 Release Team and the Shadows in place, are we good to close this issue @palnabarun @onlydole? Anything outstanding for this one?

🎊

**Comment by palnabarun** [comment]
@jeremyrickard @lachie83 -- I'm +1 on closing this. We have a full house! 🎉

**Comment by palnabarun** [comment]
Since the team has been finalized. closing this.

/close
