### ISSUE TITLE
Create Notional 1.21 Schedules

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#1388]
Create rough outline of 1.21 schedule for both a four-release cadence and a three-release cadence for consideration as part of overall release cadence discussions

/sig release
/area release-team
/milestone v1.21
/assign @palnabarun @jeremyrickard

**Comment by justaugustus** [comment]
xref: https://github.com/kubernetes/sig-release/discussions/1290

**Comment by palnabarun** [comment]
Here is the link to a proposed schedule that we discussed on: [Proposed 2021 Release Timeline](https://docs.google.com/spreadsheets/d/19YNuEsy347tiOm3U0fyEId7ghm1XrYpqU321uqUCu1Y/edit?usp=sharing)

**Comment by palnabarun** [comment]
For 1.21, we were working on the schedule [here](https://docs.google.com/spreadsheets/d/1q7UvVvZQKtrZaXCWejlUZCJYrAYckHPaTsnZ0lEJ9f4/edit?usp=sharing) and the final goto source of truth is in [the release directory](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.21/README.md).

**Comment by jeremyrickard** [comment]
Going to go ahead and close this, since we've documented notional schedules and have kicked off 1.21! 

Good luck 1.21 team :)

/close
