### ISSUE TITLE
Standard SIG metadata

### ISSUE THREAD

**Issue by jbeda** [kubernetes/sig-release#14]
Who are the SIG leads?  What is the mailing list? When are meetings? Where are the notes and recordings?

This is all missing from here and the community repo.  See https://github.com/kubernetes/community/issues/891.

**Comment by calebamiles** [comment]
Hey @jbeda we can add a forwarding link in the community repo. Communications information is listed in the [README](https://github.com/kubernetes/sig-release#join-us) and our [member file](https://github.com/kubernetes/sig-release/blob/master/members.md) unfortunately contains only Phil and I who are the leads but I'll be happy to migrate that membership list to some machine readable format as we keep talking about a tool to set GitHub team membership from a file checked into source control.

**Comment by enisoc** [comment]
This seems to be fixed:

https://github.com/kubernetes/community/tree/master/sig-release
https://github.com/kubernetes/community/blob/master/sig-list.md
