### ISSUE TITLE
Release Team Lead access for @palnabarun @kikisdeliveryservice @savitharaghunathan @bai

### ISSUE THREAD

**Issue by palnabarun** [kubernetes/sig-release#1404]
### GitHub Username(s)

- @palnabarun 
- @kikisdeliveryservice 
- @savitharaghunathan 
- @bai 

### Release Cycle

Kubernetes 1.21

### Prerequisites

- [x] Ensure new Release Team Lead:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
  - [x] Has completed the [CNCF Inclusive Speaker Orientation](https://training.linuxfoundation.org/training/inclusive-speaker-orientation/). Please drop in the certification ID in the comments once completed.
    - [x] Nabarun Pal
    - [x] Kirsten Garrison
    - [x] Savitha Raghunathan
    - [x] Vlad Gorodetsky

### Onboarding

- [x] Release Team Lead has agreed to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.
  This must be done as an issue comment by the incoming Release Team Lead.
- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) ~> (https://github.com/kubernetes/org/pull/2405)
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
  - `sig-release`
- [x] Update `kubernetes/sig-release` `OWNERS` ~> (https://github.com/kubernetes/sig-release/pull/1407 and https://github.com/kubernetes/sig-release/pull/1405)
  - Release Team Lead and Shadows
    - Add an `approvers` entry in `releases/release-1.21/OWNERS`
  - **Release Team Lead only**
    - In `OWNERS_ALIASES`, add an entry in the following sections:
      - `release-team`
      - `release-team-lead-role`
- [x] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml) ~> (https://github.com/kubernetes/k8s.io/pull/1513)
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [x] Manually grant access to the following Google Groups:
  - [kubernetes-release-team](https://groups.google.com/a/kubernetes.io/g/release-team) (Add as Manager)
  - [kubernetes-sig-leads](https://groups.google.com/forum/#!forum/kubernetes-sig-leads) (Add as Member)
- [x] Grant calendar access
- [x] Grant Zoom credentials (host key)
- [x] Add incoming leads to `release-team-leads` Slack Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml) ~> (https://github.com/kubernetes/community/pull/5393)
  - Add slack ID(s) to [`users.yaml`](https://git.k8s.io/community/communication/slack-config/users.yaml), if they are not yet in the file
  - Add username(s) to [`usergroups.yaml`](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)

### Offboarding

- [x] Remove from GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
- [x] Remove from Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [x] Manually remove from the following Google Groups:
  - [kubernetes-release-team](https://groups.google.com/a/kubernetes.io/g/release-team) (Add as Manager)
  - [kubernetes-sig-leads](https://groups.google.com/forum/#!forum/kubernetes-sig-leads) (Add as Member)
- [x] Remove from `release-team-leads` Slack Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)
  - Remove slack ID(s) from [`users.yaml`](https://git.k8s.io/community/communication/slack-config/users.yaml), if no longer in a group
  - Remove username(s) from [`usergroups.yaml`](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)

cc: @kubernetes/release-engineering @kubernetes/release-team

**Comment by palnabarun** [comment]
I have completed the training. My LF training certificate ID is LF-o61x5t3r6e.

**Comment by savitharaghunathan** [comment]
I have completed the training! Here's my certificate id: `LF-a7hzkmrc4m`

**Comment by savitharaghunathan** [comment]
✨ I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications

**Comment by palnabarun** [comment]
I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by bai** [comment]
I have completed the training. My training certificate ID is `LF-yqwnil3c9f`. 

I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by divya-mohan0209** [comment]
I have completed the training. My training certificate ID is LF-cuyg856pxb. 

I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by kikisdeliveryservice** [comment]
I completed my training: `LF-tst9jc3b5s`

I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by justaugustus** [comment]
/assign @justaugustus 
/unassign @palnabarun 

I'll take care of offboarding as part of some periodic access updates.
Thanks for all of your hard work this cycle team!

**Comment by kikisdeliveryservice** [comment]
I  believe this was done, anything else that we need to do @justaugustus before closing??

**Comment by savitharaghunathan** [comment]
we generally keep this issue open until the offboarding tasks are done

**Comment by palnabarun** [comment]
I have verified the offboarding tasks and checked for the absence of access to the privileged mailing lists. Hence closing this.

Please feel free to reopen this, if it is otherwise.

/assign
/close
