### ISSUE TITLE
Chair/Technical Lead access for @jeremyrickard

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1421]
### GitHub Username

@jeremyrickard 

### [Chair/Technical Lead](https://git.k8s.io/sig-release/lead/onboarding.md) role

Technical Lead
ref: https://groups.google.com/g/kubernetes-dev/c/78E3IobBKH0

### Chair and Technical Lead Onboarding

**All pull requests within these checklists should be marked with an _explicit_
hold and only released once approved by a SIG Release (subproject) owner.**

- [x] Addition of a new Release Manager has been discussed with and approved by
      SIG Release owners
- [x] Ensure new Chair/Technical Lead:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-release-team](https://groups.google.com/a/kubernetes.io/g/release-team)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
    - [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
    - [release-managers](https://groups.google.com/a/kubernetes.io/forum/#!forum/release-managers)
    - [release-managers-private](https://groups.google.com/a/kubernetes.io/forum/#!forum/release-managers-private)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
  - [x] Is part of the [@kubernetes/sig-release-admins](https://github.com/orgs/kubernetes/teams/sig-release-admins) GitHub team
- [x] Update [Release Managers](https://git.k8s.io/sig-release/release-managers.md) page to include the new Chair or Technical Lead

### Chair/Technical Lead

- [x] Chair/Technical Lead has agreed to abide by the guidelines set forth in
  the [Security Release
  Process](https://git.k8s.io/security/security-release-process.md),
  specifically the embargo on CVE communications.
  (This must be done as an issue comment by the incoming Chair/Technical Lead.)
- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-engineering`
  - `release-managers`
  - `sig-release-admins`
- [x] Update `OWNERS`
  - [x] `kubernetes/sig-release` `OWNERS_ALIASES` (https://github.com/kubernetes/sig-release/pull/1401)
    - Add entry in the `sig-release-leads` section
  - [x] `kubernetes/release` `OWNERS_ALIASES` (https://github.com/kubernetes/release/pull/1832)
    - Add entry in the `sig-release-leads` section
  - [x] `kubernetes/test-infra` `OWNERS_ALIASES` (https://github.com/kubernetes/test-infra/pull/20372)
    - Add entry in the `sig-release-leads` section
  - [x] `kubernetes/kubernetes` `OWNERS_ALIASES` (https://github.com/kubernetes/kubernetes/pull/97700)
    - Add entry in the `sig-release-approvers` section
  - [x] `kubernetes/k8s.io` `OWNERS_ALIASES` (https://github.com/kubernetes/k8s.io/pull/1529)
    - Add entry in the `release-engineering-approvers` section
- [x] Update `SECURITY_CONTACTS`
  - [x] `kubernetes/release` (https://github.com/kubernetes/release/pull/1832)
  - [x] `kubernetes/sig-release` (https://github.com/kubernetes/sig-release/pull/1401) 
- [x] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml) (https://github.com/kubernetes/k8s.io/pull/1529)
  - `leads` (members)
  - `k8s-infra-release-admins` (members)
  - `k8s-infra-release-editors` (members)
  - `release-comms` (owners)
  - `release-managers` (owners)
  - `release-managers-private` (owners)
- [ ] Manually grant permission to post on [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
- [x] Manually add to the [Release Team Google Group](https://groups.google.com/a/kubernetes.io/g/release-team) (https://github.com/kubernetes/k8s.io/pull/1529)
- [x] Update Slack `release-managers` and `release-team-leads` User Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml) (https://github.com/kubernetes/community/pull/5407)
- [x] Manually add to the [#release-private](https://kubernetes.slack.com/archives/GKEA5EL67) Slack channel

Dan already has a set of PRs in-flight, so I'll leave him to handle this onboarding.
/assign @hasheddan 
cc: @kubernetes/sig-release-admins

**Comment by saschagrunert** [comment]
I think this is mostly done, right @justaugustus ? @jeremyrickard can you double check that you have all permissions?

**Comment by jeremyrickard** [comment]
I do hereby agree to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by jeremyrickard** [comment]
@saschagrunert looks good, except for: I don't have posting permissions for Kubernetes-announce. If I don't need that, i think we are good.

**Comment by saschagrunert** [comment]
> @saschagrunert looks good, except for: I don't have posting permissions for Kubernetes-announce. If I don't need that, i think we are good.

I think those permissions have to be granted manually, right @justaugustus?

**Comment by jeremyrickard** [comment]
I think the posting permission is only relevant for patch announcements and what not, so I think this is good. I'll open an issue if I need this in the future.

/close
