### ISSUE TITLE
Release Manager offboarding for @gianarb

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/sig-release#1442]
### GitHub Username

@gianarb

### [Release Manager](https://git.k8s.io/sig-release/release-managers.md) role

Release Manager Associate

### Tenure

Conclusion of permanent tenure (offboarding).

### Release Manager Offboarding

**All pull requests within these checklists should be marked with an _explicit_ hold and only released once approved by a Release Engineering subproject owner.**

- [x] Removal of a new Release Manager has been discussed with and approved by Release Engineering subproject owners

- [x] Update [Release Managers](https://git.k8s.io/sig-release/release-managers.md) page to remove the new Release Manager (https://github.com/kubernetes/sig-release/pull/1441)

### Release Manager Associate

- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) (https://github.com/kubernetes/org/pull/2469)
  - `milestone-maintainers`
  - `release-engineering`
- [ ] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-viewers@`
  - `release-managers@`

cc: @kubernetes/release-engineering
/assign

**Comment by saschagrunert** [comment]
@cpanato mentioned that he can take over this part

**Comment by cpanato** [comment]
@hasheddan @saschagrunert I was double-checking the last item and I don't see `gianarb`  email configured in k8s.io.

I checked with Gianluca his email just to be sure, so I think we are good to close this issue

**Comment by saschagrunert** [comment]
@cpanato thank you for double checking
/close
