### ISSUE TITLE
GitHub PR reviews act as /lgtm + /approve for SIG Release repos

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1464]
#### What would you like to be added:

From https://github.com/kubernetes/test-infra/pull/20819#issuecomment-778016276:

> @kubernetes/sig-release-leads -- How would y'all feel about making this change for SIG Release repos as well?

Let's follow Aaron and SIG Testing's lead and turn this on for SIG Release repos.

Use:
- https://github.com/kubernetes/test-infra/pull/20819 as example of how to configure this
- https://github.com/kubernetes/community/tree/master/sig-release#subprojects as a reference point for the repositories we own

#### Why is this needed:

Easy review/approval workflow.
(Further outlined in https://groups.google.com/g/kubernetes-sig-testing/c/gumjq2guMa0.)

cc: @kubernetes/release-engineering 
/help
/milestone v1.21
/priority important-soon

**Comment by supriya-premkumar** [comment]
I can take this one up.

**Comment by saschagrunert** [comment]
@supriya-premkumar this is awesome, feel free to reach out anytime if there is anything unclear.

/assign @supriya-premkumar 
/remove-help

**Comment by dims** [comment]
@supriya-premkumar as mentioned on slack the following 
- https://github.com/kubernetes/test-infra/pull/20927/files
- https://github.com/kubernetes/test-infra/pull/20819/files

the list of repositories under sig-release management can be found here:
https://github.com/kubernetes/community/tree/master/sig-release#release-engineering
