### ISSUE TITLE
Change Timing of Burndown Meetings

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#148]
Contributors, Release Team, SIG Leads:

Previously, burndown meetings have been at 10am PST/PDT every day they are held (MWF in Slush, then every weekday in freeze).  This timeslot has two problems:

1. On Thursdays, it conflicts with the Community Meeting right when the Release Lead needs to be mobilizing the community to close last-minute bugs.
2. 10am PDT is pretty late for folks in Europe/Asia.

The latter has been a real problem, resulting in a minority of SIG leads actually attending the burndown meetings.

However, I am also aware of the limitations of the schedules of Googlers who work in Mountain View, which makes meetings earlier in the day hard.  Given that important roles in each RT are generally filled by MTV googlers, simply switching to 8am PST/PDT meetings would cause a different group of people to drop out.  Also, for those of us who work on mixed US/Europe teams, that 8am timeslot is awefully crowded.

As such, I can think of 3 possible courses going forwards:

1. Ignore the issue and keep the burndown meetings at 10am
2. Move the meetings to 8am Pacific and ask the googlers to change their commutes when needed for burndown;
3. Alternate burndown meeting times so that we spread the inconvenience around;
4. Some other creative solution?

If you are a current or former release team member, a SIG lead, or a contributor with a feature in 1.11, please comment below on what timings would work best to ensure that you attend burndowns.f

**Comment by justaugustus** [comment]
I'm in favor of alternating the meetings to make it more [in]convenient.

**Comment by BenTheElder** [comment]
10am+ PDT is definitely more convenient for me but release meetings are important IMHO, I will attend them any time.
One suggestion: whatever option is chosen we could make Thursdays special to avoid the community meeting if we aren't already.

**Comment by tpepper** [comment]
I too am in favor of alternating the [in]convenience.  We can all do our part.

IIRC in the 1.10 cycle we had briefly done Thursdays at a different time to also avoid the community meeting.  It's really useful to be able to attend that meeting for cross-project pulse and also for broad shoutouts where we're getting to need help on things.

**Comment by jberkus** [comment]
OK, proposed:

During early burndown, meetings will be:

* M: 10am PDT
* W: 8am PDT
* F: 10am PDT

... where Wednesday is the meeting we try to get all SIG leads to attend.  

During later burndown (final 10 days), we'll have: 

* M: 10am
* T: 8am
* W: 10am
* Th: 8am
* F: 10am

Works?
