### ISSUE TITLE
Cut 1.21.0-beta.1 release

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/sig-release#1485]
## Scheduled to happen: 

- [x] Screenshot unhealthy release branch testgrid boards and add them as a comment

- [x] Stage & release
  - [x] Notify [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y): [see notification](https://link-to-slack-message)
  
  - [x] Collect metrics and add them to the `Release steps` table below

- [x] Send notification [email](https://link-to-email-on-kubernetes-announce-google-group)

## Release steps

[krel](https://github.com/kubernetes/release/tree/master/docs/krel) version:
```
GitVersion:    v0.4.2
GitCommit:     6439ecb1da38043716d69ad3cb159358aebb4e4d
GitTreeState:  clean
BuildDate:     2021-03-09T07:20:07Z
GoVersion:     go1.16
Compiler:      gc
Platform:      darwin/amd64
```

| Step | Command | Link | Start | Duration | Succeeded? |
| --- | --- | --- | --- | --- | --- |
| Mock stage | `krel stage --type beta` | https://console.cloud.google.com/cloud-build/builds;region=global/4ee464e6-a569-4d06-8146-987c1d0c6ab6?project=kubernetes-release-test | 08:47:22 | 00:40:47 | yes |
| Mock release | `krel release --type=beta --build-version=v1.21.0-beta.0.860+faa3a5fbd4431c` | https://console.cloud.google.com/cloud-build/builds;region=global/b7c09a73-951c-4967-8fd9-09d05d9693db?project=kubernetes-release-test | 09:38:52 | 00:05:16  | yes |
| Stage | `krel stage --type=beta --build-version=v1.21.0-beta.0.860+faa3a5fbd4431c --nomock` | https://console.cloud.google.com/cloud-build/builds;region=global/97a8f0df-618a-46fa-97a0-116f541c7b4d?project=kubernetes-release-test | 10:12:11 | 00:39:29 | yes  |
| Image Promotion | `krel promote-images -i --fork=mkorbi --tag=v1.21.0-beta.1` | https://github.com/kubernetes/k8s.io/pull/1768|  |  |  |
| Release | `krel release --nomock --type=beta --build-version=v1.21.0-beta.0.874+40a411a61af315` | https://console.cloud.google.com/cloud-build/builds;region=global/e7a07003-bee4-4d96-bed5-dfe64794db61?project=kubernetes-release-test | 11:20:58 |  |  |
| Notify | `krel announce send --nomock --tag=v1.21.0-beta.1` | https://groups.google.com/g/kubernetes-dev/c/cwrzxfX4biI & https://groups.google.com/g/kubernetes-announce/c/Q9e1FGtMW_I|  | -- |  |

## Open questions

/milestone v1.21
/assign @mkorbi 
/cc @kubernetes/release-managers
/priority important-soon
/kind documentation

**Comment by saschagrunert** [comment]
Scheduled for March 9th, maybe we should add this information to the issue template.

**Comment by mkorbi** [comment]
### Testgrid dashboards for master

Boards checked for FAILING:
- [sig-release-master-blocking](https://testgrid.k8s.io/sig-release-master-blocking)
- [sig-release-master-informing](https://testgrid.k8s.io/sig-release-master-informing)


<details><summary><tt>2021-03-09 08:01:23.862229 +0000 UTC</tt> FAILING <a href="https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2004-master&width=30">sig-release-master-informing#gce-windows-2004-master - TestGrid</a></summary><p>

![sig-release-master-informing#gce-windows-2004-master](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2021-03-09-932a5c33-a99d-412e-8e3b-25ebce99ca5f/sig-release-master-informing-gce-windows-2004-master-FAILING.jpg)

</p></details>
<details><summary><tt>2021-03-09 08:01:23.862229 +0000 UTC</tt> FAILING <a href="https://testgrid.k8s.io/sig-release-master-informing#Conformance - OpenStack&width=30">sig-release-master-informing#Conformance - OpenStack - TestGrid</a></summary><p>

![sig-release-master-informing#Conformance - OpenStack](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2021-03-09-932a5c33-a99d-412e-8e3b-25ebce99ca5f/sig-release-master-informing-Conformance_-_OpenStack-FAILING.jpg)

</p></details>
<details><summary><tt>2021-03-09 08:01:23.862229 +0000 UTC</tt> FAILING <a href="https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-master&width=30">sig-release-master-informing#gce-windows-2019-master - TestGrid</a></summary><p>

![sig-release-master-informing#gce-windows-2019-master](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2021-03-09-932a5c33-a99d-412e-8e3b-25ebce99ca5f/sig-release-master-informing-gce-windows-2019-master-FAILING.jpg)

</p></details>
<details><summary><tt>2021-03-09 08:01:23.862229 +0000 UTC</tt> FAILING <a href="https://testgrid.k8s.io/sig-release-master-informing#gce-windows-20h2-master&width=30">sig-release-master-informing#gce-windows-20h2-master - TestGrid</a></summary><p>

![sig-release-master-informing#gce-windows-20h2-master](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2021-03-09-932a5c33-a99d-412e-8e3b-25ebce99ca5f/sig-release-master-informing-gce-windows-20h2-master-FAILING.jpg)

</p></details>
<details><summary><tt>2021-03-09 08:01:23.862229 +0000 UTC</tt> FAILING <a href="https://testgrid.k8s.io/sig-release-master-informing#capa-conformance-v1alpha3-k8s-master&width=30">sig-release-master-informing#capa-conformance-v1alpha3-k8s-master - TestGrid</a></summary><p>

![sig-release-master-informing#capa-conformance-v1alpha3-k8s-master](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2021-03-09-932a5c33-a99d-412e-8e3b-25ebce99ca5f/sig-release-master-informing-capa-conformance-v1alpha3-k8s-master-FAILING.jpg)

</p></details>
<details><summary><tt>2021-03-09 08:01:23.862229 +0000 UTC</tt> FAILING <a href="https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-v1alpha3-k8s-master&width=30">sig-release-master-informing#capg-conformance-v1alpha3-k8s-master - TestGrid</a></summary><p>

![sig-release-master-informing#capg-conformance-v1alpha3-k8s-master](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2021-03-09-932a5c33-a99d-412e-8e3b-25ebce99ca5f/sig-release-master-informing-capg-conformance-v1alpha3-k8s-master-FAILING.jpg)

</p></details>
<details><summary><tt>2021-03-09 08:01:23.862229 +0000 UTC</tt> FAILING <a href="https://testgrid.k8s.io/sig-release-master-informing#gce-windows-1909-master&width=30">sig-release-master-informing#gce-windows-1909-master - TestGrid</a></summary><p>

![sig-release-master-informing#gce-windows-1909-master](https://storage.googleapis.com/k8s-staging-releng/testgridshot/master/2021-03-09-932a5c33-a99d-412e-8e3b-25ebce99ca5f/sig-release-master-informing-gce-windows-1909-master-FAILING.jpg)

</p></details>




**comment generated by [krel](https://github.com/kubernetes/release/tree/master/docs/krel)**
