### ISSUE TITLE
1.21 major themes contact

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/sig-release#1497]
With major themes submission formalizing to use GitHub Discussions, we hope that this cycle will be the last time that the release team needs to reach out to SIGs for their response.

Having that said, since the process is new, the release notes team will be using this issue to track the work on nudging SIGs for entries on major themes for 1.21 cycle.

The Slack channel for each SIG is usually `#sig-<name>`, but accurate links are available in [k/community under `sig-list.md`](https://github.com/kubernetes/community/blob/master/sig-list.md). The plan is to start asking for responses on public Slack channel (non-disruptively).

The following is a template meant for a guide, so feel free to use the language you're comfortable with!
```
Hello SIG <NAME>, the 1.21 release notes team is gathering major themes entries for 
the release and if you have anything to call out, we would really appreciate it if your 
SIG can submit the content in https://github.com/kubernetes/sig-release/discussions/1436.
Ideally we would like this to be completed by March 24. Thanks!
```

Some SIGs have activities which aren't quite coupled with Kubernetes releases, but it's worth checking anyway in case there are things worth calling out in what they did between the previous release and current release. One example is [SIG UI releasing dashboard version 2.0](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/release-notes-draft.md#dashboard-v2) in between Kubernetes 1.18 and 1.19 releases.

We'll try to keep the list below up-to-date, but please double check in comments if someone has contacted their channel:
- [x] API Machinery
- [x] Apps
- [x] Architecture
- [x] Auth
- [x] Autoscaling
- [x] CLI
- [x] Cloud Provider
- [x] Cluster Lifecycle
- [x] Contributor Experience
- [x] Docs
- [x] Instrumentation
- [x] Multicluster
- [x] Network
- [x] Node
- [x] Release
- [x] Scalability
- [x] Scheduling
- [x] Security
- [x] Service Catalog
- [x] Storage
- [x] Testing
- [x] UI
- [x] Usability
- [x] Windows

/assign wilsonehusin ashnehete melodychn pmmalinov01 soniasingla

**Comment by ashnehete** [comment]
I'll contact the following SIGs:
1. CLI
2. Cloud Provider
3. UI
4. Docs

**Comment by soniasingla** [comment]
I'll contact:

1. Contributor Experience
2. Release
3. Testing
4. Multicluster

**Comment by pmmalinov01** [comment]
I will reach out to:

1. API Machinery
2. Architecture
3. Network
4. Security

**Comment by melodychn** [comment]
I can reach out to:

1. Apps
2. Auth
3. Storage
4. Usability

**Comment by wilsonehusin** [comment]
Okay I covered the rest! Let's try to get these notifications out in the next 24 hours so it won't disappear over the weekend, especially with the deadline being less than a week.

Go team! :tada:

/close
