### ISSUE TITLE
Update [1.8 release team][] with shadow release lead.

### ISSUE THREAD

**Issue by idvoretskyi** [kubernetes/sig-release#15]
Initially opened by @calebamiles at https://github.com/kubernetes/sig-release/projects/2

**Comment by idvoretskyi** [comment]
@calebamiles isn't shadow release role equal to the secondary release one?

**Comment by jdumars** [comment]
Agreed.  I was under the impression that the secondary lead is the shadow.

**Comment by idvoretskyi** [comment]
@jdumars we can close this now, right?
