### ISSUE TITLE
Assemble Kubernetes 1.22 Release Team 🎉 

### ISSUE THREAD

**Issue by onlydole** [kubernetes/sig-release#1505]
The time is upon us to start assembling the 1.22 release team! 

Please review the Release Team Selection Process docs for details on the process and criteria.

At this stage, we only require nominations for Role Leads. Once role leads are nominated we will then send out a shadow application survey.

/sig release
/area release-team
/milestone v1.22

cc @justaugustus @saschagrunert @LappleApple

**Comment by palnabarun** [comment]
Thank you @onlydole for creating the issue and getting the ball rolling for v1.22. You're awesome!

It was a pleasure working with the 1.21 Release Team and it's now time to pass on the baton.

I would like to nominate @savitharaghunathan as the Kubernetes 1.22 Release Lead. She has been doing an amazing job in the Release Cycle for the past 1 year, having started as a Docs Shadow in 1.18, leading Docs in 1.19, and shadowing the Release Lead in 1.20 and 1.21. It was a pleasure working with her over the release cycles.

Savitha would be doing a great job in leading 1.22! 🎉

**Comment by savitharaghunathan** [comment]
> Thank you @onlydole for creating the issue and getting the ball rolling for v1.22. You're awesome!
> 
> It was a pleasure working with the 1.21 Release Team and it's now time to pass on the baton.
> 
> I would like to nominate @savitharaghunathan as the Kubernetes 1.22 Release Lead. She has been doing an amazing job in the Release Cycle for the past 1 year, having started as a Docs Shadow in 1.18, leading Docs in 1.19, and shadowing the Release Lead in 1.20 and 1.21. It was a pleasure working with her over the release cycles.
> 
> Savitha would be doing a great job in leading 1.22! 🎉

Thank you, @palnabarun :)  I am honored to be nominated to lead 1.22 🎉  It is going to be awesome :)

**Comment by reylejano** [comment]
I'm excited to nominate @PI-Victor to be the 1.22 Docs Lead  🎉

**Comment by PI-Victor** [comment]
> I'm excited to nominate @PI-Victor to be the 1.22 Docs Lead 🎉

Thanks for the nomination, it's awesome, and thanks for giving me the opportunity to get to know this community better!

Y'all rock! 🤘🏻

**Comment by mkorbi** [comment]
> I'm incredibly thankful I got a chance to work with everyone for the 1.21 release -- you were all amazing and so unbelievably kind. 💜
> 
> That being said, I'm super excited to nominate @mkorbi for 1.22 CI Signal Lead 🎉 🎉

Thank you @thejoycekung for the nomination! :) Super excited and happy about it 🎉

**Comment by MonzElmasry** [comment]
Thanks @erismaster for the nomination, Im super excited  :woman_dancing:

**Comment by JamesLaverack** [comment]
> For 1.22, I am excited to nominate @JamesLaverack for Enhancements Lead! 🎉 🥳

![image](https://user-images.githubusercontent.com/1119526/113061429-ec9aca80-91a9-11eb-8e28-f76b25475598.png)

Thank you @annajung. I'm looking forward to working with everyone on 1.22!

**Comment by wilsonehusin** [comment]
I would like to nominate @pmmalinov01 for release notes lead in 1.22! Pavel has been proactive and empathetic in working with the release team and I'm excited to see him take on this challenge

/pony

**Comment by pmmalinov01** [comment]
> I would like to nominate @pmmalinov01 for release notes lead in 1.22! Pavel has been proactive and empathetic in working with the release team and I'm excited to see him take on this challenge
> 
> /pony

Thanks for the nomination, I am so happy that I am part of this community and eager to continue your great work!

**Comment by divya-mohan0209** [comment]
I'm so grateful to have had the opportunity to work with all the leads and shadows and being a part of the 1.21 Release team has been an amazing experience. 

That being said, I would like to pass on the baton to @Pensu for the 1.22 Release cycle. 🎉✨

**Comment by Pensu** [comment]
> I'm so grateful to have had the opportunity to work with all the leads and shadows and being a part of the 1.21 Release team has been an amazing experience.
> 
> That being said, I would like to pass on the baton to @Pensu for the 1.22 Release cycle. 🎉✨

Thank you so much for giving me the opportunity @divya-mohan0209. Super excited and looking forward to work with you all! 🎉✨

**Comment by onlydole** [comment]
I nominate, @guineveresaenger as the next emeritus advisor for Kubernetes 1.22! It's been a long, winding, wonderful road working with all of you, and I can think of no one better to carry that spirit forward than Guin! 😄

**Comment by guineveresaenger** [comment]
I've missed you fam! @onlydole thank you for the kind words!

**Comment by onlydole** [comment]
The team is assembled and this issue is complete!

/close
