### ISSUE TITLE
downloadkubernetes.com is stuck since v1.20.1

### ISSUE THREAD

**Issue by puerco** [kubernetes/sig-release#1514]
#### What happened:

The downloads listed at downloadkubernetes.com are stuck at `v1.20.1`. 

#### What you expected to happen:

I would expect the downloads to be current (v1.21.0 as today)

#### How to reproduce it (as minimally and precisely as possible):

Open https://www.downloadkubernetes.com/ all downloads for releases since 1.20.1 are missing.

#### Anything else we need to know?:

This had happened before, I think it is a process that runs in the VM of the site.

**Comment by jimangel** [comment]
It appears this is resolved?

**Comment by saschagrunert** [comment]
Yeah, it is and it's related to https://github.com/kubernetes-sigs/downloadkubernetes/issues/80
