### ISSUE TITLE
Define and implement the release cadence survey

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/sig-release#1526]
The [release cadence KEP][0] states that there is a necessity for a feedback survey about the implemented cadence change:

> SIG Release will draft an experience survey and distribute it to k/dev) and include it in the release notes of the first three releases from which the new cadence has been applied. This survey will include questions around the release cadence and how it impacted end users and can be used to make a final decision regarding release cadence (i.e. promoting this KEP to stable).
>
> Survey contents are to be determined, but we welcome content suggestions to continually improve the process.

The following questions have to be resolved before sending out the survey to the community:

- **When should the survey be done?**
  There are [discussions about doing it late 2021][1] if we have enough data to collect.
- **Which questions do we want to include?**
  What is the outcome of the survey? For example, one target should be to [be able to elaborate on alternative release
 models][2] (releasing faster) for Kubernetes and verify if the current cadence is still the right one.

[0]: https://github.com/kubernetes/enhancements/blob/0def15c4112e07a529a30d6dc402948a17d97a1e/keps/sig-release/2572-release-cadence/README.md#feedback-survey
[1]: https://github.com/kubernetes/enhancements/pull/2567#discussion_r614462937
[2]: https://github.com/kubernetes/enhancements/pull/2567#discussion_r614708624

/priority important-longterm
/help

**Comment by Damans227** [comment]
Hey @saschagrunert How are you ? I am shadowing on the K8s v1.22 release team. Can I help you with this issue ?  Since, I am a new contributor, I would need some guidance and support from a senior person.

**Comment by saschagrunert** [comment]
> Hey @saschagrunert How are you ? I am shadowing on the K8s v1.22 release team. Can I help you with this issue ? Since, I am a new contributor, I would need some guidance and support from a senior person.

Hey, thank you for jumping into this discussion! :pray: 

I think the first step we can do is defining a set of questions we would like to ask. We could start iterating in a Google Doc to get further feedback from the community. 

@Damans227, do you wanna start with that?

**Comment by Damans227** [comment]
Sure, does it matter where I create this google doc ? Can I create it on my shared drive ?

**Comment by saschagrunert** [comment]
> @saschagrunert Sure, does it matter where I create this google doc ? Can I create it on my shared drive ? Also, apologies in advance, I am gonna have a fair share of noob questions.

No worries, yeah it's totally fine if you share a doc (publicly) directly from your account. I'm happy to contribute and add a certain point we can put it into markdown and request more feedback from a broader group.

**Comment by Damans227** [comment]
I have created the new doc and it is publicly available to edit on this link:

https://docs.google.com/document/d/14d4P24BrL280IXgDsKzXX89UFsI0X275HGYT4RcrASU/edit?usp=sharing

Please feel free to make any necessary changes and share your feedback.

**Comment by saschagrunert** [comment]
Added some first thoughts :+1:

**Comment by saschagrunert** [comment]
@Damans227 do you think that you could use my input to create some first questions?

**Comment by Damans227** [comment]
Yes of-course. I will create a google form with questions around those ideas which you have shared. I should be able to get this done very shortly, likely by some time tomorrow evening. Thanks for following up.

**Comment by Damans227** [comment]
@saschagrunert Please take a look, and share your feedback. 

https://docs.google.com/forms/d/15nhhCYjvy8cbV9ELEer9knwiFIcNwPT8ybfEwxTLyLo/edit?usp=sharing

**Comment by saschagrunert** [comment]
> @saschagrunert Please take a look, and share your feedback.
> 
> https://docs.google.com/forms/d/15nhhCYjvy8cbV9ELEer9knwiFIcNwPT8ybfEwxTLyLo/edit?usp=sharing

Thanks, I think there is a commenting section when being able to edit the document. I requested access to do so.

**Comment by Damans227** [comment]
I have granted you the access to edit.

**Comment by saschagrunert** [comment]
> I have granted you the access to edit.

This looks already really good! I added a question about the customer base/size. What do you think about this one?

**Comment by Damans227** [comment]
Yup, this looks good already and thanks for adding that question. It is not marked as required though, is that intentional ? Also, I haven't made Github handle question required as well, what do you think about that ?

**Comment by saschagrunert** [comment]
> Yup, this looks good already and thanks for adding that question. It is not marked as required though, is that intentional ? Also, I haven't made Github handle question required as well, what do you think about that ?

Hm, I think we're fine having them optional.

**Comment by Damans227** [comment]
Ok, cool. Thanks for your feedback.

**Comment by saschagrunert** [comment]
I made some edits and gave the SIG Release leads editing permissions to give them a chance to make some edits.

**Comment by saschagrunert** [comment]
@Damans227 do you wanna put the survey into surveymonkey or should I take care of it? :)

**Comment by Damans227** [comment]
I went ahead and implemented the survey into survey monkey. PTAL, https://www.surveymonkey.com/r/HF36WH7

**Comment by saschagrunert** [comment]
Thank you @Damans227! @kubernetes/sig-release-leads PTAL

**Comment by saschagrunert** [comment]
Status update: We plan to push this survey out in the beginning of 2022

**Comment by saschagrunert** [comment]
@Damans227 can you please add myself to the survey that I'm able to see the results? My account is `saschagrunert`.

**Comment by saschagrunert** [comment]
Mail sent: https://groups.google.com/a/kubernetes.io/g/dev/c/5Sj-Mk0_I1Y

**Comment by Damans227** [comment]
> https://www.surveymonkey.com/r/HF36WH7

Yes, of course. I am working on this now.

**Comment by Damans227** [comment]
@saschagrunert So, it looks like I can not add you to my "team" on survey monkey and give you the access to its results without upgrading to a paid plan. The only option available to share the survey data in free tier is to generate a public link and publish the responses online.

**Comment by saschagrunert** [comment]
> @saschagrunert So, it looks like I can not add you to my "team" on survey monkey and give you the access to its results without upgrading to a paid plan. The only option available to share the survey data in free tier is to generate a public link and publish the responses online.

Sounds good, let's revisit the survey from time to time and probably close it by the end of the cycle :) Then we can evaluate the results.

**Comment by jberkus** [comment]
Hey, all, I'm going to ask you to pull the survey and use Kubernetes' official survey account for it.  Also there's a few other things missing like GDPR headers.

**Comment by jberkus** [comment]
Also --- we can have contributor-comms publicize the survey.

**Comment by jberkus** [comment]
Drafting replacement with Sascha and Damans

**Comment by jberkus** [comment]
Survey is running now: https://www.surveymonkey.com/r/k8s-cadence-2022

**Comment by saschagrunert** [comment]
The release cadence survey is now closed.

#### Summary

87 People answered the questions

![screenshot](https://user-images.githubusercontent.com/695473/168017704-986cf63b-a8b5-43c7-ae8e-c60eab1adfee.png)
![screenshot](https://user-images.githubusercontent.com/695473/168017800-0c135179-40ab-461b-bf38-2cfc2bd20b24.png)
![screenshot](https://user-images.githubusercontent.com/695473/168017871-035bb271-3d87-4ae9-8508-49b6d9cfebfa.png)
![screenshot](https://user-images.githubusercontent.com/695473/168017975-4a261058-0378-46b3-b543-a0c4a38a51d4.png)
