### ISSUE TITLE
Auto-generated release notes file has bugs

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/sig-release#1528]
- Related issue: https://github.com/kubernetes/website/issues/27606

#### What happened:
[Auto-generated release notes file](https://github.com/kubernetes/website/blob/master/content/en/docs/setup/release/notes.md) (being served in [here](https://kubernetes.io/docs/setup/release/notes/)) has bugs.

#### What you expected to happen:

[As-is]
```Markdown
## Changelog since v1.20.0

# Release notes for v1.21.0-rc.0

[Documentation](https://docs.k8s.io/docs/home)

# Changelog since v1.20.0

## What's New (Major Themes)

### Deprecation of PodSecurityPolicy
```

[To-be]
```Markdown
## Changelog since v1.20.0

## What's New (Major Themes)

### Deprecation of PodSecurityPolicy
```

[As-is]
```Markdown
## Dependencies

### Added
...

### Changed
...

### Removed
...

## Dependencies <!-- Duplicate -->

### Added <!-- Duplicate -->
...

### Changed <!-- Duplicate -->
...

### Removed <!-- Duplicate -->
...
```

[To-be]
```Markdown
## Dependencies

### Added
...

### Changed
...

### Removed
...
```

[As-is]
```Markdown
## Downloads for v1.21.0

filename | sha512 hash
-------- | -----------
```

[To-be]

```Markdown
## Downloads for v1.21.0

### Source Code

filename | sha512 hash
-------- | -----------
```

#### How to see the bugs:
- Visit https://kubernetes.io/docs/setup/release/notes/
- Visit https://github.com/kubernetes/website/blob/master/content/en/docs/setup/release/notes.md

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by pmmalinov01** [comment]
That is interesting. I know about PR https://github.com/kubernetes/kubernetes/pull/100968 that should fix the current release notes and remove duplication and not needed items. Maybe, the kubernetes.io has not picked the fixed changelog?
/cc wilsonehusin

**Comment by jihoon-seo** [comment]
CC: @wilsonehusin

**Comment by wilsonehusin** [comment]
ouch i didn't realize this is happening in k/website too. thanks for bringing this up @jihoon-seo!

the fix should be pretty close to what @pmmalinov01 mentioned. if anyone would like to take it, you're welcome to. otherwise i will get to this sometime this weekend!

**Comment by wilsonehusin** [comment]
> Maybe, the kubernetes.io has not picked the fixed changelog?

🤔 looks like k/website part was manually done by the docs team of release team, which makes sense that they picked up the one with bug because we didn't catch the k/k bug until a day after or so.

**Comment by wilsonehusin** [comment]
so I think this bug should go to [k/release](https://github.com/kubernetes/release) because the actual tool which generates these documents are in that repository.

@jihoon-seo would you be interested to contribute code as well? let me know and we can work on it together, I'm `@wilsonehusin` on Kubernetes Slack 😃 

(of course @pmmalinov01 you're invited too)

**Comment by jihoon-seo** [comment]
I opened an issue https://github.com/kubernetes/release/issues/2012,
so I am going to close this issue.
Thank you @pmmalinov01 and @wilsonehusin !
