### ISSUE TITLE
Domain transfer: downloadkubernetes.com

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1549]
#### What would you like to be added:

Transfer downloadkubernetes.com from @chuckha to Kubernetes Community control.

#### Why is this needed:

While we handled the repo migration for this domain in https://github.com/kubernetes/org/issues/2131, we didn't transfer the domain over.

Chuck is spinning down some personal infra and we need to [finish configuring Netlify](https://github.com/kubernetes-sigs/downloadkubernetes/issues/10) to have the site updating on a more frequent cadence.

/assign
/area release-eng

**Comment by justaugustus** [comment]
I've initiated a domain transfer from Chuck to myself, which should be complete by 5/2.
From there, I'll handle the transfer to CNCF service desk.

**Comment by justaugustus** [comment]
This got lost in the queue.
@idvoretskyi @caniszczyk -- What's the right way to proceed w/ the domain transfer?

/remove-lifecycle stale
/milestone v1.24

**Comment by idvoretskyi** [comment]
cc @amye to provide more details

**Comment by idvoretskyi** [comment]
@justaugustus just file an issue to the CNCF ServiceDesk!

**Comment by justaugustus** [comment]
/lifecycle rotten
I need to take of this, as I currently own the Netlify site
