### ISSUE TITLE
Migrate CI Signal Report tool

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/sig-release#1586]
#### What would you like to be added:
I would like to find an official place for the CI Signal Reporting tool, to keep improving it:
https://github.com/alenkacz/ci-signal-report

Right now I fixed some issues so we can use it again, but I think we can do more with it. There was also a short chatting with @alenkacz who basically brought up the idea to bring the tool to the release team.
#### Why is this needed:
The key benefit is the SIG-oriented summary of the report and some basic statistics of the progress. The report is used to be published in the #release-ci-signal and used in the weekly release meeting.

However, I believe we can do more out of it:
- automate the report to be pushed in #release-ci-signal
- maybe (!?) automate to push weekly to the sigs the open issues (tbd)
- improving a go/no-go decision

**Comment by justaugustus** [comment]
Slack discussion: https://kubernetes.slack.com/archives/C2C40FMNF/p1622718810193000
Next steps, IIUC: @alenkacz to migrate into k/release.

**Comment by alenkacz** [comment]
Yes yes, I'll do it!

**Comment by mkorbi** [comment]
Hey @alenkacz 

to give you some support, as a c&p License you can use this one: https://github.com/kubernetes/sig-release/blob/master/LICENSE

To request the donation you have to open here a ticket: https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-repo&template=repo-create.md&title=

I prepared the submission template here: https://gist.github.com/mkorbi/c20a27ec72d07c510b69d45b09e48fda

**Comment by mkorbi** [comment]
as the new CI Signal team is looking into improving it I would like to give another ping @alenkacz 
/cc @encodeflush @leonardpahlke
