### ISSUE TITLE
Cut 1.22.0-alpha.3 release

### ISSUE THREAD

**Issue by wilsonehusin** [kubernetes/sig-release#1589]
## Scheduled to happen: 

Tuesday, 2021-06-07 09:00 GMT -7 (16:00 GMT)

## Release Steps

- [x] Screenshot unhealthy release branch testgrid boards
- Mock Run
  - [x] Stage
  - [x] Release
- NoMock Run
  - [x] Stage
  - [x] Image Promotion: https://github.com/kubernetes/k8s.io/pull/2162
  - [x] Release
- [x] Notify #release-management]: [announcement](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1623179501269900?thread_ts=1623166979.262000&cid=CJH2GBF7Y)
- [x] Send notification: [`k-dev` announcement](https://groups.google.com/g/kubernetes-dev/c/NbfAD5UAJ-w)
- [x] Collect metrics and add them to the `Release steps` table below

## Release Tools Version

```
✦ ❯ krel version
GitVersion:    v0.9.0
GitCommit:     f3f045344694c286947b17e720a35a66f75e50d5
GitTreeState:  clean
BuildDate:     2021-06-08T00:28:54Z
GoVersion:     go1.16.4
Compiler:      gc
Platform:      linux/amd64
```

## Release Jobs History

| Step | Command | Link | Start | Duration | Succeeded? |
| --- | --- | --- | --- | --- | --- |
| Mock stage | `bin/krel stage --submit=false --log-level=info --type=alpha --branch=master --build-version=v1.22.0-alpha.2.493+b7514645d4e5d3` | [GCB](https://console.cloud.google.com/cloud-build/builds/a7537a35-9763-4f4e-bfa8-6022baaf77f3;step=3?project=kubernetes-release-test) |  2021-06-08T16:02:16+00:00 | 00:50:32 | Yes |
| Mock release | `bin/krel release --submit=false --log-level=info --type=alpha --branch=master --build-version=v1.22.0-alpha.2.493+b7514645d4e5d3` | [GCB](https://console.cloud.google.com/cloud-build/builds/3805ab0f-1578-40ec-9ce0-b6f06d0590e2?project=648026197307) | 2021-06-08T16:57:16+00:00 | 00:04:19 | Yes |
| Stage | `bin/krel stage --submit=false --nomock --log-level=info --type=alpha --branch=master --build-version=v1.22.0-alpha.2.495+0322d34a3e0b64` | [GCB](https://console.cloud.google.com/cloud-build/builds/e1812800-7510-44d0-84d5-4404cb4b9779;step=3;tab=detail?project=kubernetes-release-test) | 2021-06-08T17:11:36+00:00 | 00:51:17 | Yes |
| Release | `krel release --nomock --build-version=v1.22.0-alpha.2.495+0322d34a3e0b64` | [GCB](https://console.cloud.google.com/cloud-build/builds/500414ea-4d5d-4ee9-92a2-6bd92e7a00c4?project=kubernetes-release-test) | 2021-06-08T18:17:56+00:00 | 00:04:38 | Yes |

## Open Questions

/milestone v1.22
/assign wilsonehusin
/cc @kubernetes/release-managers
/priority important-soon
/kind documentation

**Comment by wilsonehusin** [comment]
🤨 

/milestone v1.22
/assign wilsonehusin

**Comment by pmmalinov01** [comment]
Good luck! 
/pony

**Comment by puerco** [comment]
Board screenshot as shared in #release-management 
![image](https://user-images.githubusercontent.com/3935899/121217157-2e4d8e80-c847-11eb-887e-7256b5389891.png)
