### ISSUE TITLE
Suggest to add a presubmit checking for validating the release notes yaml files 

### ISSUE THREAD

**Issue by cici37** [kubernetes/sig-release#1595]
#### What would you like to be added:
A presubmit check to validate the release notes yaml files.

#### Why is this needed:
When I try to create the release notes PR as a release note shadow, met an issue of the existing yaml files under `sig-release/releases/release-[version]/release-notes/maps/` is not valid hence the release note script would fail directly(https://github.com/kubernetes/release/issues/2114). It would be great to have a checking to prevent the similar issue from further happening.

**Comment by wilsonehusin** [comment]
yes! I like this pre-submit approach, probably something simple with [`yq`](https://github.com/mikefarah/yq) (but more robust than this oneliner) like `find . -type f -name "*.yaml" | xargs yq r` to make sure exit code is parse-able.

I think we'll need to tinker around with [`k/test-infra`](https://github.com/kubernetes/test-infra) to add Prow jobs, but I'm not exactly sure where...

@cpanato I know you did stuff about adding tests to other repos -- mind teaching me / us how to do so? :)

**Comment by cici37** [comment]
From my understanding, adding a separate presumit job configuration into `https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/kubernetes-builds.yaml` would do the magic? Please correct me if there is anything wrong with my understanding ^^

**Comment by wilsonehusin** [comment]
🤔 that looks right, but I wonder if there is already a boilerplate elsewhere. might be worth doing a search in the repository and/or posting on `#sig-release` to see if anyone is around to confirm 😄

**Comment by saschagrunert** [comment]
We would have to create a new config since we do not have any presubmits for k/sig-release right now. There are different images available for different purposes. For example we maintain a [`gcr.io/k8s-staging-releng/releng-ci:latest-go1.16` image](https://github.com/kubernetes/release/blob/master/images/releng/ci/Dockerfile) in `k/release`, where I could imagine that we add required tools to this one.

**Comment by cpanato** [comment]
@puerco let me know if you need any help
