### ISSUE TITLE
Release Manager access for onlydole

### ISSUE THREAD

**Issue by puerco** [kubernetes/sig-release#1601]
### GitHub Username

@onlydole 

### [Release Manager](https://git.k8s.io/sig-release/release-managers.md) role

Release Manager

### Tenure

temporary: Taylor (@onlydole ) is a Release Manager Associate being granted temporary elevated access to cut the v1.22.0-beta.0 release. Access should be revoked after the 1.22.0-beta.0 release is cut.

### Release Manager

- [x] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-editors@`
    - Temporary access grant: https://github.com/kubernetes/k8s.io/pull/2249
    - Temporary access drop: https://github.com/kubernetes/k8s.io/pull/2280

cc: @kubernetes/release-engineering
/milestone v1.22

**Comment by onlydole** [comment]
Thank you, @puerco! This is complete and I'm good to have this access removed ✅

**Comment by puerco** [comment]
Temporary access was dropped.
/close
