### ISSUE TITLE
Update policy about promoting CI jobs to informing/blocking dashboards

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/sig-release#1611]
Goal is to [enhance the existing documentation](https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md) about the management (promotion and demotion) of master informing and blocking jobs in our dashboards:

- https://testgrid.k8s.io/sig-release-master-informing
- https://testgrid.k8s.io/sig-release-master-blocking

The outcome of the consensus in https://github.com/kubernetes/sig-release/issues/1608 should be used as input for the documentation update.

**Comment by kaiwalyakoparkar** [comment]
Hey, @saschagrunert will you please guide me, I would like to work on this.

**Comment by saschagrunert** [comment]
> Hey, @saschagrunert will you please guide me, I would like to work on this.

Thank you for taking the opportunity here @kaiwalyakoparkar, let's wait on the resolution of the linked issue (https://github.com/kubernetes/sig-release/issues/1608) first.

**Comment by kaiwalyakoparkar** [comment]
> > Hey, @saschagrunert will you please guide me, I would like to work on this.
> 
> Thank you for taking the opportunity here @kaiwalyakoparkar, let's wait on the resolution of the linked issue (#1608) first.

Thank you so much for replying @saschagrunert looking forward to seeking guidance and work on this :smiley:

**Comment by saschagrunert** [comment]
I'm going to work on this tomorrow.
