### ISSUE TITLE
1.22 Kubernetes Major themes contact

### ISSUE THREAD

**Issue by pmmalinov01** [kubernetes/sig-release#1615]
With major themes submission formalizing to use GitHub Discussions, we hope that this cycle will be the last time that the release team needs to reach out to SIGs for their response.

Having that said, since the process is new, the release notes team will be using this issue to track the work on nudging SIGs for entries on major themes for the 1.22 release cycle.

The Slack channel for each SIG is usually #sig-<name>, but accurate links are available in [k/community](https://github.com/kubernetes/community) under [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md). The plan is to start asking for responses on public Slack channel (non-disruptively).

The following is a template meant for a guide, so feel free to use the language you're comfortable with!

```
Hello SIG <NAME>, the 1.22 release notes team is gathering major themes entries for 
the release and if you have anything to call out, we would really appreciate it if your 
SIG can submit the content in https://github.com/kubernetes/sig-release/discussions/1575
Ideally, we would like this to be completed by July 19. Thanks!
```

Some SIGs have activities that aren't quite coupled with Kubernetes releases, but it's worth checking anyway in case there are things worth calling out in what they did between the previous release and current release. One example is Immutable Secrets and ConfigMaps from the 1.21 release or Dockershim deprecation from the 1.20.

We'll try to keep the list below up-to-date, but please double-check in comments if someone has contacted their channel:

- [x]  API Machinery
- [x]  Apps
- [x]  Architecture
- [x]  Auth
- [x]  Autoscaling
- [x]  CLI
- [x]  Cloud Provider
- [x]  Cluster Lifecycle
- [x]  Contributor Experience
- [x]  Docs
- [x]  Instrumentation
- [x]  Multicluster
- [x]  Network
- [x]  Node
- [x]  Release
- [x]  Scalability
- [x]  Scheduling
- [x]  Security
- [x]  Service Catalog
- [x]  Storage
- [x]  Testing
- [x]  UI
- [x]  Usability
- [x]  Windows

/assign @simcard0000 @Damans227 @sladyn98 @cici37 
/milestone v1.22

**Comment by cici37** [comment]
Have sent message out to 
 ✅ API Machinery
 ✅ Apps
 ✅ Architecture
 ✅ Cloud Provider

**Comment by pmmalinov01** [comment]
All sigs have been reached via Slack. Not it is only left to wait if they have something to contribute to the Major Themes.
