### ISSUE TITLE
Assemble Kubernetes 1.23 Release Team 🎉 

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/sig-release#1623]
Hi Kubernetes fam! We've been working really hard and gearing up for the current release, so it is time to being assembling the 1.23 release team!

Please review the [Release Team Selection Process docs](https://github.com/kubernetes/sig-release/blob/master/release-team/release-team-selection.md) for details on the process and criteria.

At this stage, we only require nominations for Role Leads. Once role leads are nominated we will then send out a shadow application survey.

/sig release
/area release-team
/milestone v1.23

cc @justaugustus @saschagrunert @savitharaghunathan

**Comment by savitharaghunathan** [comment]
It was an honor to lead the 1.22 cycle. Thank you team for giving me this opportunity :) 

I would like to nominate @reylejano as the 1.23 Release Team Lead! Rey has experience with various release team roles and I believe he will be a great lead! Congratulations @reylejano 🎉 ❤️ 

/pony party

**Comment by Damans227** [comment]
You did a great job @savitharaghunathan  Your leadership during the turbulent times is greatly appreciated. Looking forward to continue working with you further. You are a champion!

**Comment by reylejano** [comment]
Thank you for @guineveresaenger for being EA for 1.22!

> I would like to nominate @reylejano as the 1.23 Release Team Lead! Rey has experience with various release team roles and I believe he will be a great lead! Congratulations @reylejano 🎉 ❤️

Thank you @savitharaghunathan for guiding us through the 1.22 release and for nominating me as the 1.23 Release Team Lead -- I'm truly honored 🎉

**Comment by Damans227** [comment]
Also, congratulations on your new role @reylejano keep up the good work!!👏👏👏

**Comment by JamesLaverack** [comment]
I'm super happy to nominate @salaxander as v1.23 Enhancements Lead. 🎉 Xander has done a great job as an enhancements shadow this cycle and I'm looking forward to him as a role lead.

**Comment by JamesLaverack** [comment]
Oh sorry forgot my

/pony party

**Comment by salaxander** [comment]
Thanks @JamesLaverack! So excited to work with many of you again on 1.23! :)

**Comment by savitharaghunathan** [comment]
Congratulations @salaxander 🎊🎉

**Comment by mkorbi** [comment]
The (sometimes) hardest part of the release. I wish I could nominate a Co-Leadership for the CI Signal, the team turns from all first release team members to a very proactive team and I believe every one of you could lead the 1.23 CI Signal! Therefore, I very much hope to see you all back on the team and support each other ✌️

Back to business - I'm excited to nominate @encodeflush as the next 1.23 CI Signal lead! Again, I think this release was all about a great teamwork and you grow together, and I trust in you to keep the things moving this way!

/pony party

**Comment by encodeflush** [comment]
Thank you for your trust in me @mkorbi I am so happy and excited to continue working on my favorite project with you all :)

**Comment by guineveresaenger** [comment]
I am happy and excited to nominate @jeremyrickard to be Emeritus Adviser for 1.23! 🥳 Thank you for your long and continued service. I'm excited to have the next release team be in excellent hands! 👨‍🏫

**Comment by reylejano** [comment]
It's super **_rad_** to have @jeremyrickard as the 1.23 Emeritus Adviser 🎉

**Comment by pmmalinov01** [comment]
I am overjoyed to nominate @cici37 for the release notes lead in 1.23. Cici has improved and contributed a lot in the past release. She is proactive and engaged in working with the release team. I am happy to see her take this challenge.

/pony

**Comment by Damans227** [comment]
Congrats @cici37 way to go!! 👏👏 Keep up the great work.

**Comment by savitharaghunathan** [comment]
Congratulations @encodeflush and @cici37 🎊🎉

**Comment by salaxander** [comment]
Big congrats @encodeflush and @cici37! Super excited to work with both of you!! 🎉

**Comment by MonzElmasry** [comment]
Im super excited to nominate @voigt as v1.23 Bug Triage Lead. :tada: :tada:

**Comment by PI-Victor** [comment]
I'm happy to nominate @jlbutler as Docs lead for v1.23. Jesse has stepped up in a time of need to become Comms lead and i think the Docs lead hat will fit just perfectly. Thank you, once again, Jesse for all the support and work in this release!

**Comment by savitharaghunathan** [comment]
Congratulations @voigt and @jlbutler 🎉 
/pony party

**Comment by jlbutler** [comment]
Thanks @PI-Victor! Very happy to help out however I can, and looking forward to working on 1.23 with the team! 🚀

**Comment by jlbutler** [comment]
I'm so happy to nominate @karenhchu as Comms lead for 1.23! Karen served as Comms Lead for 1.18 and is stepping up again, thank you Karen and looking forward to working with you!

**Comment by reylejano** [comment]
Congratulations and thank you to @cici37 @encodeflush @jlbutler  @karenhchu @salaxander @voigt ! 
I'm looking forward to work with everyone on 1.23!

**Comment by guineveresaenger** [comment]
This is ready to be worked on! :tada:

/assign @reylejano

**Comment by reylejano** [comment]
The team is assembled, the issue is complete
/close
