### ISSUE TITLE
Release Team Lead access for @reylejano @jameslaverack @jrsapi @mkorbi @monzelmasry 

### ISSUE THREAD

**Issue by reylejano** [kubernetes/sig-release#1652]
### GitHub Username(s)

- @reylejano
- @JamesLaverack 
- @jrsapi 
- @mkorbi 
- @MonzElmasry 

### Release Cycle

Kubernetes 1.23

### Prerequisites

- [x] Ensure new Release Team Lead:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
  - [x] Has completed the [CNCF Inclusive Speaker Orientation](https://training.linuxfoundation.org/training/inclusive-speaker-orientation/)

### Onboarding

- [x] Release Team Lead has agreed to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.
  This must be done as an issue comment by the incoming Release Team Lead.
- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) https://github.com/kubernetes/org/pull/2881
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
  - `sig-release`
- [x] Update `kubernetes/sig-release` `OWNERS` https://github.com/kubernetes/sig-release/pull/1654
  - Release Team Lead and Shadows
    - Add an `approvers` entry in `releases/release-x.y/OWNERS`
  - **Release Team Lead only**
    - In `OWNERS_ALIASES`, add an entry in the following sections: https://github.com/kubernetes/sig-release/pull/1653
      - `release-team`
      - `release-team-lead-role`
- [x] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml) https://github.com/kubernetes/k8s.io/pull/2541
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [x] Manually grant access on the following Google Groups:
  - [release-team](https://groups.google.com/a/kubernetes.io/g/release-team) (Add as Manager)
<strike>  - [kubernetes-sig-leads](https://groups.google.com/forum/#!forum/kubernetes-sig-leads) (Add as Member)</strike>
- [x] Grant calendar access
- [x] Grant Zoom credentials (host key)
- [x] Add incoming leads to `release-team-leads` Slack Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml) https://github.com/kubernetes/community/pull/5950
  - Add slack ID(s) to [`users.yaml`](https://git.k8s.io/community/communication/slack-config/users.yaml), if they are not yet in the file
  - Add username(s) to [`usergroups.yaml`](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)

cc: @kubernetes/release-engineering @kubernetes/release-team
/milestone v1.23
/priority critical-urgent

**Comment by reylejano** [comment]
I have completed the CNCF Inclusive Speaker Orientation training: LF-gg98o5wyjx

I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by mkorbi** [comment]
[CNCF  Inclusive Speaker Orientation](https://www.credly.com/badges/b93cb2c4-3196-488a-9c06-5ff1b703d11e/public_url)
I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by jrsapi** [comment]
I have completed the CNCF Inclusive Speaker Orientation training cert ID: LF-c5j6kr89v5

I solemnly swear to abide by the guidelines set forth in the [Security Release Process](https://github.com/kubernetes/security/blob/master/security-release-process.md), specifically the embargo on CVE communications.

**Comment by JamesLaverack** [comment]
I have completed the [CNCF Inclusive Speaker Orientation](https://training.linuxfoundation.org/training/inclusive-speaker-orientation) training. Certificate ID Number: `LF-8i8itysb26`

I solemnly swear to abide by the guidelines set forth in the [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.

**Comment by MonzElmasry** [comment]
I have completed the [CNCF Inclusive Speaker Orientation](https://training.linuxfoundation.org/training/inclusive-speaker-orientation) training. Certificate ID Number: `LF-vk68gykyeg`

I solemnly swear to abide by the guidelines set forth in the [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.

**Comment by justaugustus** [comment]
Let's take offboarding as an action for the 1.24 team.
/close
