### ISSUE TITLE
Add note about access to milestone maintainers link in the Kubernetes Docs lead handbook

### ISSUE THREAD

**Issue by SubhasmitaSw** [kubernetes/sig-release#1658]
The README.md for Kubernetes Docs Lead Handbook contains a broken link directing to 'milestone maintainers'. 

where to find the issue : sig-release/release-team/role-handbooks/docs/
broken link : https://github.com/orgs/kubernetes/teams/website-milestone-maintainers/

**Comment by sftim** [comment]
I think you're saying that the hyperlink should point to https://github.com/orgs/kubernetes/teams/website-milestone-maintainers/ but I might be wrong.

If you have enough access, https://github.com/orgs/kubernetes/teams/website-milestone-maintainers/ is a valid hyperlink.

**Comment by SubhasmitaSw** [comment]
Oh, I was not aware of the access, it's valid since I don't have the access and it shows an error. Don't you think it would be better if mentioned the accessibility of this website in the docs? It might prevent someone else from doing the same thing I did.

**Comment by reylejano** [comment]
/retitle Add note about access to milestone maintainers link in the Kubernetes Docs lead handbook
/kind cleanup
/triage accepted

PR https://github.com/kubernetes/sig-release/pull/1659 fixes this issue

**Comment by BenTheElder** [comment]
To view the team you have to be a github kubernetes org member IIRC, we've run into this in other places before : /
