### ISSUE TITLE
Release Manager access for palnabarun 

### ISSUE THREAD

**Issue by puerco** [kubernetes/sig-release#1665]
### GitHub Username

@palnabarun 

### [Release Manager](https://git.k8s.io/sig-release/release-managers.md) role

Release Manager

### Tenure

temporary: Nabarun Pal (@palnabarun ) is a Release Manager Associate being granted temporary elevated access to cut the v1.22.1/v1.23.0-alpha.1 releases. Access should be revoked after the releases are cut.

### Release Manager

- Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-editors@`
    - [ ] Temporary access grant
    - [ ] Temporary access drop

cc: @kubernetes/release-engineering
/milestone v1.23

**Comment by saschagrunert** [comment]
I think this can be closed
