### ISSUE TITLE
Consider multiple retrospectives during the cycle rather than 3 at the end

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/sig-release#1695]
The idea is to move the retrospectives from the end of the cycle to the second half of it. This provides faster feedback loops to catch-up on issues and follow-ups. It also enables the team to solve possible problems directly during the cycle rather than handing them over to the next team, which they're probably not part of.

Thoughts on that @kubernetes/release-team-leads ?

**Comment by jeremyrickard** [comment]
I personally like this idea. With 1.23 especially, the retros will fall pretty late into December (considering when people start to be unavailable for holiday vacations). 

Doing them earlier will allow for better course correction and problem solving during the cycle, and might make for more opportunities for RT members to contribute during the cycle and be more engaged.

**Comment by justaugustus** [comment]
How about immediately as we head into burndown?

**Comment by justaugustus** [comment]
cc: @kubernetes/sig-release-leads
