### ISSUE TITLE
Release Manager access for Verolop

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1713]
### GitHub Username

@Verolop 

### [Release Manager](https://git.k8s.io/sig-release/release-managers.md) role

Release Manager

### Tenure

permanent: https://groups.google.com/a/kubernetes.io/g/release-managers/c/zSiEg0dUQRE

### Release Manager Onboarding

**All pull requests within these checklists should be marked with an _explicit_ hold and only released once approved by a Release Engineering subproject owner.**

- [x] Addition of a new Release Manager has been discussed with and approved by Release Engineering subproject owners
- [x] Ensure new Release Manager:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
- [x] Update [Release Managers](https://git.k8s.io/sig-release/release-managers.md) page to include the new Release Manager: https://github.com/kubernetes/website/pull/29757

### Release Manager

- [x] Release Manager has agreed to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.
  (This must be done as an issue comment by the incoming Release Manager.)
- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml): https://github.com/kubernetes/org/pull/2984
  - `milestone-maintainers`
  - `release-engineering`
  - `release-managers`
- [x] Update `OWNERS`
  - [x] `kubernetes/sig-release` `OWNERS_ALIASES` (https://github.com/kubernetes/sig-release/pull/1802)
    - Add entry in the `release-engineering-reviewers` section
      (only if they are not already in the `release-engineering-reviewers`
      or `release-engineering-approvers` section)
  - [x] `kubernetes/release` `OWNERS_ALIASES`: https://github.com/kubernetes/release/pull/2331
    - Add entry in the `release-engineering-reviewers` section
      (only if they are not already in the `release-engineering-reviewers`
      or `release-engineering-approvers` section)
  - [x] `kubernetes/test-infra` `OWNERS_ALIASES` (https://github.com/kubernetes/test-infra/pull/24809)
    - Add entries in the following sections:
      - `release-engineering-reviewers`
      - `release-engineering-approvers`
      - `publishing-bot-reviewers`
  - [x] `kubernetes/kubernetes` `OWNERS_ALIASES` (https://github.com/kubernetes/kubernetes/pull/107431)
    - Add entry in the `release-engineering-reviewers` section
      (only if they are not already in the `release-engineering-reviewers`
      or `release-engineering-approvers` section)
- [x] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml) https://github.com/kubernetes/k8s.io/pull/2872
  - `k8s-infra-release-editors@`
  - `k8s-infra-release-viewers@`
  - `release-managers@`
  - `release-managers-private@`
  - `release-team@`
- [x] Manually grant permission to post on [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
- [x] Update Slack `release-managers` User Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml) (https://github.com/kubernetes/community/pull/6302)
- [x] Manually add to the [#security-release-team](https://kubernetes.slack.com/archives/G0162T1RYHG) Slack channel

/assign @Verolop @puerco 
cc: @kubernetes/release-engineering

**Comment by Verolop** [comment]
I abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by justaugustus** [comment]
@Verolop @puerco -- Just wanted to check in on this one :)

**Comment by palnabarun** [comment]
All done! Closing.

/close
