### ISSUE TITLE
1.23 Kubernetes Major themes contact

### ISSUE THREAD

**Issue by cici37** [kubernetes/sig-release#1742]
With major themes submission formalizing to use GitHub Discussions, we hope that this cycle will be the last time that the release team needs to reach out to SIGs for their response.

Having that said, since the process is new, the release notes team will be using this issue to track the work on nudging SIGs for entries on major themes for the 1.23 release cycle.

The Slack channel for each SIG is usually #sig-, but accurate links are available in k/community under sig-list.md. The plan is to start asking for responses on public Slack channel (non-disruptively).

The following is a template meant for a guide, so feel free to use the language you're comfortable with!

```
Hello SIG <NAME>, the 1.23 release notes team is gathering major themes entries for 
the release and if you have anything to call out, we would really appreciate it if your 
SIG can submit the content in https://github.com/kubernetes/sig-release/discussions/1709
Ideally, we would like this to be completed by Nov 23. Thanks!
```

It is great if we would propose some Major Themes candidates when nudging SIGs based on tracked enhancements we have [here](https://docs.google.com/spreadsheets/d/1P1J1QpayRmh2SNjs8T-wBCb6SgEOdWTRQ7MBol7yibk/edit#gid=0). Please feel free to tag the enhancement owner from each SIG to make sure if they want it to be included in Major Themes. 

Some SIGs have activities that aren't quite coupled with Kubernetes releases, but it's worth checking anyway in case there are things worth calling out in what they did between the previous release and current release. One example is Immutable Secrets and ConfigMaps from the 1.21 release or Dockershim deprecation from the 1.20.

We'll try to keep the list below up-to-date, but please double-check in comments if someone has contacted their channel:

- [x] API Machinery
- [x] Apps
- [x] Architecture
- [x] Auth
- [x] Autoscaling
- [x] CLI
- [x] Cloud Provider
- [x] Cluster Lifecycle
- [x] Contributor Experience
- [x] Docs
- [x] Instrumentation
- [x] Multicluster
- [x] Network
- [x] Node
- [x] Release
- [x] Scalability
- [x] Scheduling
- [x] Security
- [x] Service Catalog
- [x] Storage
- [x] Testing
- [x] UI
- [x] Usability
- [x]  Windows

/assign @AuraSinis @parul5sahoo @Damans227 @sam-cogan 
cc @reylejano @JamesLaverack @jrsapi @mkorbi @MonzElmasry 
/milestone v1.23

**Comment by JamesLaverack** [comment]
Happy to take a few of these. I won't send messages or tag people until *after* code freeze though. 😅

**Comment by cici37** [comment]
> Happy to take a few of these. I won't send messages or tag people until _after_ code freeze though. 😅

Sure. We will not start unless code freeze is over^^ Thank you for jumping in  :)

**Comment by parul5sahoo** [comment]
I would like to take up, API Machinery, Architecture, Autoscaling, CLI, Node.

**Comment by cici37** [comment]
> I would like to take up, API Machinery, Architecture, Autoscaling, CLI and Node.

Thank you for taking it up. Please update after you have contacted those SIGs so we could mark it in description for tracking.

**Comment by cici37** [comment]
/close
All SIGs have been contacted and will watch the Major Theme discussion in https://github.com/kubernetes/sig-release/discussions/1709
