### ISSUE TITLE
Cut v1.23.0-rc.1

### ISSUE THREAD

**Issue by Verolop** [kubernetes/sig-release#1769]
## Release Steps

- [x] Create a thread on #release-management: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1638584308362300
- [ ] Screenshot unhealthy release branch testgrid boards
- Mock Run
  - [x] Stage
  - [x] Release
- NoMock Run
  - [x] Stage
  - [x] Image Promotion: 
  - [x] Release
- [x] Notify #release-management: 
- [x] Send notification: 
- [ ] Collect metrics and add them to the `Release steps` table below

## Release Tools Version

```
GitVersion:    vM.m.p
GitCommit:     191ddd0b0b49af1adb04a98e45cebdd36cae9307
GitTreeState:  clean
BuildDate:     YYYY-MM-DDTHH:mm:ssZ
GoVersion:     go1.16.3
Compiler:      gc
Platform:      linux/amd64
```

## Release Jobs History

| Step | Command | Link | Start | Duration | Succeeded? |
| --- | --- | --- | --- | --- | --- |
| Mock stage | `krel stage --type rc --branch release-1.23 --build-version v1.23.0 ` |https://console.cloud.google.com/cloud-build/builds;region=global/303c70de-8de5-44f3-8fe0-76a4559ea19a?project=kubernetes-release-test |December 4, 2021 at 3:14:16 AM UTC |3:20:07 AM UTC |NO |
| Mock stage | `krel stage --type rc --branch release-1.23 --build-version v1.23.0 `|https://console.cloud.google.com/cloud-build/builds;region=global/056d0f4c-a399-4d9f-8ce0-19c73f565167?project=kubernetes-release-test |December 4, 2021 at 3:31:31 AM UTC |3:33:12 AM UTC |NO |
| Mock stage | `krel stage --type rc --branch release-1.23 --build-version v1.23.0-rc.0.14+a3fc39c3e3c43a` |https://console.cloud.google.com/cloud-build/builds;region=global/eba1ae7c-1cfd-4329-b486-4840ac301364;tab=detail?project=kubernetes-release-test |December 4, 2021 at 3:43:01 AM UTC |3:50:13 AM UTC |NO |
| Mock stage | `krel stage --type rc --branch release-1.23 --build-version v1.23.0-rc.0.14+a3fc39c3e3c43a ` |https://console.cloud.google.com/cloud-build/builds/6e525eaa-86fe-4b03-a437-c7a2dea12d4b;tab=detail?project=kubernetes-release-test |December 4, 2021 at 4:52:03 AM UTC |5:49:03 AM UTC |YES |
| Mock release | `krel release --type=rc --branch=release-1.23 --build-version=v1.23.0-rc.0.15+a3fc39c3e3c43a `|https://console.cloud.google.com/cloud-build/builds/d2c8ce59-f398-468b-b22e-6f021fefdf7b?project=kubernetes-release-test |December 4, 2021 at 5:57:50 AM UTC|6:06:41 AM UTC |YES |
| Stage | `krel stage --type rc --branch release-1.23 --build-version v1.23.0-rc.0.14+a3fc39c3e3c43a --nomock` |https://console.cloud.google.com/cloud-build/builds/ec859092-ef7a-4fcb-a609-22c648d82923?project=648026197307 | December 4, 2021 at 6:13:35 AM UTC| | |
| Release | `krel release [arguments]` | | | | |

## Action Items

- [ ] Add `--build` as a flag on `krel` (so krel can pull the specified sha to use as a build point)

## Open Questions

/assign @Verolop 
/cc @kubernetes/release-managers
/priority important-soon
/kind documentation

**Comment by saschagrunert** [comment]
@puerco can we close this one?
