### ISSUE TITLE
Release Team Lead access for @JamesLaverack @jlbutler @salaxander @cici37 @mkorbi

### ISSUE THREAD

**Issue by JamesLaverack** [kubernetes/sig-release#1791]
### GitHub Username(s)

- @JamesLaverack
- @jlbutler
- @salaxander
- @cici37
- @mkorbi

### Release Cycle

Kubernetes 1.24

### Prerequisites

- [x] Ensure new Release Team Lead:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [ ] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
  - [ ] Has completed the [CNCF Inclusive Speaker Orientation](https://training.linuxfoundation.org/training/inclusive-speaker-orientation/)

### Onboarding

- [ ] Release Team Lead has agreed to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.
  This must be done as an issue comment by the incoming Release Team Lead.
- [ ] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
  - `sig-release`
- [x] Update `kubernetes/sig-release` `OWNERS`
  - Release Team Lead and Shadows
    - Add an `approvers` entry in `releases/release-x.y/OWNERS`
  - **Release Team Lead only**
    - In `OWNERS_ALIASES`, add an entry in the following sections:
      - `release-team`
      - `release-team-lead-role`
- [x] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-viewers@`
  - `release-managers@`
  - `release-team@`
- [x] Grant calendar access
- [x] Grant Zoom credentials (host key)
- [ ] Add incoming leads to `release-team-leads` Slack Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)
  - Add slack ID(s) to [`users.yaml`](https://git.k8s.io/community/communication/slack-config/users.yaml), if they are not yet in the file
  - Add username(s) to [`usergroups.yaml`](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)

### Offboarding

- [ ] Remove from GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
- [ ] Remove from Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [ ] Manually remove from the following Google Groups:
  - [kubernetes-release-team](https://groups.google.com/a/kubernetes.io/g/release-team) (Add as Manager)
  - [kubernetes-sig-leads](https://groups.google.com/forum/#!forum/kubernetes-sig-leads) (Add as Member)
- [ ] Remove from `release-team-leads` Slack Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)
  - Remove slack ID(s) from [`users.yaml`](https://git.k8s.io/community/communication/slack-config/users.yaml), if no longer in a group
  - Remove username(s) from [`usergroups.yaml`](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)

cc: @kubernetes/release-engineering @kubernetes/release-team

**Comment by mkorbi** [comment]
I agree abide to follow the guidelines set embargo on CVE communications.
[Inclusive Speaker](https://www.credly.com/badges/b93cb2c4-3196-488a-9c06-5ff1b703d11e/public_url)

**Comment by JamesLaverack** [comment]
I have completed the CNCF Inclusive Speaker Orientation training. Certificate ID Number: LF-8i8itysb26

I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by jlbutler** [comment]
I have completed the CNCF Inclusive Speaker Orientation training. Certificate ID Number: LF7pd08wfey1

I agree to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by cici37** [comment]
I have completed the CNCF Inclusive Speaker Orientation training. Certificate ID Number: LF3ontws1w6c
I agree to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.
