### ISSUE TITLE
A better Readme

### ISSUE THREAD

**Issue by Mihir-Bhasin** [kubernetes/sig-release#1807]
#### What would you like to be added:
I guess the readme should be more improvised

**Comment by saschagrunert** [comment]
Hey @Mihir-Bhasin :wave: thank you for opening this issue!

> I guess the readme should be more improvised

Do you mind elaborating a bit on which parts should be improved and how?

**Comment by Mihir-Bhasin** [comment]
I think a bit of information related to the purpose of SIG would be a great addition, moreover, we can also add how can Contribute to hassle-free issues management.

**Comment by justaugustus** [comment]
/help
cc: @kubernetes/sig-release-admins
