### ISSUE TITLE
Ensure groups.google.com/g/kubernetes-release-team is properly archived

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#1811]
With the introduction of the release-team@ google group, the old list should be in archived/no sending mode. 

Ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1642001447091100

We should: 

[ ] Review all handbooks to ensure it's not referenced anywhere
[ ] Update lead handbook to reference it being deprecated and that it shouldn't be added to any document sharing
[ ] Ensure that the list is properly put into archived mode. 

/sig release
/priority important-soon
/kind documentation

**Comment by jeremyrickard** [comment]
@justaugustus I'll take a look through the handbooks if you can handle the mailing list management.

**Comment by palnabarun** [comment]
(until this is verified to be done)

**Comment by jeremyrickard** [comment]
Verified that both the web posting and email posting are disabled. 

/close
