### ISSUE TITLE
Design 1.25 shadow application survey

### ISSUE THREAD

**Issue by JamesLaverack** [kubernetes/sig-release#1814]
Discussion in SIG Release (meeting [11th January 2022](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit#heading=h.35ldyn8zvdd9)) and in #sig-contribex ([Slack thread](https://kubernetes.slack.com/archives/C1TU9EB9S/p1641941787049000)) has highlighted the need to ask applicants for permission to use their data for analytical purposes.

However, there is also discussion around redesigning the shadow survey to collect information to better inform release team role leads during shadow selection.

Given these requirements, I'm opening this issue to help design the 1.25 shadow selection survey ahead of time to help the 1.25 EA.

**Comment by justaugustus** [comment]
/milestone v1.24
(since we want this done ahead of the start of the v1.25 release)

**Comment by jrsapi** [comment]
@JamesLaverack Have you started to draft the 1.25 shadow survey? Can you share so we can review?

**Comment by reylejano** [comment]
@kubernetes/sig-release-leads , @cici37, @JamesLaverack, @jrsapi , @jberkus 
I've shared the draft of the v1.25 shadow application with you. 
If you have not received a link, please reach out to me.
The v1.25 shadow application includes a request to opt-in or opt-out to use applicants' data
