### ISSUE TITLE
Create 1password vaults for SIG Release

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1833]
#### What would you like to be added:

Create 1password vaults for SIG Release

#### Why is this needed:

...because like, sharing passwords and stuff.

/assign @mrbobbytables @justaugustus 
cc: @kubernetes/sig-release-admins @kubernetes/release-managers

**Comment by saschagrunert** [comment]
I think this is done, right?

**Comment by mrbobbytables** [comment]
Yeah, just a few release managers remaining that need to accept the invite and added to the team

**Comment by saschagrunert** [comment]
> Yeah, just a few release managers remaining that need to accept the invite and added to the team

Good, let's keep it open until everyone has accepted.

**Comment by justaugustus** [comment]
Yep, let's keep this open.
Still need to confirm other invites and drop my existing creds into the new vault

**Comment by mrbobbytables** [comment]
Everyone has been invited and added to the appropriate teams 👍
