### ISSUE TITLE
ci-signal-org, record short onboarding clips

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/sig-release#1856]
**Summary:** Improve Ci Signal onboarding with short clips 

**Current situation:** Currently the CI Signal onboarding is mainly reading the [handbook](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/ci-signal/README.md) and asking questions back to the ci signal lead

**Desired outcome:** A picture says more than 100 words - I guess short clips showcasing day to day / week to week work would be very beneficial to understand what the ci signal does

/kind documentation

**Comment by lauralorenz** [comment]
Clips to cover IMHO:

- dashboards overview
- how to analyze a flake
- communication demo (slack thread, CI signal board draft for observing, turn into issue)
- release branch go/no go responsibilities walkthrough
- how to make CI signal report (@leonardpahlke)
- how to sign up for and give weekly status meeting updates

**Comment by leonardpahlke** [comment]
Yes, I think these clips would help a lot. We might need to add some clips down the road since we are discussing & developing a few new tools.

- CI Signal dashboard https://github.com/kubernetes/k8s.io/issues/3071
- sippy [slack thread](https://kubernetes.slack.com/archives/CN0K3TE2C/p1647439378698369)
- CI Signal Report CLI is still work in progress

I would propose to start with these three and then collect some feedback.

> 1. [testgrid] dashboards overview
> 2. how to analyze a flake
> 3. release branch go/no go responsibilities walkthrough

> how to make CI signal report (@leonardpahlke)

this is planned to change (see issue https://github.com/kubernetes/release/issues/2443)

WDYT @lauralorenz ?

**Comment by eddiezane** [comment]
cc

**Comment by leonardpahlke** [comment]
In the past there were already some recordings about CI Signal deep dives

* Flake finders 1 https://youtu.be/9muoWaXZK8I?t=14
* Flake finders 2 https://youtu.be/Hqlm2h2AEvA?t=7
* CI Signal Intro / Onboarding https://youtu.be/bttEcArAjUw?t=39

See [slack thread](https://kubernetes.slack.com/archives/CN0K3TE2C/p1648037435691849)

**Comment by leonardpahlke** [comment]
Tracking the progress on the ci signal onboarding clips:
1. - [ ] [testgrid] dashboards overview
2. - [ ] how to analyze a flake
3. - [x] release branch go/no go responsibilities walkthrough

**Comment by leonardpahlke** [comment]
@markyjackson-taulia (YT Admin) how can we upload the clips to YT after recording?

**Comment by markyjackson-taulia** [comment]
> @markyjackson-taulia (YT Admin) how can we upload the clips to YT after recording?

You can dm me the clip and I will upload

**Comment by lauralorenz** [comment]
x-posting from the DMs, got the new vids in a properly accessible [google drive folder accessible here](https://drive.google.com/drive/folders/1-2LG9s-JwCzcFYFJpyPNT4YicK4ao8XY?usp=sharing) with a [README](https://docs.google.com/document/d/13q9VR4yhV0x_7ZrEsW0fujLATdNYG4DYnW81CYXnsec/edit?usp=sharing) for suggested titles / ordering for a youtube playlist. Sent to @markyjackson-taulia on slack DMs too for upload.

**Comment by markyjackson-taulia** [comment]
@lauralorenz All videos have been uploaded and reside here: https://www.youtube.com/playlist?list=PL69nYSiGNLP2Lzsjir9W7S8u0UsQeeW71

**Comment by leonardpahlke** [comment]
Thank you all so much! :) I opened a PR to add a reference to the YT playlist in the ci signal handbook.
