### ISSUE TITLE
process docu: release team CI Signal Lead updates

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#189]
The CI Signal role was much more active in the 1.11 release and better coordinated with the docs role.  We should incrementally update documentation on the role, recent process improvements, and current intended improvements:

https://github.com/kubernetes/sig-release/blob/master/README.md
https://github.com/kubernetes/sig-release/tree/master/release-process-documentation/release-team-guides

**Comment by AishSundar** [comment]
Ack @tpepper will finish it this week :)
