### ISSUE TITLE
process docu: release team Test Infra Lead

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#190]
The release team's Test Infra Lead role is only minimally documented in one short bullet of text in:
https://github.com/kubernetes/sig-release/blob/master/README.md
with no details in:
https://github.com/kubernetes/sig-release/tree/master/release-process-documentation/release-team-guides

This role's a bit of a black box on the release team's side, even though I think a lot of information is captured in the test-infra repo generally.  A bit more documentation for the release team will be especially useful now that we're pushing harding for the CI signal to be more continuously clean instead of a later stabilization period.  This will mean more of the release team looks more at CI and test infra and failures regularly.

**Comment by cjwagner** [comment]
The process for this next release will be different than those of previous releases because we will be using Tide instead of the submit-queue. I'll document the process throughout this release so that we have a guide for 1.13

**Comment by BenTheElder** [comment]
Thanks @cjwagner.
I'd say the role is support the release by maintaining the automation as needed by the release, also including new jobs/dashbaords for the release, but we're also trying to change a lot of this. I'll take Cole up on having this documented as we go through the next release. We'll have to talk to @AishSundar about her awesome notes on CI signal :-)

**Comment by AishSundar** [comment]
@BenTheElder I have https://github.com/kubernetes/sig-release/issues/189#event-1689370439 assigned to me ^^ and I promise to update it soon

**Comment by krzyzacy** [comment]
assume this is https://github.com/kubernetes/sig-release/pull/255?

/close

**Comment by cjwagner** [comment]
I'd still like to keep this open until I can add more to the document. #255 is awesome, but it doesn't include details about the Tide workflow yet.
/reopen

**Comment by AishSundar** [comment]
@cjwagner do you plan to add  more updates to the TestInfra lead handbook, specifically around Tide, before 1.13 starts?

**Comment by cjwagner** [comment]
Yes, I'm going to update the role guide before I meet with the 1.13 test-infra shadows to go over the test-infra tasks.

**Comment by justaugustus** [comment]
@cjwagner -- have you had a chance to update the Test Infra docs?

**Comment by cjwagner** [comment]
Yes. #313  #333 
/close
