### ISSUE TITLE
Tracking Sheet links are broken

### ISSUE THREAD

**Issue by paravatha** [kubernetes/sig-release#1905]
#### What happened:
In the below release 1.25 README.md 
https://github.com/kubernetes/sig-release/tree/master/releases/release-1.25#tracking-docs

**These 2 below links are not working, I am getting "Page not found | 404" error**

[Feature blog Tracking Sheet](http://bit.ly/k8s125-feature-blog)
[Bug Triage Tracking Sheet](https://bit.ly/k8s125-bug-triage-tracking) 

#### What you expected to happen:
I am expecting to view the Google docs sheets

#### How to reproduce it (as minimally and precisely as possible):
Click those 2 links
#### Anything else we need to know?:
N/A
#### Environment:
N/A
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by saschagrunert** [comment]
Hey @paravatha, the next release cycle will start on May 23rd and we're still in the preparation phase. The tracking sheet can be found there but as time of writing is still empty: https://docs.google.com/spreadsheets/d/1Lnft8598eIQsqBp8W6X_LwaqBNZViYssQoFgGS8aJ3g/edit?usp=sharing

**Comment by palnabarun** [comment]
Both the short links point to the correct documents. Closing this issue for now. Please feel free to re-open in case you feel otherwise.

/close
