### ISSUE TITLE
Update Meeting Times and Cadence

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#1912]
As discussed in the [24 May Release Engineering Meeting](https://www.youtube.com/watch?v=1LWic-qogYI&t=477s), we should consider merging the SIG Release Meeting and the Release Engineering subproject meetings. Along with this, we should take a moment and consider alternate times or alternating meeting times. 

Some items mentioned in the releng meeting:

* Often the SIG Release and Release Engineering meetings have topics that skew toward the other meeting
* The current time slot is not especially friendly to those in Pacific Time
* The current time slot competes with other relevant meetings, including OpenSSF things

Proposal:

* Combine SIG Release and releng meetings
* Alternate time slots (1 aligned with EU/Eastern US, 1 aligned more with Pacific Time)
* Explicitly document and clarify conditions for cancelling meetings based on lack of agenda

TODO:

[x] Communicate to mailing list(s)
[x]  Determine new time(s) 
[x ] Update calendar invites
[x] Update / merge meeting notes
[x] Update community documentation
[x] Work to better follow agenda cutoff 

/sig release
/kind documentation
/priority important-soon

**Comment by jeremyrickard** [comment]
cc: @justaugustus @saschagrunert @puerco @cpanato

**Comment by saschagrunert** [comment]
I generally like the proposal 👍

Additionally I’d like to clarify when and under which conditions meetings get cancelled.

For example: We propose in slack to cancel the meetings if no agenda item is available around 1 day before they happen. If folks still want to meet and walk the board, or for example have a late agenda item, then we will use that conversation to negotiate.

**Comment by jrsapi** [comment]
I'm in agreement with the proposal. 

My hope by staggering the hours we can be more time zone exclusive for those who are not able to attend the current time.

**Comment by JamesLaverack** [comment]
👍 

Agree that SIG Release and Release Engineering meetings, in their current form, kind of merge together. I'm in support of this proposal.

**Comment by jeremyrickard** [comment]
Going to close this one out, since we've updated all the things. 

/close
