### ISSUE TITLE
process docu: release team Docs Lead

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#192]
The release team's Docs Lead role is only minimally documented in two bullets of text in:
https://github.com/kubernetes/sig-release/blob/master/README.md#docs-lead
and there are old docs in:
https://github.com/kubernetes/sig-release/tree/master/release-process-documentation/documentation-guides

A lot has changed lately around docs generally and also specific to release, including some really good observations and improvements around interacting with the release team's Features Lead and SIG leads.

It would be good to have old docs merged into an up-to-date doc for the role at:
https://github.com/kubernetes/sig-release/tree/master/release-process-documentation/release-team-guides

**Comment by zacharysarah** [comment]
@tpepper Agreed, an updated guide would be good. I'll echo my suggestion in #139 that @mistyhacks (and maybe @zparnold as he enters the docs release lead role for 1.12) continue any updates.

**Comment by mistyhacks** [comment]
Yeah I'll work on this after the smoke clears from 1.11. 👼

**Comment by justaugustus** [comment]
@zparnold -- Are we all set with the Docs Handbook?

**Comment by idealhack** [comment]
cc @jimangel docs lead of 1.14

**Comment by jimangel** [comment]
@msohn I'll fix the link today.

@justaugustus (3 months later...) we have a couple handbooks out there but none are considered "complete." One of my goals this cycle is to correct that along with docs for shadow responsibilities.

Thanks for the CC @idealhack!

**Comment by jimangel** [comment]
/unassign @zparnold
/assign @jimangel

cc @zacharysarah
