### ISSUE TITLE
process docu: release team Release Notes Lead

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#193]
We've formalized having a Release Notes lead, but both:
https://github.com/kubernetes/sig-release/blob/master/README.md
is missing a section for the role overview, and:
https://github.com/kubernetes/sig-release/tree/master/release-process-documentation/release-team-guides
is missing a detail reference on the role and associated processes.

There has been a lot of activity in this area over the past months and it would be good to get current best practices (and pain points) documented for broader visibility and insuring things are clear as volunteers cycle through the role.

**Comment by justaugustus** [comment]
@nickchase / @marpaia -- How are we doing with the Relnotes Handbook?

/assign @marpaia 
/remove-lifecycle rotten
/lifecycle frozen

**Comment by idealhack** [comment]
cc @dstrebel release notes lead of 1.14

**Comment by marpaia** [comment]
The release notes lead handbook is pretty up-to-date as of today, I last updated it on 1.13 release day to include the external dependencies bit. I'll note that while we've documented the current things that must be done and how they've been done in the past, this role is for sure ripe with areas of potential improvement in my opinion.

**Comment by justaugustus** [comment]
What's the current status of this?
/assign @jeefy 
/unassign @marpaia @nickchase

**Comment by jeefy** [comment]
The role handbook will need to be updated for 1.16 to describe doing a JSON dump as well as a Markdown dump, and then in 1.17 the Markdown dump instructions should be deprecated (and moved exclusively into the `release-notes` tool repo)

The (JSON) process is only slightly different from the Markdown process, but I want to focus finishing the last site-related updates before I address the handbook updates. 🎉
