### ISSUE TITLE
Release Manager access for @jeremyrickard and @jrsapi

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#1965]
### GitHub Username

@jeremyrickard, @jrsapi

### [Release Manager](https://git.k8s.io/sig-release/release-managers.md) role

Release Manager Associate / 1.25 Branch Manager shadows (https://github.com/kubernetes/sig-release/pull/1964)

### Tenure

permanent

### Release Manager Onboarding

**All pull requests within these checklists should be marked with an _explicit_ hold and only released once approved by a Release Engineering subproject owner.**

- [x] Addition of a new Release Manager has been discussed with and approved by Release Engineering subproject owners
- [x] Ensure new Release Manager:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/a/kubernetes.io/g/dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
- [x] Update [Release Managers](https://git.k8s.io/sig-release/release-managers.md) page to include the new Release Manager: PR https://github.com/kubernetes/website/pull/35003

### Release Manager Associate

- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml): PR https://github.com/kubernetes/org/pull/3556
  - `milestone-maintainers`
  - `release-engineering`
- [x] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml) PR: https://github.com/kubernetes/k8s.io/pull/3970
  - `k8s-infra-release-viewers@`
  - `release-managers@`

/assign @Verolop @jeremyrickard @jrsapi
cc: @kubernetes/release-engineering

**Comment by jeremyrickard** [comment]
I think we've gotten all the checklist covered now. @justaugustus @Verolop did I miss anything?

**Comment by justaugustus** [comment]
> I think we've gotten all the checklist covered now. @justaugustus @Verolop did I miss anything?
> 

Awesome!
For each of the checklist items, can you also provide links to the PRs, for completeness?

**Comment by palnabarun** [comment]
Can we close this issue now that both @jeremyrickard and @jrsapi are onboarded?

/kind documentation
/priority important-longterm

**Comment by jrsapi** [comment]
Checklist is complete. LInks to PRs added. Closing.
