### ISSUE TITLE
Update go version playbook with information about creating and running canary presubmit jobs

### ISSUE THREAD

**Issue by liggitt** [kubernetes/sig-release#1972]
#### What would you like to be added:

Update https://github.com/kubernetes/sig-release/blob/master/release-engineering/handbooks/go.md to include information about bumping the go version in the canary test image and running the canary presubmit jobs

#### Why is this needed:

When bumping minor go versions, we always need to ensure CI passes on the new version before merging.

We have a canary test image that can be built with the new go version, and canary {unit,verify,integration,dependencies} presubmit jobs that use the new image, but https://github.com/kubernetes/sig-release/blob/master/release-engineering/handbooks/go.md does not include information about updating the canary image or triggering those tests.

Making that info part of the playbook would make sure the person driving the update knows those tools are available and makes use of them prior to merge.

cc @dims @justaugustus

**Comment by RajGM** [comment]
Hi @liggitt 
Can I take this up?

**Comment by liggitt** [comment]
Sure, open for anyone to take, thanks
