### ISSUE TITLE
1.25 Kubernetes Major themes contact

### ISSUE THREAD

**Issue by csantanapr** [kubernetes/sig-release#1981]
With major themes submission formalizing to use GitHub Discussions, we hope this cycle will be the last time the release team needs to reach out to SIGs for their response.

Since the new process, the release notes team will use this issue to track the work on nudging SIGs for entries on major themes for the 1.25 release cycle.

The Slack channel for each SIG is usually #sig-, but accurate links are available in k/community under sig-list.md. The plan is to ask for responses on the public Slack channel (non-disruptively).

The following is a template meant for a guide, so feel free to use the language you're comfortable with!

```
Hello SIG <NAME>, the 1.25 release notes team is gathering major themes entries for 
the release, and if you have anything to call out, we would appreciate it if your 
SIG can submit the content in [Kubernetes 1.25 Major Themes](https://github.com/kubernetes/sig-release/discussions/1925)
Ideally, we would like this to be completed by Aug 8th. Thanks!
```

It would be great if we would propose some Major Themes candidates when nudging SIGs based on [tracked enhancements](https://docs.google.com/spreadsheets/d/1Lnft8598eIQsqBp8W6X_LwaqBNZViYssQoFgGS8aJ3g/edit#gid=0). Please feel free to tag the enhancement owner from each SIG to make sure if they want it to be included in Major Themes.

Some SIGs have activities that aren't quite coupled with Kubernetes releases, but it's worth checking anyway in case there are things worth calling out in what they did between the previous release and current release. One example is Immutable Secrets and ConfigMaps from the 1.21 release or Dockershim removal from the 1.24.

We'll try to keep the list below up-to-date, but please double-check in the comments if someone has contacted their channel:

- [x] API Machinery
- [x] Apps
- [x]  Architecture
- [x]  Auth
- [x]  Autoscaling
- [x]  CLI
- [x]  Cloud Provider
- [x]  Cluster Lifecycle
- [x]  Contributor Experience
- [x]  Docs
- [x]  Instrumentation
- [x]  Multicluster
- [x]  Network
- [x]  Node
- [x]  Release
- [x]  Scalability
- [x]  Scheduling
- [x]  Security
- Service Catalog (SIG archived)
- [x]  Storage
- [x]  Testing
- [x]  UI
- [x]  Usability
- [x]  Windows

/assign @csantanapr @ramrodo @Divya063 @DiptoChakrabarty @orsenthil
cc @reylejano @cici37 @salaxander @gracenng @leonardpahlke @jlbutler
/milestone v1.25

**Comment by csantanapr** [comment]
Contacting:

API Machinery
 Apps
 Architecture
 Auth

**Comment by Divya063** [comment]
Contacted:
- Autoscaling
- CLI
- Cloud Provider
- Cluster Lifecycle

**Comment by DiptoChakrabarty** [comment]
Contacted

- testing
- security
- node
- network

**Comment by ramrodo** [comment]
I'll contact:
- Contributor Experience
- Docs
- Multicluster
- Release
- Scalability
- Scheduling

**Comment by ramrodo** [comment]
Contacted:

- [x] Storage
- [x] UI
- [x] Usability
- [x] Windows

Notes:
- SIG Service Catalog was archived by https://github.com/kubernetes/community/pull/6632

**Comment by csantanapr** [comment]
All sigs were contacted and data collected
/close
