### ISSUE TITLE
Assemble Kubernetes 1.26 Release Team 🚀 🕐 🎊

### ISSUE THREAD

**Issue by reylejano** [kubernetes/sig-release#1993]
Hi Kubernauts! 

Thank you to the 1.25 Release Team for all their hard work and dedication as we near the end of the 1.25 release cycle. 
One of the last tasks is to assemble the 1.26 Release Team!

Please review the [Release Team Selection Process docs](https://github.com/kubernetes/sig-release/blob/master/release-team/release-team-selection.md) for details on the process and criteria.

At this stage, we only require nominations for Role Leads. Once role leads are nominated we will then send out a shadow application survey.

/sig release
/area release-team
/milestone v1.26
/kind documentation
/priority important-soon

cc: @justaugustus @saschagrunert @cpanato @puerco @jeremyrickard  @cici37

**Comment by cici37** [comment]
It's been an absolute honor to lead the Kubernetes 1.25 release. Thanks the community for the opportunity 🙏

I am excited to nominate @leonardpahlke as the 1.26 Release Team Lead! 🎉  Leo has been an excellent addition to the release team over the last few releases and I believe he will be a great lead in Kubernetes 1.26 release. Congratulations @leonardpahlke ! 🎉 ❤️

**Comment by reylejano** [comment]
It was a great honor to have been the Emeritus Adviser on the 1.25 Release Team. 
It's a privilege to honor @palnabarun as the Emeritus Adviser for the 1.26 Release Team!
Nabarun was the 1.21 Release Lead, lead shadow on 1.20, Enhancements Lead on 1.19, Enhancements Shadow on 1.18 and 1.17, Release Manager and several other community roles

Nabarun will be a great EA and will bring extensive experience

/pony

**Comment by leonardpahlke** [comment]
Thank you so much, @cici37 @reylejano and everyone else! 1.25 was awesome so far, and I can't wait to get started on 1.26!!! Thank you all :)

**Comment by RinkiyaKeDad** [comment]
A big thanks to everyone on the 1.25 Release Team for a great experience! Huge congrats to @leonardpahlke 🎉 

I'm very happy to nominate @Nivedita-coder as the next CI Signal Lead! Her efforts during the 1.25 cycle were really commendable, and I'm sure she'll continue doing great in 1.26 as well!

**Comment by Nivedita-coder** [comment]
Thank you @RinkiyaKeDad!! It has been great working with you. Super excited for 1.26! :confetti_ball:

**Comment by Priyankasaggu11929** [comment]
Thank you Cici, Rey, and everyone on the 1.25 Release Team, for a wonderful release cycle. And congratulations @leonardpahlke 🎉 

I'm very happy to nominate @rhockenbury as the Enhancements Lead for the 1.26 release cycle. As the Enhancements shadow for the previous two release cycles, he has greatly contributed to the release team and also brings a lot of project-wide experience. Congratulations Ryler! 🙂

**Comment by csantanapr** [comment]
It was a great honor to have been release notes lead for 1.25 release, but I had such a great release notes team that it was a pleasure to work with. 

I would like to nominate @ramrodo as Release Notes Lead for 1.26 release cycle.
Rodolfo's attention to detail and helping everyone on the team 🙏 were invaluable. He will do a great job 🎉  as a lead

**Comment by kcmartin** [comment]
It was a great privilege and honor to serve as the Docs Lead for 1.25! ⭐ Thank you to my Docs shadows, and all the hard-working members of the 1.25 Release Team for their invaluable help! 🙏 

I would like to nominate @krol3 as Docs Lead for the 1.26 release cycle.
Carol is a valued collaborator, and I know she'll continue to make solid contributions in this next step on her Kubernetes journey! 🎉

**Comment by ramrodo** [comment]
Thanks, @csantanapr! It was a great team collaboration and amazing people. I enjoyed and learned a lot with all of you. I'll do my best in 1.26 🚀

**Comment by helayoty** [comment]
It was such an honor and an amazing time to work with everyone on the 1.25 Release Team. Great experience! 
 Congratulations @leonardpahlke  for a well deserved role 🎉

I'm very happy to nominate @encodeflush as the next Bug Triage Lead for the 1.26 Release! His efforts and dedications during the 1.25 release were really remarkable. I'm sure he will continue doing an amazing impact on the release and for the whole community. Congratulation Hossein 🥳 🎉

**Comment by encodeflush** [comment]
Thank you @helayoty for nominating and trust in me :blue_heart: It was a pleasure to work as bug triage shadow with such a great team. 
For me it is a great honor and experience to be part of the amazing release team   :rocket:

**Comment by katcosgrove** [comment]
Serving as the Comms Lead for v1.25 has been an honor and a pleasure. All of my shadows have been incredible, and with their help we've managed to pull together an incredible **fifteen** feature blogs, more than any release so far! Thanks to all of you for your hard work and dedication.

I'm happy to nominate @fsmunoz as the Kubernetes v1.26 Comms Lead. Throughout the release, he consistently went above and beyond his assigned duties, even on very short notice. I know he'll do a great job for the community next release! Congratulations, Frederico!

**Comment by fsmunoz** [comment]
What a ride... I'm at a loss of words, I was super happy to join in as a shadow (a great programme) and it was amazing to learn from the Comms team, and particularly from @katcosgrove . I'll try my very best to live up to your trust, and it's obviously a huge and unexpected honour that I will cherish.

**Comment by reylejano** [comment]
The 1.26 Release Team is assembled 🎉 🙏 
/close
