### ISSUE TITLE
Generate hierarchical release notes

### ISSUE THREAD

**Issue by enisoc** [kubernetes/sig-release#20]
There is an effort underway to generate release notes from PRs, grouped by SIG and area labels. As the release team, we should engage with them to help test the tool and give feedback.

https://github.com/kubernetes/release/pull/434
https://github.com/kubernetes/release/pull/435

**Comment by xiangpengzhao** [comment]
ack. will join in the effort :)

**Comment by Bradamant3** [comment]
This effort can really help only after we get better written release notes. I'd like to start with the content that the sigs produce in the first place. Editing after the fact, as previous releases have shown, is a great deal more work.

**Comment by enisoc** [comment]
@Bradamant3 That makes sense. What do you think is a good first step for improving the content? Publicizing a guide?

One way this hierarchical tool could help us improve content is by giving us a snapshot into the current relnotes, in a form that we can take to each SIG and give specific recommendations. For example, we could flag some sample relnotes as Good or Needs Improvement for each SIG, to show what we mean by quality content. The SIGs can then start to burn down their respective Needs Improvement lists. What do you think?

**Comment by Bradamant3** [comment]
cc @nickchase

**Comment by nickchase** [comment]
@enisoc Editing after the fact can indeed be more work, but without this we'd need to do the writing from scratch anyway -- and without pre-sorted clues as to what's been accomplished -- so I think this can only help.  But I agree that this is a good way for us to have something to go back to the SIGs with.  It will also help us to see where we're either getting too many or too few release notes, IMO.

**Comment by Bradamant3** [comment]
@enisoc @nickchase On my TODO list is putting together a guide, with template. (Here's a larger writeup, in case y'all haven't seen it): https://docs.google.com/document/d/17af5ZkRX83ISvizml9FKPc9TCtCIp9PecXpNGh324M8/edit#heading=h.ypeaydkz068g

**Comment by xiangpengzhao** [comment]
BTW, the release note process of the bot has changed, I send two PRs to update PR template and docs:
https://github.com/kubernetes/kubernetes/pull/54114
https://github.com/kubernetes/community/pull/1221

@Bradamant3 PTAL. Thanks!

**Comment by enisoc** [comment]
Hierarchical release notes were generated and used to seed the initial draft of the hand-curated notes.
