### ISSUE TITLE
Docs for PRR Freeze Risk

### ISSUE THREAD

**Issue by gracenng** [kubernetes/sig-release#2011]
**What would you like to be added**: with the removal of the word "soft" in PRR freeze from 1.25 retro, I would like to add more clarifications about PRR Freeze risks. What happens if a KEP misses a PRR Freeze, what to do and the risks that involve.

**Why is this needed**: It has been my observation that the expectations of the PRR freeze is not well understood by the community and even the release teams handbook doesn't have any documentation on this.

I'm considering adding this to the few documents:
- [ ] Release Phase
- [x] Enhancements release handbook
- [x] sig-arch PRR docs under k/community

**Comment by saschagrunert** [comment]
@gracenng is this still something you'd like to work on?
