### ISSUE TITLE
Temporary Release Manager access for @jeremyrickard

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#2032]
### GitHub Username

@jeremyrickard 

### [Release Manager](https://git.k8s.io/sig-release/release-managers.md) role

Release Manager

### Tenure

temporary: Jeremy is a Release Manager Associate being granted temporary elevated access to cut releases. Access should be revoked after the 1.26.0-alpha.1 release is cut.

### Release Manager Onboarding

**All pull requests within these checklists should be marked with an _explicit_ hold and only released once approved by a Release Engineering subproject owner.**

- [x] Addition of a new Release Manager has been discussed with and approved by Release Engineering subproject owners
- [x] Ensure new Release Manager:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/a/kubernetes.io/g/dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
- [x] Update [Release Managers](https://git.k8s.io/website/content/en/releases/release-managers.md) page to include the new Release Manager

### Release Manager Associate

- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-engineering`
- [] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-editors@` : 
  - `release-managers@`
  
cc: @kubernetes/release-engineering

**Comment by saschagrunert** [comment]
Can this be closed?
