### ISSUE TITLE
Cut v1.26.0-alpha.3 release

### ISSUE THREAD

**Issue by salaxander** [kubernetes/sig-release#2066]
## Release Steps

- [X] Create a thread on #release-management: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1667314085009659
- [x] Screenshot unhealthy release branch testgrid boards
- Mock Run
  - [x] Stage
  - [x] Release
- NoMock Run
  - [x] Stage
  - [x] Image Promotion: https://github.com/kubernetes/k8s.io/pull/4406
  - [x] Release
- [X] Notify #release-management: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1667343222846359?thread_ts=1667314085.009659&cid=CJH2GBF7Y
- [X] Send notification: https://groups.google.com/a/kubernetes.io/g/dev/c/3lNLJFZOe6o
- [ ] Collect metrics and add them to the `Release steps` table below

## Release Tools Version

```
GitVersion:    unknown
GitCommit:     278889f9e119deb133cac365ba75f4bf0033273a
GitTreeState:  clean
BuildDate:     2022-11-01T13:34:46
GoVersion:     go1.19
Compiler:      gc
Platform:      darwin/arm64
```

## Release Jobs History

| Step | Command | Link | Start | Duration | Succeeded? |
| --- | --- | --- | --- | --- | --- |
| Mock stage | `krel stage` | https://console.cloud.google.com/cloud-build/builds/41a1382f-5e23-44f3-906e-919b6f25abc0?project=kubernetes-release-test | Nov 1, 2022, 9:44:59 AM | 01:11:14 | ✅  |
| Mock release | `krel release --build-version=v1.26.0-alpha.2.522+7a2984fddfda9a` | https://console.cloud.google.com/cloud-build/builds/84dd2eff-45f9-4fa5-a535-9760f9ae3be9?project=kubernetes-release-test | Nov 1, 2022, 11:00:34 AM | 00:08:40 | ✅  |
| Stage | `krel stage --type alpha --branch master --nomock` | https://console.cloud.google.com/cloud-build/builds/55fb70e3-92bf-497b-86c7-699457af6f4c?project=kubernetes-release-test | Nov 1, 2022, 11:18:15 AM | 01:15:25 | ✅ |
| Release | `krel release --nomock --build-version=v1.26.0-alpha.2.522+7a2984fddfda9a` | https://console.cloud.google.com/cloud-build/builds/62a7ed44-cda0-4dab-8531-4bf6fa38b759?project=648026197307 | Nov 1, 2022, 3:43:28 PM | 00:09:01 | ✅ |

## Open Questions

/milestone v1.26
/assign @jeremyrickard 
/cc @kubernetes/release-managers
/priority important-soon
/kind documentation

**Comment by salaxander** [comment]
`krel testgridshot` is not working at the moment

**Comment by xmudrii** [comment]
@salaxander `krel testgridshot` has been broken for a long time. Can you please screenshot boards manually if there are any failing tests otherwise just leave a comment saying that everything is okay? :slightly_smiling_face:

**Comment by salaxander** [comment]
> @salaxander `krel testgridshot` has been broken for a long time. Can you please screenshot boards manually if there are any failing tests otherwise just leave a comment saying that everything is okay? 🙂

Looks like we have 1 failure on master informing
![Screenshot 2022-11-01 at 12 47 05 PM](https://user-images.githubusercontent.com/1063495/199324902-a221b428-a793-435f-adbe-ed128594c441.png)

**Comment by salaxander** [comment]
As no issues have surfaced, I'm going to close the issue 🎉
