### ISSUE TITLE
1.26 Kubernetes Major Themes contact

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/sig-release#2067]
The release notes team will use this issue to track the work on nudging SIGs for entries on major themes for the 1.26 release cycle.

The Slack channel for each SIG is usually `#sig-`, but accurate links are available in k/community under `sig-list.md`. The plan is to ask for responses on the public Slack channel (non-disruptively).

The following is a template meant for a guide, so feel free to use the language you're comfortable with!

```
Hello SIG <sig-name>,

The 1.26 release notes team is gathering major themes entries for  the release,
and if you have anything to call out, we would appreciate it if your SIG can submit the content in
[Kubernetes 1.26 Major Themes GitHub discussion](https://github.com/kubernetes/sig-release/discussions/2047)
 
Ideally, we would like this to be completed by **Tuesday, 29th November 2022**.

Thanks!
```

It would be great if we would propose some Major Themes candidates when nudging SIGs based on [tracked enhancements](https://github.com/orgs/kubernetes/projects/98/views/1?layout=board). Please feel free to tag the enhancement owner from each SIG to make sure they want it to be included in Major Themes.

Some SIGs have activities that aren't quite coupled with Kubernetes releases, but it's worth checking anyway in case there are things worth calling out in what they did between the previous release and the current release. One example is Immutable Secrets and ConfigMaps from the 1.21 release or Dockershim removal from 1.24.

We'll try to keep the list below up-to-date, but please double-check in the comments if someone has contacted their channel:

- [ ] API Machinery
- [ ] Apps
- [ ] Architecture
- [ ] Auth
- [ ] Autoscaling
- [ ] CLI
- [ ] Cloud Provider
- [ ] Cluster Lifecycle
- [ ] Contributor Experience
- [ ] Docs
- [ ] Instrumentation
- [ ] Multicluster
- [ ] Network
- [ ] Node
- [ ] Release
- [ ] Scalability
- [ ] Scheduling
- [ ] Security
- [ ] Storage
- [ ] Testing
- [ ] UI
- [ ] Usability
- [ ] Windows

/assign @ramrodo @harshanarayana @AnaMMedina21 @laxmikantbpandhare @sayantani11
(since there are around 23 SIGs listed here, please select between 4-5 SIGs for each one)
cc @leonardpahlke @fsmunoz 
/milestone v1.26

**Comment by ramrodo** [comment]
I'll start with the first 5:

- [ ] API Machinery
- [ ] Apps
- [ ] Architecture
- [ ] Auth
- [ ] Autoscaling

**Comment by harshanarayana** [comment]
I'' follow up on the following

- [ ]  Instrumentation
- [ ]  Multicluster
- [ ]  Network
- [ ]  Node
- [ ]  Release

**Comment by AnaMMedina21** [comment]
I will be taking the next four:

- [x]  Scalability
- [x]  Scheduling
- [x] Security
- [x]  Storage

**Comment by laxmikantbpandhare** [comment]
I will follow up on following.

 Testing
 UI
 Usability
 Windows

**Comment by ramrodo** [comment]
We already reached out to all the above SIGs. Closing this issue.
/close
