### ISSUE TITLE
Use Prow for Cherry Pick Approval

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#2083]
#### What would you like to be added:

Move away from manually applying the cherry pick approved label and instead leverage prow to do this. 

#### Why is this needed:

Currently, we rely on a manual application (or removal) of the cherry pick approval label. This requires individuals to be in a specific Github Team, which we currently restrict to full release managers. If we want release manager associates to review cherry picks, they have to review and then wait for a release manager to apply it based on their review. If we migrate to utilizing prow to do this, we could extend the responsibility of approving cherry picks to RMA and give them additional opportunities to support the release management process.

**Comment by saschagrunert** [comment]
Good point, so the plugin would check the list of current RM(A)'s and then act based on a comment for each PR? We could add some pre-condition checking, like is the PR already approved/lgtm'ed and are there any missing labels?

Later on we also have a sync feature, means if we approve one CP then we auto-approve the ones for related release branches as well.

**Comment by jeremyrickard** [comment]
@saschagrunert  yeah, that's exactly what I had in mind.

Plugin will act based on comment for the PRs and do basic validation:
1. ensure it has LGTM and Approved
2. check for any other missing labels
3. check that the person giving the comment is either RM or RMA

If those checks passed, we would remove the `do-not-merge/cherrypick-not-approved` label and add the `cherry-pick-approved` label. Then things could merge with the rest of the automation already in place.

I think the sync feature is a good idea for a later enhancement to this plugin once we have it up and working.

**Comment by xmudrii** [comment]
@jeremyrickard Are you still interested to take care of this issue?
/remove-lifecycle rotten
