### ISSUE TITLE
Add support for k8s-stable4 version marker

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/sig-release#2094]
#### What would you like to be added:

We should add support for the `k8s-stable4` version marker because it might happen that we support 4 branches in parallel. 

(Part of https://github.com/kubernetes/sig-release/issues/850.)

#### Why is this needed:

We had a problem that we supported 1.25, 1.24, 1.23, and 1.22 at the same time. In this case, both `ci-kubernetes-build-1.23` and `ci-kubernetes-build-1.22` pointed to the `k8s-stable3` version marker. This might cause issues with tests or produce test results that are not reliable because the same `k8s-stable3` version marker is getting changed by two different jobs for two different release branches.

We mitigated this manually by adding the `k8s-stable4` version marker in https://github.com/kubernetes/test-infra/pull/27945, but we'll mostly like end up with the same problem again once 1.26 is out. That being said, we might need to modify [`config-rotator`](https://github.com/kubernetes/test-infra/blob/master/releng/config-rotator/main.go) and update docs.

**Comment by justaugustus** [comment]
(transferred this to k/sig-release)

**Comment by xmudrii** [comment]
@justaugustus I would consider this done since we support the `stable4` marker and there are jobs using it. Do you think it's okay to close this issue or is there anything I forgot about?

**Comment by justaugustus** [comment]
> Do you think it's okay to close this issue or is there anything I forgot about?

Let's wait until https://github.com/kubernetes/test-infra/pull/28119 merges. :)

**Comment by xmudrii** [comment]
We have full support for the stable4 version marker with https://github.com/kubernetes/test-infra/pull/29098. It's also documented here: https://github.com/kubernetes/community/blob/ad1bca23543ed0adc27c2ce7935454b0b7be9b12/contributors/devel/sig-release/kubernetes-versions.md?plain=1#L331

With that, I'm going to close this issue.
/close
