### ISSUE TITLE
Release Blog should not include CNCF content

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#2128]
SIG-Release:

The current release blog template, and thus the actual release blogs from the last 3 releases, includes two sections of CNCF-generated content that are irrelevant to the release.  These are "User Highlights" and "Ecosystem Updates".

These should be removed from the template, and maybe from the 1.26 blog as well depending on how long it takes to approve this.

Reasons:

- None of the items in these sections have anything whatsoever to do with the release, which is confusing to readers.
- CNCF has their own blog where they can publish such items.
- The randomness of selection results in these sections de-facto promoting various non-Kubernetes projects and private companies
- The release blog post is already really long, and we should be making it shorter, not padding it with unrelated content

If I get some general +1s here, I'll write a PR against the blog template.  Thanks!

Attn: @fsmunoz

**Comment by ameukam** [comment]
cc @kubernetes/sig-release-leads

**Comment by fsmunoz** [comment]
Commenting as 1.26 Comms Lead, those sections were added (as mentioned) following an established practice, which is documented in the template. I have no particular context on when and why they were added, and assumed that there were good reasons for it.

That said, I personally agree that the User Highlights section reads a bit out of character. The Ecosystem Updates not so much, especially since it mentions the next KubeCon, but I can understand the reasoning against it since it's not, strictly speaking, related to the release.

**Comment by leonardpahlke** [comment]
+1 

It would be interesting to analyze whether the release blogs get much traffic and whether it is worth linking to the CNCF blog, for example (so readers are teased to dig into other topics too). But I agree with your observation.

**Comment by jberkus** [comment]
> Commenting as 1.26 Comms Lead, those sections were added (as mentioned) following an established practice, which is documented in the template. 

There's been a couple times that our Comms lead was also a member of the CNCF marketing staff, so they might have been seen the release blog as if it was a CNCF publication.

I'll create the PR.

**Comment by jberkus** [comment]
PR created.

The Kubecon mentions etc. are a different section; not proposing to remove that.

**Comment by sftim** [comment]
> &hellip;an established practice, which is documented in the template. I have no particular context on when and why they were added, and assumed that there were good reasons for it.

Same for me (as an editor for the Kubernetes blog)

Have we checked with CNCF marketing that they're happy about this?

**Comment by jberkus** [comment]
Why would we check?

I'm getting a sneaking suspicion how this irrelevant content got into the blog in the first place.

**Comment by palnabarun** [comment]
I think it is okay to remove the sections due to reasons laid out by Josh.

**Comment by palnabarun** [comment]
We need to set a timebox to get this merged. Otherwise, it will keep getting bumped from one release to another.
