### ISSUE TITLE
Enforce Release Team "docs ready for reviewers" deadline

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/sig-release#2131]
#### What would you like to be added:

Discuss options to enforce the release team deadline "docs ready for reviewers" and document it. At the moment this is a soft deadline and does not work.

release-docs documentation: https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#before-the-prs-ready-for-review-deadline 

#### Why is this needed:

In the v1.26 Release Team retro we discussed that any deadline we set should get enforced and since we agreed that we cannot drop the deadline we need to discuss options to enforce it.

cc @kubernetes/sig-docs-leads @kubernetes/release-team-leads
/assign @salaxander @JamesLaverack

**Comment by katcosgrove** [comment]
I believe this issue is resolved with the merging of #2383, which replaces the "PR Ready for Review" deadline with a Docs Freeze and exception request process. Thoughts @leonardpahlke?

**Comment by leonardpahlke** [comment]
yup. 👍
