### ISSUE TITLE
short image url broken the world peace

### ISSUE THREAD

**Issue by willzhang** [kubernetes/sig-release#2146]
#### What would you like to be added:

```
format1: <registry_url>/<image_name>:<image_tag>

format2: <registry_url>/<project_name>/<image_name>:<image_tag>
```

everyone use long format image url in the world(docker.io  quay.io ghcr.io) ,but only this five image use short format image url ,who controlr this action and why?
```
root@node51:~# kubeadm config images list
I0117 09:21:50.999039 1387839 version.go:256] remote version is much newer: v1.26.0; falling back to: stable-1.25
registry.k8s.io/kube-apiserver:v1.25.5
registry.k8s.io/kube-controller-manager:v1.25.5
registry.k8s.io/kube-scheduler:v1.25.5
registry.k8s.io/kube-proxy:v1.25.5
registry.k8s.io/pause:3.8
registry.k8s.io/etcd:3.5.6-0
registry.k8s.io/coredns/coredns:v1.9.3
```

#### Why is this needed:
1、This leads to the need for special processing of these special images during image distribution, resulting in various kinds of confusion。
2、harbor not support format1, But Harbor is widely used in production environment

#### suggestion
release k8s core component image for this format:
```
registry.k8s.io/kubernetes/pause:3.7
registry.k8s.io/kubernetes/kube-apiserver:v1.25.5
registry.k8s.io/kubernetes/kube-controller-manager:v1.25.5
registry.k8s.io/kubernetes/kube-scheduler:v1.25.5
registry.k8s.io/kubernetes/kube-proxy:v1.25.5
```

related1: https://github.com/kubernetes/registry.k8s.io/issues/139

**Comment by saschagrunert** [comment]
@willzhang we already promote images two both locations, with and without the `/kubernetes` prefix. For example both URLs point to the same image:

```
> podman pull registry.k8s.io/kubernetes/kube-apiserver:v1.26.0
…
a31e1d84401e66c2f4162d70fdbd7db2a43d34f85785911c9cd57402a3d8e761

> podman pull registry.k8s.io/kube-apiserver:v1.26.0
…
a31e1d84401e66c2f4162d70fdbd7db2a43d34f85785911c9cd57402a3d8e761
```

**Comment by willzhang** [comment]
but as default ,kubeadm not use this url, can let kubeadm use this url as default?

**Comment by neolit123** [comment]
> but as default ,kubeadm not use this url, can let kubeadm use this url as default

we technically can, but as i mentioned before it would take a long time and needs a good plan

**Comment by saschagrunert** [comment]
Alright, looks like we're already set from a release perspective and have to handle it in kubeadm.
/close
