### ISSUE TITLE
Release Manager Associate access for @gracenng  @ramrodo 

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#2163]
### GitHub Username

@gracenng  @ramrodo 

### [Release Manager](https://git.k8s.io/sig-release/release-managers.md) role

Release Manager Associate

### Tenure

permanent

e.g., permanent, temporary

### Release Manager Onboarding

**All pull requests within these checklists should be marked with an _explicit_ hold and only released once approved by a Release Engineering subproject owner.**

- [ ] Addition of a new Release Manager has been discussed with and approved by Release Engineering subproject owners
- [ ] Ensure new Release Manager:
  - [ ] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/a/kubernetes.io/g/dev)
  - [ ] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [ ] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
- [ ] Update [Release Managers](https://git.k8s.io/website/content/en/releases/release-managers.md) page to include the new Release Manager

### Release Manager Associate

- [ ] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-engineering`
- [ ] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-viewers@`
  - `release-managers@`

cc: @kubernetes/release-engineering

**Comment by gracenng** [comment]
hey Jeremy, @ramrodo and I have completed the items for RMA above (I don't have edit access to the description.) Gonna close this issue - will keep an eye out for upcoming tasks
