### ISSUE TITLE
v1.27 Kubernetes Major Themes contact

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes/sig-release#2167]
The release notes team will use this issue to track the work on nudging SIGs for entries on major themes for the v1.27 release cycle.

The Slack channel for each SIG is usually `#sig-`, but accurate links are available in `k/community` under [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md). The plan is to ask for responses on the public Slack channel (non-disruptively).

Following is a bootstrap template that you can use to reach out to the individual sigs informing them about the [Major Themes collection](https://github.com/kubernetes/sig-release/discussions/2166) discussion thread.

 
```markdown
Hello SIG <sig-name>,

Major themes are an essential part of the Kubernetes release cycle as they provide a birds eye view of major improvements that are coming as part of the upcoming release. 

As part of the effort aimed towards collecting the Major themes for the  v1.27 cycle, release notes team is working towards gathering major themes entries. If you have anything to call out, we would appreciate it if your SIG can submit the content in
[Kubernetes 1.27 Major Themes GitHub discussion](https://github.com/kubernetes/sig-release/discussions/2166)
 
Ideally, we would like this to be completed by **Tuesday 21st March 2023**.

Thanks!
```

It would be great if we would propose some Major Themes candidates when nudging SIGs based on [tracked enhancements](https://github.com/orgs/kubernetes/projects/117). Please feel free to tag the enhancement owner from each SIG to make sure they want it to be included in Major Themes.

Some SIGs have activities that aren't quite coupled with Kubernetes releases, but it's worth checking anyway in case there are things worth calling out in what they did between the previous release and the current release. One example is Immutable Secrets and ConfigMaps from the 1.21 release or Dockershim removal from 1.24.

We'll try to keep the list below up-to-date, but please double-check in the comments if someone has contacted their channel:

- [ ] API Machinery
- [ ] Apps
- [ ] Architecture
- [ ] Auth
- [ ] Autoscaling
- [ ] CLI
- [ ] Cloud Provider
- [ ] Cluster Lifecycle
- [ ] Contributor Experience
- [ ] Docs
- [ ] Instrumentation
- [ ] Multicluster
- [ ] Network
- [ ] Node
- [ ] Release
- [ ] Scalability
- [ ] Scheduling
- [ ] Security
- [ ] Storage
- [ ] Testing
- [ ] UI
- [ ] Usability
- [ ] Windows
- [ ] K8s Infra

/assign @AnaMMedina21 @harshanarayana @rjsadow @sanchita-07 @yrs147 

/milestone v1.27

xref: https://github.com/kubernetes/sig-release/issues/2067

**Comment by harshanarayana** [comment]
I will reach out to the following SIGs. 

- [ ] API Machinery
- [ ] Apps
- [ ] Architecture
- [ ] Auth
- [ ] Autoscaling

**Comment by rjsadow** [comment]
I'll reach out to 

- [ ] CLI
- [ ] Cloud Provider
- [ ] Cluster Lifecycle
- [ ] Node
- [ ] Testing

**Comment by yrs147** [comment]
I'll reach out to the following SIGs:-
 * [ ]  Docs
 * [ ]  Storage
 * [ ]  Scalability
 * [ ]  Network
* [ ]  Release

**Comment by sanchita-07** [comment]
I'll reach out to the following SIGs:-

 * [ ]  Multicluster
 * [ ]  Security
 * [ ]  Scheduling
 * [ ]  Contributor Experience
* [ ]  Usability

**Comment by AnaMMedina21** [comment]
I'll reach out to the SIGs left:

- [ ] Instrumentation
- [ ]   UI
- [ ]  Usability
- [ ]  Windows
