### ISSUE TITLE
Update CONTRIBUTING.md file

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/sig-release#2200]
In the 2022 Annual Report template, there is a question about the CONTRIBUTING.md file:

> Does your [CONTRIBUTING.md] help **new** contributors engage with your group specifically by pointing
   to activities or programs that provide useful context or allow easy participation?

I believe we have a good deal of info about how to contribute and join release teams, but this isn't gathered specifically in that file. We should update it to make things more discoverable.

**Comment by ggold7046** [comment]
Hi @jeremyrickard , I would like to work on this. Could you guide me how to start on this ?

**Comment by ADITYADAS1999** [comment]
> In the 2022 Annual Report template, there is a question about the CONTRIBUTING.md file:
> 
> > Does your [CONTRIBUTING.md] help **new** contributors engage with your group specifically by pointing
> > to activities or programs that provide useful context or allow easy participation?
> 
> I believe we have a good deal of info about how to contribute and join release teams, but this isn't gathered specifically in that file. We should update it to make things more discoverable.

Hey @jeremyrickard this issue is still on going ?
