### ISSUE TITLE
Fix the documentation and code to adjust the changes of removing rc cut in minor releases

### ISSUE THREAD

**Issue by cici37** [kubernetes/sig-release#2216]
#### What happened:

While cutting release, found documentation and code is not properly reflect the changes of not having rc cut, especially for image promotion. 

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by yuvarajrece** [comment]
Can i work on this?

**Comment by saschagrunert** [comment]
@cici37 do you still consider to work on this or do you like to hand it over to @yuvarajrece ?
