### ISSUE TITLE
1.12.0 timeline: Dates in the milestone definitions section have wrong month

### ISSUE THREAD

**Issue by chrisohaver** [kubernetes/sig-release#227]
https://github.com/kubernetes/sig-release/blob/master/releases/release-1.12/release-1.12.md

A couple dates in the milestone definitions section are off by a month (either that or the table above it is wrong). Specifically, the ones I noticed...

Code Freeze: says August 4th, 2018.... table above it says September 4th ...
Code Slush: says July 28th, 2018 ... table above it says August 28th ...

**Comment by nikhita** [comment]
@chrisohaver thanks for catching that! 

I believe the table is right here. Aug 4 is too close for code freeze. :)

/cc @tpepper 
to confirm this

**Comment by tpepper** [comment]
Affirmative!

Thank you for reporting!
