### ISSUE TITLE
v1.28 Kubernetes Major Themes contact

### ISSUE THREAD

**Issue by sanchita-07** [kubernetes/sig-release#2272]
The release notes team will use this issue to track the work on nudging SIGs for entries on major themes for the v1.28 release cycle.

The Slack channel for each SIG is usually `#sig-`, but accurate links are available in [k/community](https://github.com/kubernetes/community) under [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md). The plan is to ask for responses on the public Slack channel (non-disruptively).

Following is a bootstrap template that you can use to reach out to the individual sigs informing them about the [Major Themes collection](https://github.com/kubernetes/sig-release/discussions/2271) discussion thread.
```
Hello SIG <sig-name>,

Major themes are an essential part of the Kubernetes release cycle as they provide a birds-eye view of major improvements that are coming as part of the upcoming release. 

As part of the effort aimed towards collecting the Major Themes for the v1.28 cycle, the release notes team is working towards gathering major themes entries. If you have anything to call out, we would appreciate it if your SIG can submit the content in
[Kubernetes 1.28 Major Themes GitHub discussion](https://github.com/kubernetes/sig-release/discussions/2271)
 
Ideally, we would like this to be completed by **Tuesday 25th July 2023**.

Thank you!
```
It would be great if we would propose some Major Themes candidates when nudging SIGs based on [tracked enhancements](https://github.com/orgs/kubernetes/projects/140). Please feel free to tag the enhancement owner from each SIG to make sure they want it to be included in Major Themes.

Some SIGs have activities that aren't quite coupled with Kubernetes releases, but it's worth checking anyway in case there are things worth calling out in what they did between the previous release and the current release. One example is Dockershim removal from 1.24 or Immutable Secrets and ConfigMaps from the 1.21 release.

We'll try to keep the list below up-to-date, but please double-check in the comments if someone has contacted their channel:

 * [x] API Machinery
 * [x] Apps
 * [x] Architecture
 * [x] Auth
 * [x] Autoscaling
 * [x] CLI
 * [x] Cloud Provider
 * [x] Cluster Lifecycle
 * [x] Contributor Experience
 * [x] Docs
 * [x] Instrumentation
 * [x] K8s Infra
 * [x] Multicluster
 * [x] Network
 * [x] Node
 * [x] Release
 * [x] Scalability
 * [x] Scheduling
 * [x] Security
 * [x] Storage
 * [x] Testing
 * [x] UI
 * [x] Windows
 
 /assign @AnaMMedina21 @fsmunoz @michaelfromyeg @muddapu @rashansmith
  
cc @leonardpahlke @gracenng @neoaggelos @helayoty @marosset @mickeyboxell 

/milestone v1.28

xref: https://github.com/kubernetes/sig-release/issues/2167

**Comment by sanchita-07** [comment]
I will reach out to the following SIGs:-

* [ ] API Machinery
* [ ] Apps
* [ ] Architecture
* [ ] Auth

**Comment by fsmunoz** [comment]
I can do (

[ ] Storage
[ ] Windows
[ ] CLI
[ ] Network

**Comment by muddapu** [comment]
I will do

Autoscaling
 CLI
 Cloud Provider
 Cluster Lifecycle

**Comment by rashansmith** [comment]
I will do 
 - [ ] Contributor Experience
 - [ ] Docs
 - [ ] Instrumentation
 - [ ] K8s Infra

**Comment by michaelfromyeg** [comment]
I can do

- [ ] Multicluster
- [ ] Network
- [ ] Node
- [ ] Release

(@fsmunoz -- might be prudent if you switch to the 4 items following Release, just so we all have some continuous set of that original list. Will hopefully make things slightly easier to track! Right now you and @muddapu both have CLI.)

**Comment by AnaMMedina21** [comment]
just adding to the note above, apart from CLI being selected twice, so is Network 
_____
I'll take
- [ ] Scalability
- [ ] Scheduling
- [ ] Security
- [ ] Testing

**Comment by fsmunoz** [comment]
As per our discussion, I ended up taking:

- [ ] Storage
- [ ] Windows
- [ ] UI
- [ ] Usability
