### ISSUE TITLE
Document release webinar format / process

### ISSUE THREAD

**Issue by marosset** [kubernetes/sig-release#2287]
We should add documentation around the release webinars to the release lead handbook (things like how to schedule, formatting, etc) and also add it the release cycle issue template.

Here are links to the release webinars for 1.26 and 1.27 for reference
- 1.26 https://community.cncf.io/events/details/cncf-cncf-online-programs-presents-cncf-live-webinar-kubernetes-v126-release-1/
- 1.27 https://github.com/kubernetes/sig-release/issues/2223

cc @leonardpahlke @gracenng @salaxander @Atharva-Shinde

**Comment by leonardpahlke** [comment]
We should follow the outline of the 1.27 call and not the one from 1.26 :D

**Comment by leonardpahlke** [comment]
Perhaps @gracenng could document this after the webinar for 1.28?

**Comment by leonardpahlke** [comment]
/remove-lifecycle rotten

cc @katcosgrove
