### ISSUE TITLE
Documentation for KEP-1731 (OpenBuildService)

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/sig-release#2290]
We need to deliver:

- Documentation updates to k/website for how to use packages published on the community infra (latest until Friday, July 28)
- Feature blog post describing why are we moving away from the Goolge infra, how the new infra work, what are benefits, deprecation timeline, and similar (latest until Tuesday, August 8)

/assign
/sig release
/area release-eng
/kind documentation
/priority critical-urgent

**Comment by saschagrunert** [comment]
@xmudrii can this one be closed?

**Comment by xmudrii** [comment]
Yes, it is done.
/close
