### ISSUE TITLE
Streamline release team slack channels

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/sig-release#2293]
**Current situation**: The release team communicates mainly via Slack. The release team uses the sig-release channel for the main communication. Part of the communication takes place in subteam channels. Most subteam channels are not very busy with only a handful of messages per release. One exception is the ci-signal channel, which is very heavily used.

**Proposal**: Merge the `release-docs`, `release-comms`, `release-enhancements`, `release-notes`, `release-bug-triage` subteam channels into a new one named `release-team`. The `release-ci-signal` channel will remain as it is. This will hopefully simplify communication and make it easier to follow all the happenings in the release team.

This was discussed in the last release team retro (mid-cycle retro 1.28) and in the Sig release meeting on July 25 with supporting comments on it. 

@kubernetes/sig-release-leads

**Comment by palnabarun** [comment]
I like the idea of consolidating the channels with reasonably less usage, in favor of a common channel.

**Comment by sftim** [comment]
The low traffic levels are for me a feature not a bug.

This means that instead of interfacing with #release-docs and #release-comms (low traffic), SIG Docs need to interface with a higher-traffic general #release-team channel.

**Comment by leonardpahlke** [comment]
I will close this issue since there are good points raised against it! 👍 Thanks all
