### ISSUE TITLE
[LFX Fall '23 Mentorship] Build a Go library and CLI for interacting with OpenBuildService

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/sig-release#2295]
This is a LFX mentorship project intended to run in Fall 2023

### Description

Kubernetes is set to start using [OpenBuildService](http://openbuildservice.org) as a platform for building, publishing, and hosting Kubernetes system (Debian and RPM) packages. The current integration with the OpenBuildService platform assumes a lot of manual tasks and depending on `osc` command-line tool written in Python. At SIG Release, we're striving to automate as many tasks as possible. We want to build a library and CLI written in Go for interacting with the OpenBuildService APIs and platform that can be integrated with our existing [release tooling (`krel`)](http://github.com/kubernetes/release).

### Relevant Issues

The list below includes relevant issues, but the scope of the project is not limited to these issues:

```[tasklist]
### Relevant Issues
- [ ] https://github.com/kubernetes/release/issues/3055
- [ ] https://github.com/kubernetes/release/issues/3180
```

### Expected Outcomes

Library and CLI tool for interacting with OpenBuildService platform via their publicly available APIs. Both library and CLI tool should be properly tested via unit, integration, and end-to-end tests, and properly documented.

### Recommended Skills

Golang, working with APIs

### Additional Links

- [Kubernetes Contributor Guide](https://www.kubernetes.dev/docs/guide/)
- [SIG Release Contributing Guide](https://github.com/kubernetes/sig-release/blob/master/CONTRIBUTING.md)
- [OpenBuildService](http://openbuildservice.org)
- [OpenBuildService documentation](https://openbuildservice.org/help/)
- [OpenBuildService instance hosted by SUSE](http://build.opensuse.org)
- [OpenBuildService API documentation](https://api.opensuse.org/apidocs/index)

**Comment by subh-cs** [comment]
I want to work on this issue during LFX. Currently going through all the possibility and will write a detailed idea list for the same.

**Comment by satyampsoni** [comment]
Hey @xmudrii , I am interested in applying for this project under this LFX term.
Actually, I had some questions and it would be a great help if you could answer them.

Here's what I understood:  
The goal of this project is to streamline the integration of Kubernetes with OpenBuildService, making it more efficient and reducing manual intervention by leveraging Go-based tools for automation.
This focuses on the development of a Go library and CLI (Command-Line Interface) for interacting with the OpenBuildService (OBS) platform. OpenBuildService is intended to be used as a platform for building, publishing, and hosting Kubernetes system packages in Debian and RPM formats. However, the current integration with OBS relies on manual tasks and the use of the "OSC" command-line tool, which is written in Python. To address this limitation and automate various tasks, the Kubernetes Special Interest Group (SIG) Release wants to create a Go-based library that acts as an API client for OBS for seamless communication with the publicly available OBS APIs and CLI tool to interact with the OBS platform using functions and methods provided by the API client library.

To ensure the reliability and robustness of the library and CLI, they should be thoroughly tested with unit tests, integration tests, and end-to-end tests. Furthermore, proper documentation should be provided to aid users in understanding how to use the library and CLI effectively.

My doubt is How can we ensure a smooth integration between the library, CLI, and the existing release tooling, krel? 
and are there documentations to read about the OBS APIs and How it operates?

**Comment by swaingotnochill** [comment]
Hi Team, I wish to work on this problem statement for the LFX term 3. In terms of skills, I satisfy the recommendations. I will follow up for more details on the slack channel.

**Comment by anj20** [comment]
Hi @xmudrii , I am interested in working on this project.

**Comment by xmudrii** [comment]
@satyampsoni This is a good understanding of the problem.

> My doubt is How can we ensure a smooth integration between the library, CLI, and the existing release tooling, krel?
and are there documentations to read about the OBS APIs and How it operates?

Speaking of the former question, the focus of the project is going to be OBS APIs that we use. At this stage we don't want to build a library that supports every single API call. These API calls that we use should be exposed via functions that are going to be easily used from krel and that's something that we're going to clearly define at the beginning of the project.

The OBS team recently created a new API documentation via Swagger: https://api.opensuse.org/apidocs/index

If you want to experiment, you can create your own OBS account and give a try to that API.

**Comment by sarthaksarthak9** [comment]
Hello, @xmudrii  I am interested in applying for this project under this LFX term
If you could clarify some of my doubts it could be great help

Here, what I understood:
the project involves building a Go library and CLI tool to interact with the OpenBuildService platform, which will be used for building, publishing, and hosting Kubernetes system packages (both Debian and RPM packages).

The current integration with OpenBuildService is manual and relies on the osc command-line tool written in Python. The goal of this project, led by SIG Release, is to automate as many tasks as possible related to OpenBuildService. By creating a new library and CLI tool written in Go, they aim to streamline the process and make it more efficient.

Some of my doubts are 
how to obtain representative datasets that mimic the actual scenarios where krel and the new tool are used?
Managing authentication securely and effectively with OBS APIs , how to securely handle API keys or tokens?
how to interact with specific OBS APIs, their endpoint?

**Comment by xmudrii** [comment]
> how to obtain representative datasets that mimic the actual scenarios where krel and the new tool are used?

- Check this package for calls to `osc`: https://github.com/kubernetes/release/tree/master/pkg/obs
  - Example: https://github.com/kubernetes/release/blob/02e7ecde711f4422b33c7841b0eadbc6eed413c8/pkg/obs/stage.go#L193-L215
- We also need to handle calls such as:
  - Creating new projects
  - Updating existing projects
  - Updating permissions for projects
  - Updating project's meta
  - Creating packages

> Managing authentication securely and effectively with OBS APIs , how to securely handle API keys or tokens?

OBS doesn't have a concept of API keys or tokens. We solved this by using a dedicated user to interact with the OBS API and with the `osc` CLI.

> how to interact with specific OBS APIs, their endpoint?

See the API documentation for more details: https://api.opensuse.org/apidocs/index
You can create an account for free on http://build.opensuse.org and use your home project to experiment with various API calls.

I also recommend checking out OBS documentation for more details about how OBS works: https://openbuildservice.org/help/

**Comment by nitishfy** [comment]
This is a great idea and I'd love to get involved into this!

**Comment by Nupoor10** [comment]
Hii, @xmudrii I would love to get involved with this project. I am currently getting familiar with the OpenBuildService platform . Looking forward to making an amazing contribution!

**Comment by dipankardas011** [comment]
Interesting, improvements for more automation. Certainly looking forward to it

**Comment by anirudhprabhakaran3** [comment]
Hello! I was just going through this project, and I wanted to express my interest in this! Will go through all the documentation and links provided and draft a proposal for submission!

**Comment by AHB102** [comment]
Hi @xmudrii would absolutely love be a part of it in the upcoming LFX term.Surely coming up with a proposal.

**Comment by ishashankmittal** [comment]
Hey! @xmudri , I am Shashank Mittal pursuing my undergrad at IIT BHU (Indian Institute of Technology (BHU) Varanasi). I am highly interested in Open Source and Software Development. I would love to contribute to this project and participate in this LFX Fall'23!

**Comment by xmudrii** [comment]
The LFX Fall mentorship cycle has been successfully completed! Congrats @nitishfy!
/close
