### ISSUE TITLE
[1.9] Feature Freeze

### ISSUE THREAD

**Issue by enisoc** [kubernetes/sig-release#23]
According to the proposed schedule, feature freeze is Fri, Oct 27.

I want to send a reminder to k8s-dev soon, but I wanted to check if we're asking for anything different this cycle.

@idvoretskyi Do you require anything at feature freeze other than that the issues are populated in the features repo?

@Bradamant3 There's something in the proposed schedule about "release talking points" and "sig themes" being due at feature freeze time. Can you elaborate on what we need the SIGs to provide?

**Comment by Bradamant3** [comment]
IIRC, 1.9 is now slated to be a maintenance release? If so, we should minimize the themes, although I know that sig-apps is planning to move the workloads api wholesale to v1. @idvoretskyi ran this aspect of things for 1.8 -- can you help out here too? Am I understanding correctly? Should we be reaching out to sigs? (I need to do so in any case wrt release notes.)

**Comment by idvoretskyi** [comment]
@enisoc 
> @idvoretskyi Do you require anything at feature freeze other than that the issues are populated in the features repo?

No, nothing else.

@Bradamant3 yes, we need reach to SIGs. Also, on maintenance/non-maintenance releases - it seems, we would avoid using this terminology for the future, as discussed at 1.8 retro. No final agreement yet, but let's focus on release deliverability, not terminology.

**Comment by enisoc** [comment]
Features are populated at http://bit.ly/k8s19-features.
