### ISSUE TITLE
Improve handbook communications about notifications to the blog owners 

### ISSUE THREAD

**Issue by krol3** [kubernetes/sig-release#2323]
#### Why is this needed:
- In each release, we have feature blogs, in the handbook we need to improve the notifications to the authors about publication blog date.
- The notification could happen in the blog PR and by the public channel in kubernetes #sig-docs-blog

cc: @leonardpahlke  @reylejano

**Comment by krol3** [comment]
I can create the PR about this too.

**Comment by sftim** [comment]
BTW, it's Ok to signpost the authors to the project board. I think it's better to communicate more directly and comment on the PR eg “this article is scheduled for the 12th of Whenever”, though.
