### ISSUE TITLE
[1.29] Release Team Lead access for @Priyankasaggu11929, @mehabhalodiya, @mickeyboxell, @neoaggelos, @ramrodo

### ISSUE THREAD

**Issue by Priyankasaggu11929** [kubernetes/sig-release#2329]
### GitHub Username(s)

- @Priyankasaggu11929  
- @mehabhalodiya 
- @mickeyboxell 
- @neoaggelos  
- @ramrodo 

### Release Cycle

Kubernetes 1.29

### Prerequisites

- [x] Ensure new Release Team Lead:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/a/kubernetes.io/g/dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
  - [x] Has completed the [CNCF Inclusive Speaker Orientation](https://training.linuxfoundation.org/training/inclusive-speaker-orientation/)

### Onboarding

- [X] Release Team Lead has agreed to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.
  This must be done as an issue comment by the incoming Release Team Lead.
- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) - https://github.com/kubernetes/org/pull/4443
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
  - `sig-release`
- [x] Update `kubernetes/sig-release` `OWNERS`
  - [X] Release Team Lead and Shadows - https://github.com/kubernetes/sig-release/pull/2331
    - Add an `approvers` entry in `releases/release-x.y/OWNERS`
  - **Release Team Lead only** (PR - https://github.com/kubernetes/sig-release/pull/2330)
    - In `OWNERS_ALIASES`, add an entry in the following sections: 
      - `release-team`
      - `release-team-lead-role`
- [x] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  PR - https://github.com/kubernetes/k8s.io/pull/5782
  - `k8s-infra-release-viewers@`
  - `release-managers@`
  - `release-team@`
- [x] Grant calendar access - [asked for access](https://kubernetes.slack.com/archives/C2C40FMNF/p1693472113103199)
- [x] Grant Zoom credentials (host key) - [asked for access](https://kubernetes.slack.com/archives/C2C40FMNF/p1693472113103199)
- [x] Add incoming leads to `release-team-leads` Slack Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml) -   PR: https://github.com/kubernetes/community/pull/7519
  - Add slack ID(s) to [`users.yaml`](https://git.k8s.io/community/communication/slack-config/users.yaml), if they are not yet in the file
  - Add username(s) to [`usergroups.yaml`](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)

### Offboarding

- [ ] Remove from GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml) -  https://github.com/kubernetes/org/pull/4443https://github.com/kubernetes/org/pull/4443
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
- [ ] Remove from Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [ ] Manually remove from the following Google Groups:
  - [kubernetes-release-team](https://groups.google.com/a/kubernetes.io/g/release-team) (Add as Manager)
  - [kubernetes-sig-leads](https://groups.google.com/forum/#!forum/kubernetes-sig-leads) (Add as Member)
- [ ] Remove from `release-team-leads` Slack Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)
  - Remove slack ID(s) from [`users.yaml`](https://git.k8s.io/community/communication/slack-config/users.yaml), if no longer in a group
  - Remove username(s) from [`usergroups.yaml`](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)

cc: @kubernetes/release-engineering @kubernetes/release-team

**Comment by Priyankasaggu11929** [comment]
I have completed the CNCF Inclusive Speaker Orientation training — Certificate ID Number: [LF-vm42e2205f](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/2db3da22-4422-48ed-b3d9-bc3d02374cc2-priyanka-saggu-c8a882f4-c45e-419e-84a9-f9a07ba1baac-certificate.pdf)

I agree to abide by the guidelines set forth in the [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the [embargo](https://github.com/kubernetes/committee-security-response/blob/main/private-distributors-list.md#embargo-policy) on CVE communications.

**Comment by Priyankasaggu11929** [comment]
Hello @mehabhalodiya, @mickeyboxell, @neoaggelos, @ramrodo — could you all please complete the [CNCF Inclusive Speaker Orientation (LFC101)](https://training.linuxfoundation.org/training/inclusive-speaker-orientation/) training and comment your Certificate ID here.

Also an undertaking of the following. Thanks!

> Release Team Lead has agreed to abide by the guidelines set forth in the
[Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.
> This must be done as an issue comment by the incoming Release Team Lead.

**Comment by neoaggelos** [comment]
I have completed the CNCF Inclusive Speaker Orientation training. Certificate ID Number: [LF-aoiq9wdo0f](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/ef21dc52-c0dd-45ad-a935-97d9cb7019d2-angelos-kolaitis-06be778a-8a51-4ab3-bc3d-701a5a66a268-certificate.pdf)

I agree to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by npolshakova** [comment]
I have completed the CNCF Inclusive Speaker Orientation training — Certificate ID Number: LF-fyfro6wrzc

I agree to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by ramrodo** [comment]
I have completed the CNCF Inclusive Speaker Orientation training. Certificate ID Number: [LF-yrn62qqjfj](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/5127349a-2525-481d-be8f-b84735d28e90-rodolfo-martnez-vega-8d45aab9-dc57-4ae0-8826-98e0c44efb85-certificate.pdf)

I agree to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by mehabhalodiya** [comment]
I have completed the CNCF Inclusive Speaker Orientation training. Certificate ID Number: [LF-p153rzyntb](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/b98f503e-9781-477e-90b5-63d89e825040-meha-bhalodiya-fbf3dca8-8861-4017-8e79-4f5d435d62e5-certificate.pdf)

I agree to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by mickeyboxell** [comment]
I have completed the CNCF Inclusive Speaker Orientation training. Certificate ID Number: LF-ivrocskska

I agree to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by Priyankasaggu11929** [comment]
On-boarding of 1.29 Release Team leads is completed!

**Comment by Priyankasaggu11929** [comment]
1.29 Release Cycle finished!

/close
