### ISSUE TITLE
https://storage.googleapis.com/k8s-release-dev/ci/latest.txt seems to return invalid value

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/sig-release#2333]
#### What happened:
In the past few days, we have been seeing v1.28.x-xxx /v1.27.x-xxx versions at [latest.txt](https://storage.googleapis.com/k8s-release-dev/ci/latest.txt).

#### What you expected to happen:
[latest.txt](https://storage.googleapis.com/k8s-release-dev/ci/latest.txt) should ideally have ci versions of v1.29

#### How to reproduce it (as minimally and precisely as possible):
Keep viewing https://storage.googleapis.com/k8s-release-dev/ci/latest.txt 
#### Anything else we need to know?:
Our job that creates k8s cluster with version at latest.txt is failing at kubeadm init phase intermittently, due to below error when ever there are .28/.27 versions displayed there.
```
remote version is much newer: v1.29.0-alpha.0.589+debe30de70b2c9; falling back to: stable-1.28
[ERROR ImagePull]: failed to pull image gcr.io/k8s-staging-ci-images/kube-apiserver:v1.28.1: output: E0906 05:21:27.038162   25819 remote_image.go:171] \"PullImage from image service failed\" err=\"rpc error: code = NotFound desc = failed to pull and unpack image \\\"gcr.io/k8s-staging-ci-images/kube-apiserver:v1.28.1\\\"
```

Image pull failure is expected as falling back to stable version expects a different image bucket!

Failed Job link: https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64le/1699286523272237056 (It had v1.28.1-19+16bd870d488ccb at latest.txt)

Passed Job: https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64le/1699331845675552768 (It had v1.29.0-alpha.0.593+04292dd94bd999 at latest.txt)

**Comment by dims** [comment]
@Rajalakshmi-Girish https://dl.k8s.io/ci/latest-fast.txt can you please try this one?

**Comment by dims** [comment]
details here https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/kubernetes-versions.md

BUT just realized that this may not work for you! as it won't have `ppc64le`

**Comment by dims** [comment]
so ... for now till this gets sorted out ... try https://storage.googleapis.com/k8s-release-dev/ci/latest-1.29.txt

**Comment by dims** [comment]
/assign @xmudrii 

Marko, `ci-kubernetes-build` [logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build/1699481809215033344/build-log.txt) show the following which look ok:

```
level=info msg="Updating version, because v1.29.0-alpha.0.607+d7b7a85fbc0b38 > v1.28.1-28+d70cef6247096d"
level=info msg="Validating uploaded version file at https://storage.googleapis.com/k8s-release-dev/ci/latest.txt"
level=info msg="Version equals response"
level=info msg="Testing v1.29.0-alpha.0.607+d7b7a85fbc0b38 > latest-1.txt (published)"
level=info msg="Updating version, because v1.29.0-alpha.0.607+d7b7a85fbc0b38 > v1.28.1-28+d70cef6247096d"
level=info msg="Validating uploaded version file at https://storage.googleapis.com/k8s-release-dev/ci/latest-1.txt"
```

However, `ci-kubernetes-build-1-28` [logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build-1-28/1699462935404875776/build-log.txt) show:

```
level=info msg="Updating version, because v1.28.1-28+d70cef6247096d > v1.29.0-alpha.0.607+d7b7a85fbc0b38"
level=info msg="Validating uploaded version file at https://storage.googleapis.com/k8s-release-dev/ci/latest.txt"
level=info msg="Version equals response"
level=info msg="Testing v1.28.1-28+d70cef6247096d > latest-1.txt (published)"
level=info msg="Updating version, because v1.28.1-28+d70cef6247096d > v1.29.0-alpha.0.607+d7b7a85fbc0b38"
level=info msg="Validating uploaded version file at https://storage.googleapis.com/k8s-release-dev/ci/latest-1.txt"
level=info msg="Version equals response"
level=info msg="Testing v1.28.1-28+d70cef6247096d > latest-1.28.txt (published)"
level=info msg="Updating version, because v1.28.1-28+d70cef6247096d > v1.28.1-24+f87cd0b8ee3faa"
level=info msg="Validating uploaded version file at https://storage.googleapis.com/k8s-release-dev/ci/latest-1.28.txt"
level=info msg="Version equals response"
level=info msg="Testing v1.28.1-28+d70cef6247096d > k8s-stable1.txt (published)"
level=info msg="Updating version, because v1.28.1-28+d70cef6247096d > v1.28.1-24+f87cd0b8ee3faa"
level=info msg="Validating uploaded version file at https://storage.googleapis.com/k8s-release-dev/ci/k8s-stable1.txt"
level=info msg="Version equals response"
```

So `ci/latest.txt` is getting stomped on for sure! Though 1.27 [logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build-1-27/1699476775911821312/build-log.txt) look good to me, so don't know how that is stomping on latest.txt

**Comment by neolit123** [comment]
> @Rajalakshmi-Girish https://dl.k8s.io/ci/latest-fast.txt can you please try this one?

but latest-fast.txt points to artifacts that are not built yet, seems like a bug according to the description:
>> latest-fast markers reference linux/amd64-only builds generated via the ci-kubernetes-build-fast job, which run approximately every 5 minutes.

 latest-fast resolved to:
> v1.29.0-alpha.0.628+2d5b6f16f50633

> time="10:40:15" level=info msg="Downloading https://storage.googleapis.com/k8s-release-dev/ci/v1.29.0-alpha.0.628+2d5b6f16f50633/bin/linux/amd64/kubelet\n"
> time="10:40:15" level=warning msg="HTTP GET https://storage.googleapis.com/k8s-release-dev/ci/v1.29.0-alpha.0.628+2d5b6f16f50633/bin/linux/amd64/kubelet failed: 404 Not Found. Retry in few seconds"

latest-1.29 points at a different commit that has artifacts.
> v1.29.0-alpha.0.623+4f303d123659fb

**Comment by xmudrii** [comment]
I unintentionally made a regression in https://github.com/kubernetes/release/pull/3223, sorry about that! I created a revert PR for now: https://github.com/kubernetes/release/pull/3254

**Comment by neolit123** [comment]
> I unintentionally made a regression in [kubernetes/release#3223](https://github.com/kubernetes/release/pull/3223), sorry about that! I created a revert PR for now: [kubernetes/release#3254](https://github.com/kubernetes/release/pull/3254)

since a lot of tests depend on makers including kubectl (IIRC) and kubeadm, i wasthinking how can this be tested.
a peridic job can exist in release blocking that does the following and sends emails on failure:
- goes over some important markers from https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/kubernetes-versions.md (latest.txt is a good start)
- does a URL probe at https://dl.k8s.io/ci/marker-foo.txt and then at k/k github to see if this tag exists. [1]
- then a nice to have would be to go over our artifact buckets and check for existence of artifacts [2]

most marker failures have been around [1] and [2] or a combination of them.
