### ISSUE TITLE
shutdown release.triage.k8s.io

### ISSUE THREAD

**Issue by ameukam** [kubernetes/sig-release#2345]
https://release.triage.k8s.io/ is currently unmaintained and unused. Github projects have been used to do triage for enchancements.

Suggestion to shut it down.

/assign @kubernetes/release-team-leads 
cc @kubernetes/release-engineering

**Comment by saschagrunert** [comment]
+1

**Comment by ameukam** [comment]
cc @kubernetes/sig-release-leads 
_I tagged the wrong group_ 🤦🏾‍♂️

**Comment by ameukam** [comment]
Ingress deleted:
```bash
$kubectl -n triageparty-release delete ingress triage-party-release
ingress.networking.k8s.io "triage-party-release" deleted
```

Certificate deleted:
```bash
$ kubectl -n triageparty-release delete managedcertificate release-triage-k8s-io
managedcertificate.networking.gke.io "release-triage-k8s-io" deleted
```

Namespace deleted:
```bash
$ kubectl delete ns triageparty-release
namespace "triageparty-release" deleted
```

**Comment by ameukam** [comment]
This is done.
/close
