### ISSUE TITLE
Kubernetes v1.29 Major Themes contact

### ISSUE THREAD

**Issue by fsmunoz** [kubernetes/sig-release#2351]
The release notes team will use this issue to track the work on nudging SIGs for entries on major themes for the v1.29 release cycle.

The Slack channel for each SIG is usually `#sig-`, but accurate links are available in [k/community](https://github.com/kubernetes/community) under [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md). The plan is to ask for responses on the public Slack channel (non-disruptively).

Following is a bootstrap template that you can use to reach out to the individual sigs informing them about the [Major Themes Collection](https://github.com/kubernetes/sig-release/discussions/2349) discussion thread:

```
Hello SIG <sig-name>,

Major themes are an essential part of the Kubernetes release cycle as they provide a birds-eye view of major improvements that are coming as part of the upcoming release. 

As part of the effort aimed towards collecting the Major Themes for the v1.29 cycle, the release notes team is working towards gathering major themes entries. If you have anything to call out, we would appreciate it if your SIG can submit the content in
[Kubernetes 1.29 Major Themes GitHub discussion](https://github.com/kubernetes/sig-release/discussions/2349)
 
Ideally, we would like this to be completed by **Tuesday 14th November 2023**.

Thank you!
```

Different SIGs have a differente number of [tracked enhancements](https://github.com/orgs/kubernetes/projects/161). Some SIGs have activities that aren't quite coupled with Kubernetes releases, but it's worth checking anyway in case there are things worth calling out in what they did between the previous release and the current release. One example is Dockershim removal from 1.24 or Immutable Secrets and ConfigMaps from the 1.21 release.

In this release, I've split up the number of SIGs based on a mix of those that have tracked enhancements, and those that do not, in order to provide a balanced group of options: each shadow should pick a group, I'll start with the first one, which includes some extra to make sure that each shadow has the same number - please select the group in the comments and I'll update this list.

*Group 1* @fsmunoz
- [x]  Node **Added themes**
- [x]  Cloud Provider **Ack**
- [x] Architecture **Ack, nothing to add**
- [x]  Contributor Experience  **Ack, nothing to add**
- [x]  Release **Ack, nothing to add**
- [x]  Testing **Ack**
- [x]  Scalability

*Group 2* @mengjiao-liu 
- [x] API Machinery
- [x]  Scheduling **Added themes**
- [x]  Autoscaling
- [x]  Security

*Group 3* @muddapu 
- [x]  Network **Added themes**
- [x]  Instrumentation 
- [x]  Cluster Lifecycle **Ack, nothing to add**
- [x]  Docs  **Ack, nothing to add**

*Group 4* @fykaa 
- [x]  Auth  **Added themes**
- [x]  CLI 
- [x]  K8s Infra  **Ack, nothing to add**
- [x]  Multicluster

*Group 5* @rashansmith 
- [x]  Storage **Added themes**
- [x] Apps 
- [x] Windows **Added themes**
- [x] UI  **Ack, nothing to add**

We'll try to keep the list up-to-date, but please double-check in the comments if someone has contacted their channel. We can debate more details in Slack.

/assign @rashansmith @muddapu @mengjiao-liu @fykaa 

cc @Priyankasaggu11929  @salaxander 

/milestone v1.29

xref: #2272

**Comment by mengjiao-liu** [comment]
> As part of the effort aimed towards collecting the Major Themes for the v1.29 cycle, the release notes team is working towards gathering major themes entries. If you have anything to call out, we would appreciate it if your SIG can submit the content in
[Kubernetes 1.28 Major Themes GitHub discussion](https://github.com/kubernetes/sig-release/discussions/2349)

nit: Please correct 1.28 to 1.29 above. @fsmunoz

**Comment by mengjiao-liu** [comment]
I'll pick up the Group 2.

**Comment by fykaa** [comment]
I'll pick Group 4

**Comment by muddapu** [comment]
I will pick group 3

**Comment by rashansmith** [comment]
Group 5

- [x] Storage
- [x] Apps
- [x] Windows
- [x] UI

**Comment by fykaa** [comment]
Should we be closing this issue? @fsmunoz

**Comment by sanchita-07** [comment]
I am closing this issue since all the SIGs have been reached out to and it has been tracked.
