### ISSUE TITLE
Define criteria for a job to be release-blocking

### ISSUE THREAD

**Issue by enisoc** [kubernetes/sig-release#24]
This is a tracker for writing a concrete policy for deciding whether a given job should be release-blocking.

**Comment by enisoc** [comment]
We cut [v1.9.0-alpha.2](https://github.com/kubernetes/sig-release/issues/22) with the following jobs failing out of the current master-release-blocking set:

- gci-gce-serial
- gci-gke-serial
- gci-gce-alpha-features
- gce-scale-correctness
- soak-gce-gci
- kubeadm-gce

Once we define criteria, we will be following up to evaluate these for continued blocking status.

**Comment by spiffxp** [comment]
Still working on a proposal, but here's my rough take for now:

An ideal candidate job for release-blocking:
- Finishes a run in 60 minutes or less
- Runs at least every 2 hours
- Passes 90% of all runs in the past week (regardless of underlying commit)
- Is capable of passing 3 times in a row against the same commit
- Is owned by a SIG that is responsive to @kubernetes/sig-foo-test-failures
- Fails for no more than 10 runs in a row

**Comment by jdumars** [comment]
Aaron and I worked on some definitions around this in a Google doc, and I would like to reconcile that effort with this PR.  The doc is here: https://docs.google.com/document/d/1kCDdmlpTnHPQt5z8JzODdFCc3T2D4MKR53twsDZu20c/edit We had intended to do the necessary pre-work and then submit it as a proposal, but the process for "process proposals" is not clear.  (my head just exploded)

**Comment by jdumars** [comment]
Also, I don't think this should be in a KEP. These are procedural guard rails around the build ecosystem, and require a different audience and level of review.

**Comment by spiffxp** [comment]
I'm going to try and reframe this into a step by step guide on how to move a job from:
- non-blocking to release-blocking
- bring-your-own-ci to triggered-by-k8s-prow
- pr-optional to pr-non-blocking
- pr-non-blocking to pr-blocking

Criteria will include responsive humans and metrics on signal reliability that are available to us today

Then PR this into test-infra/docs

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/sig-release/pull/346 did this I think?

**Comment by spiffxp** [comment]
/close
Criteria are documented but not yet fully enforced (re: metrics on duration and flakiness)

Will continue to work that against #347
