### ISSUE TITLE
Prune / update `kubernetes-milestone-maintainers` GitHub team

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#241]
Once we document the process for maintaining the `milestone-maintainers` GitHub team (https://github.com/kubernetes/community/issues/2424 / https://github.com/kubernetes/sig-release/pull/239) and gather some data on who's been actively using `/milestone` commands, we should prune / update the list as necessary.

/sig release
/assign @tpepper 

rel:
- #239 (comment)
- https://docs.google.com/spreadsheets/d/1BhKpWwAVMxhtGAd_wOTCzduj-B4SDAp6C_wcSqo7SwA

**Comment by justaugustus** [comment]
@tpepper -- bump. did we close the loop on this?

**Comment by tpepper** [comment]
I owe a PR or two here still.

**Comment by justaugustus** [comment]
Bump. Also assigning current RT Lead + Shadow.
/assign @AishSundar @spiffxp

**Comment by neolit123** [comment]
+1 this should probably happen every 1-2 cycles.

**Comment by justaugustus** [comment]
@tpepper @AishSundar @spiffxp -- did we have a chance to take care of cleaning up the `kubernetes-milestone-maintainers` Github team?

**Comment by AishSundar** [comment]
I wasn't doing anything towards this. At a minimum we can ping folks marked so on [this spreadsheet](https://docs.google.com/spreadsheets/d/1BhKpWwAVMxhtGAd_wOTCzduj-B4SDAp6C_wcSqo7SwA/edit#gid=0) if @tpepper hasn't already.

**Comment by justaugustus** [comment]
Thanks! @aishsundar or @tpepper, can you give me edit access to that sheet? I hopped comments on the relevant people, but I'll also clean the list up once I have access to munge the actual list.

**Comment by AishSundar** [comment]
I dont have edit access either. Lets wait for @tpepper

**Comment by spiffxp** [comment]
A modest proposal as we start off a new year: new year, new team.  Drop everyone.  Add the release team.  Add current SIG chairs or TLs.  Add back anyone who asks, have them provide rationale.

**Comment by justaugustus** [comment]
@spiffxp -- Great idea! I'm in favor of purging the list for the new year. :)

**Comment by tpepper** [comment]
Is it possible to update the Prow "/milestone" command help info, if not already sufficiently clear, to have something like:  "If you believe you should be able to issue the /milestone command, please contact your SIG chairs and have them propose you as an additional delegate for this responsibility."

**Comment by justaugustus** [comment]
@tpepper -- Yep! PR here: https://github.com/kubernetes/test-infra/pull/10669
