### ISSUE TITLE
Kubernetes v1.30 Major Themes contact

### ISSUE THREAD

**Issue by rashansmith** [kubernetes/sig-release#2428]
The release notes team will use this issue to track the work on nudging SIGs for entries on major themes for the v1.30 release cycle.

The Slack channel for each SIG is usually `#sig-`, but accurate links are available in [k/community](https://github.com/kubernetes/community) under [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md). The plan is to ask for responses on the public Slack channel (non-disruptively).

Following is a bootstrap template that you can use to reach out to the individual sigs informing them about the https://github.com/kubernetes/sig-release/discussions/2424 discussion thread:

```
Hello SIG <sig-name>,

Major themes are an essential part of the Kubernetes release cycle as they provide a birds-eye view of major improvements that are coming as part of the upcoming release. 

As part of the effort aimed towards collecting the Major Themes for the v1.30 cycle, the release notes team is working towards gathering major themes entries. If you have anything to call out, we would appreciate it if your SIG can submit the content in
[Kubernetes 1.30 Major Themes GitHub discussion](https://github.com/kubernetes/sig-release/discussions/2424)
 
Ideally, we would like this to be completed by **Tuesday 19th March 2024**.

Thank you!
```

Different SIGs have a different number of [tracked enhancements](https://github.com/orgs/kubernetes/projects/175). Some SIGs have activities that aren't quite coupled with Kubernetes releases, but it's worth checking anyway in case there are things worth calling out in what they did between the previous release and the current release. One example is Dockershim removal from 1.24 or Immutable Secrets and ConfigMaps from the 1.21 release.

In this release, I've split up the number of SIGs based on a mix of those that have tracked enhancements, and those that do not, in order to provide a balanced group of options: each shadow should pick a group, I'll start with the first one, which includes some extra to make sure that each shadow has the same number - please select the group in the comments and I'll update this list.

Group 1 @rashansmith 
 - [ ] Node 
 - [ ] Cloud Provider
 - [ ] Architecture 
 - [ ] Contributor 
 - [ ] Release 
 - [ ] Testing 
 - [ ] Scalability

Group 2 @OrlinVasilev 
 - [ ] API Machinery 
 - [X] Scheduling 
 - [X] Autoscaling 
 - [ ] Security

Group 3 @npolshakova 
 - [X] Network 
 - [ ] Instrumentation 
 - [ ] Cluster Lifecycle 
 - [ ] Docs 

Group 4 @fykaa 
 - [ ] Auth 
 - [ ] CLI 
 - [ ] K8s Infra 
 - [ ] Multicluster

Group 5 @satyampsoni 
 - [X] Storage 
 - [X] Apps 
 - [X] Windows 
 - [ ] UI 

We'll try to keep the list up-to-date, but please double-check in the comments if someone has contacted their channel. We can debate more details in Slack.

/assign @fykaa @npolshakova @OrlinVasilev @satyampsoni 

cc @katcosgrove @gracenng 

/milestone v1.30

xref: https://github.com/kubernetes/sig-release/issues/2351

**Comment by npolshakova** [comment]
I can reach out to group 3!

**Comment by fykaa** [comment]
I'll pick Group 4

- [x] Auth
- [x] CLI
- [x] K8s Infra - Nothing from K8s Infra in this release.
- [x] Multicluster

**Comment by satyampsoni** [comment]
I'll go for Group 5
