### ISSUE TITLE
Revisit use of milestone-maintainer munger

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#243]
I want to get rid of all mungers and fully rid us of mungegithub (https://github.com/kubernetes/test-infra/issues/3331)

I question the utility of milestone-maintainer.  By what measure do we think it's working?  Anecdotally I feel like it's generating a lot of noise.

If I can save us a lot of work and not bother porting milestone-maintainer, I'd rather do that.  If there is functionality that is useful, I'd like to examine whether we could implement it some other way.

**Comment by spiffxp** [comment]
/assign
@kubernetes/sig-release-proposals

**Comment by spiffxp** [comment]
Possible re-implementation using `commenter`

Here's an example of using `commenter` in periodic prowjob: https://github.com/kubernetes/test-infra/blob/75543f5d7c7ea75e190486bd55bc102abae1e4dd/config/jobs/kubernetes/test-infra/test-infra-periodics.yaml#L157-L189

Here's what that could look like enforcing that an issue in the v1.12 milestone has at least one of a set of `kind/foo` labels
```
- |-
  --query=repo:kubernetes/kubernetes
  milestone:v1.12
  -label:kind/bug
  -label:kind/cleanup
  -label:kind/failing-test
  -label:kind/flake
  -label:kind/feature
- --updated=12h
- --token=/etc/token/bot-github-token
- |-
  --comment=Issues in the current milestone must have certain labels.
  Please ensure this issue has one of `kind/bug`, `kind/cleanup`, 
  `kind/failing-test`, `kind/flake` or `kind/feature` applied.  
  
  eg: `/kind bug` will apply the `kind/bug` label
        
  Remove a kind label with `/remove-kind`, eg: `/remove-kind bug` will remove the `kind/bug` label
  
  If you find this comment confusing or annoying, please [file an issue against kubernetes/sig-release](https://github.com/kubernetes/sig-release/issues/new)
- --template
- --confirm
```

Cons:
- There would need to be a comment per requirement expressible as a github query, and certain constraints that milestone-maintainer checks may not be expressible as such.
- There is copy-paste and non-dryness between the queries and messages
- Deadline for issue removal can't be based off of "since issue was added to milestone", only "since issue was last updated", meaning it would be possible to keep commenting "bump" to keep an issue inside its deadline

Pros:
- There is way less logic to wade through to understand what this does
- This requires no code changes to deploy
- This could be constrained to a single yaml file under sig-release's control

**Comment by jberkus** [comment]
If your first comment was a proposal to remove milestone-maintainer and not replace it with anything, -1 to that.

As for replacing it with commentor, a cautious +1 if we can work out the details?  Specifics:

>     There would need to be a comment per requirement expressible as a github query, and certain constraints that milestone-maintainer checks may not be expressible as such.

The answer to this is pretty clearly to go through the requirements that we *want* to have and see if they can all be expressed as search queries.

> There is copy-paste and non-dryness between the queries and messages

This is potentially a major blocker.  There's already lots of complaints about the comment traffic created by milestone-maintainer; increasing the number of comments (like having separate comments, one each for missing kind/ priority/ and sig/ labels)  would probably cause a revolt.
   
> Deadline for issue removal can't be based off of "since issue was added to milestone", only "since issue was last updated", meaning it would be possible to keep commenting "bump" to keep an issue inside its deadline

I think this is a problem we can live with, *unless* updates by bots actually cause issues/PRs to keep getting "bumped".  Generally, issues/PR which are missing labels, milestones, etc., also aren't getting regular updates from humans.  If they are, then human intervention is probably better than bot intervention anyway.

**Comment by spiffxp** [comment]
To sum up the conversation we had about this during today's sig-release meeting:
- we're going to disable the milestone-maintainer munger
- ultimately most humans have been doing the munger's job already, and tend to catch things the munger doesn't catch, so we expect the keep the quality bar this way

There was much discussion of _why_ it did the things it did, or what we wanted things to look like:
- we want label hygiene in general to be better more consistent, ie: `kind/` `priority/` `sig/` on all issues _and_ pr's
- it would be nice to auto-milestone PR's prior to code freeze, and enforce milestone during code freeze, so that users can later see "in which release did this PR land?" at a glance from the PR
- the reason milestone munger nagged about _specific_ `kind/` labels was that come burndown time (ie: during code slush, code freeze), issues in the milestone should represent the punch list of critical things to fix before releasing.  It shouldn't include things like `kind/feature` or `kind/cleanup`, and should really only be about fixing `kind/bug` and `kind/test-failure`'s.  Or some subset of labels.
- same thing for `priority/` labels, during a burndown, we only focus on high priority items, we're not going to suddenly accept a `priority/backlog` PR
- there was concern about code sneaking in without SIG oversight, ie: two devs getting in a room and merging each other's work without the SIG being aware
- there was discussion about preventing PR's from merging unless they had a `sig/` label applied (this would be a pain to express directly as a github query, but could be done with a workflow similar to `do-not-merge/release-note-label-needed`)

Ultimately I want us to automate away as much of the release team toil as we can, so just turning milestone-maintainer off and walking away is not the end game. Rather I would welcome proposals that allow us to trust the automation rather than duplicate or ignore its work, and keep the contributor experience as frictionless as possible.

**Comment by tpepper** [comment]
+1

Sadly, turning off milestone-maintainer munger is an acknowledgment that this specific instance of automation here did not end up replacing any particular release team manual activities.  The manual activities remain in place for risk management at the release team level.  And that toil remains as a worthy candidate for a next iteration toward automating away.

**Comment by jberkus** [comment]
@spiffxp  I believe that merge requirements can be enforced via Tide in the future.  That is, we can require labels, milestones, etc. in Tide instead of needing a munger to do it.

**Comment by guineveresaenger** [comment]
I honestly don't like the part where the munger removes bugs from the milestone. Bugs aren't subject to feature freeze, and when they drop off the milestone, even though they're being worked on, we have to hunt down SIG leads to put them back, which creates unnecessary housekeeping and constant vigilance.

How would users be prompted to add a milestone label currently? That's a different functionality, right?

**Comment by spiffxp** [comment]
/close
milestone-maintainer was disabled earlier today https://github.com/kubernetes/test-infra/pull/8909
