### ISSUE TITLE
EOL policy for older release-1.y jobs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#244]
Historically test-infra carries up to five sets of jobs to support kubernetes/kubernetes:
- k8s-dev : master
- k8s-beta : release-1.11
- k8s-stable1 : release-1.10
- k8s-stable2 : release-1.9
- k8s-stable3 : release-1.8

When we create the release-1.12 branch, this mapping will become:
- k8s-dev : master
- k8s-beta : release-1.12
- k8s-stable1 : release-1.11
- k8s-stable2 : release-1.10
- k8s-stable3 : release-1.9

At which point the release-1.8 jobs will go away.  This means we will drop CI coverage of a release we now consider unsupported up to 6 weeks into the 1.12 release cycle.

How long have we waited in the past?
- release-1.7 jobs went away apr 13 (https://github.com/kubernetes/test-infra/issues/7459) or about 2 weeks into the 1.11 release cycle
- release-1.6 jobs went away jan 30 (https://github.com/kubernetes/test-infra/pull/6538) or about 5 weeks into the 1.10 release cycle
- release-1.5 jobs went away oct 30 (https://github.com/kubernetes/test-infra/issues/4862) or about 4 weeks into the 1.9 release cycle

In that light, 6 weeks seems like a pretty conservative waiting period.

I'd like to propose we adopt a policy of the test-infra role dropping the release-1.y jobs for the oldest release on week 4, or whatever week feature freeze takes effect, as a standard part of the release timeline.

**Comment by spiffxp** [comment]
FYI @krzyzacy @BenTheElder @cjwagner 
as previous test-infra roles

**Comment by BenTheElder** [comment]
> I'd like to propose we adopt a policy of the test-infra role dropping the release-1.y jobs for the oldest release on week 4, or whatever week feature freeze takes effect, as a standard part of the release timeline.


This SGTM, we should perhaps discuss with the patch managers / release leads?

**Comment by krzyzacy** [comment]
it was mostly me being bumping release versions, was meant to do that after I migrate all the goodies to config/jobs first

but agree we probably should have some standards.

**Comment by krzyzacy** [comment]
I'm also trying to accommodate gke releases as there's a fleet of gke blocking jobs, but 4 weeks sounds reasonable.

I'll add some docs, it's pretty straight forward for release blocking jobs, but there might be miscellaneous jobs that need to be managed by each individual sigs.

**Comment by spiffxp** [comment]
a) we don't actually have a test-infra handbook, oops, but yes this should be a part of one when it exists
b) thus, I'd like it to just be a standard part of the release schedule, in the same way that we call out test-infra creating release branch jobs
c) nothing to update in community... our "three version" support policy is buried in a nested doc, and I think I'd like to ask sig-arch about bringing that someplace front and center, but that's orthogonal to this
