### ISSUE TITLE
Document need for ensuring krte/kubekins/kubekins-v2 images are present for running jobs in a newly created branch

### ISSUE THREAD

**Issue by dims** [kubernetes/sig-release#2465]
CI jobs in the newly created 1.30 branch were failing because images that are used for testing were missing. The following steps were done for 1.30 to first ensure that the images were minted and then the jobs had to be updated

- https://github.com/kubernetes/test-infra/pull/32342
- https://github.com/kubernetes/test-infra/pull/32343
- https://github.com/kubernetes/test-infra/pull/32344

Let's please document this in the Branch Manager Handbook or somewhere appropriate.

**Comment by mehabhalodiya** [comment]
I think this is already documented: https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/branch-manager.md#update-e2e-variants

**Comment by xmudrii** [comment]
+1, this seems to be already properly documented. Also, I believe that if this is done before generating the release jobs, PRs such as https://github.com/kubernetes/test-infra/pull/32343 and https://github.com/kubernetes/test-infra/pull/32344 are not needed. @dims are we good to close this issue?

**Comment by dims** [comment]
sounds good @xmudrii - hopefully we follow the documentation next time :)
