### ISSUE TITLE
[1.9] Set due dates for docs/relnotes/marketing dependencies

### ISSUE THREAD

**Issue by enisoc** [kubernetes/sig-release#25]
@zacharysarah @Bradamant3 @nwoods3

While cleaning up the [release timeline](https://github.com/kubernetes/features/blob/master/release-1.9/release-1.9.md#timeline), I only kept items I understand -- mostly code/build-related.

I'd like help from the docs/relnotes/marketing leads to repopulate and document deadlines for things you need from other teams (devs, SIGs, etc.).

Here are some of the things that were previously listed in the timeline that I didn't understand well enough to commit to:

* Release talking points draft due
* SIG themes due in relnotes draft
* First draft of feature related release notes due
* Blog post draft for release team review
* Final draft of feature related release notes due
* Finalize release talking points

I'd like to clarify what deliverable is needed, and who is responsible for delivering it. For example, who writes the release talking points? If it's something the release team does, what do we need from SIGs before we can get it done?

**Comment by Bradamant3** [comment]
cc @idvoretskyi who helped with themes in relnotes for 1.8. I'll ping on Slack also. cc @nickchase who's helping with relnotes especially the script for generating. I need to dig some more to find where information for "feature related relnotes" might come from. (Came from pestering individual sigs for 1.8)
Blog post and talking points come from marketing. @nwoods3 do you need help here?

**Comment by nwoods3** [comment]
@Bradamant3 re: blog post and talking points - Yes, I will need the release team's help and Aparna has been a big help on these for the last several releases too. I am updating the marketing plan we used for 1.8 for 1.9 and will send that around to the release team on Monday, 10/30. The plan will have a timeline for the blog and talking points. We can discuss on the next release team call and I can answer any questions. The blog and talking points will not really come together under after the code freeze. I recommend we hold a messaging discussion around this time to solidify what we want to say in the blog and talking points.
