### ISSUE TITLE
Kubernetes v1.31 Major Themes contact

### ISSUE THREAD

**Issue by a-mccarthy** [kubernetes/sig-release#2527]
### Overview

The release comms team will use this issue to track the work on nudging SIGs for entries on major themes for the v1.31 release cycle.

Major theme discussion for 1.31: https://github.com/kubernetes/sig-release/discussions/2526
Major theme deadline: **Tuesday 23rd July 2024**.

Major themes are collect during each release cycle for every SIG to see what should be highlighted in the release blog, webinar, and other communications. Different SIGs have a different number of [tracked enhancements](https://github.com/orgs/kubernetes/projects/183/). Some SIGs have activities that aren't quite coupled with Kubernetes releases, and it's worth checking with them in case there are things worth calling out in what they did between the previous release and the current release. One example is Dockershim removal from 1.24 or Immutable Secrets and ConfigMaps from the 1.21 release.

### What do I need to do?

1. Pick a group of SIGs to reach out to (listed below), and comment your selection on this issue
2. Reach out to the SIGs in slack to ask for Major Themes feedback and directing them to the github discussion using the template below
3. Comment here when you've completed reaching out to the SIGs

Depending on the responses we get, we may need to send out a reminder in Slack later in the release cycle to each SIG to get more feedback on Major Themes.

### How do I find a SIG's slack channel?

The Slack channel for each SIG is usually #sig-, but accurate links are available in [k/community](https://github.com/kubernetes/community) under [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md). The plan is to ask for responses on the public Slack channel (non-disruptively).

### What should I say?

Following is a bootstrap template that you can use to reach out to the individual SIGs informing them about the discussion thread. This template includes the important information to convey to the SIG, but you are free to add your own personalization to the message if you'd like to.

___

Hello SIG [sig-name],

Major themes are an essential part of the Kubernetes release cycle as they provide a birds-eye view of major improvements that are coming as part of the upcoming release. The release comms team is asking for your help gathering Major Themes for this release. If you have anything to call out, we would appreciate it if your SIG can submit the content in
[Kubernetes 1.31 Major Themes GitHub discussion](https://github.com/kubernetes/sig-release/discussions/2526).
 
Ideally, we would like this to be completed by **Tuesday 23rd July 2024**.

Thank you!

___

### SIG groups

The following are groups of SIGs we need to reach out to. The SIGs are groups together in a mix of those that have tracked enhacements for this release and those that do not. Please comment below with the group you'd like to reach out to. 

Group 1 @a-mccarthy 

- [x]  Node
- [x]  Cloud Provider
- [x]  Architecture
- [x]  Contributor
- [x]  Release
- [x]  Testing
- [x]  Scalability

Group 2 @edithturn 

- [x]  API Machinery
- [x]  Scheduling
- [x]  Autoscaling
- [x]  Security

Group 3 @rashansmith 

- [x]  Network
- [x]  Instrumentation
- [x]  Cluster Lifecycle
- [x]  Docs

Group 4 @mbianchidev 

- [x]  Auth
- [x]  CLI
- [x]  K8s Infra
- [x]  Multicluster

Group 5 @hailkomputer 

- [x]  Storage
- [x]  Apps
- [x]  Windows
- [x]  UI

We'll try to keep the list up-to-date, but please double-check in the comments if someone has contacted their channel. We can debate more details in Slack.

/milestone v1.31

xref: https://github.com/kubernetes/sig-release/issues/2351

**Comment by edithturn** [comment]
Hello @a-mccarthy I checked Group Two in Slack, and there is no communication about the release yet. I would like to take Group Two.

**Comment by rashansmith** [comment]
Hello @a-mccarthy, I can take group 3!

**Comment by mbianchidev** [comment]
I'll gladly take group 4 :)

**Comment by hailkomputer** [comment]
And I can take the group 5

**Comment by a-mccarthy** [comment]
thanks all! I've updated the issue description with your chosen groups.  Lets try to reach out in slack by the end of next week, June 28th. Sound good?

**Comment by hailkomputer** [comment]
All of group 5 (Storage, Apps, Windows and UI SIGS) have been contacted over slack.

**Comment by mbianchidev** [comment]
Contacted group 4 just now! :)

**Comment by rashansmith** [comment]
Group 3 sigs have been contacted!

**Comment by a-mccarthy** [comment]
YAY! For now, we have reached out to all the SIGs 🎉  we will see how many responses we get, and then do a reminder post in early July.

Thanks everyone 🌟

**Comment by edithturn** [comment]
I also contacted group 2! No responses yet! :)

**Comment by mbianchidev** [comment]
Sent a reminder! 

Two sigs opted out:

**Multicluster** - Stephen Kitt
"Hi 
[@mbianchidev](https://kubernetes.slack.com/team/UU1JM5G5A)
, since we’re not synced to the main release cycle we don’t really have anything that makes sense as a 1.31-related change
:white_check_mark:
1"

**k8s-infra** - Davanum Srinivas

Another opted in:

**Auth** - Rita Zhang
"will add stuff to that discussion thread. thanks for the bump!"

The last one is not replying

CLI, but Maciej Szulik reacted with "ack" to my first message so I figure they will share, most probably the Kustomize thing going off kubectl?
