### ISSUE TITLE
Remove `status/*` labels

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#259]
Based on the conversation on https://github.com/kubernetes/sig-release/pull/239, the `status/*` labels have not proven to be useful. Additionally, with the disabling of `milestone-munger`, applying / maintaining these labels are now a manual task.

They should be removed.

rel: https://github.com/kubernetes/sig-release/pull/239

/sig release
/cc @tpepper

**Comment by spiffxp** [comment]
Related: there a number of release-specific labels I want to remove from all repos but k/k https://github.com/kubernetes/test-infra/pull/9091

FYI: label application isn't yet fully manual, the [`/status` command](https://prow.k8s.io/command-help#status) is handled by the `milestonestatus` prow plugin, [currently enabled for k/k](https://github.com/kubernetes/test-infra/blob/f7939d9aa5be3d6b8ad2c5eb8db92897d8fcf922/prow/plugins.yaml)

**Comment by justaugustus** [comment]
https://github.com/kubernetes/test-infra/pull/9091 and https://github.com/kubernetes/test-infra/pull/9610 have merged, so we can close this.
/close
