### ISSUE TITLE
Promote ci-crio-cgroupv1-node-e2e-conformance and ci-crio-cgroupv2-node-e2e-conformance node conformance jobs to release blocking

### ISSUE THREAD

**Issue by kannon92** [kubernetes/sig-release#2602]
#### What would you like to be added:

We would like to promote these crio conformance jobs to be blocking for the release. They were in informing and they are good indictators of serious issues in the release.

TestGrid: https://testgrid.k8s.io/sig-release-master-informing#ci-crio-cgroupv2-node-e2e-conformance

Job was added in 1.30.

Triage for cgroup v2 job: https://storage.googleapis.com/k8s-triage/index.html?date=2024-08-19&sig=node&job=ci-crio-cgroupv2-node-e2e-conformance

Triage for cgroup v1 job: https://storage.googleapis.com/k8s-triage/index.html?date=2024-08-19&sig=node&job=ci-crio-cgroupv1-node-e2e-conformance

**Comment by saschagrunert** [comment]
+1 from my side

Let's set a lazy consensus until Sept 18 (+4 weeks from now).

**Comment by saschagrunert** [comment]
Lazy consensus will be reached tomorrow.

**Comment by cpanato** [comment]
+1

**Comment by saschagrunert** [comment]
Get's closed by https://github.com/kubernetes/test-infra/pull/33117
