### ISSUE TITLE
Kubernetes v1.32 Release Highlights contact

### ISSUE THREAD

**Issue by mbianchidev** [kubernetes/sig-release#2640]
### Overview
The release comms team will use this issue to track the work on nudging SIGs for entries on release highlights for the v1.32 release cycle.

Release Highlights discussion for 1.32: #2526 Release Highlights deadline: **Tuesday 19th November 2024**.

Release Highlights are collected during each release cycle for every SIG to see what should be highlighted in the release blog, webinar, and other communications. Different SIGs have a different number of [tracked enhancements](https://github.com/orgs/kubernetes/projects/195). Some SIGs have activities that aren't quite coupled with Kubernetes releases, and it's worth checking with them in case there are things worth calling out in what they did between the previous release and the current release. One example is the Dockershim removal from 1.24 or Immutable Secrets and ConfigMaps from the 1.21 release, as well the cgroup v2 change in 1.31.

### What do I need to do?
1. Pick a group of SIGs to reach out to (listed below), and comment your selection on this issue
2. Reach out to the SIGs in slack to ask for Release Highlights feedback and directing them to the github discussion using the template below
3. Comment here when you've completed reaching out to the SIGs

Depending on the responses we get, we may need to send out a reminder in Slack later in the release cycle to each SIG to get more feedback on Release Highlights Themes.

### How do I find a SIG's slack channel?
The Slack channel for each SIG is usually #sig-, but accurate links are available in [k/community](https://github.com/kubernetes/community) under [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md). The plan is to ask for responses on the public Slack channel (non-disruptively).

### What should I say?
Following is a bootstrap template that you can use to reach out to the individual SIGs informing them about the discussion thread. This template includes the important information to convey to the SIG, but you are free to add your own personalization to the message if you'd like to.

Hello SIG [sig-name],

Release Highlights are an essential part of the Kubernetes release cycle as they provide a birds-eye view of improvements, breaking or user-facing changes that are coming as part of the upcoming release. The release Comms team is asking for your help gathering your Release Highlights for this release. If you have anything to call out, we would appreciate it if your SIG can submit the content in [Kubernetes 1.32 Release Highlights GitHub discussion](https://github.com/kubernetes/sig-release/discussions/2639).

Ideally, we would like this to be completed by **Tuesday 19th November 2024**.

Thank you!

### SIG groups
The following are groups of SIGs we need to reach out to. The SIGs are groups together in a mix of those that have tracked enhacements for this release and those that do not. Please comment below with the group you'd like to reach out to.

Group 1 @rashansmith 

* [x]   Node
* [x]   Cloud Provider
* [x]   Architecture
* [x]   Contributor

Group 2 @rytswd 

* [x]   Auth
* [x]   CLI
* [x]   K8s Infra
* [x]   Multicluster 

Group 3 @wrkode 

* [x]   API Machinery
* [x]   Scheduling
* [x]   Autoscaling
* [x]   Security
* [x]   Testing

Group 4 @mbianchidev 

* [x]   Network
* [x]   Instrumentation
* [x]   Cluster Lifecycle
* [x]   Docs (not necessary to reach out)
* [x]   Release (not necessary to reach out)

Group 5 @edithturn 

* [x]   Storage
* [x]   Apps
* [x]   Windows
* [x]   UI
* [x]   Scalability

We'll try to keep the list up-to-date, but please double-check in the comments if someone has contacted their channel. We can debate more details in Slack.

/milestone v1.32

xref: #2527

**Comment by rashansmith** [comment]
I'll take group 1!

**Comment by edithturn** [comment]
I can take group 5!!  :)

**Comment by rashansmith** [comment]
> I'll take group 1!

outreach is done!

**Comment by rytswd** [comment]
I can take group 2 if it isn't taken yet! 🫠 (But I'm open to take any of the groups TBH!)

**Comment by mbianchidev** [comment]
It's all taken, once every shadow applies for a group I'll take the remaining one!

**Comment by wrkode** [comment]
I can take Group 3

**Comment by rytswd** [comment]
I've done all my reach-outs, as per below:

SIG Auth: https://kubernetes.slack.com/archives/C0EN96KUY/p1729268043204719
SIG CLI: https://kubernetes.slack.com/archives/C2GL57FJ4/p1729268176802849
SIG K8s Infra: https://kubernetes.slack.com/archives/CCK68P2Q2/p1729268333281389
SIG Multicluster: https://kubernetes.slack.com/archives/C09R1PJR3/p1729268450185009

I will be updating #2639 once I hear any updates on any of them 👍

**Comment by wrkode** [comment]
I've completed all reach-outs for Group 3:

SIG API Machinery https://kubernetes.slack.com/archives/C0EG7JC6T/p1729395705977889
SIG Scheduling https://kubernetes.slack.com/archives/C09TP78DV/p1729395760440169
SIG Autoscaling https://kubernetes.slack.com/archives/C09R1LV8S/p1729395845110249
SIG Security https://kubernetes.slack.com/archives/C019LFTGNQ3/p1729395874993209
SIG Testing https://kubernetes.slack.com/archives/C09QZ4DQB/p1729395904480689

**Comment by mbianchidev** [comment]
Good job team on completing the outreach! 
Now we wait for the opt-in and keep [the discussion](https://github.com/kubernetes/sig-release/discussions/2639) updated :)

**Comment by mbianchidev** [comment]
Closing this as the 1.32 cycle is done.

Good job team!
