### ISSUE TITLE
Clean up Triage Party references

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#2660]
@Vyom-Yadav — can you create an issue to clean up Triage Party related things?

I'm not sure that we use it anymore, but I also want to make sure we don't leave any infra dangling if we don't.

_Originally posted by @justaugustus in https://github.com/kubernetes/sig-release/pull/2632#discussion_r1835747331_

**Comment by Vyom-Yadav** [comment]
I checked for usages on hound (https://cs.k8s.io/?q=triage.*party&i=fosho&files=&excludeFiles=&repos=).

Relevant PRs:

- https://github.com/kubernetes/community/pull/8197
- https://github.com/kubernetes/sig-release/pull/2670
- https://github.com/kubernetes/test-infra/pull/33878

For completeness of this issue, triage party for sig release was removed at https://github.com/kubernetes/k8s.io/commit/eb5b0bb4326edf78540f8a0f5ac7ff5217b9fdc0

**Comment by Vyom-Yadav** [comment]
/close 

All relevant PRs have been merged.

**Comment by justaugustus** [comment]
Thanks Vyom!
