### ISSUE TITLE
Expand on slush definition

### ISSUE THREAD

**Issue by pbarker** [kubernetes/sig-release#269]
In the 8/30 sig-arch meeting the question was raised on whether api adds could be merged in slush. The consensus was a firm no. This isn't reflected in the current docs and we should consider explicitly calling out types of changes that are restricted.

**Comment by justaugustus** [comment]
This is open for anyone who wants to write a quick blurb. @jdumars?
/help

**Comment by spiffxp** [comment]
/milestone v1.14

It's not clear to me whether code slush has served its intended purpose.  From what I can tell, it is meant to signal that we aren't accepting any major refactors, but is intended to allow for a higher velocity of code changes than code freeze.

Does it simplify things if we just get rid of it entirely?  If we keep it around, can we more tightly quantify what is and is not allowed in a way that we can verify the effectiveness of this added process?

**Comment by nikopen** [comment]
+1 on getting rid of code slush. In the current handbook iteration of bug-triage there's 'early release', 'pre-code-slush', 'code-slush', 'code-freeze' and 'burndown' - I'm in favor of fewer stages with clearer definitions while I'm cleaning up the handbook (https://github.com/kubernetes/sig-release/pull/430).

In its stead, there can be clearer timelines and boundaries on code freeze - freeze could happen a bit earlier, with a clearer signal, i.e. 'major features should be ideally finished around the first half of code freeze timeslot'.

**Comment by spiffxp** [comment]
Discussed at release team this morning.  The experience of previous release team members was that code slush was a useful "code freeze is coming" deadline.  For example, some SIGs would wait until code slush to decide whether or not a feature was going to land.  Most felt a blast across kubernetes-dev@/twitter/slack would be sufficient for this.

The actual mechanism of requiring additional labels and milestones seemed maybe not worth the hassle.  Code slush as a concrete phase maybe doesn't need to exist.
