### ISSUE TITLE
Release Signal Handbook - Fix timeline of release-x.y-blocking and release-x.y-informing dashboards

### ISSUE THREAD

**Issue by wendy-ha18** [kubernetes/sig-release#2701]
#### What happened:
The [Mid-Release Cycle](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/release-signal#mid-release-cycle) section in the Release Signal Handbook mentions that during weeks 6 to 9, the team needs to monitor the `release-x.y-blocking and release-x.y-informing dashboards daily`. However, these dashboards are not created until after the rc-0 branch is cut, which typically occurs around week 12 (two weeks after Code Freeze).

This misleading has been mentioned on [v1.31 retro](https://docs.google.com/document/d/1T684LzolwI4Dbh6kwJI23orzswqPT0l7v6rfE5L_ERE/edit?tab=t.0), we should address it before v1.33.

![image](https://github.com/user-attachments/assets/bec7f230-bf2e-4a5a-9a60-3c38f1adca53)

#### Suggest fix:
Update the Release Signal Handbook by removing references to the release-x.y-blocking and release-x.y-informing dashboards from the [Mid-Release Cycle](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/release-signal#mid-release-cycle) section. Instead, include this information in the [Code Freeze](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/release-signal#code-freeze) section, as these dashboards are created after the rc-0 branch is cut (normally around week 12).

/kind documentation
/priority important-soon

**Comment by Vyom-Yadav** [comment]
Good catch Wendy (https://github.com/kubernetes/sig-release/commit/8d691aebb07c44bf7d7fc15c223a678d7b6c18ef missed this section). Can we close this issue now?
