### ISSUE TITLE
Clean up old release OWNERS

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#281]
As we move into new release cycles, we should also seek to update OWNERS across the repo to only include release team lead roles from the past, say, N - 3 or N - 4 cycles.

There should also be instructions about this written in the Release Team Lead handbook.

/sig release
/good-first-issue
cc: @calebamiles @idvoretskyi

**Comment by idvoretskyi** [comment]
@justaugustus makes sense, +1!

**Comment by justaugustus** [comment]
Fixed in #341.
/remove help
/assign
