### ISSUE TITLE
Add Kendrick Coleman to kubernetes-milestone-maintainers

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#283]
It was noted in https://github.com/kubernetes/features/issues/367#issuecomment-419488048 that @kacole2 doesn't have milestone maintainer access and I'd like to grant that to him now.

/sig release
/assign @tpepper

**Comment by justaugustus** [comment]
Although, I now realize that he's not part of the Kubernetes GH org. We'll get that fixed!
@kacole2, can you file for [membership](https://git.k8s.io/community/community-membership.md), cc me on that request and then come back here and let us know when that's complete?

**Comment by justaugustus** [comment]
Kendrick has been added to the Kubernetes org: https://github.com/kubernetes/org/issues/75

**Comment by kacole2** [comment]
So that means I can to those dog and cat images on issues now?

**Comment by tpepper** [comment]
added

**Comment by justaugustus** [comment]
Thanks @tpepper!
/meow
