### ISSUE TITLE
Address markdown format symbols in PR release note block?

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/sig-release#29]
Some PRs' release notes have markdown format symbols (e.g., `-`, `*`), this leads to bad format in the CHANGELOG (see [1.9 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md)). 

https://github.com/kubernetes/kubernetes/pull/54175
https://github.com/kubernetes/kubernetes/pull/52792
https://github.com/kubernetes/kubernetes/pull/53043

We may not avoid PR authors to use such symbols, so should we address this case in the release note tool? @roycaihw

/cc @enisoc @david-mcmahon @Bradamant3

**Comment by roycaihw** [comment]
PR authors use symbols like `-` and `*` for multi-line release notes (kubernetes/kubernetes#54443). It's not clear how are we going to deal with them in current CHANGELOG. 
And some release note with unintended newlines (`\r\n`) can also leads to bad formatting (kubernetes/kubernetes#54177)

These might become worse after we introduce the hierarchical release note(kubernetes/release#435) which uses indention to format the release note. 

One possible solution is to squash release note into one line, by removing `\r\n` and leading `-`/`*` in each line.

**Comment by xiangpengzhao** [comment]
It'd be better to take care of this case. Otherwise we should send PR to fix the format in CHANGELOG manually.
