### ISSUE TITLE
Create release-1.9 branch

### ISSUE THREAD

**Issue by enisoc** [kubernetes/sig-release#30]
According to the [timeline](https://github.com/kubernetes/features/blob/master/release-1.9/release-1.9.md#timeline), we should create the `release-1.9` branch and start setting up test infra on Thu Nov 16.

@dashpole You can create the branch with `anago`, and then we'll need you to run `branchff` every day to keep it up to date. Let me or @david-mcmahon know if you have any questions.

@BenTheElder Do you have access to any instructions from previous release test-infra leads on what needs to be set up?

**Comment by BenTheElder** [comment]
I have a pretty good idea what we did last go round, discussing with
@krzyzazy today what makes sense for this time.

**Comment by david-mcmahon** [comment]
I don't believe `--stage` will work with branching.  It should be relatively easy to add this, but it's not yet supported.  Do take advantage of the new workflow and re-entrancy functionality and do test it out with a mock run first.  Please file issues if you encounter any bumps.

**Comment by david-mcmahon** [comment]
I take that back. `--stage` works fine.  Give it a try.

**Comment by BenTheElder** [comment]
Test-Infra progress is being tracked here: https://github.com/kubernetes/test-infra/issues/5558#issuecomment-345341709

Most of the important jobs have been running and the sig-release dashboards are up but not every job we'd like is done and more jobs should be added to the blocking dashboard as well as dashboards for other sigs.

I'll have the rest of the setup reviewed and in Monday.

**Comment by BenTheElder** [comment]
Federation jobs are pending sig-multicluster discussing how to handle them at their meeting, GPU jobs are out for review, all other jobs should be already up and running though not all of them are green yet. 

The last PR after that I am sending out is to move more jobs into the release-1.9-blocking dashboard that are already in the release-1.9-all dashboard. I will get @spiffxp and @krzyzacy to review the state of testgrid after that to see if there's anything else.

**Comment by BenTheElder** [comment]
Minus the federation jobs I think we actually finished yesterday with the addition of the GPU jobs.

I'm looking into test-go and verify though which appear to be broken on the infra side.

**Comment by BenTheElder** [comment]
We discussed this in the meeting today, I think we can mark this done.
