### ISSUE TITLE
process docu: release team Bug Triage Lead

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/sig-release#309]
Bug triage has been super active and under went quite a bit of revamp in 1.12 cycle, mainly due to killing munger and retiring a few labels. opening this tracking bug to ensure all the changes are captured as part of the [Bug triage lead handbook](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/bug-triage/README.md) in time for 1.13 cycle. @guineveresaenger I know you have been on top of keeping the doc updated. If there are no more pending updates feel free to close this issue.

/assign @guineveresaenger 
/cc @tpepper @nikopen 
/sig release
/milestone v1.13

**Comment by AishSundar** [comment]
Thanks @guineveresaenger. I see that [/kind is a required label](https://github.com/kubernetes/community/blob/master/contributors/devel/release.md#tldr) throughout the release cycle. so I am curious what are folks assigning kind to if the PR is not for a feature? are you seeing other values like "failing-test", "flaky-test" etc?

**Comment by guineveresaenger** [comment]
@AishSundar I see kind/cleanup, kind/api-change, also king/bug but also a lot of `needs-kind` which is because folks are not sure if a "bugfix" should be labeled as "kind/bug" so it makes it harder to discover.

**Comment by guineveresaenger** [comment]
Basically, I'd suggest 2 things:

1. add notes to bug triage handbook to mark bug fixes as `kind-bug` early on; I can make a PR to that effect

2. some kind of education across sigs (in pr template? what does that look like? is there a PR template?) to put in kind/bug

**Comment by AishSundar** [comment]
Thanks @guineveresaenger, we should definitely do #1. Also probably link to https://github.com/kubernetes/community/blob/master/contributors/devel/release.md#issue-kind-label

For #2, here's the [PR template](https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md) if you want to update it with some useful label etiquettes. 

As discussed offline in slack, please also add the process to ping RT lead to be added to milestone maintainer privileges.

**Comment by guineveresaenger** [comment]
@AishSundar - opened a PR for the pull request template. ^^

**Comment by guineveresaenger** [comment]
@AishSundar - this can be closed as both tasks are (finally!) done. :)

**Comment by AishSundar** [comment]
Thanks a lot for keeping at this @guineveresaenger. @nikopen as FYI.

/close
