### ISSUE TITLE
[1.9] Code Slush

### ISSUE THREAD

**Issue by enisoc** [kubernetes/sig-release#31]
According to the [timeline](https://github.com/kubernetes/features/blob/master/release-1.9/release-1.9.md#timeline), we should start Code Slush on Mon, Nov 20 (after 3pm PST).

As far as I know, this involves the following:

* Update [submit queue config](https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml) to set `do-not-merge-milestones` and `additional-required-labels`.
  * Block empty milestone, as well as all milestones > v1.9.
  * Require `status/approved-for-milestone` label.
* Update [milestone bot config](https://github.com/kubernetes/test-infra/blob/master/mungegithub/misc-mungers/deployment/kubernetes/configmap.yaml) to set `milestone-modes` and `milestone-freeze-date`.
  * Set mode for `v1.9` to `slush`.
  * Set freeze date to `Wed, Nov 22`.

@marun Does that look right to you?

cc @jberkus

**Comment by marun** [comment]
lgtm

**Comment by enisoc** [comment]
Code slush is now in effect.
