### ISSUE TITLE
Add information about what qualifies for a milestone

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#320]
/sig release
/help

rel: https://github.com/kubernetes/community/pull/2408

**Comment by justaugustus** [comment]
Anyone interested in doc-ing this?

**Comment by tpepper** [comment]
I've added some words via a PR in the community repo https://github.com/kubernetes/community/pull/4081 regarding how we review cherry-pick PRs for inclusion on a milestone's release-X.Y branch.

**Comment by alejandrox1** [comment]
@onlydole may be useful to chat with bug triage people. would be useful to sync whatever info we end up adding here with the bug triage handbook

**Comment by onlydole** [comment]
@smourapina - could I sync with you and the team this week on this issue?

**Comment by smourapina** [comment]
Sure @onlydole, let's do that!

**Comment by markyjackson-taulia** [comment]
I sent over the initial draft to @onlydole of items from a bug-triage perspective

**Comment by markyjackson-taulia** [comment]
cc @onlydole 
Per v1.18 release meeting adding the google doc here:
https://docs.google.com/document/d/1vEycLfyNDO95O6qIx1bsYaQWYCHYFgAOK6DNdBy_aPM/edit

**Comment by onlydole** [comment]
Talking more with @tpepper, we need to focus on two primary paths:

1. Release team side of things (or triage or CI signal, review/approver/OWNER, etc): put guidance in the role handbooks so they can operationalize what’s expected of their role

2. PR / cherry pick submitter: put guidance in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md so they know what’s expected of them for their change to merge

I'll update this PR with changes more in-line with those two focuses

**Comment by LappleApple** [comment]
Hey @onlydole, are you still actively working on this?

**Comment by onlydole** [comment]
Howdy, @LappleApple! I was on a holding pattern for this, and I don't think there's a clear way forward on this issue. I'd like to bring it up on the next release team meeting as a topic to see how we could close this out! 

/remove-lifecycle stale

**Comment by LappleApple** [comment]
Awesome, @onlydole! Go ahead and add to the meeting agenda as your time and schedule allow :)
