### ISSUE TITLE
Enforce requiring milestone on k/k for merge

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#321]
/sig release
/help

rel: kubernetes/community#2408

**Comment by spiffxp** [comment]
As discussed during release 1.13 meeting and retro, this seems like it's undue friction to impose early in the release cycle.

ref: https://github.com/kubernetes/sig-release/issues/243#issuecomment-409391292 for a summary of the discussion we had around this in July

**Comment by justaugustus** [comment]
To add more context...
While we did mention the idea during the 1.12 retro, we did not have the time to dive in. The referenced issue above also does not make any determination on this.

I do believe requiring milestone for all merges would create some additional friction, but I don't think that that friction is undue. Overall, I feel it would serve to relieve some of the triage burden for the release team.

I've added this as an agenda item for the 11/6 SIG Release meeting.
/cc @calebamiles @jdumars @tpepper

**Comment by tpepper** [comment]
Discussed in Nov. 20 SIG Release meeting:  no solid recollections of justifications for going back to this.  Nobody's clamoring for it.  If something were to be implemented, all felt it must be more automated, and that would be in support of easier GitHub-based discovery of PRs in a given milestone.

**Comment by nikopen** [comment]
+1 - enforcing it can be a burden, but instead the bot can automatically apply the milestone to anything that merges against the upcoming release. This way anyone can use the github UI / search queries to easily see what went in.

**Comment by justaugustus** [comment]
I caught up on yesterday's [SIG Release meeting](https://youtu.be/jmJOczWHFik).
For context, I opened this because we kind of sped through this on the 1.12 Retro and I wanted to make sure we had a firm decision around whether this was of value.

Given the discussion on the call, I'm satisfied and happy to close this now. :)
/close
