### ISSUE TITLE
Security Team Google Groups refactor

### ISSUE THREAD

**Issue by philips** [kubernetes/sig-release#326]
The PST needs some refactor of communication channels to help manage everything going on. 

## Membership Management
**Legacy group confusion**
Problem: kubernetes-security@googlegroup and security@kubernetes exist for legacy reasons and is confusing when adding folks

Delete kubernetes-security@googlegroups.com, prefer security@kubernetes.io going forward

- [x] Update docs https://github.com/kubernetes/sig-release/pull/328 and https://github.com/kubernetes/website/pull/10516
- [x] Send deprecation notice for October 31st
- [x] Unsubscribe everyone and turn off posting DO NOT DELETE

**Delegate release manager subscription management**

Problem: every 3 months new release managers come on board. We missed adding the 1.12 release managers until a few weeks ago for example :(
Solution: Delegate responsibility to update this to the previous release managers.

Actions:
- [x] Create security-release-team@kubernetes.io with the current active release managers
- [x] Give ownership of this group to release managers to self-govern as release managers change
- [x] Subscribe security-release-team@ to security@kubernetes.io 
- [x] Remove non PST members from direct subscription to security@kubernetes.io

NOTE: this can’t be done on googlegroups.com because of the no nesting rules on the non-Gsuite groups

**Move kubernetes-distributors-announce to kubernetes.io**

Problem: manual maintenance of PST and release manager subscriptions on that list :( :( :( 

- [x] Create distributors-annouce@kubernetes.io
- [x] Migrate membership
- [x] Announce deprecation notice for October 31st
- [x] Shut off posting to kubernetes-distributors-announce@googlegroups.com

## Introduce Public and Private Discussion Lists
Problem: meta discussion about the security processes happen on the security@kubernetes.io list making it difficult to triage issues
Solution: create public and private meta discussion lists

Actions:
- [x] Create kubernetes-security-discuss@googlegroups.com which anyone can subscribe to and subscribe the current set of folks
- [x] Create security-discuss-private@kubernetes.io for private non disclosure discussion (PST membership additions, review of proposals like distributor subscription requests, etc)

**Comment by philips** [comment]
The PST has already discussed these changes in a Google doc. Putting it here for visibility of the @kubernetes/steering-committee as I need to make the changes on kubernetes.io Google Groups.

**Comment by philips** [comment]
The only thing remaining on this is the shutdown of the old lists.

**Comment by justaugustus** [comment]
@philips -- I believe this is still active, right?
/remove-lifecycle stale

**Comment by philips** [comment]
this is done.
