### ISSUE TITLE
Make kind, sig labels auto-copy to PRs

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#33]
Due to the changes from PR milestone automation (#26), we now have a hard requirement that kind, sig and priority labels need to be populated for PRs.  I propose that we add to our automation to make that easy, specifically:

If a PR is linked to an issue, and the PR has no kind, sig, or priority labels, the kind, sig and priority labels from the linked issue should be copied to the PR automatically.

Obstacle: Github's notion of a PR being linked to an issue is rather loose; basically, if the PR is mentioned at all in the issue.  This could lead to PRs being tagged that are only mentioned tangentally.  Is there a useful way around this?

**Comment by enisoc** [comment]
I'd be in favor of an explicit command to set the associated issue, like:

/issue #33

**Comment by jberkus** [comment]
Closing this because I don't see any reasonable way to accomplish it, unless the SIGs adopt some kind of tagging format.
