### ISSUE TITLE
Proposal: selection process for Shadows

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#368]
**The Problem:**

RT Section Lead/Shadow is a mentorship relationship, but we have not been treating it as one.  Instead of having a process to select the most suitable mentees for a given cycle, we simply accept anyone who volunteers before a certain deadline, up to four shadows per lead.  This has resulted in leads having too many shadows for them to manage, and shadows not being mentored for the role they are shadowing.  Further, we have contributors volunteering to shadow without any clear idea of what they're committing to or what the requirements and expectations are.

**The Proposal:**

We should have a semi-formal selection process, which should work as follows:

1. shadow applicant applies for their shadow position using a specific questionnaire for the shadow role.  A draft template for these questionnaires follows.
2. the section lead and the RT Lead (or shadow) review the questionnaires and pick the candidates with the necessary time availability and other requirements for the role.
3. the section lead and the RT Lead have a brief chat with each qualified candidate (by slack, video, or other convenient mechanism) to select for mentorship match.
4. The section lead and RT lead pick the final Shadows for that RT.

As a prerequisite to this, it would also be good to establish guidelines on how many shadows are the maximum practical for a given role.  For example, CI signal can't really make use of more than 2 shadows, but Docs is capable of keeping up to 4 shadows busy.

This also begs the question of whether we should have a process for selecting section leads.  To date, one hasn't seemed necessary because, unlike shadows, we have a shortage rather than a surplus of volunteers, and generally all section leads are well-known from prior release teams.

## draft template for shadow questionnaire

You have asked to be a _role_ Shadow for the _ver_ Release Team. This questionnaire is to determine how well you match the position's requirements, and to give you an idea what's involved.  In cases where there are too many applicants for a particular role, it may also be used to decide who is selected this release cycle.  Please note that you are expected to be inexperienced in some areas, as Shadow is a mentored role.

1. The _role_ handbook [link] defines the tasks and responsibilities of the role for this release cycle.  Are you prepared to assist in fulfilling these duties?  Please read the full handbook before answering.
 
2. _role_ Shadow requires a substantial time commitment, especially
during _busy_period_ (_dates_). This can be more than _time requirement_, and may include attending video meetings at inconvenient times.  Is this time you can commit to?

*Example: Issues/PR Triage requires a substantial time commitment, especially during the 2nd half of the release cycle (Nov. 5 to Dec. 5). This can be more than an hour a day, and may include attending video meetings at inconvenient times. Is this time you can commit to?*

(optional)
2.a. _role_ Shadow also requires _additional requirement_.  Is this something you are comfortable with?

*Example: Release Notes Shadow also requires editing and rewriting release notes, in English, to make them clearer and more accurate.  Is this something you are comfortable with?*

3. Do you have any schedule conflicts during this release cycle (_dates_), such as vacations, school, or intense periods of work, that would make you unavailable for more than a couple of workdays?

4. The purpose of shadowing is to train new Release Team members.
Assuming that your job or life situations don't change between now and
then, are you willing to volunteer for the _role_ Lead for _ver+1_ or
_ver+2_?  This usually requires support from your employer, as you will
probably need to do release work during work hours.

5. What's your current experience and involvement with _related_SIG_if_any_ and _area_of_expertise_?

*Example: What's your current experience and involvement with SIG-Testing, and automated tests in general?*

6. Are you already a Kubernetes Org member?

7. Have you applied to, or served on, a prior release team?  Please give details.

8. What time zone are you usually in?

9. Any comments on what interested you in this role and the release team?

**Comment by jberkus** [comment]
/kind design
/priority important-soon

cc
@tpepper @justaugustus @calebamiles @spiffxp

**Comment by justaugustus** [comment]
I'll take a swing at a PR for this.
/assign

**Comment by justaugustus** [comment]
(For the record, I'm +1 for this!)

**Comment by justaugustus** [comment]
Spoke with @idvoretskyi and we'll plan to generate a Survey monkey survey for the questionnaire. I was originally thinking Google Forms, but the SurveyMonkey route will be more inclusive.

Won't be able to tackle this until after Thanksgiving though. This week is ruff.
/woof

**Comment by mbohlool** [comment]
> +1 for considering time zone in selection, and for cross-timezone backups, especially for patch release manager selection, since coordinated security releases can often fall outside working hours

Patch release duties are mostly independent of the branch and can be done by any patch release manager. I suggest we have a patch release team instead of individual managers. Each member can still be responsible for one release but all of the team would be in sync with everything on all active releases and every member of the team will also have the ability to do the release. In the case of security releases, one team member can take care of all releases (as the jobs can be run in parallel and it is mostly busy work). If the release toke longer than working day of that person, it can be transferred to another member of the team in an appropriate timezone.

**Comment by spiffxp** [comment]
@jberkus I would like for us to have shadow selection more or less wrapped up by the end of next week (Friday, Jan 11th).  Where do we stand on using this?

**Comment by justaugustus** [comment]
@spiffxp -- ball is in my court on the questionnaire. Will be out well ahead of end of next week.

**Comment by justaugustus** [comment]
@spiffxp -- draft shadow questionnaire is ready for review here: https://github.com/kubernetes/sig-release/pull/433
