### ISSUE TITLE
Define roles and processes for Patch Release Management Team

### ISSUE THREAD

**Issue by nikhita** [kubernetes/sig-release#369]
The release team is moving from the role of a Patch Release Manager to a Patch Release Management _Team_: https://github.com/kubernetes/sig-release/tree/master/release-team#kubernetes-release-team-roles.

The [current handbook](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/patch-release-manager/README.md) defines processes and suggestions for a patch release manager.

We need to now define processes for the Patch Release Management Team instead. This can include (but not limited to) how many roles this team should have, what responsibilities these roles would entail, etc.

It is important to do this soon, given that we would starting the selection process for the 1.14 release team (https://github.com/kubernetes/sig-release/issues/368).

/assign @justaugustus @tpepper @aleksandra-malinowska

**Comment by nikhita** [comment]
/kind design
/priority important-soon

cc @spiffxp @jberkus @calebamiles

**Comment by justaugustus** [comment]
As an aside the Patch Release Team and Branch Manager roles in the Release Team will become extensions of the to-be-formed Release Engineering subproject within SIG Release.

**Comment by yue9944882** [comment]
how about linking this document to patch team introduction too? highlighting that patch releases are meant for fixing production-impacting bugs 

[https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#patch-releases](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#patch-releases)

**Comment by ttousai** [comment]
To summarize #408. Patch release manager should be renamed patch release management team for  1.14.

cc @spiffxp @tpepper @aleksandra-malinowska

**Comment by tpepper** [comment]
We need to make it explicit what is the holiday coverage plan.  Traditionally the project slows down dramatically during major holidays.  Folks should know they can continue to trust in patch managers being appropriately reachable during these periods, especially the security team in the event of needing handling on critical vulnerabilities.  This hasn't been a problem generally, but coverage expectations should be made more clear.

**Comment by tpepper** [comment]
It's my intention to finish 1.14 with this well defined and with it better defined move forward spreading it into a team effort, so perfect to add to milestone.

**Comment by aleksandra-malinowska** [comment]
@justaugustus is the discussion going on somewhere about Release Engineering subproject? If so, does it make this issue obsolete?

**Comment by justaugustus** [comment]
@aleksandra-malinowska -- It's on the backlog, but we haven't actively started discussing it. I was planning on using what you and Tim draft as part of the basis for that conversation.

**Comment by aleksandra-malinowska** [comment]
Thanks. It sounds like we may be out of sync then. To be honest, I'm not sure if whatever is drafted based on the assumption that there'd be a PRM team will be useful if we're extrapolating it to other roles. For example, it may be a feasible option to have one patch release team manage all supported minor releases, but if we want to merge this role with branch manager, would there have to be a team per release? What are the constraints?

**Comment by nikhita** [comment]
@aleksandra-malinowska I think that's a great gist of the main concerns right now. :+1: 

> single point of failure/bottleneck per branch.

One more point slightly related to this - lack of shadows for patch release managers. This means we end up with lots of tribal knowledge. Having leads + shadows like other roles would be nice IMO.

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/sig-release/pull/553 for v1.14

**Comment by idealhack** [comment]
FYI we have a new PR addressing this issue https://github.com/kubernetes/sig-release/pull/782#issuecomment-530584333

**Comment by justaugustus** [comment]
Closed via https://github.com/kubernetes/sig-release/issues/369.
/close
