### ISSUE TITLE
Separate binary publishing from latest release marker file update

### ISSUE THREAD

**Issue by liggitt** [kubernetes/sig-release#390]
Currently, the release process looks roughly like this:
1. tag source
2. build binaries
3. push binaries and update marker files (e.g. https://dl.k8s.io/release/stable-1.12.txt)
4. build and push rpm/deb packages
5. send release notification

Should we avoid incrementing the marker files until after the build artifacts are pushed out, so the process looks more like this:

1. tag source
2. build binaries
3. push binaries
4. build and push rpm/deb packages
5. update marker files (e.g. https://dl.k8s.io/release/stable-1.12.txt)
6. send release notification

cc @MaciekPytel

**Comment by justaugustus** [comment]
/remove-help
/assign
/kind cleanup
ref: https://github.com/kubernetes/sig-release/issues/759
