### ISSUE TITLE
Missing step in release notes playbook: external dependencies

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#400]
We missed updating the list of external dependencies for the release notes until the day of cutting release for v1.13.0.  We likely are missing a step in the release notes playbook to do this explicitly.

What we did today was copy the old list and as humans look at the versions of everything listed today.  What we would like is a more formal specification or manifest TBD by cluster lifecycle.

External dependencies can likely be broken into:
- node-level dependencies
- cluster-level dependencies
- addons

/cc @AishSundar @marpaia @liggitt @neolit123 
Correct me if this isn't what/how we did it today

/cc @timothysc @justinsb 
FYI, this would be the manual workaround we'd be using until such time as we have a more formal artifact to consume

/sig release
/sig cluster-lifecycle
/priority important-soon
/kind cleanup

**Comment by AishSundar** [comment]
@marpaia until we have a more formal and automated way to generating these, can you update the release notes lead handbook to capture this step and also list the manual workaround we followed.

**Comment by marpaia** [comment]
@AishSundar for sure, will do.

**Comment by timothysc** [comment]
@spiffxp I was looking through that list, and it's well beyond the scope of sig-cluster-lifecycle and treads pretty deeply into sig-apps as well.

**Comment by timothysc** [comment]
/assign @timothysc 

I'll try to help make this easier for the bits that we manage.

**Comment by spiffxp** [comment]
/assign @neolit123 
Since you had mentioned maybe working on this in #sig-release.  Please /unassign if you're not

**Comment by spiffxp** [comment]
/assign @dstrebel @jeefy @onyiny-ang 
to make sure this is on release-notes radar

**Comment by spiffxp** [comment]
/close
I believe this was addressed by https://github.com/kubernetes/sig-release/pull/485
