### ISSUE TITLE
Non-US TZ-friendly SIG meeting time

### ISSUE THREAD

**Issue by CsatariGergely** [kubernetes/sig-release#411]
Please organize a SIG meeting time more friendly for Europe.

**Comment by idealhack** [comment]
+1 to this

btw add a slack ref related: https://kubernetes.slack.com/archives/C2C40FMNF/p1542764004499700

**Comment by justaugustus** [comment]
Yep, for 2019, we'll release a Doodle to see if there's a better time we can be holding these at or if we can instead have alternating meeting times.

Just as a heads-up, a decent portion of SIG Release members are located on Pacific time, but we'll do our best to try and accommodate! :)

/assign

**Comment by marpaia** [comment]
Just to update from today's Release Team meeting, once shadows are selected, we will send a doodle out like @justaugustus said and try to find a meeting time that works for as many people as possible. There are a few role leads in Europe this release as well, so once the contact sheet is filled out we should be able to see if we can maybe make an additional meeting that is as friendly as possible for European timezones.

**Comment by idealhack** [comment]
@marpaia Thanks for the updates! I thought you are referring to the release team meeting? while this issue was for the SIG meetings?

**Comment by marpaia** [comment]
Oh yeah, nice catch @idealhack. I am in-fact talking about the 1.14 release team meetings.

**Comment by justaugustus** [comment]
Apologies for not taking care of this. 
I think we would need someone in a European timezone/timezone-adjacent to facilitate this.
I'm maxed out on meetings and both Tim and Caleb are on PT.

Is anyone interested in coordinating this?
/help

/priority important-longterm
/milestone v1.15

**Comment by justaugustus** [comment]
Doodle poll up for meeting times: https://doodle.com/poll/z5i65er4hymr3s4h

/remove-help
/priority important-soon
/remove-priority important-longterm
/kind feature

**Comment by justaugustus** [comment]
Notice sent to MLs: https://groups.google.com/d/topic/kubernetes-sig-release/jw2UV-fKjEY/discussion

**Comment by tpepper** [comment]
/close
We are now meeting 8am Pacific Mondays for SIG Release and Release Engineering (alternating weeks).
