### ISSUE TITLE
Proposal: v1.13 patch release schedule

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#427]
/assign @tpepper @aleksandra-malinowska 
/kind documentation

I'd like to propose that the v1.13 patch release team lay out a schedule for patch releases.  I have often seen requests for "when is the X patch release getting cut" in many slack channels.  I suspect having this information ahead of time would save some angst.

**Comment by aleksandra-malinowska** [comment]
Sounds good. Where should we put it?

**Comment by tpepper** [comment]
We've got separate folders per release in sig-release repo, and the release team members are listed there.  I think as we shift toward a sustaining team of sorts, it would be good to give that its own unique landing page.  The individual release team markdown docs could link to that one page.

This would make it more discoverable for folks wanting to know what are current releases, current supported branches, when to expect next releases, and how to get code into a next release.  A portion of that is covered in https://github.com/kubernetes/community/blob/master/contributors/devel/release.md but again that's not a place folks are going to immediately see.

**Comment by justaugustus** [comment]
@tpepper @aleksandra-malinowska -- are we in a good place to close this out?

**Comment by justaugustus** [comment]
Closing this as the patch release schedule now exists: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md
/close
