### ISSUE TITLE
Migrate the release-1.x dirs out of kubernetes/features to here

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#43]
It's been confusing to have to bounce between multiple repos to get details about the release and the release team.

If we can't outright remove the files in kubernetes/features we should at least tombstone them as links to copies that exist here.

No explicit due date or priority on this, it's a thing I'm interested in but I'd be just as happy if someone other than me got this done.

**Comment by idvoretskyi** [comment]
LGTM.

I can work on this before 1.10 release cycle will start.

**Comment by enisoc** [comment]
SGTM. Note that we'll need to coordinate changing any paths that the tooling looks at (e.g. `release-notes-draft.md`).

cc @david-mcmahon

**Comment by idvoretskyi** [comment]
Did it https://github.com/kubernetes/sig-release/pull/46, it can be closed.
