### ISSUE TITLE
Identify and assign release-blocking job owners

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#441]
First part of #347 

We'd like to ensure there are testgrid alerts setup for all jobs on the release-master-blocking dashboard (and release-master-upgrade).  Those alerts should preferably go to a publicly accessible google group, staffed by a SIG.

Would be nice if the jobs had the owner in their description, as well as what they do.

For the tricky cases like upgrades-that-sig-cluster-lifecycle-refuses-to-own-and-only-a-few-google-people-but-usually-that-just-means-one-overburdened-person we can either make google groups, or add the individuals (testgrid supports multiple e-mail addresses IIRC?)

/assign @BenTheElder @mariantalla 
Would like CI Signal to push this with Release lead shadow.

/milestone v1.14
/kind documentation
/sig release
/sig testing

**Comment by BenTheElder** [comment]
I wish I could favourite issues :-)

TestGrid does support multiple addresses.

**Comment by spiffxp** [comment]
I've opened https://github.com/kubernetes/test-infra/pull/10870 to get my guesses out for review

**Comment by spiffxp** [comment]
I'm working this in https://github.com/kubernetes/test-infra/pull/10870

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-release-master-blocking now has an "OWNER: sig-foo (subproject)" in its description for every job, and a description of what each job does.

sig-scalability owns:
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

sig-release release-engineering owns:
- https://testgrid.k8s.io/sig-release-master-blocking#build-master

sig-release release-team owns:
- https://testgrid.k8s.io/sig-release-master-blocking#integration-master
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-slow
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features

sig-testing owns
- https://testgrid.k8s.io/sig-release-master-blocking#bazel-build-master
- https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master
- https://testgrid.k8s.io/sig-release-master-blocking#verify-master

sig-network owns:
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-ingress

sig-node owns:
- https://testgrid.k8s.io/sig-release-master-blocking#node-kubelet-master

sig-scheduling owns:
- https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

The next step is to send alerts to a publicly accessible google group staffed by members of the sig / subproject who will be responsive.

**Comment by spiffxp** [comment]
[I created kuberentes-sig-testing-alerts@](https://github.com/kubernetes/test-infra/issues/7814) for sig-testing's use

I'd like to propose doing the same for any of the above SIGs that don't already have a google group dedicated to receiving alerts from testgrid.  I would add the existing sig chairs / tech leads as Owners, and they would then add in whatever staff they deem necessary to stay on top of failures.

Alternatively, a sig can opt to use their existing discussion group for this purpose (sig-cluster-lifecycle does this today)

**Comment by spiffxp** [comment]
Sent an `[ACTION REQUIRED]` e-mail to the SIGs listed above.  If I hear no response from them before May 14th, I will be using their discussion list as the alert email address

**Comment by spiffxp** [comment]
Discussed with #sig-release, consensus from two SIG chairs (@tpepper @justaugustus) and current release lead (@claurence) is to use the kuberentes-release-team@ address for their alerts

**Comment by bsalamat** [comment]
> sig-scheduling owns:
  https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

I don't think SIG scheduling own those tests. I don't know who the owner is though.

**Comment by spiffxp** [comment]
@bsalamat The only test case involved has SIG scheduling's name in it "[sig-scheduling] [Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests"

Summarizing discussion offline:
- This exact job ci-kubernetes-e2e-gce-device-plugin-gpu also lives in https://testgrid.k8s.io/wg-resource-management with an alert address setup
- WG's cannot own code, SIG's can.  So ultimately it needs to fall to one of the SIGs in the WG.
- For now, I'm going to use the same address used by https://testgrid.k8s.io/wg-resource-management and have a separate discussion of whether this should still be considered a release-blocking job

**Comment by bowei** [comment]
this (e-mail address) can be changed later?

**Comment by spiffxp** [comment]
@bowei yes email address can be changed later, but we will no longer allow jobs to be release blocking without an associated email address... if you decide you don't want to own the job, and cannot find an owner, the job can no longer be release blocking

**Comment by spiffxp** [comment]
@bowei sig-network already appears to have https://groups.google.com/forum/#!forum/kubernetes-sig-network-test-failures alerted to be other jobs, I can use that

**Comment by spiffxp** [comment]
Remaining sigs/jobs:

sig-scalability owns:
- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

sig-node owns:
- https://testgrid.k8s.io/sig-release-master-blocking#node-kubelet-master

**Comment by spiffxp** [comment]
For sig scalability, will be using kubernetes-sig-scale@: https://groups.google.com/d/msg/kubernetes-sig-scale/IKtP9Ed3jvs/S7ZgpP38AAAJ

**Comment by spiffxp** [comment]
For sig-node, will be using kubernetes-sig-node@: https://groups.google.com/d/msg/kubernetes-sig-node/TxqAtFjLkuw/vb39Hn1xAgAJ

**Comment by justaugustus** [comment]
@spiffxp -- looks like we're all set with this one? Can we close it?

**Comment by spiffxp** [comment]
/close
Yeah, this has been in place for a bit
