### ISSUE TITLE
Don't use priority/critical-urgent as a gating label during code freeze

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#456]
Followup from https://bit.ly/k8s113-retro

Previous release leads and patch release managers have found that there's not a lot of clear documentation or well understood "case law" to facilitate decisions on whether a given change justifies the risk of letting it land.  We use `priority/critical-urgent` which has a description, but in reality different people seem to interpret the label in different ways, and each decision comes down to a negotiated one-off.

Perhaps its use is vestigial.  We used it as an additional piece of friction to differentiate from Code Slush, where being in the milestone was good enough.  Humans really like using priority labels during the burndown to do a quick bucket/sort of PR's remaining.  But is there value in having the bots pay attention to the same label?

I propose we find out by dropping the requirement, with the right to arbitrarily bring the requirement back in if we find that Code Freeze is not accomplishing the goal of making the release more stable.

/assign @amwat 
test-infra will need a playbook update

/assign @nikopen 
I suspect bug triage will need a playbook update

https://github.com/kubernetes/community/blob/master/contributors/devel/release.md will need an update

/milestone v1.14
Let's get this done this release cycle prior to code freeze

**Comment by nikopen** [comment]
Great retro outcome!! This will ease the burden of issue management.

I've updated the triage handbook accordingly.

**Comment by spiffxp** [comment]
I think once https://github.com/kubernetes/community/pull/3463 merges we can call this done

**Comment by nikopen** [comment]
Merged / done 

/close
