### ISSUE TITLE
Try splitting release schedule out of release-lead playbook

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#457]
There is an extraordinary amount of week-by-week detail in the release-team-lead playbook.  I would like to see if we can split that out into a suggested template schedule.  I'm not sure if week-by-week makes sense, maybe something that breaks up into phases.

There is some amount of overlap with https://github.com/kubernetes/community/blob/master/contributors/devel/release.md#the-release-cycle for example

/area release-team
/milestone v1.14
/kind documentation

/assign @spiffxp @BenTheElder @marpaia 
release lead and shadows

**Comment by puerco** [comment]
@alejandrox1  I can help with this one. Has anyone already defined templates for this?

**Comment by alejandrox1** [comment]
@puerco yes you can!

some notes on this issue...

Whatever info we end up creating from this issue should done in coordination with other teams.
It would be useful if other handbooks linked back to a doc we create to fulfill this issue.
For example, the first couple weeks is mostly enhancements-related work, we should make sure that the info we publish is linked to from the release lead handbook and from the enhancements handbook.

We should also try and be as explicit as possible, have the work laid out in the form of a checklist -make it as hard as possible to miss steps.

I'm thinking that we could do something like what has been done with these:
* https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md
* https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md

**Comment by alejandrox1** [comment]
@puerco any updates on this work?

**Comment by puerco** [comment]
Not yet sorry, I'm just starting to tackle this during this week

**Comment by puerco** [comment]
@alejandrox1 I'm starting to split the handbook into phases. Can you take a look at the following format proposal tell what you think ? Only consider the format for now:

https://github.com/puerco/sig-release/blob/release-schedule-docs/release-team/role-handbooks/release-team-lead/release-schedule.md
