### ISSUE TITLE
Document access requirements for release team members

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#479]
It would be great to put together a top-level list of things that all RT members need to do, lists they need to join/be added to, GitHub teams, etc.

ref: #478 

/area release-team
/cc: @spiffxp @BenTheElder @marpaia 
/help

**Comment by nzoueidi** [comment]
@marpaia are you still working on this? If not, can I work on it. Thanks.

**Comment by BenTheElder** [comment]
Is the list of things stable now? OTOH my head @nzoueidi this probably includes:
- kubernetes org membership (which includes kubernetes-dev mailinglist)
- release specific team mailing list (?)
- milestone-burndown mailing list (?)
- leads at least the milestone maintainers github team IIRC
- release lead should be in github.com/kubernetes/release OWNERS
- #sig-release on kubernetes slack?
- release team contacts sheet entry?

**Comment by nzoueidi** [comment]
Thanks @BenTheElder for providing this list. However, I am still waiting for the inputs of @marpaia.

**Comment by justaugustus** [comment]
To be honest, with no offense intended to you @nzoueidi, but I would prefer that this documentation be handled by a current or former Release Team member (ideally the current RT Lead or RT Lead Shadows). They're the ones who will have the best context on this.

**Comment by nzoueidi** [comment]
Sure @justaugustus no problem at all. I thought that this issue was opened ideally for newcomers.

**Comment by marpaia** [comment]
It's not a list, but I'd love to document the distribution of the meeting owner key for the Zoom account as well.

**Comment by marpaia** [comment]
Initial PR is up at #512! Definitely let me know if there's anything we've missed or should expand on.
