### ISSUE TITLE
coordinated contact point for patch release team

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#516]
Related to #331 we need a single point of contact for the patch release branch managers or "patch release team".

I propose creating a "kubernetes-patch-release-team" Google Group for this purpose.  This group's initial membership would be @aleksandra-malinowska @feiskyer @foxish and @tpepper.

Similarly a GitHub team would enable @ mentioning the team.

Part of #331 needs to be defining the forward criteria for membership in the group/team and how we add and remove members across time.

In the meantime it would be easier/consistent/discoverable to have a list as the one subscribed to the kubernetes-security list (instead of multiple folks directly) and use the group/team as the reference to "contact us" in our announcements in kubernetes-dev-announce and kubernetes-dev instead of telling people to @ specific people.

**Comment by tpepper** [comment]
@kubernetes/sig-release what precedent/preferences do we have for formalizing a closed sub-project team?  There's been the release-team and milestone-burndown and some shuffling around on those.  This would need to be a closed mailing list (ie: public can send to it, only members receive) due to the security nature.

**Comment by BenTheElder** [comment]
Presumably the [PST](https://kubernetes.io/docs/reference/issues-security/security/#report-a-vulnerability) has precedent for this?

**Comment by tpepper** [comment]
I feel like this group is sort of a sub-team of SIG Release and PST.   I believe we'll want member nominees to get approval from both of those bodies.

**Comment by tpepper** [comment]
pull #534 includes an example of how I hope this list is useful for discoverability and ease of contact...a mailto: link :)

**Comment by tpepper** [comment]
We now have @kubernetes/patch-release-team in addition to the email kubernetes-patch-release-team@googlegroups.com so marking this as done.
