### ISSUE TITLE
Proposal: shadow halo process

### ISSUE THREAD

**Issue by lachie83** [kubernetes/sig-release#571]
In an effort to build a pool of capable community members to serve on the release team and to ensure succession, the shadow role was created and implemented many release cycles ago. It occurred to me that there is no clear path for shadows to NOT serve on consistent release cycles and still be eligible for a lead role and hence I would like to discuss an idea that I refer to as "shadow haloing". 

The purpose of shadow haloing is to provide a capable contingent of shadow members that are eligible to serve lead roles without the burden of having to commit consistently to contiguous release processes. This may also aide in easing burnout by having already served as a shadow but not been given the opportunity to serve as a lead.

The initial details are as follows:
* An existing shadow is eligible to serve in a lead role so long as they have served on a release team in any role within the last three releases.

I am reluctant to put too much process in this issue without having discussed the high level concept for now. The process can be as simple as proving eligibility and submitting interest in serving a role on a specific release team and providing sufficient verbiage around this being a valid path.

**Comment by tpepper** [comment]
I think this is/was the intent, if not well worded as such in the english language document?

**Comment by lachie83** [comment]
okay thanks for the confirmation - I couldn't find wording to validate so thought I would ask the question and also put a timebox how long the acquired skills would remain relevant. Is there currently any expiry date on release team skills if a member has been out of the loop for more than a few cycles.?

**Comment by qedrakmar** [comment]
As a lapsed shadow, I agree with the "last three releases" timebox.  I might have been able to serve as lead to the role I shadowed over a year ago, but not now, without shadowing again.  I think it's a fair expiration date.

**Comment by jberkus** [comment]
Yeah, I think this was always the intention as well ... submit a PR update to the Role docs?

**Comment by lachie83** [comment]
Sure. I'll submit a PR. Thanks for the feedback.

**Comment by justaugustus** [comment]
What's the status on this?
/milestone v1.15

**Comment by justaugustus** [comment]
What's the current status of this?

**Comment by alejandrox1** [comment]
ping @lachie83 any updates on this?
/milestone v1.17

**Comment by alejandrox1** [comment]
ping @lachie83 any updates on this?

**Comment by LappleApple** [comment]
Hi, can this be closed?
