### ISSUE TITLE
Branch Manager Handbook needs participation info

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#573]
The current [branch manager handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/branch-manager) contains a bunch of technical instructions about how to create a branch and how to fast forward, etc.  However, it doesn't contain any of the information we need to recruit new BMs, such as:

1. What the Branch Manager Does
2. What the position's background requirements are
3. How many hours a week it takes

I'm pretty sure this is directly related to our inability to recruit BM shadows for 1.15.

/kind documentation
/priority important-soon
@claurence @Bubblemelon @hoegaarden

**Comment by justaugustus** [comment]
What's the status on this?
/milestone v1.15
/area release-team

**Comment by hoegaarden** [comment]
> What's the status on this?

On the way, see: https://github.com/kubernetes/sig-release/pull/604
