### ISSUE TITLE
Tracking: All RT Role Handbooks should have participation info

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#574]
Based on #573 and #369, not all Role Handbooks have the required information in order for someone to volunteer for the role.  This information includes, at a minimum:

1. Summary of what the role does
2. Estimated time commitment for the role
3. A timeline of how that time commitment is spread out over the release period
4. Any background/experience required for the role

It may additionally include, as applicable and as folks have time:

* A listing of all of the tasks the role performs (e.g. https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/ci-signal Overview)
* Calendar of jobs by release week
* Additional suggestions on what kind of person is appropriate for the role

First step on this will be to audit which Roles already have these things, so, a checklist:

- [x] Lead
- [x] Enhancements
- [x] CI Signal
- [x] Test Infra
- [x] Bug Triage
- [x] Branch Manager
- [x] Docs
- [x] Release Notes
- [x] Communications

/area release-team
/kind documentation
/priority important-longterm

**Comment by jberkus** [comment]
* CI Signal: has all info
* Bug Triage: has tasks and timing, but not any experience/requirements
* Communications: has tasks, timeline and requirements, but no time commitment estimates
* Docs: has none of the things
* Enhancements: has all of the things
* Release Notes: has requirements, tasks and timeline, but no time estimates.
* Lead: has all of the things.

Next step will be filing bugs against all of the above handbooks that need more information.

**Comment by imkin** [comment]
- test-infra would be working this release to update based on the new automation.
One of the responsibilities for the shadows is to suggest changes to the handbook for improvements apart from what is identified.

**Comment by justaugustus** [comment]
Looks like we're done with this! :tada: 
/close
