### ISSUE TITLE
Bug Triage role handbook needs requirements info

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#577]
The Bug Triage Role Handbook currently has information about time requirements and timeline, but not what qualifications are required to shadow or lead.  Please add.

ref #574 

@soggiest @nikopen

**Comment by justaugustus** [comment]
What's the status on this?
/milestone v1.15

**Comment by justaugustus** [comment]
What's the current status of this?

**Comment by soggiest** [comment]
I still need to update this, will prioritize next week

**Comment by jberkus** [comment]
Bump.  We've now opened the shadow application, and new potential shadows have no clue what the requirements of the job are.

@soggiest @nikopen @xmudrii

**Comment by nikopen** [comment]
I don't think the requirements idea aligns with this role. 

'requirements' can be derived from the context of the handbook itself, and it's the candidate's job to read it in any case. 

I'd even say, if the candidate is simply able to read and understand the content and context of the handbook, then s/he is eligible. 

If the new leads feel that there's a need for explicit requirements feel free to write them up.

**Comment by xmudrii** [comment]
@jberkus Can this issue be closed now that #672 is merged?
