### ISSUE TITLE
Communications Handbook needs time estimates

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#578]
The Communications Role Handbook currently has information about task, deadlines, and requirements, but no time estimates of the commitment to shadow or lead. Please add.

ref #574

/kind documentation
/area release-team
/priority important-longterm

**Comment by jberkus** [comment]
/assign @castrojo 
cc @kbarnard10 @onlydole

**Comment by justaugustus** [comment]
What's the status on this?
/milestone v1.15

**Comment by justaugustus** [comment]
What's the current status of this?

**Comment by jberkus** [comment]
@castrojo @onlydole hey, this needs to be closed ASAP.  New shadows are applying to this role, and they don't know what the requirements are.

**Comment by onlydole** [comment]
Hey @jberkus and @justaugustus - we will take a look at this and get this gap closed 👍🏼

**Comment by onlydole** [comment]
@jberkus and @castrojo - we can close this issue. Let me know if you need anything else done on this front!

**Comment by idealhack** [comment]
https://github.com/kubernetes/sig-release/pull/671 fixed this, looks like we can close this.
