### ISSUE TITLE
Docs Handbook needs all the participation info

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#579]
The Docs Role Handbook currently has no information about what's needed to to shadow or lead so that people can volunteer.  At a minimum, you need:

* Summary of what the role does
* Estimated time required
* General timeline and deadlines
* Experience/skills requirements

Please add.

ref #574

/kind documentation
/area release-team
/priority important-longterm

**Comment by jberkus** [comment]
cc @jimangel 

/assign @MAKOSCAFEE

**Comment by justaugustus** [comment]
What's the status on this?
/milestone v1.15
