### ISSUE TITLE
Release Notes Handbook needs time estimates

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#580]
The  Role Handbook currently has information about tasks, deadlines, and requirements , but not any time estimates to shadow or lead. Please add.

ref #574

/kind documentation
/area release-team
/priority important-longterm

/assign @onyiny-ang 
cc @dstrebel @jeefy

**Comment by onyiny-ang** [comment]
Thanks for bringing this to my attention. I will add them and make a PR.
