### ISSUE TITLE
Test-Infra Handbook Needs requirements, time estimates, and timeline

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#581]
The Test-Infra Role Handbook currently has one requirement, and a task list, but not time estimates, a timeline of work, or the rest of the requirements to shadow or lead. Please add.

ref #574

/kind documentation
/area release-team
/priority important-longterm

/assign @imkin 
cc @amwat @BenTheElder @cjwagner

**Comment by imkin** [comment]
cc: @taragu @Katharine @mariantalla

**Comment by justaugustus** [comment]
What's the status on this?
/milestone v1.15

**Comment by justaugustus** [comment]
What's the current status of this?

**Comment by imkin** [comment]
@justaugustus we were changing the scope and requirements of test-infra role this release and hence held back on defining them to not "double-work". 
Now that the role for test-infra has been split to branch-manager, I will work with other role-leads and files issues to split the handbook too.

We should just close this issue.

**Comment by justaugustus** [comment]
Agreed.
/close
