### ISSUE TITLE
cherry pick process enhancements

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#611]
Having exercised the cherry pick approval process now for a period, I believe we're in need of some next level process enhancements.

The [SIG Arch meeting on April 25, 2019](https://docs.google.com/document/d/1BlmHq5uPyBUDlppYqAAzslVbAO8hilgjqZUTaNXUhKM/edit#) included a brief survey of patch releases and there is a general sense that the backport acceptance criteria are weak or unevenly applied.

The cherry pick automation does provide some level of consistency across master PR and patch branch PRs.  But it can't synthesis missing labels or missing details.  A PR on master may have merged with relatively little detail, and later be recognized as a big deal and proposed for cherry pick.  That detail needs filled in for the cherry pick reviewers.  Or even when immediately felt to be a cherry pick candidate the answers to likely reviewer questions are not readily available in an issue, the commit message, the PR description, or associated discussion threads on GitHub.

- [ ] define better proposal criteria for developers in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md
- [ ] define better acceptance criteria for patch managers in [backport acceptance criteria](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/patch-release-manager#cherry-pick-requests)
- [ ] codify criteria in cherry pick automation and PR template

A cherry-pick PR specific template might look something like, eg:

# Description
```<autopopulated from tool>```

## How Has This Been Tested?
- [ ]  Covered by existing conformance testing
- [ ]  Covered by existing e2e testing
- [ ]  Covered by existing integration testing
- [ ]  Covered by existing unit testing
- [ ]  Added new testing to cover
- [ ]  Tested locally/manually
- [ ]  Consideration given to upgrade scenarios
- [ ]  Have not tested

## Type of change:
- [ ]  Regression fix (non-breaking change which fixes regression ```<LINK ISSUE HERE>```)
- [ ]  Bug fix (non-breaking change which fixes standing issue ```<LINK ISSUE HERE>```)
- [ ]  Cleanup (fix to test, flake or other CI signal noise ```<LINK TO TESTGRID HERE>```)
- [ ]  New feature (non-breaking change which adds functionality)

## Criticality / Risk / Complexity / Benefit:
- [ ]  Test/CI fix
- [ ]  Easily triggered in common usage scenario
- [ ]  Complex trigger
- [ ]  Loss of data
- [ ]  Memory corruption
- [ ]  Panic, crash, hang
- [ ]  Security
- [ ]  Cloud provider specific

## Checklist:
- [ ]  I have discussed the change with SIG(s) leadership and they:
  - [ ]  agree it is valid for cherry picking to this branch.
  - [ ]  suggest it is also required on other branches ```<LINK TO OTHER CHERRY PICKS HERE>```.
- [ ]  My change requires a change to the documentation.
- [ ]  I have updated the documentation accordingly.
- [ ]  I have reviewed the release note.

**Comment by justaugustus** [comment]
@tpepper -- How close are we on this one?

/remove-lifecycle rotten
/milestone v1.18
