### ISSUE TITLE
Add key release dates to SIG Release calendar

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#617]
ref: https://groups.google.com/d/msg/kubernetes-sig-pm/3bOMguYeN-0/uT9e8U4qAAAJ
/help
/priority important-soon
/area release-team
/milestone v1.15

**Comment by sNathan13** [comment]
I can take this, with some help from the sig-release team.

**Comment by justaugustus** [comment]
This is complete with the creation of the Kubernetes Release Calendar: https://bit.ly/k8s-release-cal
/assign
/kind feature
/close

(@sNathan13 -- apologies for missing your note. This is something that would've required admin permissions on our calendars.)
