### ISSUE TITLE
Patch release process should update kubernetes/website Kubernetes versions

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#626]
The docs folks have a file which tracks the current patch release: https://github.com/kubernetes/website/blob/cb559f13c2c6deaa5fa309660afe82ee4adf5cd8/config.toml#L69-L130

When making a new patch release, this file should get the updated patch release number automatically.

**Comment by jimangel** [comment]
I don't want to lose sight of this... Adding in the 1.15/1.16 doc leads:

/cc @makoscafee @simplytunde

Thanks for opening!
