### ISSUE TITLE
Cut 1.12.9 release

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/sig-release#627]
/assign 

Scheduled to happen Monday, 2019-05-27

Any bumps or issues encountered along the way, post here. /close when the release has been cut.

- [ ] screen shot master's unhealthy testgrid boards and add them as a comment 
- [ ] stage & release
  - [ ] notify [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF/) 
  - [ ] collect metrics, links, ... and add them as a comment 
- [ ] build & publish packages (debs & rpms)
- [ ] send notification mail

/milestone v1.12
/sig release
/area release-team

**Comment by feiskyer** [comment]
staging build link [here](https://console.cloud.google.com/cloud-build/builds/0a993182-2a79-4157-9c5f-ef902b126abf?project=kubernetes-release-test).

**Comment by feiskyer** [comment]
Build failed: 

```sh
Step #1: Asking Jenkins for a good build (this may take some time)...
Step #1: FAILED: Curl to testgrid/config/config.yaml
Step #1: No sig-release-1.12-blocking list found in the testgrid config.yaml!
```

**Comment by idealhack** [comment]
@feiskyer you can try https://github.com/kubernetes/release/pull/715

**Comment by feiskyer** [comment]
Staging build success now at [here](https://console.cloud.google.com/cloud-build/builds/9e49128e-724c-4107-b5d1-22656d73f2a9?project=kubernetes-release-test).

**Comment by feiskyer** [comment]
Release build succeed now at [here](https://console.cloud.google.com/cloud-build/builds/15f45fda-07e1-4b2f-a213-e0043cbb6632?project=kubernetes-release-test).

```sh
$ docker pull gcr.io/google-containers/kube-controller-manager-amd64:v1.12.9
$ docker run gcr.io/google-containers/kube-controller-manager-amd64:v1.12.9 kube-controller-manager --version
Kubernetes v1.12.9

$ curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.12.9/bin/linux/amd64/kubectl 
$ chmod +x kubectl
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T16:08:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by feiskyer** [comment]
Update: release build succeed, but there's something wrong with DEB on Xenial. @sumitranr is helping to find what's wrong.

**Comment by feiskyer** [comment]
Xenial build is finished now and release notification email has sent.

/close
