### ISSUE TITLE
Move Patch Release handbook to release-engineering directory

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#632]
Now that the Patch Release Manager/Team is no longer part of the Release Team, we should move the handbook under `k/sig-release/release-engineering` to show that this team lives under the Release Engineering subproject.

/assign @tpepper @aleksandra-malinowska @hoegaarden @feiskyer 
/priority important-longterm
/milestone v1.15
/area release-eng

**Comment by idealhack** [comment]
this was done in https://github.com/kubernetes/sig-release/pull/689, closing
