### ISSUE TITLE
Revisions to Shadow questionnaire

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#645]
We adopted a Shadow questionnaire in #368. The questionnaire we used for the 1.15 cycle [is here](https://forms.gle/LTYDgYCaseGBrLbm9).

Questions for 1.16 cycle: 

1. Does anyone object to using the application process for 1.15?
2. What questions do you want to add to the questionnaire?
3. What questions would you want to remove from the questionnaire, or change?

@claurence @justaugustus @kacole2 @alejandrox1 @imkin @soggiest @bubblemelon @MAKOSCAFEE  @onyiny-ang @castrojo

**Comment by Bubblemelon** [comment]
Re: 
> What questions do you want to add to the questionnaire?

[As suggested](https://kubernetes.slack.com/archives/GH1PUAHT3/p1554488413008700) by @imkin: “Have you read through the handbook? Do you have any questions about a role? Do you have feedback on the handbook?” 

This was talked about early in the 1.15 cycle. Perhaps have hints on these questions in the Comments section of the questionnaire? This would be helpful to see of how much the applicant has dug into the handbook (if they choose to provide this info).

**Comment by claurence** [comment]
For the question: Can you commit to the time? *

I'm thinking there might be value in breaking up this question into can you do the baseline commitment then asking how much additional time do they have  - I feel like most people would say "yes" here, but it doesn't give us a good idea how much of the commitment they are willing to make.  

i.e.
- Can you commit to a 1 hr a week meeting for the first 2 month of the release (with the understanding that things come up and you may need to last minute miss a meeting)? y/n
- Can you commit to 3 1 hr a week meetings or 5 1 hr a week meetings in the final month (with the understanding that things come up and you may need to last minute miss a meeting)? y/n
- Shadowing often requires ad-hoc time commitments that vary based on roles.  What is the best estimate to how much time you could dedicate throughout the next release cycle outside of the regular meetings? (open answer).

**Comment by lachie83** [comment]
I agree with Claire's comments. We'll also need to remove the test-infra role as it's dissolving for 1.16 - https://github.com/kubernetes/sig-release/issues/631. Other than that - it looks great. Thanks

**Comment by jberkus** [comment]
Questionnaire is updated & approved, so closing.
