### ISSUE TITLE
Assemble Kubernetes 1.16 Release Team 

### ISSUE THREAD

**Issue by claurence** [kubernetes/sig-release#648]
Issue for assembling the Kubernetes 1.16 Release Team.

Please review the [Release Team Selection Process docs](https://github.com/kubernetes/sig-release/blob/master/release-team/release-team-selection.md) for details on the process and criteria.

I'll open a companion PR to go along with this issue 

/sig release 
/area release-team
/milestone v.1.16

**Comment by claurence** [comment]
/assign @claurence @lachie83 

I've asked @lachie83 to take on role of release lead for v.1.16

**Comment by lachie83** [comment]
Thank you very much for considering me for the lead role Claire. I accept your nomination and am excited to serve on the 1.16 release team.

**Comment by jberkus** [comment]
+1 on Lachie

**Comment by nikopen** [comment]
Hail to the new lead!

Happy to continue in the lead team from the breezy shadows during hothot summer 🌞

**Comment by claurence** [comment]
pinging @kacole2 @alejandrox1 @Bubblemelon @soggiest @onyiny-ang @imkin @makoscafee ping to remind y'all to nominate successors for your roles here!

**Comment by kacole2** [comment]
I'm going to continue with 1.16 Enhancement Tracking. @mrbobbytables will shadow me once again as well. @craiglpeters has expressed interest in shadowing CI Signal so I would like to put my nomination up for him to be a shadow in that role.

**Comment by raelga** [comment]
I will love to get in involved as a shadow for this release (first timer!) :)

**Comment by jberkus** [comment]
@raelga the Shadow application will go up probably next week.

**Comment by castrojo** [comment]
I'd like to nominate @onlydole for comms lead for 1.16.

**Comment by Bubblemelon** [comment]
Nominaing @idealhack as Branch Manager Lead for v1.16! :tada: :confetti_ball:

**Comment by makoscafee** [comment]
I would like to nominate @simplytunde for Docs Lead for 1.16

**Comment by onlydole** [comment]
> I'd like to nominate @onlydole for comms lead for 1.16.

I graciously accept! This group rocks 🎉

**Comment by jberkus** [comment]
Hey, the CI Signal 1.15 shadows aren't sufficiently available for 1.16 cycle.  This means we want to open this up to any prior release shadows, or even prior CI Signal leads, from earlier releases.

@mariantalla @AishSundar @mortent @smourapina @surajnarwade

**Comment by soggiest** [comment]
I would love to shadow CI Signal for 1.16. I'm just about ready to nominate my replacement, as well.

**Comment by surajnarwade** [comment]
@jberkus , I'm in :smile_cat:

**Comment by alejandrox1** [comment]
@surajnarwade just to clarify, you’re in for ci signal lead for v1.16?

**Comment by surajnarwade** [comment]
@alejandrox1 , I have very little experience so I will not be able to lead but I can be shadow and happy to help wherever possible

**Comment by palnabarun** [comment]
I am eagerly waiting for the shadow applications. Excited to work in the team. :smile: 

PS: I am a first timer.

**Comment by alejandrox1** [comment]
@surajnarwade ah alright, not a problem. 
 just wanted to clarify @jberkus ‘s message: right now we are looking for someone to take ci signal shadow as it is discouraged for a lead to be a lead for two consecutive cycles.

**Comment by justaugustus** [comment]
As a few have mentioned on the thread, we are currently staffing the role leads for the 1.16 cycle.
As soon as all lead positions are nominated and staffed AND the updated questionnaire is complete, we will notify both here and on kubernetes-dev.

Thanks everyone for your interest so far! :)

**Comment by soggiest** [comment]
I nominate @xmudrii for Bug Triage lead for 1.16

**Comment by onyiny-ang** [comment]
I'd like to nominate @saschagrunert for Release Notes lead--he's taken the shadow role to a whole new level this release and will be a great lead for 1.16 (in which we expect to see the release notes completel the move to a new format: https://github.com/kubernetes-sigs/release-notes)

**Comment by jberkus** [comment]
The Release team [Shadow Questionnaire](https://forms.gle/q69PuRM8V9ByVzEA6) is now ready.

Shadows, start your applications!

@surajnarwade @palnabarun @raelga

**Comment by imkin** [comment]
I guess its good to close this now.

**Comment by jeefy** [comment]
I think this should stay open till @justaugustus has sent out feedback/messages to the unselected shadows. 

That's the final loop to close on this.

**Comment by justaugustus** [comment]
This is now complete.
Thank you everyone who volunteered! :)

/close
