### ISSUE TITLE
Monitoring CI jobs from previous releases

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#656]
During the Kubernetes release cycle, the CI signal team is charged with monitoring the dashboards for master and for the release we are working on, i.e., master-blocking, master-informing, 1.15-blocking, 1.15-informing.

The criteria for cutting a new release is heavily based on the health of the `*-blocking` dashboards with the `*-informing` ones providing extra context.
However, there is no group that actively monitors older releases after a release is made even though we, as a community, keep working on patch releases for the latest 3 minor releases.

Kubernetes 1.x.0 releases are known to not be completely production ready. I think having some sort of dedicated CI signal team that keeps an eye out on older release dashboards would help provide more visibility into the factors that affect the quality and stability of our releases.

/priority important-longterm
/area release-eng
/cc @tpepper @mariantalla @spiffxp

**Comment by tpepper** [comment]
See also https://github.com/kubernetes/sig-release/issues/369

We're working as @kubernetes/patch-release-team to build out a workflow that's open to more folks helping in monitoring branch CI health versus the incoming and merged cherry picks onto those branches.  Patch release team monitors the older releases testgrid boards.
