### ISSUE TITLE
Update Release Handbook due to dissolving test-infra lead role.

### ISSUE THREAD

**Issue by imkin** [kubernetes/sig-release#658]
Following up on https://github.com/kubernetes/sig-release/issues/631 this issue is to track changes to the release-handbook

https://github.com/kubernetes/sig-release/issues/631#issuecomment-499961100 lists a few possible changes to the hand book that references to test-infra handbook.

/assign @claurence

**Comment by claurence** [comment]
https://github.com/kubernetes/sig-release/pull/669 has my edits for this

**Comment by imkin** [comment]
#669 is merged. Hence closing this one. /close
