### ISSUE TITLE
Update Branch Manager Handbook due to dissolving of test-infra role.

### ISSUE THREAD

**Issue by imkin** [kubernetes/sig-release#659]
Following up on #631 this issue is to track changes to the branch-manager-handbook needed for the transition of some of the responsiblities.

- Add config/jobs forking steps from test-infra handbook to branch manager handbook.
- Make changes to any references to test-infra lead to new appropriate roles/channel.

/assign @Bubblemelon 
/cc @claurence @lachie83 @tpepper @justaugustus

**Comment by Bubblemelon** [comment]
The above referenced PR resolves this issue.
