### ISSUE TITLE
Address tpepper's review on build admins doc

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#660]
Address post-merge feedback from @tpepper.
ref: https://github.com/kubernetes/sig-release/pull/657#pullrequestreview-247820881

/assign @justaugustus @sumitranr 
/priority important-soon
/kind cleanup
/milestone v1.16

**Comment by markyjackson-taulia** [comment]
@justaugustus should this get moved in to the 1.17 milestone?
