### ISSUE TITLE
Add links to relevant docs in Release Notes

### ISSUE THREAD

**Issue by jeefy** [kubernetes/sig-release#667]
Per https://kubernetes.slack.com/archives/C2C40FMNF/p1560536323319700

It'd be awesome if, in the release notes, we link to new and/or relevant documentation on the K8s website. I think this is entirely reasonable and something that should be looked into in the next release or so. 

With the website it would be relatively easy and painless to add a new (optional) field in the JSON. That way it could be captured by either a field in the PR template OR a separate PR to update the JSON with the doc(s) link.

**Comment by saschagrunert** [comment]
How about adding an additional section to the PR template, which could be parsed by the release-notes tool afterwards:

```
\   ```documentation
\    - Link
\    - Link
\    - Link
\   ```
```

**Comment by pswica** [comment]
@saschagrunert 
I think it's a great idea. 

I think we would need to parse the links to make sure that they are on the Kubernetes website. Other things to keep in mind are links changing on the website overtime. A final thing thing to address would be irrelevant links. What if people added a link to the main kubernetes website for their PR. Would that really be relevant if it appeared dispersed over 20 PRs or so?

**Comment by saschagrunert** [comment]
> What if people added a link to the main kubernetes website for their PR. Would that really be relevant if it appeared dispersed over 20 PRs or so?

Yeah I guess we have to review the PRs with keeping in mind that the documentation links will appear in the release-notes and need to  add valuable benefits to the users. Nevertheless we can parse all URLs and classify them by the location. So we would be able to separate KEP links or filter only for KEPs inside the website.

**Comment by saschagrunert** [comment]
@jeefy do we want to close this or is there anything else which needs to be done? :)

**Comment by jeefy** [comment]
🌮 

/close
