### ISSUE TITLE
bot feedback on PRs for patch release branches

### ISSUE THREAD

**Issue by tpepper** [kubernetes/sig-release#680]
When a pull request is submitted on a release branch the next steps for a submitter are less clear than for a standard PR.  Can we improve the bot messages there?

It would be nice to get feedback to the submitter around:
* if they did not use the cherry-pick automation.  
* that they are responsible for getting OWNERS approval on the PR and OWNERS may misunderstand the status thinking they already approved the patch (ie: in the parent PR or in another peer PR against another branch, but all need approved)
* The review cadence for cherry pick approval: the patch release team does weekly-ish merging and are more active on that closer to a coming patch release (every 3-4 weeks) and less active just after making a patch release

relates to https://github.com/kubernetes/sig-release/issues/369

**Comment by tpepper** [comment]
@kubernetes/patch-release-team what else can we do to better illustrate the workflow to PR submitters?

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/test-infra/pull/12968

**Comment by justaugustus** [comment]
ref: https://github.com/kubernetes/test-infra/pull/13148, https://github.com/kubernetes/test-infra/pull/13137

**Comment by cblecker** [comment]
red: https://github.com/kubernetes/test-infra/pull/14275
