### ISSUE TITLE
machine readable release schedule

### ISSUE THREAD

**Issue by yastij** [kubernetes/sig-release#718]
Currently our release planning is published a markdown. this issue tracks the move toward a more machine-friendly format (e.g. yaml) that users can use as release signal

/assign
/area release-eng
/priority important-soon
/kind cleanup

**Comment by yastij** [comment]
@justaugustus - should the release handbook be updated too ? If yes, can you point me where ?

Thanks

**Comment by justaugustus** [comment]
@yastij -- I'm planning to sweep the [Branch Manager](https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/branch-manager.md) and [Patch Release Team](https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/patch-release-manager.md) now that both groups have moved under Release Engineering.

I think it would still be great to have the markdown, in addition to the yaml, to make it easy for people who may not want/need to consume the yaml. 

Could we do something similar to the [k/community docs generation](https://github.com/kubernetes/community/blob/2734c273c3d4dbdb440bcadd088aa8b289906b9a/Makefile#L9-L10)?

**Comment by frapposelli** [comment]
any updates on this?

**Comment by yastij** [comment]
@frapposelli - didn't have time to get to this yet, I'll probably get to it by the end of the week
