### ISSUE TITLE
new issue templates

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/sig-release#723]
currently the only issue template is for cutting a release, we should probably add some more templates

<img width="1035" alt="Screen Shot 2019-07-16 at 2 26 51 PM" src="https://user-images.githubusercontent.com/917931/61331078-0594f980-a7d6-11e9-8071-9ffa85228184.png">

cc @justaugustus

**Comment by saschagrunert** [comment]
I think this is done
/close
