### ISSUE TITLE
moving sigs.k8s.io/kind CI into release blocking

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/sig-release#724]
In particular https://testgrid.k8s.io/conformance-kind#kind%20(IPv6),%20master%20(dev)&width=5 would be a candidate to be our only IPv6 release-blocking signal.

This has been pretty stable for a few quarters now, with failing jobs generally being due to actual Kubernetes breakage (which has been fixed each time!)

cc @aojea @justaugustus @spiffxp

**Comment by spiffxp** [comment]
The linked job is currently failing (it's running a `[Serial]` Conformance test, probably shouldn't be)

**Comment by aojea** [comment]
@spiffxp the fix is here https://github.com/kubernetes/kubernetes/pull/80398

The problem was because that job was recently promoted to conformance, but due to the lack of IPv6 testing, we couldn´t detect it until it was merged

**Comment by aojea** [comment]
@BenTheElder @spiffxp the ipv6 kind is green again, the job.is pretty stable, the failures were known issues due to a new test promoted to conformance that wasn't ready for ipv6

**Comment by spiffxp** [comment]
I would like to see both ipv4 and ipv6

We know kind supports Conformance tests and would like to start there.  I am interested in seeing kind run more than Conformance tests.  The options I see there are:
- do what we do for the current release-blocking jobs: allow tests to be added over time, kick them out if they're harming signal
- use canary jobs to add in tests and verify the canary jobs remain healthy before adding the tests to the release-blocking jobs

**Comment by aojea** [comment]
@spiffxp we have a PR that is running all non Slow, Disruptive,Flaky, Feature e2e tests and a Skip regex for the e2e tests that are failing in kind (some of them fail because kind doesn´t allow ssh or mounting nfs volumes inside the nodes, ...)
https://github.com/kubernetes-sigs/kind/pull/701/files

**Comment by aojea** [comment]
/close
kind jobs were added as release blocking
