### ISSUE TITLE
Update and clarify release notes process for k/k pull requests

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/sig-release#729]
We have a lot of new processes and tools for improving our release notes, and need to make sure that someone opening a k/k pull request does not experience major stumbling blocks.

Currently, the [pull request template](https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md) links to the [release notes doc](https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md) but the process is not explained too well, and in fact links back to a "brief example" in the pull request template, which a) doesn't exist, and b) this experience is circular. 😨 

We also have https://relnotes.k8s.io/ which should be mentioned somewhere.

There is automation underway that I don't have any details on - if @justaugustus could elaborate?

/sig contributor-experience
/sig testing
/sig release

/cc @simplytunde 
/cc @saschagrunert 
/cc @onyiny-ang 
/cc @justaugustus 
/cc @jeefy

**Comment by saschagrunert** [comment]
Thanks for the issue creation @guineveresaenger 🙏 We still have to implement the display  of the new docs section in the release notes website. I will propose a PR in the next couple of days if no one else is already planning to do this.

**Comment by guineveresaenger** [comment]
@saschagrunert do we have any updates on this? Thank you! 🙇‍♀

**Comment by saschagrunert** [comment]
> @saschagrunert do we have any updates on this? Thank you!

Yes, the major implementation has been done in 
- https://github.com/kubernetes-sigs/release-notes/pull/76
- https://github.com/kubernetes-sigs/release-notes/pull/81

We still want to be able to filter these docs on the website, where I will start working on corresponding issue (https://github.com/kubernetes-sigs/release-notes/issues/82) in the upcoming days.

For sake of automation we have this one, but it's not directly related to the additional docs section:
- https://github.com/kubernetes/release/issues/834

**Comment by saschagrunert** [comment]
Hey @guineveresaenger as an update the referencing PR (https://github.com/kubernetes/kubernetes/pull/81159) got merged. We still have these two open
- https://github.com/kubernetes/community/pull/4004
- https://github.com/kubernetes/kubernetes/pull/81278

Do you think we can drop https://github.com/kubernetes/kubernetes/pull/81278 from referencing here  from here since it's already related to https://github.com/kubernetes/sig-release/issues/668 ?

**Comment by guineveresaenger** [comment]
@saschagrunert yes, that sounds right to me. and 🎉 for getting that merged!

**Comment by saschagrunert** [comment]
@guineveresaenger do you think we can close this issue? We're tracking multiple technical enhancements already in release engineering, whereas regarding the contributor experience we still have this one open: https://github.com/kubernetes/community/issues/484

**Comment by justaugustus** [comment]
At this stage, I think we've sufficiently documented and improved the process to close this out.

/close
