### ISSUE TITLE
Process and communication improvements for Release Engineering

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#732]
Some near term goals in my head:
- [ ] (https://github.com/kubernetes/sig-release/issues/897) Ensure SIG Release Chairs own all SIG Release assets
- [x] Dedupe SIG Release communication channels where possible/appropriate
- [x] Grant access to release GCP projects via Google Groups, instead of per user

So concretely, what I'd like to do:
- [x] (SIG Release) Have all SIG Release Chairs, Patch Release Team members, Branch Managers, and Build Admins agree to uphold the security embargo
- [x] (PSC) Grant access for SIG Release Chairs to manage security-release-team@kubernetes.io
- [x] (SIG Release) Rename security-release-team@kubernetes.io to release-managers-private@kubernetes.io
- [x] (SIG Release) Ensure all SIG Release Chairs, Patch Release Team members, ~Branch Managers~, and Build Admins are members of release-managers-private@kubernetes.io
- [x] (kubernetes.io GSuite Admins (@kubernetes/steering-committee)) Create release-managers@kubernetes.io, which would include Release Manager Associates and could nest release-managers-private@kubernetes.io
- [x] (SIG Release) Delete/archive Release Mgmt Google Groups:
  - kubernetes-release-managers@googlegroups.com
  - kubernetes-release-managers-private@googlegroups.com
- [x] (SIG Release) Assign the "OSS Kubernetes Release Manager" IAM role to release-managers-private@kubernetes.io in the kubernetes-release-test GCP project, which will allow members to cut releases on behalf of the project
- [x] (SIG Release) Develop a descoped viewer role for the kubernetes-release-test GCP project and assign it to release-managers@kubernetes.io, to allow Associates some limited access to follow along
- [ ] (SIG Release) Audit and prune extraneous user and service accounts from the kubernetes-release-test GCP project
- [x] (SIG Release/k8s Infra) Leverage [repo-based configs in k/k8s.io](https://git.k8s.io/kubernetes/k8s.io/groups/groups.yaml) to manage Release Manager Google Groups

(Started from conversation on [k-security-discuss](https://groups.google.com/d/topic/kubernetes-security-discuss/EYpUoONgLUA/discussion).)

/assign
/cc @kubernetes/sig-release-admins @kubernetes/release-engineering @kubernetes/product-security-committee 
/area release-eng
/priority important-soon
/kind feature cleanup
/milestone v1.16

**Comment by liggitt** [comment]
> (PSC) Grant access for SIG Release Chairs to manage security-release-team@kubernetes.io

@tpepper and @justaugustus are added as managers of the list, and can add/manager additional members/managers

**Comment by liggitt** [comment]
> Rename security-release-team@kubernetes.io to release-managers@kubernetes.io

Given the type of communications sent to the security release team list, I think the list name should reflect it's security-sensitive or private nature.

**Comment by justaugustus** [comment]
@liggitt @jonpulsifer -- sounds good.
How's:
- private: release-managers-private@kubernetes.io
- public: release-managers@kubernetes.io

**Comment by liggitt** [comment]
that seems reasonable

**Comment by jonpulsifer** [comment]
+1, sgtm

**Comment by idealhack** [comment]
+1

Let me know which I can help with.

**Comment by cpanato** [comment]
+1
let me know as well where i can help

**Comment by justaugustus** [comment]
@idealhack @cpanato -- Most of this will need to be handled by administrators of the relevant properties (SIG Chairs, PSC, kubernetes.io GSuite Admins), but I'll let you know if there's anything we can delegate! :)

**Comment by tallclair** [comment]
+1, lgtm

**Comment by philips** [comment]
@justaugustus what will the release-managers@kubernetes.io list be used for? Do you think we should consider using the https://github.com/kubernetes/k8s.io/blob/fc4218bdc7de25fc2fe4b7dca00d61c5bde61366/groups/groups.yaml automation?

**Comment by dims** [comment]
@philips i have been thinking the same thing. though currently the automation that drives the groups.yaml has a hard coded prefix `k8s-infra-` to avoid stomping existing google groups. i have to figure out how to do better ..

**Comment by justaugustus** [comment]
@philips -- @jbeda created the group for me earlier. I've closed out the steering issue (https://github.com/kubernetes/steering/issues/115). We'll use release-managers@kubernetes.io for general communications for all [Release Managers](https://github.com/kubernetes/sig-release/blob/master/release-managers.md) and release-managers-private@kubernetes.io for private comms (PSC + internal comms for Patch Release Team, SIG Chairs, and Build Admins).

And yes, I definitely want to use the [yaml-based configs](https://git.k8s.io/kubernetes/k8s.io/groups/groups.yaml) eventually, but as @dims mentioned, there is currently a restriction on group naming. I've added an item for it above.

**Comment by justaugustus** [comment]
The mailing list changes have been approved in this thread.
I've issued a PR (https://github.com/kubernetes/sig-release/pull/747) to change the references to mailing lists and a lazy consensus period of Wednesday, 8/7 at 6pm ET.

I'll wait until that time passes and [all potential members of the private mailing list have agreed to uphold the security embargo](https://github.com/kubernetes/sig-release/issues/746) before proceeding with any group membership changes/renames/archivals.

**Comment by justaugustus** [comment]
Notified k-security-discuss, release-managers, k-release-managers-private, k-sig-release, k-release-team, steering, community of changes and lazy consensus period: https://groups.google.com/d/topic/kubernetes-sig-release/xHrHQcjwWjk/discussion

**Comment by justaugustus** [comment]
Lazy consensus for mailing lists changes has been achieved.

@jbeda has granted me owner access to security-release-team@kubernetes.io and I've changed the list email address to release-managers-private@kubernetes.io.
Holds have been released on https://github.com/kubernetes/sig-release/pull/747 and https://github.com/kubernetes/test-infra/pull/13793.

**Comment by justaugustus** [comment]
Documentation updates: https://github.com/kubernetes/security/pull/45, https://github.com/kubernetes/sig-release/pull/751

**Comment by justaugustus** [comment]
Before granting release-managers-private@kubernetes.io GCP access, I'd like to clean up membership leaving only Release Managers.

Any issues with removing the following people?
- sc1 (@philips) 
- @cjcullen 
- @liggitt 
- @tallclair 

Additionally, can we create `security-release@kubernetes.io`, which would contain:
- security@kubernetes.io
- release-managers-private@kubernetes.io

Per @tallclair's suggestion on the thread, this (and unnesting `release-managers-private@` from `security@`) would allow us to minimize traffic to `release-managers-private@` to be only release-focused.

Will send to ML as well.

**Comment by justaugustus** [comment]
Most of the non-nebulous, cross-group tasks here have been completed, so we're just about ready to close this out.

@kubernetes/product-security-committee -- How do we want to handle coordinating security releases?

### Option 1
Continue as-is, with `release-managers-private@` nested within `security@`.
Allows Patch Release Team advance heads-up on potential CVEs and minimizes list sprawl

### Option 2
Use `security-release-team@`.
Right now, I'm the only member, but this would be expanded to nest:
- `release-managers-private@`
- `security@`

Here, Patch Release Team members would have to be explicitly added to the thread to action on coordinating a release.

Let me know what you think.

**Comment by justaugustus** [comment]
Ping @kubernetes/release-engineering for any last-minute thoughts...

**Comment by onlydole** [comment]
Looks good to me! 👍

**Comment by justaugustus** [comment]
> @kubernetes/product-security-committee -- How do we want to handle coordinating security releases?

PSC is trending towards option two, so I've opened https://github.com/kubernetes/k8s.io/pull/492 for discussion/review.

**Comment by justaugustus** [comment]
https://github.com/kubernetes/k8s.io/pull/492 has merged and I've confirmed that the `security-release-team@` list is now active: https://groups.google.com/a/kubernetes.io/d/topic/security/QzotN1Lq93U/discussion

The remaining tasks on the list have been opened as individual issues:
- Ensure SIG Release Chairs own all SIG Release assets: https://github.com/kubernetes/sig-release/issues/897
- Audit and prune extraneous user and service accounts from the kubernetes-release-test GCP project: https://github.com/kubernetes/sig-release/issues/898

/close
