### ISSUE TITLE
Travel sponsorship considerations for SIG Release members

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#734]
Several roles in SIG Release require sustained contributions to the project over multiple quarters (the Release Team in particular comes to mind here).

We should have a process in place for SIG Release Chairs and SIG Release subprojects owners e.g., Release Team Lead, to present a set of candidates to be considered for travel sponsorship for KubeCon/CloudNativeCon.

Once https://github.com/kubernetes/steering/pull/114 has merged, we should draft SIG-specific and complementary policy.

/assign
/cc @kubernetes/sig-release-admins 
/priority important-soon
/milestone v1.16
/kind documentation feature

**Comment by tpepper** [comment]
Steering is discussing this and hoping to formalize a process (like the diversity scholarship process), but that wont be ready in time for the upcoming KubeCon North America 2019.  For that conference there will be an ad-hoc process.

If you're struggling to find a way to KubeCon, bring it up with your SIG chair and ask them to bring it up with SIG Contributor Experience.

**Comment by justaugustus** [comment]
Pending update on https://github.com/kubernetes/steering/pull/114.
/remove-lifecycle stale
/lifecycle frozen
/milestone v1.18

**Comment by LappleApple** [comment]
Research task: Would want to record any SteerCo decision regarding travel sponsorship. 

/assign @palnabarun 
/unassign @justaugustus

**Comment by justaugustus** [comment]
Assigning Jeremy as well.
/assign @jeremyrickard 
/milestone v1.22

**Comment by jeremyrickard** [comment]
This is still undecided at that SteerCO/CNCF level. 

This initial draft https://github.com/kubernetes/steering/pull/114 of a plan was closed in June of 2020. Per https://github.com/kubernetes/steering/issues/109, it looks like this is still pretty much on hold. 

I think that we should probably close this and just track the steerco issue, as that will likely be the answer for everyone. Once that is decided, we can work on any relevant sig-release policy.

**Comment by jeremyrickard** [comment]
/close in favor of tracking https://github.com/kubernetes/steering/issues/109

We'll open a new issue once the higher level issue is resolve 👍
