### ISSUE TITLE
Merging the tasking of turning of jobs for 1.12 release and creating jobs for 1.16 release

### ISSUE THREAD

**Issue by imkin** [kubernetes/sig-release#743]
The task `release-1.12 jobs removed` in the [release 1.16 timelines](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.16#timeline) needs to be moved to week 7 ( and hence merged with `release-1.16 jobs created` task).

To do this we should do the following

- [x] fix the [readme](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.16/README.md) 
- [x] fix the [calendar](https://bit.ly/k8s-release-cal) - This task requires higher superpowers . 

A more broader question is if there is a template for the release page (and other artifacts maintained [here](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.16). If there is we should fix it too. If there is none may be we should create it? 

@lachie83 @justaugustus @tpepper @kubernetes/release-engineering @kubernetes/release-team @kubernetes/release-managers

**Comment by lachie83** [comment]
Updated calendar - there is currently no template for the release schedule however I will look into creating one.

**Comment by lachie83** [comment]
All tasks complete - closing
