### ISSUE TITLE
Granting Carlos Panato (Release Manager Associate) temporary GCP access to cut 1.16.0-alpha.3

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#748]
We'd like to grant @cpanato temporary GCP access to cut Kubernetes 1.16.0-alpha.3.
Carlos is Release Manager Associate and has consistently been interested and active on Release Engineering issues/PRs/meetings.

Unfortunately, we currently don't have an easy/simple way to grant a minimal set of permissions for Release Managers Associates to get involved with the release process, but temporary access is a compromise we can make [as we work to develop more precise IAM roles for GCP users](https://github.com/kubernetes/sig-release/issues/732). 

Discussion on this (between @calebamiles, @tpepper, @listx, @spiffxp, and myself) is here (but it's a DM, so you won't be able to see it): https://kubernetes.slack.com/archives/GLXG498AD/p1565107017001500

We plan to revoke this access once the 1.16.0-alpha.3 release is cut.

To accommodate schedules, we're moving that release to tomorrow, Wednesday, 8/7.
This was discussed and approved by the 1.16 Release Team Lead (@lachie83) + Lead Shadows (@guineveresaenger, @jeefy, @nikopen) here: https://kubernetes.slack.com/archives/C2C40FMNF/p1565113571149900

I'll close this issue once the release is cut and I've revoked Carlos' access.

/assign
cc: @kubernetes/release-engineering 
/priority important-soon
/milestone v1.16

**Comment by justaugustus** [comment]
cc: @idealhack

**Comment by justaugustus** [comment]
I've granted @cpanato `OSS Kubernetes Release Manager` and `Viewer` roles within the `kubernetes-release-test` GCP project, which will give him the requisite access to cut the 1.16.0-alpha.3 release.

**Comment by guineveresaenger** [comment]
acknowledged - thank you @justaugustus!

**Comment by cpanato** [comment]
@justaugustus alpha release is cut you can revoke my access

thanks so much for the trust on me <3

**Comment by justaugustus** [comment]
Closing the loop on this. Thanks for releasing today, @cpanato!
/close
