### ISSUE TITLE
Document current usage of kubernetes version marker files

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#759]
There exists a set of kubernetes version marker files e.g., [`stable.txt`](https://storage.googleapis.com/kubernetes-release/release/stable.txt) which are leveraged across CI jobs, but we don't have a canonical explanation of what their values are, when they should be used/changed.

See the reviews in https://github.com/kubernetes/test-infra/pull/13870 and https://github.com/kubernetes/sig-release/pull/757 as an example.

As of today, we make some reference to them in [k/test-infra/docs/kubernetes-versions](https://github.com/kubernetes/test-infra/blob/de444e721bee5dcb5203a0d915ed66b392def117/docs/kubernetes-versions.md), but the explanations could be more exhaustive.

(This is explicitly for documenting the _current_ usage of these markers, not what may happen in the future. For future usage, see [here](https://github.com/kubernetes/sig-release/issues/850))

/assign
/milestone v1.16
/priority important-soon
/kind documentation
/area release-eng
cc: @kubernetes/sig-release-admins @kubernetes/release-engineering @spiffxp @BenTheElder @nikhita

**Comment by justaugustus** [comment]
Decent write-up about version marker files in the body of this PR: https://github.com/kubernetes/test-infra/pull/14030
I'll use that as and [this doc](https://github.com/kubernetes/kubeadm/blob/master/docs/testing-pre-releases.md) as the basis for the usage doc.

**Comment by LappleApple** [comment]
Heya, are we just waiting for the referenced usage doc to close this out? If so, is there anything we could delegate here? Based on the prioritization chats this week this remains high-priority.

**Comment by neolit123** [comment]
commented here with my 2c on what markers we should keep around:
https://github.com/kubernetes/sig-release/issues/850#issuecomment-669479097

**Comment by justaugustus** [comment]
Updated https://github.com/kubernetes/test-infra/blob/master/docs/kubernetes-versions.md with current usage in https://github.com/kubernetes/test-infra/pull/18290.

/close
