### ISSUE TITLE
release-engineering roles formerly on release-team lack tombstones

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/sig-release#761]
I think https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/branch-manager should at least have a tombstone pointing to https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/branch-manager.md

https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/patch-release-manager and pointing to https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/patch-release-manager.md

Ultimately I'm sure we want these to disappear entirely, but until we do that, tombstones would be helpful

/assign @justaugustus 
/area release-eng
/area release-team
/milestone v1.15
/sig release
/priority important-soon
/kind documentation
/kind bug
I put bug because I view this as a dead link

**Comment by spiffxp** [comment]
/milestone v1.16
typo

**Comment by justaugustus** [comment]
To be added as part of https://github.com/kubernetes/sig-release/pull/852.
/remove-help
/milestone v1.18
