### ISSUE TITLE
Document process/criteria by which we decide that Informing failures are tolerable

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#775]
A current draft (#752) of the release-blocking critieria says:

> Unlike Blocking, however, jobs in Informing do not need to be green before authorizing a release, they can be failing for known and "acceptable" reasons.

We need to document further the process by which CI Signal is supposed to decide that failures in Informing can be tolerated and do not block.  Also, who decides (CI Signal/Release Lead/owning SIG?).

**Comment by alejandrox1** [comment]
/milestone v1.17
btw
