### ISSUE TITLE
Assemble Kubernetes 1.17 Release Team

### ISSUE THREAD

**Issue by jberkus** [kubernetes/sig-release#776]
Believe it or not, it's that time already if we want to have a complete team by week 2 of the release cycle.

Please [review the Release Team Selection Process docs](https://github.com/kubernetes/sig-release/blob/master/release-team/release-team-selection.md) for details on the process and criteria.

Right now, we are calling strictly for nominees for Role Leads in this space.  Once we have a new Release Lead nominee, we will assemble a PR for the 1.17 Release Team docs.

Shadows will be selected via the Shadow Volunteer Form.

/sig release
/area release-team
/milestone v1.17

cc:
@lachie83 @justaugustus

**Comment by mayankshah1607** [comment]
Hello, @jberkus ! I would like to know when shall the Shadow Volunteer Forms be out, and the link for the same.
Thank you! :)

**Comment by jberkus** [comment]
@mayankshah1607 after the leads are selected.  Just watch Kubernetes-Dev mailing list for an announcement.

**Comment by alejandrox1** [comment]
I would like to start this and nominate @alenkacz to be the v1.16 CI signal lead.

**Comment by saschagrunert** [comment]
I'm happy to nominate @cartyc to be the v1.17 Release Notes lead. :tada:

**Comment by lachie83** [comment]
I would like to nominate @guineveresaenger for 1.17 release lead. Guin has done a tremendous job serving as release lead shadow in 1.16 and I believe she would make a great lead. Thanks Guin!

**Comment by simplytunde** [comment]
I will like to nominate @daminisatya to be v1.17 Docs Team Lead

**Comment by onlydole** [comment]
I want to nominate @rawkode for 1.17 communications lead. We both came up on 1.15 and 1.16, and he will do great work in 1.17

**Comment by jberkus** [comment]
@justaugustus and I nominate @claurence as EA for 1.17.

**Comment by kacole2** [comment]
Put @mrbobbytables as the Enhancement Lead for 1.17

**Comment by cpanato** [comment]
Do i need to apply again?

**Comment by justaugustus** [comment]
@cpanato -- the [Release Managers group](https://github.com/kubernetes/sig-release/blob/master/release-managers.md) is not part of the Release Team. 

I'll send separate communications about what we're planning to do there for next cycle, but in the meantime, there's no action required on your part.

(All of that to say, yes, you'll still be a part of the Release Managers group. :) )

**Comment by markyjackson-taulia** [comment]
I would love to shadow

**Comment by xmudrii** [comment]
I would like to nominate @josiahbjorgaard for 1.17 bug triage lead. Josiah did a great job this release cycle and I believe he will do great in 1.17 too! :tada:

On the other side, after 3 release cycles on the bug triage team, I would like to step down. Not sure are those roles covered by the survey, but I'd like to express interest in:
* the release team lead shadow role
* the release engineering associate

**Comment by justaugustus** [comment]
@guineveresaenger @claurence -- Looks like we've got all of the leads locked up!
I've opened https://github.com/kubernetes/sig-release/pull/792 which includes the 1.17 team to date.

**Comment by claurence** [comment]
With all the leads assembled we're ready to open up the form for shadows: If you have interest in shadowing 1.17 please fill out the form here: https://forms.gle/3rePTvKbLF96p6zMA

cc @mayankshah1607

**Comment by guineveresaenger** [comment]
for visibility: can all confirmed members of the 1.17 team please add their info in the following spreadsheet?
https://docs.google.com/spreadsheets/d/1FlOg__qKS4NCGZapYfo6ZsMiSf45VRjYgqwDg80Qr-M/edit?usp=sharing

**Comment by markyjackson-taulia** [comment]
I would love to become a shadow and have filled out the form

**Comment by mayankshah1607** [comment]
Hi :) . I just wanted to know when the shadows will be announced

**Comment by justaugustus** [comment]
@mayankshah1607 -- We'll finalize selection for shadows tonight and notify everyone by next week. Thanks for your patience!

**Comment by guineveresaenger** [comment]
As we have a fully staffed release team, I will close this issue.

Thank you all for serving on this wild ride with me - I am honored to have every one of you on board.

Regarding those who aren't on the team this time around, I am happy and grateful to see that there is so much interest and that we will have an easy time staffing future release teams as well.

The release team is an open process/effort - meetings are open to everyone, questions and help are welcome.

Thank you all. ❤️
