### ISSUE TITLE
Move existing documentation from community/sig-release here

### ISSUE THREAD

**Issue by jdumars** [kubernetes/sig-release#8]
We need to ensure historical documentation is moved here for context and ease of use.  This process needs to be non-destructive since this change has not been radiated to the larger community.

**Comment by calebamiles** [comment]
First [attempt][] at listing the docs. I'll try and extract later today.


[attempt]: https://gist.github.com/calebamiles/24f362a28ed3596887e80c3b4e870e52

**Comment by calebamiles** [comment]
The extraction of the listed files is complete. All the old files remain in `kubernetes/community` and we will need to file a PR to update people to the new location. Marking the extraction done for now.
