### ISSUE TITLE
anago build path for tagged releases includes prior tag + commit offset, and is confusing

### ISSUE THREAD

**Issue by liggitt** [kubernetes/sig-release#819]
When building a release, anago appears to place source in a folder named using something like `git describe`. Because builds are done prior to tagging a release, that means that the build folder has the previous tag plus some number of offset commits.

Examples:
* https://github.com/kubernetes/kubernetes/issues/82854 reported against 1.16.0, stack trace had `/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b`
* https://github.com/kubernetes/kubernetes/issues/83440 reported against 1.13.12, stack trace had `/workspace/anago-v1.13.11-beta.0.31+25074a190ef2a0`

This is really confusing and makes it appear as if the user is running a non-GA build.

Can we do something like one of the following:
* if the build is part of a tagged release, create the tag prior to determining the name of the folder
* change the folder to just use the commit sha (no tag)

**Comment by liggitt** [comment]
alternately, use the -trimpath option once we get to go 1.13 that drops filesystem paths from the built binary

**Comment by lachie83** [comment]
Also seeing this more recently with 1.16.5 and 1.15.8 specifically (I know the release team are working on tooling issues so just wanted to draw attention to this). The `GitVersion` field doesn't match the release version directory `kubectl` was pulled from.
```
$ curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.5/bin/darwin/amd64/kubectl && chmod +x ./kubectl && ./kubectl version --client
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 46.5M  100 46.5M    0     0  28.3M      0  0:00:01  0:00:01 --:--:-- 28.3M
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
```

```
$ curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.8/bin/darwin/amd64/kubectl && chmod +x ./kubectl && ./kubectl version --client
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 46.3M  100 46.3M    0     0  24.1M      0  0:00:01  0:00:01 --:--:-- 24.1M
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-beta.0", GitCommit:"14ede42c4fe699a7078b566d89abc160f26857a2", GitTreeState:"clean", BuildDate:"2020-01-15T11:15:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by lachie83** [comment]
What this means is that `https://storage.googleapis.com/kubernetes-release/release/v1.15.9-beta.0/bin/darwin/amd64/kubectl` and `https://storage.googleapis.com/kubernetes-release/release/v1.15.8/bin/darwin/amd64/kubectl` have the same `GitVersion`. Which represents a change in behavior
