### ISSUE TITLE
Improve doc release handbook

### ISSUE THREAD

**Issue by daminisatya** [kubernetes/sig-release#834]
1. Explain why we need release-[current release], dev-[future release] branches. 
2. Importance of the Integration branch and the contents to go in the issue description. 
3. Example message to send to the enhancement owners to followup for docs

**Comment by alejandrox1** [comment]
/cc @VineethReddy02 @sethmccombs @irvifa @savitharaghunathan @iheanyi1 
ptal

**Comment by savitharaghunathan** [comment]
1 & 2 are done. 3 is tracked in a separate effort. Closing this issue.

/close
