### ISSUE TITLE
Document reason for inclusion of release blocking jobs

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#838]
Hello internet, in this issue I want to cover a black hole in our [release blocking criteria](https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md#release-blocking-criteria-and-dashboard) : 
> Have a documented reason for its inclusion in the Blocking suite

This is a requirement for release blocking jobs that we have not addressed.
However, the existence of such record could help us detect areas where we need to improve our testing, see block releases on non-synthetic clusters #829 for an example of such a case.

Thus, I want to open up this issue and propose we start by documenting the existing jobs, document the type of tests they run (i.e., disruptive, feature:x), document the type of infrastructure they use to run jobs (synthetic or real clusters), along with any other reason for inclusion and group them based on this information.
I propose we add this information in a simple README-like document at the same level of the release blocking criteria document - we can always move it somewhere else of copy and paste into another format, what matters is that we start.

/area release-team
/sig release
/milestone v1.17
/priority critical-urgent
/cc @kubernetes/release-team 
/cc @justaugustus @tpepper @guineveresaenger

**Comment by guineveresaenger** [comment]
Could we also do a roundup of related issues here? That would be really helpful.

**Comment by alejandrox1** [comment]
getting my life in order but let me give an update on this...
so there is some ongoing work on documenting the important bits of our jobs and that is all here 
https://docs.google.com/document/d/1SICz8QP_-F4SnTAsuhdErRtgCFlXc8yZFGLe8EXY6-E/edit?usp=sharing

this bit is gonna take a bit to polish so i'll move it to the next milestone
/milestone v1.18
/lifecycle active
