### ISSUE TITLE
New release- branches with no changes have that commit double-tagged

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/sig-release#85]
When the release-1.10 branch was created, we ended up in a new situation where the branch point commit was tagged with both the master branch (alpha) and release branch tags (beta).  This was due to a [recent commit to the tooling which excluded a change to the branch at branch time](https://github.com/kubernetes/release/pull/507) which provided the opportunity to then tag the branch at branch-point + 1.  

The immediate remedy here to set the master branch straight so it is 'git describe'ing correctly was to remove the (beta) tag from the commit.

Proposal 1:

- [x] Submit [a change to the release-1.10 branch ](https://github.com/kubernetes/kubernetes/pull/59960)solely for the purposes of tagging
- [x] Tag the release-1.10 branch with v1.10.0-beta.0
- [x] Update anago to [make a change to the release branch at branch time](https://github.com/kubernetes/release/pull/519) so it can be tagged

~~Proposal 2:~~

- [ ] Wait for the first branch fast-forward and tag v1.10-0-beta.0 at branch-point + 1
- [ ] Update anago to no longer add a new tag to the master at branch time
- [ ] Update branchff to take an option to manually to tag the master branch with the new tag after the "last" fast-forward is done. Humans required.  Fragile.  Scary.

cc @calebamiles @enisoc @kubernetes/test-infra-maintainers @jdumars 
ref https://github.com/kubernetes/kubernetes/issues/59895

**Comment by jdumars** [comment]
thank you for quickly figuring this out!

**Comment by calebamiles** [comment]
@david-mcmahon, do we really want to make a dummy change to the `release-1.10` branch since our ultimate goal is to be able to fast forward master into the `release-1.10` branch or do we just want to fast forward master onto the branch today and cut the build?

**Comment by david-mcmahon** [comment]
Do I *want* to make a dummy change?  No.  Do we need to?  Possibly.  If we wait til the first branch fast forward, then the branch will continue to 'git describe' as v1.11.0-alpha.0 until then.  That may have unforeseen ramifications.  Also, when we finally do fast-forward, we'll want to put the tag at branch-point + 1, which is odd and fragile as well.

**Comment by calebamiles** [comment]
I'm worried about having a change which exists on master but not on the `release-1.10` branch

**Comment by ixdy** [comment]
another question: why are we even creating an alpha tag now? everything on master is still slated to end up in 1.10.

**Comment by david-mcmahon** [comment]
@calebamiles, there have always been changes that landed on the release branch at branch time.  It would be ideal to replace the one we removed with another useful branch-specific, branch time change.

**Comment by calebamiles** [comment]
I suppose I still don't understand why we have branch specific changes made when cutting the branch. In my mind the steps I should do are

1. `git checkout upstream/master`
1. `git checkout -b release-1.10`
1. `git push origin HEAD`
1. `./anago release-1.10`

**Comment by david-mcmahon** [comment]
@ixdy, taking yet another step back, why are we even branching before we really want a branch? 

Having gone to that model has created quite a bit of juggling ([here](https://github.com/kubernetes/release/blob/master/branchff#L119), [here](https://github.com/kubernetes/release/blob/master/branchff#L157) and [here](https://github.com/kubernetes/release/blob/master/anago#L1092)) in the tooling to guard against unintended consequences.  

Having said that, yes, if we stick with this branch-and-fast-forward model, we could forego the alpha tag on master.  This of course will require many tooling changes including to those guards above and it's someone of a paradigm shift in the way we think of branching.  Expect fallout.

**Comment by david-mcmahon** [comment]
@calebamiles the history of changes to the branch at branch time included updating docs and pkg/version/base.go. Those were (at the time) reasonable changes, but are no longer necessary.
WRT to your steps above, all of it is handled via anago.

**Comment by calebamiles** [comment]
I suppose that was my proposal for how to reenter into a place where anago handles things again

**Comment by enisoc** [comment]
My impression is that changing the process to move branching until later is a bigger risk than David's "Proposal 1".

In case it wasn't clear above, it has already been the case historically that the release branch has commits that master doesn't. The term "fast-forward" for `branchff` has been a misnomer for a while; it's actually a merge commit. So the dummy commit in Proposal 1, while conceptually ugly, should be technically equivalent to the way things have been done for previous releases.

I don't think doing a `branchff` before tagging will help at this point. Since there are no commits on the release branch that aren't on master, it will end up (for once) doing an actual fast-forward with no merge commit, unless we modify the script to force one. That means we'll still end up tagging a commit that also exists on master, and master will once again `git describe` as being 1.10-beta instead of 1.11-alpha.

**Comment by david-mcmahon** [comment]
@enisoc thanks for highlighting and raising that important point.  So now to figure out a good post-branch replacement commit that's at least somewhat useful.

**Comment by david-mcmahon** [comment]
Tag [v1.10.0-beta.0 updated on release-1.10 branch](https://github.com/kubernetes/kubernetes/releases/tag/v1.10.0-beta.0).  This should finally resolve the orphaned v1.10.0-beta.0 tag issue.
