### ISSUE TITLE
Track enhancement slip across multiple releases

### ISSUE THREAD

**Issue by jeefy** [kubernetes/sig-release#857]
We should look across multiple releases to check the following:
- Has an enhancement slipped across multiple releases?
- Is there a specific SIG that has statistically more slips than others?

We might be able to use these metrics to identify SIGs that need help.

/assign @jeremyrickard 
/cc @mrbobbytables 
/area release-team
/kind cleanup
/priority important-longterm

**Comment by jeremyrickard** [comment]
I did a first pass of this after 1.17. I'll do a last pass after code freeze for 1.18 and present the results at a sig release meeting after!

**Comment by LappleApple** [comment]
Noting that we've been talking about this topic during the RT prioritisation sessions but I'm only now becoming aware of this particular issue. I've added it to my spreadsheet but we might be able to combine it with another enhancements-tracking issue.

**Comment by LappleApple** [comment]
Hey, during the RT prioritisation sessions it was mentioned that @johnbelamaric and @liggitt are involved in discussions about how we might establish a process around “this has been around for multiple releases, let’s either close or not” enhancements. Wondering if there is another issue filed on this topic in sig-arch/enhancements/other, or if they might be added to this one to centralise the conversation?

**Comment by LappleApple** [comment]
Closing as per @jeremyrickard: "from a “slip” perspective for 1.20 or any going forward, I don’t think we need to track long term things anymore. There aren’t that many because things either:
• finally got through
• got closed
• special cases / on hold (like sidecars)
