### ISSUE TITLE
Assemble Kubernetes 1.18 Release Team 

### ISSUE THREAD

**Issue by claurence** [kubernetes/sig-release#871]
It's that time to start assembling the 1.18 release team 

Please review the Release Team Selection Process docs for details on the process and criteria.

Right now only looking for nominations for Role Leads.  Once role leads are nominated we will then send out a shadow application survey.

/sig release
/are release-team
/milestone v1.18

cc @guineveresaenger @justaugustus @tpepper

**Comment by alenkacz** [comment]
I would like to nominate @droslean for a CI signal lead 🎉 he was a great help as a shadow and was driving a lot of innovation in the ci signal team 👏

**Comment by rawkode** [comment]
I'd like to nominate and recommend @karenhchu for Communications Lead 👍

**Comment by justaugustus** [comment]
Until we select the 1.18 RT Lead + Emeritus Adviser:
/assign @claurence @guineveresaenger

**Comment by cartyc** [comment]
I would like to nominate @evillgenius75 for Release Notes Lead 😃

**Comment by mrbobbytables** [comment]
I would like to nominate @jeremyrickard for Enhancements lead for 1.18 🎉

**Comment by daminisatya** [comment]
I would like to nominate @VineethReddy02 for Docs lead 1.18 ✨ 😄

**Comment by claurence** [comment]
@lachie83 will be taking on the emeritus advisor position for 1.18

**Comment by josiahbjorgaard** [comment]
I'll nominate @smourapina as bug triage lead for the next release cycle.

**Comment by guineveresaenger** [comment]
It is with pleasure and confidence that I nominate @alejandrox1 as overall Lead for the Kubernetes 1.18 Release team. You're going to knock it out of the park, Jorge!

All of my shadows, which are further @jeefy and @mariantalla, have been indispensable in their help and assistance, and I'm lucky in that you would both have been awesome choices as well, since y'all are so good at this! Day jobs were a real consideration in this decision, and I have faith that future releases beyond 1.18 will be in very good hands as well.

**Comment by justaugustus** [comment]
PR up for the Kubernetes 1.18 Leads and Emeritus Adviser: https://github.com/kubernetes/sig-release/pull/884

**Comment by justaugustus** [comment]
The shadow application is now live: https://forms.gle/a7B47vmxKtTJH9QE8

Note to kubernetes-dev: https://groups.google.com/d/topic/kubernetes-dev/759DW_DynrY/discussion
Tweet: https://twitter.com/stephenaugustus/status/1207059454841229313?s=20

**Comment by lachie83** [comment]
Kubernetes 1.18 release selection is complete. Roster [here](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.18/release_team.md)
