### ISSUE TITLE
Add Action Required Release Notes Process

### ISSUE THREAD

**Issue by cartyc** [kubernetes/sig-release#882]
Need to define the process by which we create action required release notes that do not have an associated PR or issue.

/area release-team

cc: @justaugustus

**Comment by alejandrox1** [comment]
/cc @evillgenius75 
wdyt?

**Comment by reylejano-rxm** [comment]
@evillgenius75 can you provide details and/or background-info

**Comment by reylejano-rxm** [comment]
Hello @cartyc, can you fill me in on this issue

**Comment by cartyc** [comment]
If I recall correctly it has to do with addressing the lack of a process for intaking a Release Note that the RN tool does not pick up and needs to be added manually.

**Comment by saschagrunert** [comment]
> If I recall correctly it has to do with addressing the lack of a process for intaking a Release Note that the RN tool does not pick up and needs to be added manually.

Created a PR which fixed this: https://github.com/kubernetes/release/pull/1073
