### ISSUE TITLE
Update Patch Release Team documentation

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#890]
Perusing the [Patch Release Team handbook](https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/patch-release-team.md), there are probably a few doc updates we could make.

As an incoming Patch Release Team member, I can take a crack at this.

Update should include verbiage to address @tpepper's review comment on https://github.com/kubernetes/sig-release/pull/868#issuecomment-560486772:
> Maybe we should consider formalizing that patch release managers are also expected to be branch managers now, where they were historically focused on a more trailing set of support tasks?

/assign
/milestone v1.18
/priority important-soon
/kind documentation cleanup

**Comment by tpepper** [comment]
We sometimes actively mentor prospective participants in this flow, outside of ones accepted as an "associate" formally.  We should strive to keep our artifacts and processes accessible to these folks so they can get a little view of how things happen and be led to believe they can safely participate if they step up.

**Comment by justaugustus** [comment]
Add notes on what our process is leading up to patch release dates:
- Freezing PRs
- Announcing deadlines
- Hold context

ref: https://kubernetes.slack.com/archives/GKEA5EL67/p1578681696008400 (<--- that's from #release-private, so only Patch Release, Branch Managers, and SIG Chairs will be able to see those messages)
