### ISSUE TITLE
Release Manager access for @saschagrunert

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/sig-release#893]
### GitHub Username

@saschagrunert 

### [Release Manager](https://git.k8s.io/sig-release/release-managers.md) role

Branch Manager

### Tenure

permanent

### Release Manager Onboarding

**All pull requests within these checklists should be marked with an _explicit_ hold and only released once approved by a Release Engineering subproject owner.**

- [X] Addition of a new Release Manager has been discussed with and approved by Release Engineering subproject owners
- [X] Ensure new Release Manager:
  - [X] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [X] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [X] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
- [X] Update [Release Managers](/release-managers.md) page to include the new Release Manager

### Branch Manager

- [x] Release Manager has agreed (on this issue) to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md),
  specifically the embargo on CVE communications
- [x] (https://github.com/kubernetes/org/pull/1440) Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-managers`
  - `release-engineering`
  - `sig-release`
- [x] Update `OWNERS`
  - (https://github.com/kubernetes/sig-release/pull/868) `kubernetes/sig-release` `OWNERS_ALIASES`
    - Add entry in the `branch-managers` section
  - (https://github.com/kubernetes/release/pull/950) `kubernetes/release` `OWNERS_ALIASES`
    - Add entry in the `branch-managers` section
  - (https://github.com/kubernetes/test-infra/pull/15465) `kubernetes/test-infra`
    - Add as reviewer for SIG Release `OWNERS`
- [x] (https://github.com/kubernetes/k8s.io/pull/481) Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-editors@`
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [x] Manually grant permission to post on [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
- [x] Manually add to the [Release Team Google Group](https://groups.google.com/forum/#!forum/kubernetes-release-team)
- [x] (https://github.com/kubernetes/community/pull/4284) Update Slack `release-managers` User Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)

cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
@saschagrunert -- Before I can close this out, I just need you to agree to the security release process in an issue comment, like this: https://github.com/kubernetes/sig-release/issues/892#issuecomment-562571918.

**Comment by saschagrunert** [comment]
I've read the [Security Release Process](https://git.k8s.io/security/security-release-process.md) and I agree to uphold it and the security embargo.

**Comment by saschagrunert** [comment]
All accesses to the google groups look good as well now. :)

**Comment by justaugustus** [comment]
Thanks Sascha!
/close
