### ISSUE TITLE
Update documentation around the security release process

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#896]
Carrying over discussion from https://github.com/kubernetes/sig-release/issues/732#issuecomment-561828879...

To better filter the audiences for security release communications, we (@kubernetes/release-engineering + @kubernetes/product-security-committee) are proposing the use of an additional kubernetes.io group (`security-release-team@`).

Membership to `security-release-team` will be restricted to:
- `security@` (PSC)
- `release-managers-private@` (SIG Release Chairs, Patch Release Team, Branch Managers)

If/when https://github.com/kubernetes/k8s.io/pull/492 merges, we will need to issue updates to, at a minimum:
- [ ] [Security Release Process](https://git.k8s.io/security/security-release-process.md) - https://github.com/kubernetes/security/issues/63
- [x] (https://github.com/kubernetes/sig-release/pull/900) [Release Managers](https://github.com/kubernetes/sig-release/blob/master/release-managers.md)
- [x] (https://github.com/kubernetes/sig-release/pull/900) [Release Manager onboarding template](https://github.com/kubernetes/sig-release/blob/master/.github/ISSUE_TEMPLATE/release-manager.md)

ref: https://groups.google.com/a/kubernetes.io/d/topic/security/E_yV--bf-8c/discussion

/assign
/area release-eng
/milestone v1.18
/priority important-soon
/kind documentation cleanup

**Comment by justaugustus** [comment]
https://github.com/kubernetes/k8s.io/pull/492 has merged and the mailing list updates have been applied.
I'll proceed with the doc updates after I cut 1.17.0.

**Comment by saschagrunert** [comment]
We can also cover the release engineering process and documentation within this issue. 

My idea of a lightweight process:

1. PSC shares the embargoed information with the release managers (still manually and ad-hoc)
2. Release managers use krel to "publish" the information right before `krel stage` in a dedicated krel subcommand. Publishing means only that we put the CVE/YAML mapping to the public Google Cloud buckets.
3. `krel stage` will pickup this information and put it into the release notes.

This is a simple process which still enhances the automation. A few lines of documentation within the release managers handbook seems sufficient, too.

Solves: https://github.com/kubernetes/release/issues/1354
Ref: https://github.com/kubernetes/release/pull/1441

**Comment by saschagrunert** [comment]
Still depends on https://github.com/kubernetes/security/issues/63

**Comment by saschagrunert** [comment]
Sill depends on https://github.com/kubernetes/committee-security-response/pull/129
