### ISSUE TITLE
Ensure RT Lead handbook includes an item for adding the release retrospective event to the release calendar

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#910]
We need to add to the release team lead handbook a note about creating the release retrospective event in the release calendar in order to ensure all the members of the release team get an invite.

The following groups should get invites
* kubernetes-release-team@googlegroups.com
* release-managers@kubernetes.io 

Calendars should get invites too:
* Community [`cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com`](https://calendar.google.com/calendar/embed?src=cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com)
* Release [`agst.us_b07popf7t4avmt4km7eq5tk5ao@group.calendar.google.com`](https://calendar.google.com/calendar/embed?src=agst.us_b07popf7t4avmt4km7eq5tk5ao@group.calendar.google.com)

/priority important-soon
/milestone v1.18
/sig release
/assign

**Comment by guineveresaenger** [comment]
This has been fixed I believe.

**Comment by alejandrox1** [comment]
/reopen
as a remainder to double check this with https://github.com/kubernetes/sig-release/pull/917

**Comment by alejandrox1** [comment]
also, where/when was it fixed?
was there a PR to add this bit to the handbook?

**Comment by guineveresaenger** [comment]
I tried to find it! I may have simply missed it and it was there all along. :(

**Comment by alejandrox1** [comment]
Gonna work on this this week
