### ISSUE TITLE
Improve final release notes draft PR timings

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/sig-release#913]
The final release notes draft has to be merged on the release day right before the final build starts running. We traditionally do that so late, because we want to ensure that every change is included and the “major themes” are under embargo until the last moment.

If the timing does not get applied correctly, then we end up having an simple generated release notes document in k/k like we get for the patch releases. 

I would like to address this issue technically without modifying the currently working process too much. So we could:

- break the build if the final draft is not available on a minor release
- use a non-git based resource (we usually use gdocs or hackmd for the edits under embargo) to pull the notes (the notes end up in any case in the k/k repo we have no need to have a copy in other repos as well)
- merge the draft early and pull the embargoed major themes from a remote resource like gdocs

Let’s collect more input here folks. :)

**Comment by justaugustus** [comment]
/remove-lifecycle stale
Sascha to link handbook updates.

**Comment by saschagrunert** [comment]
I think the handbooks are already up-to-date:
- Release Lead Handbook: https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/release-team-lead#week-12
  > Release Notes Lead PRs final draft release notes to sig-release, with Release Team Lead approving merge.
- Release Notes Handbook: https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/release-notes#week-12
  > Release Notes must be merged into master prior to the release. If this is not done the release will include the latest draft.

Closing this now, feel free to reopen if there is still anything missing.
