### ISSUE TITLE
Update Enhancements handbook

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#918]
Friendly call for the team to revisit and update the [enhancements handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/enhancements).

It may also be useful to take a look at the topics from the [1.17 release retrospective](https://docs.google.com/document/d/1AtZ_81F3E4y_04Gx31mnG5w6AG3E0AXDOuLU7RcUIso/edit#heading=h.ukbaidczvy3r).

/milestone v1.18
/priority important-soon
/kind documentation cleanup

**Comment by alejandrox1** [comment]
/assign @mrbobbytables @jeremyrickard 
ptal

**Comment by mrbobbytables** [comment]
It was recently updated in https://github.com/kubernetes/sig-release/pull/911 👍

**Comment by mrbobbytables** [comment]
I think this is safe to close now? It was updated in #911 by me and later in #936 by @jeremyrickard .

**Comment by justaugustus** [comment]
Yep!
/close
