### ISSUE TITLE
Update CI signal team handbook

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#919]
Friendly call for the team to revisit and update the [CI signal handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/ci-signal).

It may also be useful to take a look at the topics from the [1.17 release retrospective](https://docs.google.com/document/d/1AtZ_81F3E4y_04Gx31mnG5w6AG3E0AXDOuLU7RcUIso/edit#heading=h.ukbaidczvy3r).

/milestone v1.18
/priority important-soon
/kind documentation cleanup
/assign @droslean @alenkacz

**Comment by droslean** [comment]
Work that is already done: https://github.com/kubernetes/sig-release/pull/984

**Comment by alejandrox1** [comment]
This is good to go now
/close
