### ISSUE TITLE
Update Release Notes handbook

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#922]
Friendly call for the team to revisit and update the [release notes handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/release-notes).

It may also be useful to take a look at the topics from the [1.17 release retrospective](https://docs.google.com/document/d/1AtZ_81F3E4y_04Gx31mnG5w6AG3E0AXDOuLU7RcUIso/edit#heading=h.ukbaidczvy3r).

/milestone v1.18
/priority important-soon
/kind documentation cleanup
/assign @evillgenius75 @cartyc

**Comment by cartyc** [comment]
Hi @alejandrox1, Thanks for the reminder! I'm working on updating the handbook in the following PR https://github.com/kubernetes/sig-release/pull/916

**Comment by reylejano-rxm** [comment]
Hi @cartyc, were there any updates to the Release Notes handbook.
Are there any other specific sections/topics other than 'kind documentation cleanup' that needs updating?

**Comment by cartyc** [comment]
Hi @reylejano-rxm :wave: I had put in a few changes to the docs in PR #916 , which should have caught most of the issues we bumped into last cycle.

Nothing jumps out at me right now for things that need additional updating, I will review the doc and if something does I will let you know.

**Comment by reylejano-rxm** [comment]
Hi @cartyc, thank you for replying. Since the updates for this issue is in PR[ #916](https://github.com/kubernetes/sig-release/pull/916) which has been merged , can we close this issue.

**Comment by cartyc** [comment]
Sounds good, sorry I should have said it was good to close in my last comment :) Thanks @reylejano-rxm!

**Comment by reylejano-rxm** [comment]
We can close since updates for this issue are in the merged PR [#916](https://github.com/kubernetes/sig-release/pull/916) 
/close
