### ISSUE TITLE
Update Communications handbook

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#923]
Friendly call for the team to revisit and update the [communications handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/enhancements).

It may also be useful to take a look at the topics from the [1.17 release retrospective](https://docs.google.com/document/d/1AtZ_81F3E4y_04Gx31mnG5w6AG3E0AXDOuLU7RcUIso/edit#heading=h.ukbaidczvy3r).

/milestone v1.18
/priority important-soon
/kind documentation cleanup
/assign @karenhchu @rawkode

**Comment by rawkode** [comment]
Pending #929 
Merged #914

**Comment by mkorbi** [comment]
Update comms handbook
https://github.com/kubernetes/sig-release/pull/986

**Comment by mkorbi** [comment]
Updated! I think it can be closed @karenhchu 
https://github.com/kubernetes/sig-release/pull/986
