### ISSUE TITLE
Release Team Lead access for alejandrox1, mrbobbytables, and onlydole

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/sig-release#933]
### GitHub Username(s)
- @alejandrox1 
- @onlydole
- @mrbobbytables 

### Release Cycle

Kubernetes 1.18

### Prerequisites

- [x] Ensure new Release Team Lead:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)

### Onboarding

- [x] Release Team Lead has agreed to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md), specifically the embargo on CVE communications.
  This must be done as an issue comment by the incoming Release Team Lead.
- [x] Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
  - `sig-release`
- [x] Update `kubernetes/sig-release` `OWNERS`
  - Release Team Lead and Shadows
    - Add an `approvers` entry in `releases/release-x.y/OWNERS`
  - **Release Team Lead only**
    - In `OWNERS_ALIASES`, add an entry in the following sections:
      - `release-team`
      - `release-team-lead-role`
- [x] Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [x] Manually grant access on the following Google Groups:
  - [kubernetes-release-team](https://groups.google.com/forum/#!forum/kubernetes-release-team) (Add as Manager)
  - [kubernetes-sig-leads](https://groups.google.com/forum/#!forum/kubernetes-sig-leads) (Add as Member)
- [x] Grant calendar access
- [x] Grant Zoom credentials (host key)

### Offboarding

- [x] (https://github.com/kubernetes/org/pull/1785) Remove from GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-team`
  - `release-team-leads`
- [x] (https://github.com/kubernetes/k8s.io/pull/742) Remove from Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-viewers@`
  - `release-managers@`
- [x] Manually remove from the following Google Groups:
  - [kubernetes-release-team](https://groups.google.com/forum/#!forum/kubernetes-release-team) (Add as Manager)
  - [kubernetes-sig-leads](https://groups.google.com/forum/#!forum/kubernetes-sig-leads) (Add as Member)

cc: @kubernetes/release-engineering @kubernetes/release-team

**Comment by alejandrox1** [comment]
I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

**Comment by justaugustus** [comment]
@alejandrox1 -- Can you add your username to this list and update the issue title to include your usernames?

Also, do you want to take care of the PRs and then tag me for review?
/assign @justaugustus @alejandrox1

**Comment by alejandrox1** [comment]
@justaugustus yes (will update with usernames) and yes will take care of PRs as we speak.
Will ping you when this is ready

**Comment by alejandrox1** [comment]
As per the offboarding part of the template, I converted @guineveresaenger @jeefy and @mariantalla into members of the kubernetes-release-team google group.

**Comment by alejandrox1** [comment]
As per the onboarding section of the template, I made @daminisatya and @mrbobbytables managers of the kubernetes-sig-leads google group.

However, all 3 of us need to be added as members of kubernetes-sig-leads

**Comment by alejandrox1** [comment]
Updates on this (for the couple things that are not waiting for review)...
> Manually remove from the following Google Groups:
>  * kubernetes-release-team (Add as Manager)
>  * kubernetes-sig-leads (Add as Member)

I added @mrbobbytables and @daminisatya as managers to kubernetes-release-team and off-boarded the previous rt lead and shadows.
Just need to add and remove people from kubernetes-sig-leads.

Also, need access to the calendar and may be host key for zoom (I have the one from previous cycle).
/cc @justaugustus @tpepper

**Comment by justaugustus** [comment]
@alejandrox1 -- Looks like we've got most things squared away here, but I just want to confirm with you.

@mrbobbytables @daminisatya -- You still need to comment that you're aware of and agree to uphold the Security Release Process ([example](https://github.com/kubernetes/sig-release/issues/933#issuecomment-570252033)).

**Comment by mrbobbytables** [comment]
Ah, my bad^^:;;;;

I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

/pony salute

**Comment by alejandrox1** [comment]
@justaugustus seems like onboarding part is good to go pending @daminisatya going through the security releaseprocess.

Offboarding part, need to follow up on https://github.com/kubernetes/org/pull/1513#issuecomment-572080908 and manually remove previous release leads from the kubernetes-sig-leads group.

**Comment by alejandrox1** [comment]
Adding @onlydole to the lead team (thank you very much for volunteering to help :heart: )

**Comment by onlydole** [comment]
Thank you for the opportunity of a lifetime! I’m looking forward to it :smile:

**Comment by alejandrox1** [comment]
@onlydole i'll start sending PRs to get you set up but meanwhile,can you please comment that you're aware of and agree to uphold the Security Release Process (see the first couple comments)

**Comment by onlydole** [comment]
Absolutely!


I solemnly swear to abide by the guidelines set forth in the Security Release Process, specifically the embargo on CVE communications.

/woof

**Comment by justaugustus** [comment]
Awesome! Welcome to the squad, @onlydole!

@alejandrox1 -- Please ensure that all update PRs add Taylor AND remove Damini where appropriate.

**Comment by alejandrox1** [comment]
Onboarding seems to be completed.

For the off boarding process I removed the previous RT lead and shadows as manager of the kubernetes-release-team mailing list.
Everything else is yet to be done @justaugustus

**Comment by justaugustus** [comment]
@alejandrox1 -- Just a heads-up that the offboarding section is meant for your offboarding, not the previous Leads.

**Comment by alejandrox1** [comment]
In that case this is all set i guess.

**Comment by alejandrox1** [comment]
In that case this is all set i guess.
Should we close the issue or move it to the backlog?

**Comment by alejandrox1** [comment]
Time to off-board me (mostly) :crying_cat_face:

**Comment by justaugustus** [comment]
Offboarding for @alejandrox1 started here: https://github.com/kubernetes/org/pull/1785

**Comment by justaugustus** [comment]
Will be closed via https://github.com/kubernetes/k8s.io/pull/742.
