### ISSUE TITLE
Release Manager access for Daniel Mangum (@hasheddan)

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#978]
### GitHub Username

@hasheddan 

### [Release Manager](/release-managers.md) role

Release Manager Associate

### Tenure

temporary Branch Manager / permanent Release Manager Associate

### Release Manager Onboarding

**All pull requests within these checklists should be marked with an _explicit_ hold and only released once approved by a Release Engineering subproject owner.**

- [x] Addition of a new Release Manager has been discussed with and approved by Release Engineering subproject owners
- [x] Ensure new Release Manager:
  - [x] Has joined the following mailing lists:
    - [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release)
    - [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev)
  - [x] Has joined the following Slack channels:
    - [#sig-release](https://kubernetes.slack.com/messages/C2C40FMNF)
    - [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y)
  - [x] Is a [Kubernetes GitHub org member](https://github.com/kubernetes/community/blob/master/community-membership.md#member)
- [ ] Update [Release Managers](https://git.k8s.io/sig-release/release-managers.md) page to include the new Release Manager

### Branch Manager (temporary for `1.18.0-alpha.4`)

**Daniel will be granted temporary Branch Manager access to cut `1.18.0-alpha.4` and then access will be adjusted to Release Manager Associate level**

- [ ] ~Release Manager has agreed (on this issue) to abide by the guidelines set forth in the
  [Security Release Process](https://git.k8s.io/security/security-release-process.md),
  specifically the embargo on CVE communications~
- [x] (https://github.com/kubernetes/org/pull/1620) Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - `milestone-maintainers`
  - `release-managers`
  - `release-engineering`
  - `sig-release`
- [ ] ~Update `OWNERS`~
  - ~`kubernetes/sig-release` `OWNERS_ALIASES`~
    - ~Add entry in the `branch-managers` section~
  - ~`kubernetes/release` `OWNERS_ALIASES`~
    - ~Add entry in the `branch-managers` section~
  - ~`kubernetes/test-infra`~
    - ~Add as reviewer for SIG Release `OWNERS`~
- [x] (https://github.com/kubernetes/k8s.io/pull/565) Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - `k8s-infra-release-editors@`
  - `k8s-infra-release-viewers@`
  - `release-managers@`
  - ~`release-managers-private@`~
- [x] Manually grant permission to post on [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)
- [x] Manually add to the [Release Team Google Group](https://groups.google.com/forum/#!forum/kubernetes-release-team)
- [ ] ~Update Slack `release-managers` User Group [(`kubernetes/community`)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)~

### Release Manager Associate

- [x] (https://github.com/kubernetes/org/pull/1621) Update GitHub teams [(`kubernetes/org`)](https://git.k8s.io/org/config/kubernetes/sig-release/teams.yaml)
  - Remove from `release-managers`
- [x] (https://github.com/kubernetes/k8s.io/pull/566) Update Google Groups/GCP IAM membership [(`kubernetes/k8s.io`)](https://git.k8s.io/k8s.io/groups/groups.yaml)
  - Remove from `k8s-infra-release-editors@`
- [x] Manually remove permission to post on [kubernetes-announce](https://groups.google.com/forum/#!forum/kubernetes-announce)

cc: @kubernetes/release-engineering

**Comment by justaugustus** [comment]
@hasheddan has been an immense asset to the Release Engineering subproject and has expressed interest in helping to cut releases. I think he should be added to the Release Manager Associates group.

I'll proceed with onboarding tomorrow, if there are no objections.

**Comment by justaugustus** [comment]
With @saschagrunert, @tpepper, and myself in favor, I think we're clear to proceed here.

**Comment by saschagrunert** [comment]
Big +1 from my side 😊
