### ISSUE TITLE
Manually push 1.18.0-alpha.4 tag and cut 1.18.0-alpha.5 release

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/sig-release#985]
## Scheduled to happen: ~Tue, 2020-02-11~ Wed, 2020-02-12

- [x] Screenshot unhealthy release branch testgrid boards and add them as a comment
- [x] Stage & release
  - [x] Notify [#release-management](https://kubernetes.slack.com/messages/CJH2GBF7Y): [see notification](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1581532800106100)
  - [x] Collect metrics and add them to the `Release steps` table below
- [x] Send notification [email](https://groups.google.com/d/topic/kubernetes-announce/wahAv9Gc3d0/discussion)

## Release steps (`v1.18.0-alpha.5`)

| Step | Command | Link | Start | Duration | Succeeded? |
| --- | --- | --- | --- | --- | --- |
| Mock stage | `./gcbmgr stage master --buildversion=$(curl -Ls https://dl.k8s.io/ci/latest.txt)` | https://console.cloud.google.com/cloud-build/builds/0a39e34c-3ef8-4698-a947-fb43310279f0?project=kubernetes-release-test | February 12, 2020 at 2:09:16 PM GMT-5 | 47 min 9 sec | yes |
| Mock release | `./gcbmgr release  master --buildversion=v1.18.0-alpha.4.4+6541758fd4d9fc` | https://console.cloud.google.com/cloud-build/builds/8e90b7a0-d507-470e-9bdd-3acc71b8b366?project=kubernetes-release-test | February 12, 2020 at 2:57:39 PM GMT-5 | 17 min 42 sec | yes |
| Stage | `./gcbmgr stage master --buildversion=v1.18.0-alpha.4.4+6541758fd4d9fc --nomock` | https://console.cloud.google.com/cloud-build/builds/e38e54ba-183d-4b1a-9096-931cba92f1fb?project=kubernetes-release-test | February 12, 2020 at 3:24:33 PM GMT-5 | 46 min 26 sec | yes |
| Release | `./gcbmgr release --nomock master --buildversion=v1.18.0-alpha.4.4+6541758fd4d9fc` | https://console.cloud.google.com/cloud-build/builds/f78989b3-da80-4970-b78d-87ddae7149b2?project=kubernetes-release-test | February 13, 2020 at 1:19:48 AM GMT-5 | 18 min | yes |
| Notify | -- | https://groups.google.com/d/topic/kubernetes-announce/wahAv9Gc3d0/discussion |  | -- | yes |

## Action items

- [x] (https://github.com/kubernetes/release/pull/1096) Ensure anago doesn't create empty release commits on `master`
- [x] Push manual tag for `v1.18.0-alpha.4`
- [x] Manually generate release notes to capture diff between a commit behind `v1.18.0-alpha.3` and `v1.18.0-alpha.5`
- [x] (https://github.com/kubernetes/kubernetes/pull/88115) Update CHANGELOG-1.18.md to include manually generated notes and a comment on `v1.18.0-alpha.4`
- [x] (https://github.com/kubernetes/org/pull/1621, https://github.com/kubernetes/k8s.io/pull/566) Revoke Dan's temporary Branch Manager access

## Open questions

/area release-eng
/milestone v1.18
/assign
cc: @kubernetes/release-team @kubernetes/release-engineering

**Comment by justaugustus** [comment]
**Release is blocked on https://github.com/kubernetes/release/issues/1080.**

**Comment by justaugustus** [comment]
I took over this release due to the need to cut a manual tag and wanting to watch any potential issues that could've arisen from that.
/assign

**Comment by justaugustus** [comment]
Didn't have a chance to snapshot the boards ahead of the release, but here's their current status:

### Testgrid dashboards for master
Boards checked for FAILING:
- [sig-release-master-blocking](https://testgrid.k8s.io/sig-release-master-blocking)
- [sig-release-master-informing](https://testgrid.k8s.io/sig-release-master-informing)

<details><summary><tt>2020-02-13 03:13:31-0500</tt> FAILING sig-release-master-informing#capa-conformance-stable-k8s-master <a href="https://testgrid.k8s.io/sig-release-master-informing#capa-conformance-stable-k8s-master&width=30">[testgrid]</a></summary><p>

![sig-release-master-informing#capa-conformance-stable-k8s-master](https://storage.googleapis.com/kubernetes-release-gcb/testgridshot/master/2020-02-13_08-13-19_66ed943d/sig_release_master_informing_capa_conformance_stable_k8s_master.jpg)
</p></details>

<details><summary><tt>2020-02-13 03:13:31-0500</tt> FAILING sig-release-master-informing#capg-conformance-stable-k8s-master <a href="https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-stable-k8s-master&width=30">[testgrid]</a></summary><p>

![sig-release-master-informing#capg-conformance-stable-k8s-master](https://storage.googleapis.com/kubernetes-release-gcb/testgridshot/master/2020-02-13_08-13-19_66ed943d/sig_release_master_informing_capg_conformance_stable_k8s_master.jpg)
</p></details>

<details><summary><tt>2020-02-13 03:13:32-0500</tt> FAILING sig-release-master-informing#gce-cos-master-reboot <a href="https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-reboot&width=30">[testgrid]</a></summary><p>

![sig-release-master-informing#gce-cos-master-reboot](https://storage.googleapis.com/kubernetes-release-gcb/testgridshot/master/2020-02-13_08-13-19_66ed943d/sig_release_master_informing_gce_cos_master_reboot.jpg)
</p></details>

<details><summary><tt>2020-02-13 03:13:29-0500</tt> FAILING sig-release-master-informing#gce-cos-master-serial <a href="https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial&width=30">[testgrid]</a></summary><p>

![sig-release-master-informing#gce-cos-master-serial](https://storage.googleapis.com/kubernetes-release-gcb/testgridshot/master/2020-02-13_08-13-19_66ed943d/sig_release_master_informing_gce_cos_master_serial.jpg)
</p></details>

<details><summary><tt>2020-02-13 03:13:29-0500</tt> FAILING sig-release-master-informing#gce-windows-1909-master <a href="https://testgrid.k8s.io/sig-release-master-informing#gce-windows-1909-master&width=30">[testgrid]</a></summary><p>

![sig-release-master-informing#gce-windows-1909-master](https://storage.googleapis.com/kubernetes-release-gcb/testgridshot/master/2020-02-13_08-13-19_66ed943d/sig_release_master_informing_gce_windows_1909_master.jpg)
</p></details>

<details><summary><tt>2020-02-13 03:13:31-0500</tt> FAILING sig-release-master-informing#gce-windows-2019-containerd-master <a href="https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-containerd-master&width=30">[testgrid]</a></summary><p>

![sig-release-master-informing#gce-windows-2019-containerd-master](https://storage.googleapis.com/kubernetes-release-gcb/testgridshot/master/2020-02-13_08-13-19_66ed943d/sig_release_master_informing_gce_windows_2019_containerd_master.jpg)
</p></details>

<details><summary><tt>2020-02-13 03:13:29-0500</tt> FAILING sig-release-master-informing#gce-windows-2019-master <a href="https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-master&width=30">[testgrid]</a></summary><p>

![sig-release-master-informing#gce-windows-2019-master](https://storage.googleapis.com/kubernetes-release-gcb/testgridshot/master/2020-02-13_08-13-19_66ed943d/sig_release_master_informing_gce_windows_2019_master.jpg)
</p></details>

**Comment by justaugustus** [comment]
Scrollback from the manual tag push of [`v1.18.0-alpha.4`](https://github.com/kubernetes/kubernetes/releases/tag/v1.18.0-alpha.4) I did to resolve https://github.com/kubernetes/release/issues/1080:

```shell
$ git remote add danger git@github.com:kubernetes/kubernetes.git
$ git remote update
Fetching origin
Fetching upstream
Fetching danger
From github.com:kubernetes/kubernetes
 * [new branch]              feature-rate-limiting    -> danger/feature-rate-limiting
 * [new branch]              feature-serverside-apply -> danger/feature-serverside-apply
 * [new branch]              feature-workload-ga      -> danger/feature-workload-ga
 * [new branch]              master                   -> danger/master
 * [new branch]              release-0.10             -> danger/release-0.10
 * [new branch]              release-0.12             -> danger/release-0.12
 * [new branch]              release-0.13             -> danger/release-0.13
 * [new branch]              release-0.14             -> danger/release-0.14
 * [new branch]              release-0.15             -> danger/release-0.15
 * [new branch]              release-0.16             -> danger/release-0.16
 * [new branch]              release-0.17             -> danger/release-0.17
 * [new branch]              release-0.18             -> danger/release-0.18
 * [new branch]              release-0.19             -> danger/release-0.19
 * [new branch]              release-0.20             -> danger/release-0.20
 * [new branch]              release-0.21             -> danger/release-0.21
 * [new branch]              release-0.4              -> danger/release-0.4
 * [new branch]              release-0.5              -> danger/release-0.5
 * [new branch]              release-0.6              -> danger/release-0.6
 * [new branch]              release-0.7              -> danger/release-0.7
 * [new branch]              release-0.8              -> danger/release-0.8
 * [new branch]              release-0.9              -> danger/release-0.9
 * [new branch]              release-1.0              -> danger/release-1.0
 * [new branch]              release-1.1              -> danger/release-1.1
 * [new branch]              release-1.10             -> danger/release-1.10
 * [new branch]              release-1.11             -> danger/release-1.11
 * [new branch]              release-1.12             -> danger/release-1.12
 * [new branch]              release-1.13             -> danger/release-1.13
 * [new branch]              release-1.14             -> danger/release-1.14
 * [new branch]              release-1.15             -> danger/release-1.15
 * [new branch]              release-1.16             -> danger/release-1.16
 * [new branch]              release-1.17             -> danger/release-1.17
 * [new branch]              release-1.2              -> danger/release-1.2
 * [new branch]              release-1.3              -> danger/release-1.3
 * [new branch]              release-1.4              -> danger/release-1.4
 * [new branch]              release-1.5              -> danger/release-1.5
 * [new branch]              release-1.6              -> danger/release-1.6
 * [new branch]              release-1.6.3            -> danger/release-1.6.3
 * [new branch]              release-1.7              -> danger/release-1.7
 * [new branch]              release-1.8              -> danger/release-1.8
 * [new branch]              release-1.9              -> danger/release-1.9
$ git checkout master
Already on 'master'
$ git reset --hard danger/master
HEAD is now at 50c8f73a4b2 Merge pull request #88017 from feiskyer/fix-409
$ git tag -s v1.18.0-alpha.4 HEAD^
$ git push --dry-run danger v1.18.0-alpha.4 
To github.com:kubernetes/kubernetes.git
 * [new tag]                 v1.18.0-alpha.4 -> v1.18.0-alpha.4
$ git push danger v1.18.0-alpha.4 
Enumerating objects: 21957, done.
Counting objects: 100% (9472/9472), done.
Delta compression using up to 12 threads
Compressing objects: 100% (2077/2077), done.
Writing objects: 100% (6165/6165), 1.85 MiB | 2.28 MiB/s, done.
Total 6165 (delta 4734), reused 5043 (delta 3969)
remote: Resolving deltas: 100% (4734/4734), completed with 1486 local objects.
To github.com:kubernetes/kubernetes.git
 * [new tag]                 v1.18.0-alpha.4 -> v1.18.0-alpha.4
```

**Comment by justaugustus** [comment]
AIs are complete.
/close
